go.mod, x/gamm/handler.go, x/gamm/types/msgs.go, x/gamm/types/query.pb.gw.go
JoinSwapExternAmountIn, JoinSwapShareAmountOut, ExitSwapExternAmountOut, ExitSwapShareAmountIn were missing in msg.go and handler.go, this adds it in
=> Add missing Msg interfaces

app/app.go, go.mod, x/gamm/handler.go, x/gamm/types/msgs.go, x/gamm/types/query.pb.gw.go
Needed to deal with the new MsgCreateVestingAccount
=> Add vesting to module BasicManager

README.md
Update the Readme file with new Osmosis product direction.
=> Update README.md with updated direction

x/gamm/keeper/swap.go
Cherry-pick's tony's commit to fix this.
=> Fix the min/max error name mistake in gamm keeper

x/mint/spec/01_concepts.md, x/mint/spec/02_state.md, x/mint/spec/03_begin_block.md, x/mint/spec/04_params.md, x/mint/spec/05_events.md, x/mint/spec/README.md
I also don't really get why we use annual provisions internally
=> Update the mint module's docs

app/app.go, x/mint/keeper/keeper.go, x/mint/types/expected_keepers.go
=> Remove staking keeper from mint module

x/gamm/keeper/pool_service.go, x/gamm/keeper/swap.go, x/gamm/types/account.go, x/gamm/types/account_test.go
This generally improves the API and mitigates extraneous code.
It also blocks my work on updating the pool's internal weight tracking.
=> Remove SetPoolAssets, and change to UpdatePoolBalances

go.sum, proto/osmosis/claim/v1beta1/genesis.proto, proto/osmosis/claim/v1beta1/params.proto, proto/osmosis/claim/v1beta1/query.proto, x/claim/types/genesis.pb.go
=> Recreated go.sum and run make proto-all

x/gamm/client/cli/cli_test.go, x/gamm/client/cli/query.go
=> Rename Gamm CLI query from records to pool-assets

cmd/osmosisd/cmd/genesis.go
=> Initial liquid amount per address in genesis should be 20%

x/gamm/client/cli/cli_test.go, x/gamm/keeper/grpc_query_test.go, x/gamm/keeper/pool_service.go, x/gamm/keeper/pool_service_test.go, x/gamm/types/constants.go
=> Increase gamm initial shares to 100 * 10^18

app/params/genesis.go, go.mod, go.sum
closes #114 
Update to new osmosis-labs/cosmos-sdk commit on `osmo-v0.42.x` branch
=> Min Commission Rate

x/claim/keeper/activity.go, x/epochs/keeper/epoch.go, x/incentives/genesis_test.go, x/incentives/keeper/pot.go, x/incentives/keeper/pot_test.go, x/lockup/keeper/admin_keeper.go, x/lockup/keeper/export_test.go, x/lockup/keeper/lock.go, x/lockup/keeper/store.go, x/lockup/keeper/store_test.go, x/lockup/types/query.go
=> json marshal to proto marshal

startnode.sh, x/gamm/client/cli/cli_test.go, x/gamm/client/cli/parse.go
=> create pool json unknown field check

x/gamm/keeper/pool_service.go, x/gamm/keeper/share.go
Closes #171 
We should eventually add documentation for this into a more user friendly post & markdown
=> Document exit fee behaviour -- works as we want

x/incentives/keeper/pot_test.go
=> Add test for no lock pot distribution

x/pool-incentives/types/genesis_test.go, x/pool-incentives/types/gov_test.go, x/pool-incentives/types/incentives_test.go, x/pool-incentives/types/query_test.go
=> Proto marshal test for types - WIP

proto/osmosis/epochs/query.proto, x/epochs/client/cli/cli_test.go, x/epochs/client/cli/query.go, x/epochs/client/cli/tx.go, x/epochs/keeper/grpc_query.go, x/epochs/types/query.pb.go, x/epochs/types/query.pb.gw.go, x/gamm/client/cli/cli_test.go, x/gamm/client/cli/query.go
=> Missing API Endpoints - WIP

x/incentives/keeper/export_test.go, x/incentives/keeper/gauge_test.go
=> test denom map active pot ids

x/gamm/keeper/invariants.go, x/gamm/module.go
=> Simulation Invariants

x/claim/keeper/claim.go, x/claim/keeper/claim_test.go, x/claim/keeper/keeper_test.go, x/claim/spec/README.md
Fix a test not checking the right thing
Improve some code docs
=> x/claims: Fix a test not checking the right thing, code improvements 

app/app.go, x/mint/genesis.go, x/mint/keeper/hooks.go, x/mint/keeper/hooks_test.go, x/mint/keeper/keeper.go, x/mint/types/expected_keepers.go, x/mint/types/keys.go
What remains in this PR is updating all the tests to seed the developer vesting account with sufficient funds for the relevant test.
=> Make developer vesting tokens exist in a module account

x/mint/keeper/hooks.go, x/mint/keeper/hooks_test.go, x/mint/keeper/keeper.go, x/mint/keeper/keeper_test.go, x/mint/types/hooks.go, x/pool-incentives/keeper/distr_test.go, x/pool-incentives/keeper/hooks.go
=> Refactor mintedCoins -> mintedCoin

x/gamm/keeper/keeper.go, x/gamm/keeper/msg_server.go, x/gamm/keeper/swap.go, x/gamm/types/events.go, x/gamm/types/hooks.go, x/incentives/keeper/gauge.go
Adds a swap event to every swap, adds / cleans up existing gamm events
Closes #341
=> Gamm add swap events, fix up existing events

x/gamm/README.md
Added a documentation for the GAMM Module including a short description, the intended usage and an example for each function. See #157.
=> Add GAMM module documentation

app/app.go, cmd/osmosisd/cmd/airdrop.go, cmd/osmosisd/cmd/genesis.go
=> Osmosis is not gaia

x/gamm/spec/01_concepts.md
This pull request adds the documentation for gamm module, specifically the concepts of following.
- Pool and share
- Swap
- Multihop
=> Add documentation for gamm module

x/lockup/client/cli/query.go
Merging once tests pass, since this was reviewed as part of v2 work, just never landed into main
=> Add cmd for outputting all locks into a json

cmd/osmosisd/cmd/init.go
Update config.toml defaults with a second seed node.
=> add blockpane seed node

x/incentives/keeper/gauge.go, x/incentives/types/expected_keepers.go
Closes #468 , using Matt's new work in the SDK there!
This basically needs a test to check compat between debugDistribute and the new distribution function
=> only distribute once per user per gauge, use batched distribute function

x/lockup/keeper/gas_test.go, x/lockup/keeper/lock_test.go
Closes: #XXX
Improves the lock gas test, to be helpful for tracking how gas changes. (We should actually find a strategy for measuring message gas changes in general)
______
=> Refactor & improve lockup gas_test

x/txfees/README.md
Adds more detail around the txfees module in its README
______
=> Add more to the txfeees README

x/gamm/keeper/gas_test.go
This PR includes adding gas test for join pool in the gamm module, with the recent notice of gas increase for JoinPool - aiming to prevent further increase of gas in the JoinPool logic.
______
=> JoinPool gas test

x/claim/keeper/claim_test.go
=> Add test to make sure claim actions don't panic after airdrop ends

.github/workflows/gosec.yml
This really can't hurt:
https://github.com/informalsystems/gosec
Adds the informal systems Gosec tool to our CI system.
______
=> Cosmos SDK Gosec

docs/network/README.md
Created testnet instructions for new Osmosis github pages. To be merged with docs-dev. I would have committed changes directly to czar/docs, but I don't believe I have the permissions to do so. 
______
=> Joining Testnet Github Pages

docs/network/README.md
Completed joining mainnet instructions from snapshot. Minor changes to testnet instructions (grammar).
______
=> Joining Mainnet Github Pages

cmd/osmosisd/cmd/testnetify/script.sh
This PR updates testnetify to match recent state export in addition to minor fixes in comments on the testnetify script.
______
=> Testnetify Update

x/gamm/spec/01_concepts.md, x/pool-incentives/spec/03_gov.md
=> fixing some docs

cmd/osmosisd/cmd/testnetify/script.sh
Testnet genesis preparation improvements @UnityChaos and I worked on last week. Does not conflict with #657. This is closest to the modification script there, but that script takes the opposite angle. (Doing the fully correct thing from scratch, whereas this PR modifies the existing with some slight improvements)
______
=> Improve testnet mpdification script

cmd/osmosisd/cmd/balances_from_state_export.go, x/lockup/client/cli/tx.go, x/pool-incentives/client/cli/tx.go
This is a feature that will simplify the data gathering for many use cases. Has to be done against 4.x in addition to main & v6.x due to needing to use historical versions for state exporting.
______
=> update balance derivation script to allow additional filtering by pool ids

cmd/osmosisd/cmd/balances_from_state_export.go, x/lockup/client/cli/tx.go, x/pool-incentives/client/cli/tx.go
Updates export-derive-balances to take in additional filtering for amount bonded to given pool IDs, which has been a useful project to be able to better know for a number of things.
______
=> Update export-derive-balances to take in additional filtering by pool IDs

cmd/osmosisd/cmd/testnetify/README.md, cmd/osmosisd/cmd/testnetify/testnetify.py
auto change fast sync from true to false
Closes: #XXX
______
=> added tendermint bug fix

CHANGELOG.md, go.mod, go.sum, x/claim/keeper/hooks.go
Closes: #XXX
Big thing is this improves SDK pruning=default settings, and corrects comments. It also has fixes that help on main. 
______
=> Bump SDK version

docs/overview/terminology.md
Closes: #XXX
Updated broken links in /terminology.html#long-term-liquidity
(First time using GitHub so hopefully everything is in order)
______
=> Fix broken links in "long-term Liquidity" section

go.mod, go.sum
This pr bumps cosmos/gorocksdb :)
______
=> bump rocksdb

.github/workflows/test.yml
=> Make CI run on commit to all branches

CHANGELOG.md, app/app.go, go.mod, go.sum
This PR adds annotations to go.mod and app.go to give new developers better context when learning osmosis and the cosmos-sdk.
Lists of modules have been flattened, so that the code is easier to read.  
______
=> annotations

x/incentives/keeper/gauge.go
Just a small PR for adding error catch to consolidating paths for gauges!
______
=> Add error catch to gauge

app/app.go, app/upgrades/README.md, app/upgrades/v7/constants.go, app/upgrades/v7/upgrades.go
=> Add a v7 upgrade handler

go.mod, go.sum
…happening
Closes: #XXX
______
=> WIP: V6.2.0 fast.4 - log when iavl storage upgrade is in prgoress 

x/gamm/keeper/gas_test.go, x/lockup/keeper/gas_test.go
=> Gas test to work with maximum amount

x/lockup/keeper/invariants.go, x/lockup/module.go
=> Synthlock Invariant

CHANGELOG.md
=> Prepare changelog for 6.3.0 release and fix issues with other 6.x releases

CHANGELOG.md, app/app.go, app/keepers.go
Closes: #820 
Make superfluid staking keeper in app.go a pointer receiver
______
=> covert superfluid staking keeper to a ptr receiver

cmd/osmosisd/cmd/testnetify/README.md, cmd/osmosisd/cmd/testnetify/testnetify.py
- Added VotingPeriod params change
- Created dist_offset_amt and auto fetch distribution module account balance to make bug fix easier
- Total osmo supply auto subtracted by dist_offset_amt
- Updated markdown
______
=> Testnetify Improvements

proto/osmosis/claim/v1beta1/claim.proto, proto/osmosis/lockup/lock.proto, proto/osmosis/superfluid/genesis.proto, proto/osmosis/superfluid/gov.proto, proto/osmosis/superfluid/params.proto, proto/osmosis/superfluid/query.proto, proto/osmosis/superfluid/superfluid.proto, proto/osmosis/superfluid/tx.proto, x/lockup/types/lock.pb.go, x/superfluid/client/cli/tx.go, x/superfluid/handler.go, x/superfluid/keeper/msg_server.go, x/superfluid/keeper/stake.go, x/superfluid/keeper/stake_test.go, x/superfluid/simulation/operations.go, x/superfluid/types/codec.go, x/superfluid/types/gov.pb.go, x/superfluid/types/msgs.go, x/superfluid/types/params.pb.go, x/superfluid/types/superfluid.pb.go, x/superfluid/types/tx.pb.go
Removes redelegation messages from superfluid staking MVP. (The implementation was incomplete)
______
=> comment out superfluid redelegation logic

cmd/osmosisd/cmd/testnetify/testnetify.py
At first I didn't understand why the testnetify script did not give me permission to modify the validator once the chain was started, but as @UnityChaos reviewed the script she explained to me that I needed to use the osmovaloper address derived from the wallet address rather than the validator address (among other things). This fixes that error and confirmed to work through running a testnet with it. I will attempt to automate this further (the current fix forces more user input) but for now this patch allows it to work as intended. 
Also added current hours and minutes to the changed epoch start time
______
=> Use wallet pubkey and osmovaloper address correctly in testnetify script

x/superfluid/keeper/slash.go, x/superfluid/keeper/stake.go, x/superfluid/types/params.go, x/superfluid/types/times.go
Closes: #XXX
PRing my updates into the osmotime branch
______
=> updates (gitpod)

app/app.go
Fixes null ptr issue with upgrade process in app.go
______
=> Move app.setupUpgradeHandlers() after module manager and configurator

x/superfluid/keeper/stake.go, x/superfluid/keeper/twap_price.go, x/superfluid/spec/03_messages.md
=> Spec for superfluid messages - WIP

x/superfluid/spec/01_concepts.md, x/superfluid/spec/03_messages.md, x/superfluid/spec/04_epoch.md, x/superfluid/spec/07_hooks.md
Closes: #XXX
Adds additional documentation for superfluid, reviews on how we want to improve documentation and what additional documentations we need are needed!
______
=> Add spec documentation for superfluid

x/epochs/abci_test.go, x/epochs/keeper/epoch.go
This is intended to help us simplify the pipeline for superfluid reward payouts.
=> Add NumBlocksSinceEpochStart function

x/superfluid/client/cli/tx.go
=> Re-enable superfluid asset proposal CLI cmds

x/superfluid/keeper/epoch.go, x/superfluid/keeper/stake.go
=> More logic re-use between SFDelegate and SFDelegateMore

x/superfluid/keeper/stake.go
Closes: #XXX
Also changes Refresh from `SharesFromTokens` to `ValidateUnbondAmount` similar to Undelegate
______
=> And a fn for Unbond and Burn tokens

x/superfluid/keeper/stake.go, x/superfluid/keeper/stake_test.go
=> Fix broken test / lint from prior merged PR

proto/osmosis/superfluid/tx.proto, x/superfluid/handler.go, x/superfluid/keeper/grpc_query.go, x/superfluid/keeper/msg_server.go, x/superfluid/keeper/stake.go, x/superfluid/keeper/synthetic_lock_wrapper.go, x/superfluid/types/errors.go, x/superfluid/types/expected_keepers.go, x/superfluid/types/msgs.go, x/superfluid/types/tx.pb.go
Adds a message for use after SuperfluidUndelegate, to be able to make your underlying lock start unlocking.
TODOs:
* Make CLI multi-message this, which is the flow the front-end will have.
* Go tests for the logic
______
=> Superfluid unbond lock initial commit

x/lockup/keeper/lock.go, x/superfluid/keeper/hooks.go, x/superfluid/keeper/hooks_test.go, x/superfluid/keeper/stake.go, x/superfluid/types/expected_keepers.go
=> Fix lockup module driving SuperfluidUndelegate on TokenUnlock hook

x/lockup/keeper/lock_test.go, x/lockup/keeper/synthetic_lock.go
=> AddTokensToLock test 

app/app.go, app/upgrades/v7/upgrades.go, x/lockup/keeper/migration_test.go, x/mint/genesis.go, x/mint/keeper/hooks_test.go, x/mint/keeper/keeper.go, x/mint/module.go, x/mint/types/expected_keepers.go
=> mint developer rewards supply offset

x/superfluid/keeper/stake_test.go
Adds balance check to superfluidUnbondlock!
______
=> Add test for balance check for SuperfluidUnbondLock

osmoutils/cache_ctx.go, x/superfluid/keeper/epoch.go, x/superfluid/keeper/gov/gov.go, x/superfluid/keeper/slash.go, x/superfluid/keeper/stake.go, x/superfluid/spec/12_minting.md
=> Superfluid minting / invariants spec

x/lockup/keeper/lock.go
=> Fix accumulation of synthetic locks

app/ante.go, app/app.go, app/keepers.go, go.mod
Re-reviewing the wasmd changes, and adding a few little pieces.
______
=> Wasmd updates

app/app.go, app/upgrades/v7/upgrades.go, x/incentives/keeper/distribute.go, x/incentives/keeper/distribute_test.go, x/incentives/keeper/gauge.go, x/incentives/keeper/hooks.go, x/superfluid/abci.go, x/superfluid/keeper/distribution_test.go, x/superfluid/keeper/epoch.go, x/superfluid/keeper/grpc_query_test.go, x/superfluid/keeper/hooks.go, x/superfluid/keeper/hooks_test.go, x/superfluid/keeper/keeper_test.go, x/superfluid/keeper/slash_test.go, x/superfluid/keeper/stake_test.go, x/superfluid/module.go, x/superfluid/types/expected_keepers.go
Due to safety / correctness / complexity issues, we are adapting the rewards distribution pipeline for superfluid staking rewards to be correct / much simpler.
______
=> Work on rewards pipeline changes

x/superfluid/types/msgs.go
=> Add single denom check to validatebasic for MsgLockAndSuperfluidDelegate

x/lockup/keeper/iterator.go, x/lockup/keeper/lock.go, x/lockup/keeper/lock_refs.go, x/lockup/keeper/lock_test.go, x/lockup/keeper/migration.go, x/lockup/keeper/synthetic_lock.go, x/lockup/keeper/synthetic_lock_test.go, x/lockup/keeper/utils.go, x/lockup/spec/05_keeper.md, x/superfluid/keeper/stake.go, x/superfluid/spec/04_epoch.md, x/superfluid/types/expected_keepers.go
=> Superfluid Misc: Improve lockup API safety, update epochs module spec

app/ante.go, app/app.go
Thank you @alpe 
* Properly load pinned contracts on startup: https://github.com/osmosis-labs/osmosis/pull/769#pullrequestreview-889872689
* Add the tx counter ante handler: https://github.com/osmosis-labs/osmosis/pull/934#pullrequestreview-889866597
______
=> Address wasmd PR comments

x/lockup/keeper/msg_server.go, x/superfluid/keeper/distribution_test.go, x/superfluid/keeper/grpc_query.go, x/superfluid/keeper/grpc_query_test.go, x/superfluid/keeper/hooks_test.go, x/superfluid/keeper/intermediary_account.go, x/superfluid/keeper/keeper_test.go, x/superfluid/keeper/slash_test.go, x/superfluid/keeper/stake.go, x/superfluid/keeper/stake_test.go, x/superfluid/types/superfluid.go
This PR includes the implementation of lock tokens msg server implementation, bug fixes in existing tests and some minor fixes in state logic as well. 
- needs revisit on `RefreshIntermediaryAccount` testing
______
=> lock tokens msg server impl, Fix tests

scripts/multinode-local-testnet.sh, x/incentives/keeper/distribute.go, x/lockup/types/lock.go, x/superfluid/keeper/epoch.go
=> Superfluid - multinode script + code bug fixes

app/app.go, app/upgrades/v7/upgrades.go, x/superfluid/keeper/gov/gov.go, x/superfluid/keeper/superfluid_asset.go
Adds migration for superfluid for v7 upgradeHandler
______
=> Add superfluid migrations code

x/lockup/keeper/migration.go, x/lockup/keeper/migration_test.go, x/superfluid/keeper/hooks_test.go, x/superfluid/keeper/slash_test.go, x/superfluid/keeper/stake_test.go, x/superfluid/keeper/superfluid_asset_test.go, x/superfluid/types/params.go
The risk factor should start higher, as a safety mechanism for the chain. This is a huge change to proof of stake, and bounding the risk is important!
______
=> Update the risk factor from 5% to 50% 

x/gamm/pool-models/balancer/msgs.go
the balancer package within the gamm module currently uses codec for gamm, should be changed in the way that it uses its own codec
______
=> Change balancer package to use balancer codec

x/superfluid/types/codec.go
Adds Legacy Animo to superfluid module, tested in a node env that it works using `--sign-mode=amino-json`
______
=> Add codec to `x/superfluid`

scripts/wasm/README.md, scripts/wasm/get_contracts.sh, scripts/wasm/install_contracts.sh, scripts/wasm/test_cw20.sh
These can be run on a fresh osmosis 0.7.x testnet. Please check README before running, as you will likely need to adjust some variables in the scripts before running.
As I cannot easily parse out CODE_ID, PROPOSAL_ID, CONTRACT_ADDR from the cli scripts, these are hardcoded, meaning it can only be run once per testnet. This can be used as an initial smoke-test. For more advanced tests, I highly recommend using CosmJS and I will work on a more advanced suite for Osmosis 0.8.x with custom CosmWasm integrations.
______
=> Add some scripts I used to test the wasm-2 testnet

proto/osmosis/superfluid/query.proto, x/superfluid/types/codec.go
- Remove denom from url so that front end can access the url
- Adds codec for `MsgSuperfluidUnbondLock`
______
=> Fix queries, Add codec for `MsgSuperfluidUnbondLock `

x/lockup/keeper/lock.go
=> Fix slashing bug

x/lockup/keeper/migration.go, x/superfluid/keeper/epoch.go
=> Remove a warning message you get in logs

CHANGELOG.md, go.mod, go.sum
Closes: #XXX
Added current changes until 6.4 as well as the current fast storage changes for v7.
______
=> Update changelog for v7

networks/osmosis-1/upgrades/v7/guide.md
Guide for upgrading from v6 to v7.
I would not merge until the v7.0.0 tag is made, since this guide references this tag for people to prep their cosmovisor with.
______
=> v7 Upgrade Guide

networks/osmosis-1/upgrades/v7/mainnet/v7.0.0-binaries.json
=> Add v7.0.0 linux/amd64 binary to binaries.json

CHANGELOG.md
=> changelog should point to v7 guide not v5

x/lockup/keeper/migration.go
As discovered by @hleb-albau , the lockup migration does not work with this log entry. We decided to simply comment it out for now.
______
=> lock migration fix

.mergify.yml
Update mergify.yml for v7.x
______
=> Update mergify.yml for v7.x

x/gamm/handler.go, x/gamm/keeper/msg_server.go, x/gamm/module.go, x/incentives/handler.go, x/incentives/keeper/msg_server.go, x/incentives/module.go, x/superfluid/handler.go, x/superfluid/keeper/msg_server.go, x/superfluid/module.go
Closes: #967
Make all message servers in the stack take pointers to keepers
______
=> [#967] msg server impl usr ptr keepers

app/app.go, app/keepers.go, app/modules.go
Closes: #713
Make app.go boilerplate methods go into their own file
- added an appKeepers struct for the OsmosisApp to inherit listed keepers
- moved several modules list to app/modules.go
______
=> [#713] app boilerplate to files

CHANGELOG.md, osmoutils/cache_ctx.go, x/superfluid/keeper/hooks.go
=> Add the v7.0.2 to main branch

x/lockup/keeper/iterator.go, x/lockup/keeper/lock.go, x/lockup/keeper/lock_test.go, x/lockup/keeper/msg_server.go
Closes: #945
x/lockup: Change public facing methods to take in lockID instead of lock
______
=> [#945] change public facing methods to use lockID

README.md
Closes: #825 
This PR adds system requirements to the Readme.md file
______
=> system requirements

CHANGELOG.md
=> update changelog for v7.0.3

x/lockup/keeper/msg_server_test.go
Refactored `msg_server_test.go` as per @ValarDragon request. More details [here](https://hackmd.io/W2PIo4SNREGMjN9Zyo2rbQ?both)
This PR allows devs to create test for `LockTokens` easily with table driven approach. I have only added "normal working lock test" in this refactoring, however once I receive Approach ACK, i plan on adding 
PS: very new to this codebase, so apologies for any style issues and looking for literally any feedback to improve
=> test: Refactored test to follow table driven approach

CHANGELOG.md
Closes: #XXX
Updating changelog to create a tag for 7.0.4
______
=> update changelog for v7.0.4

app/app.go
Closes: #XXX
Thanks to @colin-axner for pointing this out
______
=> Remove distr account being able to receive tokens

scripts/setup_superfluid.sh
Preparing a setup to test superfluid requires a lot of in the process: Having to create a pool, swapping to set spot price, creating a lockup, submitting a gov proposal, voting on the proposal to set superfluid asset.
This script enables a quick setup of a basic superfluid environment, improving the overall testing environment. 
______
=> Add basic setup script for superfluid

x/gamm/client/cli/query.go
Closes: #979 
Removes unused flag `--swap-route-amounts` from examples.
______
=> remove --swap-route-amounts flag from example

x/epochs/abci.go, x/gamm/keeper/pool_service.go, x/txfees/keeper/feedecorator.go
Adds some more code comments for functions, refactors the JoinPoolNoSwap function to reduce complexity, and tries to simplify the conditional logic in BeginBlock.
______
=> Add some more code comments for functions discussed with @alexanderbez

app/keepers.go
Not sure how this was missed from my initial PR...maybe due to the merge conflict resolution.
______
=> chore: more app linting

startnode.sh, x/lockup/keeper/msg_server_test.go, x/superfluid/keeper/edge_case_test.go, x/superfluid/keeper/msg_server_test.go
=> Superfluid edge case test

.mergify.yml
=> chore: Update .mergify.yml (>= 1 approval)

x/gamm/keeper/pool_service.go, x/gamm/keeper/share.go, x/gamm/keeper/swap.go, x/gamm/pool-models/balancer/amm.go, x/gamm/spec/01_concepts.md, x/gamm/spec/02_pool_params.md, x/gamm/spec/03_msgs.md, x/gamm/spec/04_params.md
- Cleanup spec/docs
- Cleanup x/gamm godocs and linting
______
=> chore: x/gamm docs + cleanup

CHANGELOG.md
=> update changelog with changes from v7.x

x/gamm/keeper/invariants.go
=> Delete unused gamm invariants, fix pool account invariant

.vscode/settings.json
Adds default vscode configuration for the repo, hopefully making it easier for incoming developers to just get started with working on osmosis with vscode.
______
=> Add some default vscode settings

x/epochs/keeper/grpc_query.go, x/gamm/keeper/grpc_query.go, x/incentives/keeper/grpc_query.go, x/lockup/keeper/grpc_query.go, x/pool-incentives/keeper/grpc_query.go, x/superfluid/keeper/grpc_query.go, x/txfees/keeper/grpc_query.go
=> chore: add nil checks and tweaks to gRPC handlers

.github/labeler.yml, .github/workflows/labeler.yml
Add labeler configuration and action job that'll automatically label PRs with the relevant labels!
______
=> chore: add PR labeler to CI

cmd/osmosisd/cmd/init.go
One of our node ID's has changed and this PR fixes that.
______
=> update seed: node id change

.github/workflows/add-to-project.yml
Simple git action to automatically add issues to our project.
=> New git action to add issues to project

cmd/osmosisd/cmd/init.go
This updates the seeds in v4.x so that they're current with v7
______
=> Update seeds in v4.x

cmd/osmosisd/cmd/init.go
This pr brings the seeds in v6.x current with those in v7
______
=> chore: update seeds in v6.x

cmd/osmosisd/cmd/init.go
Add 2 Blockdaemon seed nodes (USA/EU)
N/A
This change is a trivial update to add seed nodes
- Does this pull request introduce a new feature or user-facing behavior changes? (yes / no) no
- Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (yes / no) no
- How is the feature or change documented? (not applicable   /   specification (`x/<module>/spec/`)  /  [Osmosis docs repo](https://github.com/osmosis-labs/docs)   /   not documented) n/a
=> add blockdaemon osmosis seed nodes

cmd/osmosisd/cmd/init.go
Add BlockNgine Validators seed for better connectivity 
- * update init to contain BlockNgine Validators seed node
=> Add BlockNgine mainnet seed

cmd/osmosisd/cmd/init.go
Closes: #XXX
*Add a description of the overall background and high level changes that this PR introduces *
*(or)*
*(or)*
*(example:)*
- …
=> Add Sunshine Validation Seed Node to init.go

app/app.go
Delete unused functions in app.go
Delete unused functions in app.go
- Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? no (not needed)
=> Delete unused functions from app.go

x/gamm/pool-models/balancer/amm_test.go
Closes: #XXX
`amm_test.go` is not formatted correctly (was not caught by Automerge in #1344 ). This PR fixes the formatting error
- formatted the problematic file
=> chore: format balancer amm_test.go

CHANGELOG.md, go.mod, go.sum
Closes: #1356 
Upgrades SDK to `v0.45.0x-osmo-v7.9` with the fix for https://github.com/osmosis-labs/osmosis/issues/1356
The relevant [SDK PR](https://github.com/osmosis-labs/cosmos-sdk/pull/216) changes query handling to avoid the data races experience by integrators.
updated the SDK version
=> chore: upgrade sdk to v0.45.0x-osmo-v7.9

CHANGELOG.md
Closes: #XXX
Fixes the changelog to use the desired release number
=> chore: v7.3.0 changelog

README.md
Closes: #1423
[RENDERED](https://github.com/osmosis-labs/osmosis/blob/bez/1423-readme-badges/README.md)
=> chore: README badges 

.github/ISSUE_TEMPLATE/issue.md
Closes: #XXX
The new template is currently not visible:
This change should fix it.
=> chore: let issue.md appear in templates

tests/e2e/chain/config.go, tests/e2e/chain/main.go, tests/e2e/chain_init/main.go, tests/e2e/e2e_setup_test.go, tests/e2e/e2e_test.go
Updating v7.x to what we are currently using as the v7 init docker image
=> init docker changes

.github/workflows/codeql-analysis.yml
codeql-analysis.yml had a typo which prevented it from running properly, and also sends an email on every commit saying it failed.
Changed codeql-analysis.yml to follow proper yml syntax
This change is a trivial rework / code cleanup without any test coverage
=> fix: update codeql-analysis.yml

app/forks.go, app/upgrades/v8/forks.go
Adds the check for UST in the pool
=> Checking Whitelisted Pools contain UST

Dockerfile, tests/e2e/chain/config.go, tests/e2e/chain/main.go, tests/e2e/chain_init/main.go, tests/e2e/e2e_setup_test.go, tests/e2e/e2e_test.go
Closes: #XXX
Used to create init docker image. This way for future tests we can test v8 to v9 instead of v7 to v9 which it is currently doing. While this likely achieves the same thing, we should still keep this up to date.
These changes should no longer need to be done manually now that the init changes are merged to main
- How is the feature or change documented? no
=> test: add init changes to v8.x

x/gamm/pool-models/stableswap/msgs_test.go
Closes: #1384
- I add test for stableswap msg
=> add msg_test.go for stableswap msg

.mergify.yml
Closes: #XXX
Updating mergify configuration to backport to v9.x
=> chore: update mergify to backport to v9.x

ante/sendblock_test.go
SendBlock_test was failing before, due to the from address not being 20 or 32 bytes. Not sure why this didn't fail in CI earlier.
Fixes a testcase that was failing on main.
Tests pass
=> Fix sendblock test

tests/e2e/chain/config.go, tests/e2e/chain/validator.go, tests/e2e/e2e_util_test.go, x/epochs/types/genesis.go
Some small things I noticed on reading the code, in addition to issues I'm making on the side!
* Being a human linter
* Add some TODO's
* introduce a `NewGenesisEpochInfo` function, and use to eliminate overhead.
=> Small test e2e updates / boilerplate notes

x/tokenfactory/keeper/msg_server.go
<!-- < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < ☺
v                               ✰  Thanks for creating a PR! ✰    
v    Before smashing the submit button please review the checkboxes.
v    If a checkbox is n/a - please still include it but + a little note why
v    If your PR doesn't close an issue, that's OK!  Just remove the Closes: #XXX line!
☺ > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > >  --
Help improve debugging for token factory.
- How is the feature or change documented? (not applicable   /   specification (`x/<module>/spec/`)  /  [Osmosis docs …
=> Wrap tokenfactory error

networks/osmosis-1/upgrades/v9/guide.md
This is a writeup of instruction to upgrade from v8 to v9 with and without cosmovisor
=> v9 upgrade docs

.github/labeler.yml
Improve comments for the github labeller action, that were confusing in #1662
Just adds a comment
=> Add a comment to the labeller

x/gamm/pool-models/balancer/amm.go
Aim to improve comments / logic in main function 
*(or)*
*(or)*
*(example:)*
- Does this pull request introduce a new feature or …
=> Improve comments / abstractions

app/upgrades/v10/constants.go, app/upgrades/v10/fork.go, app/upgrades/v10/upgrades.go, app/upgrades/v10/upgrades_test.go
Delete irregular state change logic, as preferred in validators discord
Covered by existing test
=> Delete irregular state change logic

x/gamm/pool-models/balancer/amm_test.go
Closes: #XXX
*(or)*
*(or)*
*(example:)*
- …
=> Remove expected liquidity field from test

networks/osmosis-1/upgrades/v10/guide.md
*(or)*
*(or)*
*(example:)*
- *Extended …
=> Update the guide

go.mod
Closes: #XXX
SDK fork branching was fixed. Referencing the correct branch in `go.mod`:
https://github.com/osmosis-labs/cosmos-sdk/tree/v0.45.0x-osmo-v8
=> chore: update sdk fork branch reference on v8.x

.github/labeler.yml
Fix label inconsistencies present atm
=> Update labeller for label stanards

go.sum, tests/e2e/chain/config.go, tests/e2e/chain/main.go, tests/e2e/chain_init/main.go
Closes: #XXX
Changes v10.x branch to utilize the chain init changes made in the most recent e2e PR to main. These changes were utilized in the following dockerhub docker image https://hub.docker.com/layers/241520518/osmolabs/osmosis-e2e-init-chain/v10.0.0/images/sha256-054fe6144ad52a4c7a560697056e4a3b3c80a9390119d38f6a06e305df427ede?context=repo
=> test: add chain init changes to v10.x

.github/workflows/add-issue-to-project.yml, .github/workflows/add-pr-to-project.yml
=> We broke adding issues to Project, this fixes it

x/gamm/pool-models/balancer/pool.go
Closes: #XXX
An unused variable got committed after #1939 was created, making it uncaught as a result. This PR removes the missed unused variable.
=> lint: remove unused v10 fork height

tests/e2e/initialization/node.go
Closes: #XXX
Broke CI in #1963 from missing to merge new linter changes from a parallel pull-request. Unblocking CI with the fix
=> lint: fix issue from parallel e2e pull request

tests/e2e/containers/config.go
Closes: #XXX
#1963 was backported to `v10.x` in #1975. This PR updates the previous version initialization image with the latest changes from #1975.
=> chore(e2e): update initialization image with changes from #1975

x/lockup/keeper/lock_test.go
Refactors unlocking test into TDD, and cleans up duplicated tests for unlocking in the x/lockup module.
Clean up existing tests for `BeginUnlock` and refactor them to be TDD
- Does this pull request introduce a new feature or user-facing behavior changes?  no
- Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`?  no
=> chore: refactor unlock test

proto/osmosis/incentives/gauge.proto, proto/osmosis/incentives/genesis.proto, proto/osmosis/incentives/params.proto, proto/osmosis/incentives/query.proto, proto/osmosis/incentives/tx.proto, x/incentives/types/gauge.pb.go, x/incentives/types/genesis.pb.go, x/incentives/types/params.pb.go, x/incentives/types/query.pb.go, x/incentives/types/tx.pb.go
Part of: #1837 
Audit, clean up, and test modifications for the incentives module
This is part 1 of 4:
1. Proto changes
2. CLI fixes
3. Tests
4. All other changes
- Better explain incentive protobufs with comments
This change is already covered by existing tests, such as check-proto CI job
=> x/incentives: protobuf updates

proto/osmosis/superfluid/genesis.proto, proto/osmosis/superfluid/params.proto, proto/osmosis/superfluid/query.proto, proto/osmosis/superfluid/superfluid.proto, proto/osmosis/superfluid/tx.proto, x/superfluid/keeper/hooks_test.go, x/superfluid/keeper/msg_server.go, x/superfluid/keeper/stake.go, x/superfluid/types/genesis.pb.go, x/superfluid/types/params.pb.go, x/superfluid/types/query.pb.go, x/superfluid/types/superfluid.pb.go
sub component of: #1955
This PR adds proto message documentation and additional documentation for msg_server and code within `x/superfluid/keeper`. 
This PR does not include ANY change or refactoring for any of the logic within `x/superfluid`
- Add documentation for `x/superfluid`
- How is the feature or change documented? additional documentations
=> chore: Add documentations for superfluid module

proto/osmosis/superfluid/genesis.proto, proto/osmosis/superfluid/params.proto, x/superfluid/types/genesis.pb.go, x/superfluid/types/params.pb.go
Extension of : #https://github.com/osmosis-labs/osmosis/pull/1991
The only last commit of this PR is what needs to be reviewed, upon the approval and merging of #1991 
Background for this PR is that https://github.com/osmosis-labs/osmosis/pull/1991 got merged without having pushing the commit for the most recent commit for the branch, which includes some feedbacks https://github.com/osmosis-labs/osmosis/pull/1991#discussion_r918368034
=> chore: fix superfluid documentation typos

x/gamm/keeper/internal/events/emit.go, x/gamm/keeper/internal/events/emit_test.go, x/gamm/keeper/keeper.go, x/gamm/keeper/msg_server_test.go, x/gamm/keeper/multihop.go, x/gamm/keeper/share.go, x/gamm/keeper/swap.go, x/gamm/keeper/swap_test.go, x/gamm/spec/README.md, x/gamm/types/events.go
Part of #1942
Refactor and test gamm swap events. This does not change when the events are emitted. It only does some basic refactor to make events more testable.
Additionally, it unit tests and documents when swap events are emitted. All other events in gamm will be tested in incoming PRs
This change added tests for swap events at 3 levels of abstraction:
- internal events package
- keeper swap methods
- message server
=> refactor(x/gamm): swap events

.github/labeler.yml
=> Add simulation to labeler

x/superfluid/keeper/distribution_test.go, x/superfluid/keeper/edge_case_test.go, x/superfluid/keeper/grpc_query_test.go, x/superfluid/keeper/hooks_test.go, x/superfluid/keeper/intermediary_account_test.go, x/superfluid/keeper/keeper_test.go, x/superfluid/keeper/slash_test.go, x/superfluid/keeper/stake_test.go
Sub-component of : #1955 
Cleans up unnecessary test fields in the existing superfluid test and remove unnecessary code complexity in the testing for superfluid, mainly `stake_test.go` 
Note that adding new test cases is not in the scope of this PR.
- Clean up structure for tests in superfluid module
This change refactors existing testings
=> chore: cleanup superfluid testing

.gitignore, Makefile, scripts/mutation-test.sh
Minor changes I made to the script to make #2105
=> mutation script: minor changes

CHANGELOG.md, go.mod, go.sum
Closes: #2122
Upgrading to: https://github.com/osmosis-labs/cosmos-sdk/releases/tag/v0.45.0x-osmo-v9.1
=> chore(deps): upgrade sdk fork dep - v10.x

CHANGELOG.md
Closes: #XXX
#1857 introduced an API break but a changelog entry wasn't added. This PR follows through with the entry
=> chore(changelog): add api breaking changelog entry from #1857

CHANGELOG.md
Closes: #XXX
Prepare changelog for v10.1
Skimmed recent PRs to observe any API breaks / important public changes,
=> chore(changelog): update changelog for v10.1

chain.schema.json
Closes: #XXX
This chain schema file being out of date with overwrite updates to the Chain registry. Adding fields for tendermint version, cosmos sdk version, cosmwasm version, and cosmwasm enabled, allows these version to be tracked here, and automatically update accordingly in the Chain registry.
dding fields for tendermint version, cosmos sdk version, cosmwasm version, and cosmwasm enabled to …
=> Update chain schema

app/modules.go, x/epochs/keeper/keeper.go, x/epochs/module.go, x/incentives/module.go, x/lockup/keeper/genesis_test.go, x/lockup/keeper/keeper.go, x/lockup/module.go, x/pool-incentives/keeper/geneis_test.go, x/pool-incentives/module.go, x/superfluid/keeper/genesis_test.go, x/superfluid/module.go, x/tokenfactory/keeper/keeper.go, x/tokenfactory/module.go, x/txfees/keeper/keeper.go, x/txfees/module.go
Closes: #2169
Remove unused cdc in app modules and keepers
remove unused cdc in keepers and appmodules
=> Remove unused cdc

networks/osmosis-1/upgrades/v11/mainnet/upgrade_11_binaries.json
Closes: #XXX
*(or)*
*(or)*
*(example:)*
- …
=> chore: add cosmovisor binaries json

networks/osmosis-1/upgrades/v11/guide.md, networks/osmosis-1/upgrades/v11/mainnet/guide.md, networks/osmosis-1/upgrades/v11/testnet/guide.md
Closes: #XXX
Adds upgrade guide from v10 to v11 for both cosmovisor and manual upgrade. 
- Adds mainnet v11 upgrade guide
- Adds testnet v11 upgrade guide
=> chore: v11 upgrade guide

CHANGELOG.md
Closes: #XXX
changelog entry for #2237 
=> chore: v11 changelog entry for gauge fees

app/keepers/keepers.go, app/wasm/stargate_binding.go, app/wasm/wasm.go
Change the stargate querier for cosmwasm to use json
=> Hackatom seoul

.markdownlint.yml, x/gamm/twap/README.md
This PR adds a spec for TWAP
Its a breakout of #2168
=> Add TWAP spec

CHANGELOG.md, go.mod, go.sum, tests/e2e/configurer/chain/commands.go, tests/e2e/configurer/config/constants.go, tests/e2e/configurer/upgrade.go, tests/e2e/e2e_test.go
Closes: #XXX
Upgrading sdk with min proposer deposit and adjusting e2e tests accordingly
=> chore(deps): upgrade sdk with min proposer deposit and update e2e

app/keepers/keepers.go, x/pool-incentives/keeper/keeper.go, x/superfluid/keeper/keeper.go, x/tokenfactory/keeper/createdenom.go, x/tokenfactory/keeper/keeper.go, x/tokenfactory/types/expected_keepers.go
Deletes unused keeper cdc arguments
=> Remove unused cdc arguments

scripts/archivenode.bash
Closes: #XXX
This is a draft for now.  When it's verified working in... (A week!?!!) will update further.
=> perf: archive node creation script

CONTRIBUTING.md
Closes: #2296
Simpler tests in contribution.md and consistent map syntax
n/a
n/a
=> [README] Contributing.md: Simplify test examples

x/lockup/keeper/store.go
Closes: #XXX
Removes the unused method
=> x/lockup: remove unused ClearAllAccumulationStores

go.mod, go.sum, scripts/mutation-test.sh, tools/tools.go
Closes: https://github.com/osmosis-labs/osmosis/issues/2116#issuecomment-1212129548
Connects our main repo to our `go-mutesting` fork.
- Update `tools/tools.go` and `scripts/mutation-test.sh` to point to our fork
=> Update tools.go and scripts to point go-mutesting to our fork

CHANGELOG.md
Closes: #XXX
Changelog for v11.0.1
=> chore: prepare v11.0.1 changelog

x/mint/keeper/export_test.go, x/mint/keeper/keeper.go, x/mint/keeper/keeper_test.go, x/mint/simulation/genesis_test.go, x/mint/types/minter.go, x/mint/types/minter_test.go
Closes: #XXX
- create common methods for handling truncations
- used by mint distributions
- used by developer rewards distributions
- make distribution functions deeper
- remove obsolete methods
=> improve abstractions for the mint rounding solution

tests/e2e/README.md
Closes: #XXX
@nicolaslara found out that our debug configuration in docs does not correctly apply the e2e build tags.
This PR updates docs with the right configuration.
Tested locally.
=> chore(e2e): update debug configuration to handle build tags

CONTRIBUTING.md, tests/e2e/README.md
Closes: #XXX
Add e2e debugging details to CONTRIBUTING.md and `tests/e2e/README`
=> docs: update e2e debugging details in CONTRIBUTING.md

simulation/executor/mock_tendermint.go, simulation/executor/simulate.go, simulation/executor/simulate_dev.go, tests/simulator/sim_test.go
Closes: #2425
Within the simulator, we want to generate an app hash which we can use to compare across runs. This ends up not being a straight forward task since we implement a bare bones mock tendermint. 
This PR introduces the absolute minimum we need to produce an app hash. This app hash is not entirely useful, as it is essentially only derived from the validator hash within the block header. If the direction of this PR is correct, the next step will be to generate a datahash via all tx results, which should then produce an apphash that has meaning (this is now completed in #2531 )
As a side note, this is my first time really digging into tendermint, so my understanding could be (and is likely) incomplete. Please lmk if anything in the PR seems to not makes sense!
- changes …
=> simulator: app hash MVP (part 1/2)

app/apptesting/osmoassert/assertions.go
Adds a small helper method for conditional assert
=> Add conditional error to osmoassert

app/apptesting/test_suite.go
Inlines the staking test helper usage, this was to mitigate a call to testing.T in the event that it may help with getting osmosis-rust able to re-use go code.
=> Inline stakinghelper

.github/workflows/contracts.yml
We currently run cosmwasm tests twice per PR, taking up some unnecessary github runner contention
=> Deduplicate cosmwasm test

.github/mergify.yml
Closes: #XXX
Backport label for v12
=> chore: mergify config for v12

go.mod, proto/osmosis/twap/v1beta1/query.proto, proto/osmosis/twap/v1beta1/query.yml, x/twap/client/grpc/grpc_query.go, x/twap/client/query_proto_wrap.go, x/twap/client/queryproto/query.pb.go, x/twap/client/queryproto/query.pb.gw.go
Closes: #2597 
* Adds GetArithmeticTwapToNow query 
* fixes proto import error in query proto file
* creates proto response struct even if error, as desired
=> Add Twap GetArithmeticToNow query

simulation/executor/stats_db.go
Closes: #XXX
Fixing simulator breakage from: https://github.com/osmosis-labs/osmosis/pull/2617 to unblock CI
=> fix(ci): simulator db close

Makefile, proto/Dockerfile, proto/buf.lock, x/gamm/pool-models/balancer/balancerPool.pb.go, x/gamm/types/query.pb.go
Closes: #XXX
Context: https://github.com/cosmos/cosmos-sdk/pull/13166
This should fix our check proto CI.
Additionally, I moved the proto-builder image to our repository to have the flexibility of updating it and pushing it to our Docker Hub: https://hub.docker.com/repository/docker/osmolabs/osmo-proto-gen
=> fix(build/ci): proto generation

app/upgrades/v8/README.md, cmd/querygen/README.md, networks/osmosis-1/upgrades/v10/guide.md, networks/osmosis-1/upgrades/v11/mainnet/guide.md, networks/osmosis-1/upgrades/v11/testnet/guide.md, simulation/ADR.md, tests/localosmosis/README.md, x/README.md, x/epochs/README.md, x/incentives/README.md, x/mint/README.md, x/pool-incentives/README.md, x/twap/README.md, x/txfees/README.md
This PR tests the `make markdown` functionality added in #2630 to determine if there are any changes that need to be made and  to clean up our existing markdown files (so as to not clutter future outputs of `make markdown` or `make mdlint`)
- Ran `make markdown`
=> Fix markdown files using `make markdown`

CHANGELOG.md
Begin cleanup / preparation of the v12 changelog. I think there is still more to go though
=> Start changelog prepartion

wasmbinding/stargate_whitelist.go
We forgot to add these queries
=> Add tokenfactory and TWAP to query whitelist

x/ibc-rate-limit/README.md
Fixes issues in rate limit linter so tests on main can pass.
=> readme lints

chain.schema.json
Closes: #XXX
Resolves failing automated Chain Registry osmosis/chain.json::codebase updates.
-add genesis object (w/ URL)
-add version array
None
*(or)*
*(or)*
This change added tests and can be verified as …
=> update chain.schema.json to align with Chain Registry

x/twap/export_test.go, x/twap/logic.go, x/twap/logic_test.go, x/twap/types/expected_interfaces.go
Closes: #2658
Add unit tests for `getSpotPrices` to increase test coverage.
Add `TestGetSpotPrices` test suite.
=> chore: Test GetSpotPrices

osmomath/sigfig_round_test.go
Closes: #2621
> Add table-driven tests for SigFigRound math function
=> add test cases for SigFigRound function

go.mod, go.sum
Closes: #XXX
Branch: https://github.com/osmosis-labs/cosmos-sdk/tree/v0.45.0x-osmo-v12
Tag: https://github.com/osmosis-labs/cosmos-sdk/releases/tag/v0.45.0-osmo-v12
=> chore: update sdk fork dependency (v12)

.gitpod.yml
Update the gitpod image to a newer, better one. 
ghcr.io/faddat/cosmos -> ghcr.io/notional-labs/cosmos
N/A because it is quite small. 
- Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? no - very minor change
- How is the feature or change documented? it isn't but I should add this to a developer guide.
=> chore: update gitpod

x/incentives/types/gauge.go
Closes: #2796
Addressing a comment that did not get addressed prior to merge.
=> x/incentives: make active inclusive of current time

go.mod, go.sum
Bump to IBC v3.3.0, which has a minor security fix.
=> bump IBC version

x/gamm/keeper/swap_test.go, x/gamm/pool-models/balancer/pool.go, x/gamm/types/constants.go
Closes: #2758 
> Refer from #2758, remove `BalancerGasFeeForSwap` constant & refact related test for v12
=> Revert fixed gas cost for v12

networks/osmosis-1/upgrades/v12/v12_binaries.json
Closes: #XXX
I am about to upgrade the testnet and would like to include a raw github link in the info parameter. Since we have not tagged v12 proper yet, I need a placeholder to point to until we create the final binaries (if I leave this info field out it may lead to syncing issues in the future for testnet).
=> chore: v12 binaries json placeholder

CHANGELOG.md
Closes: #2600
Skimmed changelog and compared to relevant branches.
=> chore: review changelog for v12

Makefile
Closes: #XXX
This PR is to address problems with building osmosis binaries
ref: https://github.com/osmosis-labs/osmosis/pull/2841#discussion_r979117987
=> chore: fix builder

cmd/querygen/templates/grpcTemplate.go, cmd/querygen/templates/grpc_template.tmpl, networks/osmosis-1/upgrades/v12/v12_binaries.json, x/twap/client/grpc/grpc_query.go
Fixes the codegen inconsitencies
=> Fix codegen inconsistency

networks/osmosis-1/upgrades/v12/mainnet/guide.md, networks/osmosis-1/upgrades/v12/testnet/guide.md
This PR includes the:
- Completed testnet upgrade guide
- Mostly complete mainnet guide
The mainnet guide will just have to be filled in with some details when the prop goes live tomorrow but the majority of it is there.
- Complete testnet v12 upgrade guide
- Outline mainnet v12 upgrade guide
=> chore: mainnet and testnet v12 upgrade guides

tests/localosmosis/docker-compose.yml
Closes: #XXX
Fixes bug found by @p0mvn when setting up for hackathon. Docker it created osmosisd folder instead of a .osmosisd folder.
* Fixes docker-compose file
=> fix: localosmosis home bug

tests/localosmosis/docker-compose.yml, tests/localosmosis/scripts/nativeDenomPoolA.json, tests/localosmosis/scripts/nativeDenomPoolB.json, tests/localosmosis/scripts/nativeDenomThreeAssetPool.json, tests/localosmosis/scripts/setup.sh
Closes: #XXX
*(or)*
*(or)*
*(example:)*
- …
=> feat: add second two asset pool to LocalOsmosis

chain.schema.json
=> Add chain registry update

.github/labeler.yml
Remove changelog from docs label in labeler.yml
=> Remove changelog from docs label

cmd/osmosisd/cmd/init.go
Update BlockNgine seed URL to re-branded AutoStake seed
=> Update BlockNgine seed -> AutoStake seed

.github/mergify.yml
=> update mergify config

chain.schema.json
Update chain scheme.json to new 12.1.0
Side note, we really need to automate this!
- Updates chain scheme for chain registry
=> chore: update chain.schema.json

app/export.go, go.mod, go.sum
This is the corresponding PR on the osmosis end for https://github.com/osmosis-labs/cosmos-sdk/pull/339
=> Using second helper function for ExportGenesis

app/apptesting/gamm.go
Closes: #XXX
Address this [TODO](https://github.com/osmosis-labs/osmosis/blob/d4e8718027c7f67dccfad7dfe00f64b1c7131a8b/app/apptesting/gamm.go#L125)
*(or)*
*(or)*
*(example:)* …
=> minor changes in gamm apptesting func

tests/e2e/configurer/chain/chain.go, tests/e2e/configurer/chain/node.go, tests/e2e/configurer/chain/queries.go, tests/e2e/configurer/upgrade.go, tests/e2e/e2e_test.go
Closes: #XXX
*(or)*
*(or)*
*(example:)*
- …
=> fix: cherry pick e2e fix

osmomath/decimal.go, osmomath/decimal_test.go, osmomath/log2_bench_test.go
Basic approx log from https://github.com/osmosis-labs/osmosis/pull/2788
=> CL: basic approx log

x/concentrated-liquidity/pool.go
Adds tickToPrice and priceToTick functions
=> feat: adds tick price functions

chain.schema.json
Closes: #XXX
To update the chain schema codebase data. This file Auto-updates the chain registry.
Added ibc data (ibc go version and enabled features(ics-20),
fix genesis name, (was version number before, now goes by name)
minor formatting chg.
--> This change is a trivial rework / code cleanup without any test coverage.
*(or)*
This change is already covered by …
=> Chain.schema.json: Added ibc data, fix genesis name, formatting

x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/pool.go, x/concentrated-liquidity/pool_test.go
Closes: #XXX
*(or)*
*(or)*
*(example:)*
- …
=> feat: further CL swap generalization

.github/labeler.yml
Closes: #3046
Adds labels for two incoming modules. This must be merged to main before getting merged to our branch, otherwise CI will not auto apply these labels.
=> chore: concentrated liquidity label

.github/mergify.yml, .github/workflows/lint.yml, .github/workflows/test.yml
Closes: #3090
Runs tests on CL branch and creates backport  mergify config
=> ci(CL): run tests on CL branch and add backport config

app/keepers/keepers.go
Adds store key for the swap router module
=> Add store key for swap router

x/gamm/keeper/swap.go
Closes: #XXX
update comment in gamm module
=> [x/gamm]Update comment in gamm module (super small change)

.github/mergify.yml
Closes: #XXX
There is a character limit on the label names. Changing to something short.
=> chore: update concentrated liquidity backport label

.github/workflows/test.yml, x/gamm/pool-models/stableswap/amm_test.go
This step has been failing on open PR's, but also isn't actually needed.
Was based on some prior understanding of github actions that seems like it may not apply.
=> CI: Delete failing step

docs/architecture/concentrated-liquidity-adr.md
This PR adds docs for the `JoinPosition` API and the math and equations on how we solve the amount of token0 and token1 given the amount to join and the upper tick and the lower tick
=> Add docs for `JoinPosition` for concentrated liquidity

.github/workflows/test.yml
Closes: #XXX
Take fix from main and implement in cl-main so CI passes
=> fix: should run CI go test

.github/workflows/contracts.yml
Closes: #XXX
*(or)*
*(or)*
*(example:)*
- …
=> chore: remove cosmwasm lint from CI

x/concentrated-liquidity/lp.go
Closes: #3155
Supports cross tick for creating a position in a concentrated liquidity pool.
=> Support cross tick create position

x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/math_test.go
Closes: #3156 
*(or)*
*(or)*
*(example:)*
- …
=> chore: liq0/liq1 table driven test framework

x/concentrated-liquidity/keeper_test.go, x/concentrated-liquidity/pool.go, x/concentrated-liquidity/pool_test.go
Closes: #XXX
*(or)*
*(or)*
*(example:)*
- …
=> chore: enable bool check for ticks and add setup

x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/math_test.go
Closes: #3156 
*(or)*
*(or)*
*(example:)*
- …
=> chore: calc swap step table driven tests

x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/math_test.go
Closes: #3156
*(or)*
*(or)*
*(example:)*
- …
=> chore: calcdelta0/calcdelta1 table drive test framework

x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/math.go, x/concentrated-liquidity/math_test.go
Closes: #3156
*(or)*
*(or)*
*(example:)*
- …
=> chore: table driven test for next sqrt price0/1

x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/pool.go, x/concentrated-liquidity/pool_test.go, x/concentrated-liquidity/tick.go, x/concentrated-liquidity/tick_test.go
Closes: #XXX
*(or)*
*(or)*
*(example:)*
- …
=> chore: table driven test for price/tick tick/price

x/concentrated-liquidity/math.go, x/concentrated-liquidity/math_test.go
Closes: #XXX
*(or)*
*(or)*
*(example:)*
- …
=> chore: add wolfram calculation to tests

chain.schema.json
updates chain.schema.json
update osmosisd and cosmos sdk version numbers, binary links
added "v" in `recommended_version` number to unify with chain registry
=> update version numbers

osmomath/decimal.go, osmomath/decimal_test.go
Closes: #3132 
`log` functions
tests added (2 test cases end with too big absolute error, I commented them in code)
- How is the feature or change documented? no
=> osmomath(log/CL): ln(x), log_1.0001(x), log_custom(x)

x/concentrated-liquidity/pool.go
Removes dust check from the iteration happening in the swapping logic.
Existing tests passing even after removing the dust check :) 
=> CL(Swap): Remove dust check 

docs/architecture/concentrated-liquidity-adr.md
Closes: #XXX
This PR documents the design of the `swaprouter` module.
Part of the spec is already prototyped here:
- https://github.com/osmosis-labs/osmosis/pull/3170
The part that remains to be implemented is creating a new store index to map pool id -> swap module. Further issues TBD.
- [Rendered Diff](https://github.com/osmosis-labs/osmosis/pull/3233/files?short_path=569fba2#diff-569fba2f555881c3b2a243808fc3e24c52d9fd1e4322adb61c468ecdfcab75c4)
- [Rendered](https://github.com/osmosis-labs/osmosis/blob/bd08800b0d91b5cffc1f63b83fbdf0fe59830f12/docs/architecture/concentrated-liquidity-adr.md)
=> docs(CL): Swaprouter module, integrations and migrations

x/concentrated-liquidity/types/codec.go, x/concentrated-liquidity/types/errors.go, x/concentrated-liquidity/types/msgs.go, x/concentrated-liquidity/types/msgs_test.go
Closes: #3140 
Implement `ValidateBasic()` for msgs.
Add tests
Test cases added & passed
=> Msgs validate basic

x/swaprouter/keeper_test.go
Closes: #3237 
Define `InitGenesis` and `ExportGenesis` tests on the suite
All existing tests passed
=> Swaprouter: refactor `InitGenesis` & `ExportGenesis`

CHANGELOG.md
Updating changelog for release
=> chore: v12 changelog

docs/architecture/concentrated-liquidity-adr.md
Update swaprouter spec with  changes from: https://github.com/osmosis-labs/osmosis/pull/3269
=> chore(CL): update swaprouter spec

x/gamm/module.go, x/gamm/pool-models/stableswap/codec.go, x/gamm/types/msgs_test.go
Add ledger serialization for Stableswap, and the cursed authz serialization. We should make this automated, I don't understand any reason as to why this is manual.
This change added tests and can be verified as follows: See the new test case
=> Add ledger support for stableswap

x/ibc-hooks/README.md
Add beginning of spec for IBC wasmhook
Add spec
=> Add basic WASM hook spec

app/app.go, app/keepers/modules.go, app/modules.go, app/upgrades/v13/upgrade_test.go, x/ibc-hooks/genesis.go, x/ibc-hooks/sdkmodule.go
PR adding module account creation on InitGenesis for IBC hooks, meant for wasm hooks' need.
Please take over
- Add IBC hooks module account
Adds test that an upgrade with no module acc adds the module account. 
- How is the feature or change documented? Spec
=> Add IBC hooks module account

x/gamm/keeper/msg_server_test.go, x/gamm/keeper/multihop.go, x/gamm/types/route.go
Breaks up the osmo router code more
=> Break up osmo router code more

tests/localosmosis/scripts/setup.sh
Closes: #XXX
*(or)*
*(or)*
*(example:)*
- …
=> fix: localosmosis home folder in setup.sh

Makefile, tests/e2e/configurer/chain/queries.go
Closes: #XXX
Context: https://github.com/osmosis-labs/osmosis/issues/3208
Needed to unblock the issue
=> fix(e2e): make test-e2e-short false failure

x/gamm/keeper/export_test.go, x/gamm/keeper/multihop_test.go
Closes: #XXX
With modifications to the osmo multi-hop fee reduction logic, we needed to also modify the table driven tests. This PR simplifies the current table driven test logic as well as implements the new fee logic.
=> chore: modify multi-hop table driven tests

x/gamm/pool-models/internal/test_helpers/test_helpers.go, x/gamm/pool-models/stableswap/amm_test.go
Component of #3370
Adds a test that slippage goes down as liquidity increases.
=> Ensure stableswap slippage improves with liquidity

proto/osmosis/gamm/v1beta1/query.proto, x/gamm/keeper/grpc_query.go, x/gamm/keeper/multihop.go, x/gamm/keeper/multihop_test.go, x/gamm/types/query.pb.go
Alternate to @mattverse 's great PR for fixing Estimate Swap. A bit worried about trying to get that code to land pre-release, relative to more code duplication. This PR tries a code dup approach.
*(or)* …
=> Code duplication approach to fixing EstimateSwap

wasmbinding/stargate_whitelist.go
Add EstimateSwapExactAmountIn to the query whitelist
- Adds EstimateSwapExactAmountIn to the query whitelist
Should we add tests for this query specifically via the stargate endpoint?
=> added EstimateSwapExactAmountIn to the stargate whitelist

x/gamm/keeper/pool_service.go
Improve some GAMM error messages
=> Improve some gamm error messages that came up in QA

x/concentrated-liquidity/pool.go, x/concentrated-liquidity/pool_test.go, x/concentrated-liquidity/position.go, x/concentrated-liquidity/tick.go
Closes: #XXX
Slight adjust to logic to allow for gap positions
Adds gap position pool test and concurrent position pool test
=> CL: Partially overlapping / gap price range test/logic

docs/architecture/concentrated-liquidity-adr.md
Closes: #XXX
Spec for concentrated liquidity fees.
Also, referenced this doc by @nicolaslara: https://hackmd.io/-fM-_9KaQkefllfn4R0sig
=> docs(CL): fees spec

app/apptesting/gamm.go, x/swaprouter/creator_test.go, x/swaprouter/keeper_test.go, x/swaprouter/router_test.go
Closes: #XXX
Adds swaprouter tests ported from main
=> CL: add swaprouter tests

networks/osmosis-1/upgrades/v13/mainnet/guide.md, networks/osmosis-1/upgrades/v13/testnet/guide.md, networks/osmosis-1/upgrades/v13/v13_binaries.json
Closes: #XXX
Adds binary json template and upgrade instruction template
=> chore: v13 upgrade template

app/keepers/keepers.go, x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/keeper.go, x/concentrated-liquidity/lp.go, x/concentrated-liquidity/lp_test.go, x/concentrated-liquidity/pool_test.go, x/concentrated-liquidity/tick_test.go, x/concentrated-liquidity/types/expected_keepers.go
Closes: #XXX
As part of an offline conversation, we agreed to remove the BankSend logic from [this PR](https://github.com/osmosis-labs/osmosis/pull/3497) and create a separate PR for it. This PR introduces the BankSend logic for creating and leaving a position.
=> feat(CL): add bank sends to positions

x/superfluid/keeper/msg_server.go, x/superfluid/keeper/unpool_test.go
Closes: #XXX
Add a test for unpooling when not whitelisted
=> test(superfluid): unpool when not whitelisted

x/gamm/pool-models/stableswap/pool_test.go
Closes: #3435
tests for `getLiquidityIndexMap`
=> gamm: TestGetLiquidityIndexMap

osmoutils/store_helper.go, osmoutils/store_helper_test.go, x/superfluid/keeper/unpool.go
Closes: #3530
We would like to rename the `osmoutils` "get" helper and simplify its spec according to the conclusion in #3530
=> refactor(osmoutils): rename GetIfFound to Get, simplify godoc

x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/keeper_test.go, x/concentrated-liquidity/pool.go, x/concentrated-liquidity/pool_test.go, x/concentrated-liquidity/tick.go, x/concentrated-liquidity/tick_test.go, x/concentrated-liquidity/types/errors.go
Partially Closes: #3157 
Adds table driven test for initOrUpdateTick
Fulfills following requirements as laid out in the issue:
=> tests[CL]: initOrUpdateTick table driven tests (1/x)

app/apptesting/test_suite.go, x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/internal/math/math.go, x/concentrated-liquidity/internal/math/math_test.go, x/concentrated-liquidity/internal/swapstrategy/one_for_zero.go, x/concentrated-liquidity/internal/swapstrategy/swap_strategy.go, x/concentrated-liquidity/internal/swapstrategy/swap_strategy_test.go, x/concentrated-liquidity/internal/swapstrategy/zero_for_one.go, x/concentrated-liquidity/swaps.go, x/concentrated-liquidity/tick.go, x/concentrated-liquidity/tick_test.go, x/concentrated-liquidity/types/errors.go
Closes: #3530
Progress towards: #3218 
This PR continues to integrate strategy pattern into the swaps.
It removes all existing `zeroForOne` checks. Instead, utilizes the strategy that dynamically utilizes the desired implementation.
All strategy logic has been moved into its own package and each strategy has been separated into its own file.
Godocs added, outlining the implementing details of each strategy.
Only pre-existing tests have been ported. New tests have not yet been added as the refactor is still in-progress and the interfaces are not finalized.
=> refactor(CL): continue integrating strategy pattern into swaps

networks/osmosis-1/upgrades/v13/v13_binaries.json
=> Add v13_binaries.json

.github/workflows/mutest-issue-generate.yml, go.mod, go.sum
This PR changes our automatic mutation tests to run bi-weekly instead of weekly and updates its version to include new filters (lower noise) and cosmos-native mutation support
- Update cron time from 1pm every Monday to 1pm on the 1st and 15th of every month
- Manually ran mutation tests to ensure version update works as intended
=> Mutation testing: update mutation tests to run bi-weekly and update version to include new functionality

x/ibc-hooks/sdkmodule.go
Forgot to set an empty value (smh we can't just omit ExportGenesis atm, and have a framework handle this for us)
Manually tested on a newly synced node.
=> Fix state export

chain.schema.json
updates chain.schema.json
update osmosisd version numbers, binary links, upgrade info
=> update chain.schema.json for v13

CHANGELOG.md, wasmbinding/stargate_whitelist.go
This PR allows WASM contracts to estimate the swap input amount if the output amount is determined.
- adds `/osmosis.gamm.v1beta1.Query/EstimateSwapExactAmountOut` query message to whitelist and registers its response with `&gammtypes.QuerySwapExactAmountOutResponse{}`
--- needs e2e test via live contract
=> Whitelist EstimateSwapExactAmountOut

cmd/osmosisd/cmd/init.go
It was suggested we should wait for governance before setting this
https://discord.com/channels/798583171548840026/842550346865180682/1050411289500979310
Remove 2s timeout_Commit
=> Remove 2s timeout_commit

.github/workflows/push-dev-docker-images.yml
This PR ports a workflow from `main` to `v13.x` so it can run on every push to `v13.x` 
- Add docker dev workflow
N.A.
- Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? no 
=> Add workflow

x/swaprouter/create_pool_test.go
Closes: #XXX
Merging test for swaprouter's `CreatePool`
=> test(x/swaprouter): TestCreatePool (merge)

x/twap/keeper_test.go, x/twap/logic_test.go
Closes: #3443
Adding 3-asset geometric twap logic tests as per issues
=> test(x/twap): 3-asset geometric logic tests

x/swaprouter/keeper_test.go
Closes: #XXX
Porting swaprouter genesis tests
=> test(x/swaprouter): genesis tests

CHANGELOG.md
First pass changelog update for v14
=> v14: First pass changelog update

x/concentrated-liquidity/model/codec.go
Closes: #XXX
`main` is broken due to merge conflict. This PR fixes it.
=> fix: merge conflict on main

tests/e2e/e2e_test.go, x/ibc-hooks/README.md
Closes: #XXX
This is a very simple PR addressing the issues brought up in https://github.com/osmosis-labs/osmosis/pull/3937/files that were not included before it was merged. It's mostly typos/stylistic changes
all tests pass
=> Address unadressed review comments for wasmhooks

.github/workflows/contracts.yml
Contract CI is failing to run because of a bad variable. Fixing that.
- use the env variable 
Contract CI runs (and passes)
=> Fix contract CI failing

tests/ibc-hooks/test_crosschain_swaps.sh, x/ibc-hooks/contracts/crosschain-swaps/README.md, x/ibc-hooks/contracts/crosschain-swaps/schema/crosschain-swaps.json, x/ibc-hooks/contracts/swaprouter/schema/execute_msg.json, x/ibc-hooks/contracts/swaprouter/schema/get_owner_response.json, x/ibc-hooks/contracts/swaprouter/schema/get_route_response.json, x/ibc-hooks/contracts/swaprouter/schema/instantiate_msg.json, x/ibc-hooks/contracts/swaprouter/schema/query_msg.json
Better docs for crosschain swaps
- Added testing details and a better spec in the readme
- Updated the schemas
all tests pass
- Does this pull request introduce a new feature or user-facing behavior changes? (yes )
- Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (/ no)
- How is the feature or change documented? (not applicable
=> Improved docs for crosschain swaps

x/tokenfactory/README.md
Adding some examples for the tokenfactory module to speed up the learning curve for a people that have reached out to learn more about it.
=> Creating a CLI Examples Section for Tokenfactory

x/concentrated-liquidity/tick_test.go
Closes: #XXX
Misc: Simple fixes for existing test cases on error checks
=> (CL): Misc test fix for ticks error catching

x/concentrated-liquidity/lp.go, x/concentrated-liquidity/lp_test.go
Closes: #XXX
Reported by @czarcas7ic 
There is a bug in `withdrawPosition` where it does not send the amounts from pool to user. 
The reason is that `sendCoinsBetweenPoolAndUser` only sent coins when the given amounts were positive.
However, `updatePosition` returned negative amounts indicating the removal from the pool.
As a result, the withdrawn amounts were never sent from pool to user. Our tests did not catch this.
- tested both `withdrawPosition` and `sendCoinsBetweenPoolAndUser` to reproduce the bug
fixed the bug by:
- improving error checking in `sendCoinsBetweenPoolAndUser`
- taking an absolute value of the amounts in `withdrawPosition`
This change added tests.
- Is a relevant changelog entry …
=> fix(CL LP): withdraw position does not send negative tokens

Dockerfile, Makefile, go.mod, go.work.sum, osmomath/go.mod, osmoutils/go.mod, x/ibc-hooks/go.mod
Closes: #XXX
Updates go to 1.19 (backport of 3947)
=> chore: Bump golang version to v1.19 (#3947)

networks/osmosis-1/upgrades/v14/mainnet/guide.md, networks/osmosis-1/upgrades/v14/v14_binaries.json
Closes: #XXX
Upgrade v14 binaries and guide
=> chore: v14 binaries and guide

x/concentrated-liquidity/client/cli/tx.go
Closes: #4028 
Refer from #4028 , I added cli for `collectFees` func
CLI can execute in my local 
=> `collectFees` cli

wasmbinding/stargate_whitelist.go, x/lockup/keeper/msg_server.go
Add LockedByID stargate whitelist so that CosmWasm contract can query lock
- Add LockedByID stargate whitelist
=> Add LockedByID stargate whitelist

CHANGELOG.md
Part of : https://github.com/osmosis-labs/osmosis/issues/2579
Add changelog entry
added
n/a
=> [ValSet-Pref] Add Changelog entry

x/concentrated-liquidity/architecture.md, x/gamm/README.md, x/poolmanager/README.md
Closes: #3881
This PR adds a README for the `poolmanager` module.
This README is extracted from the [concentrated-liquidity architecture](https://github.com/osmosis-labs/osmosis/blob/4a81ee507561a5296fdeaf5f6905dd030d36d9c8/x/concentrated-liquidity/architecture.md#L459) as well as the GAMM module spec.
The CL architecture file was also updated.
Obsolete documentation from `x/gamm/README.md` was removed. Linked to `poolmanager` instead.
=> docs(x/poolmanager): module README

chain.schema.json
What is the purpose of the change
updates chain.schema.json
Brief Changelog
update osmosisd version numbers, binary links, upgrade info
Testing and Verifying
Documentation and Release Note
Does this pull request introduce a new feature or user-facing behavior changes? (no)
Is a relevant changelog entry added to the Unreleased section in CHANGELOG.md? (no)
How is the feature or change documented? (not applicable)
=> update chain.schema.json for v14

go.mod, go.sum, go.work.sum, osmoutils/osmocli/parsers.go, osmoutils/osmocli/parsers_test.go
- add parser
- add test
Closes: #4092
Adds `Dec` parser to `osmocli`. 
ditto 
Adds test
N/A
=> osmocli: dec parser

tests/e2e/README.md
=> e2e: docs update

x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/fees.go, x/concentrated-liquidity/fees_test.go, x/concentrated-liquidity/keeper_test.go, x/concentrated-liquidity/lp.go, x/concentrated-liquidity/lp_test.go, x/concentrated-liquidity/position.go
Closes: #XXX
*(or)*
*(or)*
*(example:)*
- …
=> feat: single fee accum

x/concentrated-liquidity/architecture.md
I was going through https://github.com/osmosis-labs/osmosis/blob/main/x/concentrated-liquidity/architecture.md, left some changes that in my opinion make more sense now
=> CL, docs: architecture walkthrough 

tests/localosmosis/README.md
See title & https://github.com/osmosis-labs/osmosis/blob/main/Makefile#L418
=> Update homepath local osmosis README 

x/concentrated-liquidity/internal/math/tick.go, x/concentrated-liquidity/internal/math/tick_test.go
Closes: #3985 
When computing PriceToTick, we previously looped through exponents (incrementing or decrementing depending on if the desired price is above or below 1) until we reached the first exponent that is greater than the desired price:
https://github.com/osmosis-labs/osmosis/blob/00c430bab18e8ac9d4776180d677ca3b65aaaec5/x/concentrated-liquidity/internal/math/tick.go#L124-L143
This PR abstracts this logic into a helper function with tests, as requested in the below discussion:
https://github.com/osmosis-labs/osmosis/pull/3874#discussion_r1066576987
- Abstracts priceToTick loop into `CalculatePriceAndTicksPassed` function
- Adds tests for this function
- Is a relevant changelog entry added to …
=> chore: abstract priceToTick loop to helper func

osmoutils/cache_ctx_test.go
I broke main build when merging #3746 , this was because the last test run was 4 weeks old, and we had import path changes + the go-mod'ning happen. This PR fixes build
=> Fix main build

x/concentrated-liquidity/client/cli/tx.go
`frozenUntil` to `NewWithdrawPositionCmd`
=> CLI: add frozenUntil to example and use of NewWithdrawPositionCmd

CHANGELOG.md
Forgot to add the changelog entry for Async ICQ (sorry)
- added changelog entry
all tests pass. This change is trivial
=> Async ICQ changelog

go.work, go.work.sum
I noticed go.work was still on 1.18. I don't think this matters much, but updated it for consistency
- Updated go.work to 1.19
all tests pass. This is a trivial change that should only have effects when running locally. 
=> Update go.work to 1.19

tests/localosmosis/docker-compose.yml, tests/localosmosis/scripts/stableswapPool.json
Closes: #4239 
Add stableswap pool to localosmosis's scripts folder for testing purposes.
Add stableswapPool.json and update docker-compose
=> Add stableswapPool.json and update docker-compose

go.mod, go.sum, go.work.sum
update PFM a minor version to include https://github.com/strangelove-ventures/packet-forward-middleware/commit/231a05ea5ddb76169ce09e2b71a458e1bac604fb
Updated PFM
all tests pass
=> Minor version update to pfm

tests/e2e/initialization/config.go
Closes: #XXX
Attempting to update e2e genesis to fix e2e on https://github.com/osmosis-labs/osmosis/pull/4244
=> chore(e2e) update v14.x genesis for #4244

x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/tick.go, x/concentrated-liquidity/tick_test.go
Closes: https://github.com/osmosis-labs/osmosis/issues/3983
Adds unit tests for `validateTickInRangeIsValid` method
This PR adds new tests.
=> (CL Test): Add tests for `validateTickInRangeIsValid`

.github/workflows/push-dev-docker-images.yml
Closes: #XXX
My previous PR broke the syntax. This is the fix, the syntax was validated by the GitHub Actions VSCode extension
=> fix: github actions push dev images workflow syntax

CHANGELOG.md
Closes: #XXX
Updating changelog on main for v14.0.1
=> chore: update changelog on main for v14.0.1

CHANGELOG.md
Closes: #XXX
Updating changelog for v14.0.1 release
=> chore: v14.0.1 changelog on v14.x

scripts/cl/README.md, scripts/cl/common/common.py, scripts/cl/common/sdk_dec.py, scripts/cl/in_given_out.py, scripts/cl/math.py, scripts/cl/one_for_zero.py, scripts/cl/out_given_in.py, scripts/cl/test/test_common.py, scripts/cl/zero_for_one.py, x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/fees_test.go, x/concentrated-liquidity/internal/swapstrategy/fees.go, x/concentrated-liquidity/internal/swapstrategy/fees_test.go, x/concentrated-liquidity/swaps.go, x/concentrated-liquidity/swaps_test.go, x/concentrated-liquidity/tick.go, x/concentrated-liquidity/tick_test.go
Closes: #XXX
- Final (hopefully) fixes for functional tests
- Fixes cross-tick accumulator update logic. 
- Refactors Python scripts to use fixed point arithmetic (same as Cosmos-SDK).
- Recalculates swap test estimates
=> fix/test(CL Swaps): fix cross tick logic, re-estimate tests; final changes for functional tests

scripts/cl/README.md, scripts/cl/common/common.py, scripts/cl/common/sdk_dec.py, scripts/cl/in_given_out.py, scripts/cl/math.py, scripts/cl/one_for_zero.py, scripts/cl/out_given_in.py, scripts/cl/test/test_common.py, scripts/cl/zero_for_one.py, x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/fees_test.go, x/concentrated-liquidity/internal/swapstrategy/fees.go, x/concentrated-liquidity/internal/swapstrategy/fees_test.go, x/concentrated-liquidity/keeper_test.go, x/concentrated-liquidity/swaps.go, x/concentrated-liquidity/swaps_test.go, x/concentrated-liquidity/tick.go, x/concentrated-liquidity/tick_test.go
Closes: #4089 
This functional test swaps across various positions and checks the resulting fees claimed against what we expect.
- Functional test added
- Helper functions to create various positions added to `keeper_test.go`
=> tests: functional test for CL fees

x/concentrated-liquidity/README.md
Closes: #XXX
Update LP section and rename architecture.md to README.md
=> docs(CL): update LP section and rename architecture.md to README.md

x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/lp.go, x/concentrated-liquidity/msg_server.go, x/concentrated-liquidity/position.go
Closes: #XXX
Unexporting methods for better information hiding.
=> refactor: unexport CL lp methods

x/poolmanager/client/cli/query_test.go, x/poolmanager/client/query_proto_wrap.go, x/poolmanager/module/module.go
Closes: #4392 
Seem that we didn't regist `QueryServer` for `poolmanager` module
Missing test of queries
Registed `QueryServer` in `poolmanager.module`
Add test
*(or)*
*(or)*
*(example:)* …
=> Fix poolmanager query

x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/incentives_test.go
Closes: https://github.com/osmosis-labs/osmosis/issues/4339
Opening this PR to merge directly to main and resolve merge conflicts in https://github.com/osmosis-labs/osmosis/pull/4353
n/a
*(or)*
*(or)*
*(example:)* …
=> Re[CL:Incentives] Add further tests to uptime accumulator update logic

go.mod, go.sum, osmomath/go.mod, osmomath/go.sum, osmoutils/go.mod, osmoutils/go.sum, x/ibc-hooks/go.mod, x/ibc-hooks/go.sum
Closes: #XXX
Updating to: https://github.com/osmosis-labs/cosmos-sdk/commit/44b40d47f3108c29f07fd115e5a92b387fb7a6bd
=> chore: update sdk fork dependency

CHANGELOG.md
Closes: #XXX
Updating changelog for v15
=> chore: v15 changelog

x/concentrated-liquidity/swaps_test.go
Went through some CL's swap tests, added some visuals for readability
=> CL: swap walkthrough

x/protorev/keeper/posthandler.go
Were using an infinite gas meter in the post handler: https://github.com/osmosis-labs/osmosis/blob/main/x/protorev/keeper/posthandler.go#L39
This PR changes it to have an upperbound, in case of an accidental uncaught infinite loop. We want it to be another defense in depth against accidental non-halting behavior. (Any infinite loop with a state read would eventually halt with this)
=> Add gas meter limit to protorev

tests/localosmosis/scripts/setup.sh
Closes: #XXX
Jacky is integrating FE into localosmosis CL. Reported having issues with denoms not being registered.
This PR registers 2 denoms needed to create a uosmo uion CL pool for testing.
- Tested by creating a CL pool in localosmosis
=> fix(localosmosis): register denom metadata

tests/localosmosis/scripts/setup.sh
Closes: #XXX
Frontend is requesting a simple way to spin up localosmosis with CL state. In addition to the three gamm pools that get spun up with `make localnet-start-with-state`, this now includes a fourth CL pool with four positions.
* One OSMO<>ION CL Pool
* Four Positions  with the following tick ranges
* -1620000 3420000
* 305450 315000
* 315000 322500
* 300000 309990
=> feat: add CL state to localosmosis

.gitignore
Closes: #XXX
As discussed offline, adding go.work.sum to .gitignore
- Adds go.work.sum, to .gitignore
=> chore: add go.work.sum to .gitignore

CHANGELOG.md
Closes: #XXX
Cleaning up changelog for final tag.
=> chore: v15 changelog update

CHANGELOG.md
Closes: #XXX
Fix changelog conflict
=> chore: fix changelog conflict

networks/osmosis-1/upgrades/v15/mainnet/guide.md
Closes: #XXX
v15 upgrade guide
=> chore: v15 upgrade guide

app/apptesting/concentrated_liquidity.go, x/poolmanager/keeper_test.go, x/poolmanager/router.go, x/poolmanager/router_test.go, x/poolmanager/types/routes.go
Closes: #XXX
Adds Concentrated Liquidity Module to Pool Manager Module, needs to be done in order to support twap for CL.
Adds Concentrated Liquidity Module to Pool Manager Module, needs to be done in order to support twap for CL.
Tests have been added
=> Add Concentrated Liquidity Module to Pool Manger Module

.github/workflows/gen-upgrade-on-manual-input.yml
Closes: #4577
fixes linting issues in auto upgrade handler generation
=> Fix linting issues in auto upgrade handler generation

.github/workflows/go-mod-auto-bump.yml, go.sum, osmoutils/cache_ctx_test.go, scripts/update-go-mod.sh
Closes: #4266
This PR introduces a new workflow that is being ran when PR is created with changes in one of:
- ibc-hooks
- osmoutils
- osmomath
When one of those files are changed, a script is ran, which updates versions of ibc-hooks, osmoutils and osmomath in `go.mod` and creates a PR against a branch, that triggered this action.
https://github.com/osmosis-labs/osmosis/pull/4291#issuecomment-1459619762
no
=> go.mod auto update

Makefile
Closes: #XXX
The makefile step is broken. Fix if by moving it to the new line
=> fix: localosmosis CL position creation Makefile step

chain.schema.json
Osmosis underwent a version upgrade that had not yet been reflected in the chain schema file.
-add 'v15' and related info to chain schema file
- How is the feature or change documented? (not applicable )
=> Update chain schema for v15

app/keepers/modules.go, x/gamm/client/cli/flags.go, x/gamm/client/cli/tx.go, x/gamm/client/proposal_handler.go, x/gamm/client/rest/tx.go
Closes: https://github.com/osmosis-labs/osmosis/issues/4443
Adds Client support for migration proposals and wires it to the gov module in app.go
Add Client support for migration proposals for Concentrated Liquidity
=> CL: Add Client support for migration proposals, wire it to gov module

chain.schema.json
Updated Chain Binaries URLs to v15 (I had a typo before)
See: https://github.com/cosmos/chain-registry/pull/1637/files
Updated Chain Binaries URLs to v15 (I had a typo before)
- Does this pull request introduce a new feature or user-facing behavior changes? ( no)
=> Update Binaries version to v15 in chain.schema

CONTRIBUTING.md
Closes: #4663
This PR adds a `Common Security Consideration` section to `CONTRIBUTING.md` outlining considerations around rounding behavior (as requested in https://github.com/osmosis-labs/osmosis/pull/4503#discussion_r1126314195) and panics.
Ideally we can treat this as a living doc/reference of important vectors to keep in mind and continue to populate it as we spot more patterns.
- Add `Security Considerations` section to `CONTRIBUTING.md`, which includes:
- Rounding behavior (with an example)
- Panics (with two examples)
- How is the …
=> Add `Common Security Considerations` section to `CONTRIBUTING.md`

x/concentrated-liquidity/README.md, x/concentrated-liquidity/swaps.go
Closes: #XXX
Documenting our concentrated liquidity swaps from discussions with @jonator .
It includes the high-level explanation and logic done in the swap and adds an example in the appendix, helping to visualize the swap done over a tick range with 2 positions.
=> docs(CL): Swaps

x/gamm/keeper/migrate.go
Closes: #XXX
Small change: fix wrong name of function in description
*(or)*
*(or)*
*(example:)*
- How is the feature or change documented? (not applicable   / …
=> chore: Update description for UpdateMigrationRecords function

README.md
Closes: #4144 
Adds localosmosis header to README
=> Link to `localosmosis` in readme

cmd/osmosisd/cmd/init.go
Update AutoStake seed from .net to .com
- Does this pull request introduce a new feature or user-facing behavior changes? ( no)
=> Update AutoStake seed from .net to .com

app/upgrades/v15/upgrade_test.go
Closes: #XXX
*(or)*
*(or)*
*(example:)*
- …
=> chore: re-comment out upgrade handler test

.github/workflows/check-broken-links.yml
Closes: #4745 
Runs link checking workflow on 1st and 15th of every month (cannot explicitly specify something like `every two weeks` in cron time)
minor
=> GH Actions: link checker runs every two weeks

tests/cl-go-client/main.go
Closes: #XXX
Change existing process of creating positions in the go client for CLs to use go routines for faster performance. 
- Use Go Routines in CL Go client for creating positions
Tested manually in local environment
=> Use Go routines in CL go client

x/concentrated-liquidity/model/pool.go, x/concentrated-liquidity/model/pool_test.go, x/concentrated-liquidity/swaps.go, x/concentrated-liquidity/types/errors.go, x/concentrated-liquidity/types/pool.go
Closes: #4744 
Add a validation of passed parameters to `ApplySwap`:
- Liquidity not negative
- SqrtPrice not negative
- New tick within precision factor's boundaries
Adds unit test
n/a
=> CL: `ApplySwap` inputs validation

tests/e2e/e2e_test.go
Closes: https://github.com/osmosis-labs/osmosis/issues/4703
Remove unnecessary RL test
Remove unnecessary RL test
all tests pass
=> Remove unnecessary test

x/concentrated-liquidity/fees.go, x/concentrated-liquidity/incentives.go
Closes: #XXX
For some reason, when I merged in main in my last PR, the linter passed but failed the second time it was run. This fixes that problem.
=> fix: lint error

x/concentrated-liquidity/tick.go
Closes: #XXX
PR boke main due to merge conflict. This fixes it.
=> fix: CL query conflict breaking main

tests/e2e/configurer/chain/commands.go, tests/e2e/e2e_test.go, tests/e2e/helpers_e2e_test.go, x/concentrated-liquidity/export_internal.go
Closes: #4099
This PR introduces:
* `CollectFees` method to `NodeConfig`
* Adds fee collection functionality to e2e test
e2e test
no
=> [e2e][CL]: Collect Fees

tests/cl-go-client/main.go, x/concentrated-liquidity/tick.go
Closes: #XXX
Remove broken concurrency from go-client
=> chore: remove concurrency from go-client

Makefile, tests/e2e/initialization/config.go
Closes: #XXX
Updating genesis for v16 e2e upgrade test set up.
=> v15.x: update e2e genesis for CL canonical pool

networks/osmosis-1/upgrades/v13/mainnet/guide.md
Small chore cleaning and old TODO that was left in an upgrade guide.
=> [chore] Update v13 guide.md

app/keepers/keepers.go, x/concentrated-liquidity/keeper.go, x/concentrated-liquidity/keeper_test.go, x/concentrated-liquidity/tick_test.go, x/concentrated-liquidity/types/expected_keepers.go
Closes: #XXX
This PR is one of five PRs in an effort to make #4854 more reviewable.
The scope of this PR is limited to adding the lockup keeper dependencies to the cl keeper.
=> [CL]: add lockup keeper dependencies (1/5)

chain.schema.json
Closes: [This PR to the Chain Registry](https://github.com/cosmos/chain-registry/pull/1818/)
This PR adds the codebase data into the latest version object in the versions array to match the Chin Registry. Going forward, we can add updated version data before the update has taken place.
This PR adds the codebase data into the latest version object in the versions array to match the Chin Registry.
- How is the feature or change documented? (not applicabl`)
=> Add codebase data into latest version object

tests/localosmosis/docker-compose.yml, tests/localosmosis/state_export/docker-compose.yml, tests/localrelayer/docker-compose.yml
Closes: #XXX
fix the bug that happened while running `make localnet-build`
=> [fix: LocalOsmosis] Fix Alpine 1.20 error 

tests/e2e/initialization/config.go
Closes: #XXX
This PR is intended to support https://github.com/osmosis-labs/osmosis/pull/4929 so that we can test a realistic DAI IBC denom and not a hardcoded "dai"
- Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`?  no
=> e2e(CL): v15 genesis update for DAI IBC denom

cosmwasm/contracts/crosschain-swaps/README.md, cosmwasm/contracts/crosschain-swaps/src/msg.rs
This adds better documentation on how to use XCSv1
better docs
trivial change. All tests should pass.
=> Added XCS examples in the docs

tests/cl-genesis-positions/convert.go, tests/cl-genesis-positions/go.mod, tests/cl-genesis-positions/go.sum, tests/cl-genesis-positions/main.go
Closes: #XXX
Fixing script breakage from #4929
=> fix: authorized assets script breakage

CHANGELOG.md
Use the version name in the changelog
Use the version name in the changelog
this change is trivial
=> Name v15.1.0 in the changelog

CHANGELOG.md
Backporting the changelog from v15.x
Backporting the changelog from v15.x
trivial change
=> backport v15.1.0 changelog

tests/cl-genesis-positions/convert.go, tests/cl-genesis-positions/go.mod, tests/cl-genesis-positions/go.sum, tests/cl-genesis-positions/local_accounts.go, tests/cl-genesis-positions/main.go, tests/localosmosis/scripts/setup.sh
Closes: #XXX
Quick fix for cl script
=> fix: script hotfix

.github/workflows/test-e2e-makefile.yml, .github/workflows/test.yml
Closes: #XXX
We switched to self hosted runners, but the runner was not cleaning up after running e2e so subsequent PRs would fail.
- Adds clean up step to github action
=> bug: Update test-e2e-makefile.yml

.github/workflows/test-e2e-makefile.yml, .github/workflows/test.yml
Closes: #XXX
The self hosted runners are failing, this reverts the self hosted runner change so we can continue to get PRs through.
=> fix: revert self hosted runner

tests/cl-genesis-positions/go.mod, tests/cl-genesis-positions/go.sum, tests/cl-go-client/go.mod, tests/cl-go-client/go.sum
Closes: #XXX
Changes to concentrated liquidity paramaters broke the localosmosis start with state script.
=> fix: localosmosis with state script

x/concentrated-liquidity/README.md
Closes: #5070
This PR adds an incentives section to the README for CL.
- Discuss general goals for incentives
- Discuss status quo incentives
- Briefly touch on how uptime accumulators work and mention that they are turned off at launch through the authorization mechanism
=> [CL][Internal Review] Add Incentives section to CL README

README.md
This PR fixes the lint badge in the `README.md` (see: https://github.com/badges/shields/issues/8671).
Before:
After:
=> docs: fix github workflow badges

chain.schema.json
Closes: #[Another PR](https://github.com/cosmos/chain-registry/pull/1992)
-To update the Osmosis version info, as attempted by @niccoloraspa in another repo. (Changes here will automatically be carried there)
- Updates the version from v15.0.0 to v15.1.0, and updates binaries.
=> Update chain.schema.json info to v15.1.0

x/concentrated-liquidity/swaps.go
Closes: #XXX
I broke main. This is the fix
=> fix: merge conflict

.github/workflows/changelog-entry-reminder.yml
Closes: #XXX
Changes changelog reminder check from changelog to  A:no-changelog
=> Change changelog reminder check from changelog to  A:no-changelog

.vscode/launch.json
Closes: #XXX
Every time I want to debug a test, I have to manually edit an e2e config. This causes overhead when switching between branches.
This file adds config for every SDK module so that a developer can edit what they need quickly to debug a desired method in the applicable module
=> chore: add vs code debug config for every module

.github/workflows/check-broken-links.yml
this PR modifies broken links issue title, as in https://github.com/osmosis-labs/osmosis/issues/5181
Closes: #5181
Change Broken links report title as requested in #5181
=> change URL report title

x/concentrated-liquidity/keeper_test.go, x/concentrated-liquidity/swaps_test.go
Reduces some of the extra lines of code in swap_test. I suspect similar can be done in all of CL tests.
=> Remove superfluous swap_test lines

.github/mergify.yml
Closes: #XXX
- getting mergify configured for v16
=> [chore] added v16 mergify config

x/mint/README.md
Closes: #5224 
Minor fix of default epoch time
=> x/mint: fix outdated info in README 

x/concentrated-liquidity/types/codec.go
=> fix: typo in proposal codec registration

x/concentrated-liquidity/client/cli/tx.go, x/poolmanager/client/cli/tx.go
Closes: #XXX
- add cli example from clickup 
- 
all cli commands tested
=> [chore] add cli example in CL/PoolManager module

Makefile, app/keepers/keepers.go, app/keepers/modules.go, app/modules.go, app/upgrades/v15/constants.go, app/upgrades/v15/export_test.go, app/upgrades/v15/upgrades.go, go.mod, go.sum, tests/cl-genesis-positions/go.mod, x/twap/client/grpc/grpc_query.go
closes  #5258
Use IBC apps for async icq
No tests required, same module as before just new repo
=> Use IBC apps repo for AsyncICQ 

x/concentrated-liquidity/model/pool.go, x/concentrated-liquidity/model/pool_test.go
It came up during external audit that our tick range check was incorrect. We should investigate why higher level tests didn't catch this.
- Fixed & expanded unit tests in `pool_test.go`
=> [CL][bugfix] Fix tick range helper and update tests/comments

x/concentrated-liquidity/position.go
This PR removes a duplicate check in the same function on the same variable (came up during external audit).
=> [CL][bugfix] Remove duplicate check in full range creation

x/gamm/pool-models/stableswap/README.md
Closes: #XXX
@AlpinYukseloglu 's words
=> docs: stableswap scaling factor

tests/cl-genesis-positions/go.mod, tests/cl-genesis-positions/go.sum, tests/cl-go-client/go.mod, tests/cl-go-client/go.sum
Closes: #XXX
Fixes localosmosis make scripts by updating osmosis node deps in go scripts.
*(or)*
*(or)*
*(example:)*
=> Localosmosis: update test scripts version

go.mod, go.sum, osmoutils/coin_helper.go, osmoutils/coin_helper_test.go, x/concentrated-liquidity/incentives_test.go, x/concentrated-liquidity/keeper_test.go, x/concentrated-liquidity/position_test.go
Progress towards #5051
This PR does a refactor and cleanup of fungification tests to cut down on duplicate code and make assertions simpler/more readable. With these changes, the cases requested in #5051 can be added much more easily.
Specific changes:
* Abstract duplicate code into helpers
* Abstract long checks into helpers to minimize code assertion length
* Remove superfluous error checks
* Remove duplicate assertion
* Move `AddDecCoinsArray` to osmoutils
* Implement and test `CollapseDecCoinsArray` helper in osmoutils
=> [CL][Tests]: Clean up `FungifyPositions` tests

x/concentrated-liquidity/position_test.go
Closes: #5156 
Adds a direct unit test for `CreateFullRangePositionLocked`
Where is the change documented? 
N/A
=> [CL]: TestCreateFullRangePositionLocked

.github/workflows/check-broken-links.yml
Closes: #5385 
Add Help Wanted and Good First Issue labels to link checker report
=> Add Help Wanted and Good First Issue labels to link checker report

cosmwasm/contracts/crosschain-swaps/README.md
Updates XCS docs to represent the current deployment steps
N/A, purely docs change
=> docs(crosschain_swaps): update xcs readme

.github/workflows/changelog-entry-reminder.yml, .github/workflows/required_labels.yml
Cref #5270 
Along the same idea as that PR, no longer require state machine & changelog labels for test-only PRs, and CI change PR's.
=> Excempt more PR-types from required labels

tests/cl-genesis-positions/go.mod, tests/cl-genesis-positions/go.sum, tests/cl-go-client/go.mod
Closes: #XXX
*(or)*
*(or)*
*(example:)*
=> Update CL scripts

x/concentrated-liquidity/simulation/sim_msgs.go
Closes: #4230 
Follow the design in #4230 , calculate min amounts by random percent of desired tokens
*(or)*
*(or)*
*(example:)*
=> CreatePosition randomize TokenMinAmount0, TokenMinAmount1

x/concentrated-liquidity/incentives.go, x/concentrated-liquidity/incentives_test.go
Closes: #5416
This PR implements the suggested fix for the bug described in #5416. The issue goes into detail on what the problem is and provides an example attack vector.
- This change is thoroughly tested in the functional tests in #5410
- The purpose of this PR is to:
1. Get the fix reviewed & merged ASAP
2. Demonstrate that this issue was untested by showing that implementing the fix does not break any existing tests
=> [CL][bugfix]: Fix incentive emission share calculation

.github/workflows/import_paths.yml
Closes: #5413 
Automatically apply state compatibility and changelog labels to PRs created by import paths github action
=> feat: Adding new labels to import_paths.yml workflow

Makefile, tests/cl-go-client/README.md, tests/cl-go-client/go.mod, tests/cl-go-client/go.sum, tests/cl-go-client/main.go
Closes: #XXX
Swap tool for data team. 
Updated docs on how to use it. Please read the edited README in this file for context.
Additionally, added docs on how to use this on testnet.
=> feat/docs: CL swap tool

x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/incentives.go, x/concentrated-liquidity/lp_test.go, x/concentrated-liquidity/position.go, x/concentrated-liquidity/position_test.go, x/concentrated-liquidity/spread_rewards.go
Fixes the latest critical security bug
- Adds a test demonstrating the prior bug
=> Write test for owner check in CL, fixes ownership check bug

x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/lp.go, x/concentrated-liquidity/math/tick_test.go, x/concentrated-liquidity/pool_test.go, x/concentrated-liquidity/position_test.go
Closes: #XXX
Leaving some of the mutation testing I have went through before I call it a day today.
This PR adds tests
=> Misc: (small) add some mutation testing (1/x)

scripts/generate-docs.sh
Closes: #https://github.com/osmosis-labs/osmosis/issues/5445
Fixes make docs command (which includes process for updating swagger) 
Tested in local environment
=> Fix Swagger Gen and `make docs` command

x/concentrated-liquidity/swaps.go, x/concentrated-liquidity/swapstrategy/one_for_zero.go, x/concentrated-liquidity/swapstrategy/one_for_zero_test.go, x/concentrated-liquidity/swapstrategy/swap_strategy.go, x/concentrated-liquidity/swapstrategy/swap_strategy_test.go, x/concentrated-liquidity/swapstrategy/zero_for_one.go, x/concentrated-liquidity/swapstrategy/zero_for_one_test.go, x/concentrated-liquidity/tick.go
Reverts osmosis-labs/osmosis#5469
=> Revert "[CL]: Fix two critical tick iterator-related bugs"

app/apptesting/cosmwasmpool.go, x/cosmwasmpool/cosmwasm/msg/transmuter/transmuter_test.go, x/cosmwasmpool/model/pool_test.go, x/cosmwasmpool/pool_module_test.go, x/cosmwasmpool/whitelist_test.go
Closes: #XXX
Had issues in CI. @iboss-ptk is looking into it. If unfixed by tomorrow, going to disable for now
=> chore: temp disable cw pool tests

x/concentrated-liquidity/incentives.go, x/concentrated-liquidity/swaps.go, x/concentrated-liquidity/swapstrategy/swap_strategy.go
This is some minor DRY'ing of the swap code, plus some notes to myself as I go through it
=> Minor DRY-ing and notes on swap

x/concentrated-liquidity/incentives_test.go, x/concentrated-liquidity/python/README.md, x/concentrated-liquidity/python/clmath.py, x/concentrated-liquidity/python/swap_test.py, x/concentrated-liquidity/swaps_test.go
Starting python libraires for swaps_test.go
Also removed some unneeded fields from test vectors
=> Dev python work for swaps_test.go

wasmbinding/stargate_whitelist.go
Closes: #XXX
Adds Stargate whitelist queries for concentrated liquidity.
This change is trivial and does not require additional changes
=> Add Stargate Whitelist queries for Concentrated Liquidity

x/concentrated-liquidity/swaps_tick_cross_test.go
Closes: #XXX
Removing duplicate suite
=> fix: remove duplicate suite

.github/workflows/build.yml
This pull request improves the GitHub Actions workflow responsible for building Osmosis.
Key improvements include:
- Expanded workflow triggers to include all branches and added a pattern for versioned branches.
- Introduced multi-architecture builds to include both `amd64` and `arm64`.
Ran the workflow in my work: https://github.com/niccoloraspa/osmosis/actions/runs/5345888310 
=> [ci] Improve build Github Action

.github/workflows/generate-docs.yml
Closes: #XXX
Adds CI to generate and update docs :) 
Triggering this CI run would automatically trigger github actions bot to create a PR with the updated docs. 
A sample run of this workflow can be found in https://github.com/mattverse/osmosis/actions/runs/5374789925
This would create a PR like the following:  https://github.com/mattverse/osmosis/pull/15
=> Add CI to generate and update docs

scripts/approximations/polynomial.py
Ran into this being a performance blocker,, so doing a standard trick for speeding up the polynomial evaluation. Moves poly evaluation at one point from O(N log(N)) to O(N). If we cared about speeding it up further, we'd do horners method.
=> Speedup approx script

app/app.go, app/upgrades/v16/upgrades.go
=> chore: upgrade handler ascii

tests/cl-genesis-positions/go.mod, tests/cl-genesis-positions/go.sum, tests/cl-go-client/go.mod, tests/cl-go-client/go.sum
Closes: #XXX
*(or)*
*(or)*
*(example:)*
=> Update go scripts

tests/e2e/e2e_test.go, tests/e2e/helpers_e2e_test.go
Minor de-duplications of logic while reading #5598 
To discuss some larger ones
=> Minor de-duplication of logic in E2E

scripts/test_lock_reward_receiver.sh, x/lockup/client/cli/query.go, x/lockup/client/cli/tx.go
Closes: #XXX
Adds testing script for lock reward receiver testing script, add minor fix for cli command
=> Add lock reward receiver testing script, add minor fix for cli command

x/concentrated-liquidity/swaps.go, x/concentrated-liquidity/swapstrategy/one_for_zero.go, x/concentrated-liquidity/swapstrategy/swap_strategy.go, x/concentrated-liquidity/swapstrategy/zero_for_one.go, x/concentrated-liquidity/types/errors.go
Closes: #XXX
*(or)*
*(or)*
*(example:)*
=> fix: temp cl swap bug solution

app/keepers/modules.go, x/txfees/client/cli/tx.go, x/txfees/client/proposal_handler.go, x/txfees/client/rest/tx.go
Closes: #XXX
The proper flags were not available for the new tx fees cmd, so submitting via cli would not have been possible.
=> fix: tx fees cli cmd

x/concentrated-liquidity/fuzz_test.go, x/concentrated-liquidity/keeper_test.go, x/concentrated-liquidity/swaps.go
Closes: #XXX
- adds position removal logic in-between swaps
- adds many LPs 
- claim rewards invariant
=> tests(CL): improve fuzz suite with many random LPs and removing positions

x/concentrated-liquidity/fuzz_test.go
Closes: #XXX
Fixing fuzz edge case
More context: https://osmosis-network.slack.com/archives/C027ELA290B/p1688661702077269?thread_ts=1688658942.195169&cid=C027ELA290B
=> fix: CL swap fuzz error

app/upgrades/v16/upgrades.go
Closes: #XXX
Tick spacing 100 for the migrated pool.
=> reafactor(CL): tick spacing 100 upgrade handler

Makefile, go.mod, go.sum, osmoutils/slice_helper.go, osmoutils/slice_helper_test.go, tests/cl-go-client/main.go
Closes: #XXX
- test output 
```
root@sishir-osmosis-installer-temp:~/stackman# make localnet-cl-add-to-positions
WARNING 3: sometimes the script hangs when just started. In that case, kill it and restart
2023/07/07 23:16:50 pool already exists. Tweak expectedPoolId variable if you want another pool, current expectedPoolId 1
2023/07/07 23:16:50 Adding To position: position id 41 accountName osmo18s5lynnmx37hq4wlrw9gdn68sg2uxp5rgk26vv amount0 82153551 amount1 66145821 defaultMinAmount 0
2023/07/07 23:16:53 Added to position: position id 78 amount0 169267487 amount1 0
2023/07/07 23:16:53 Adding To position: position id 52 accountName osmo18s5lynnmx37hq4wlrw9gdn68sg2uxp5rgk26vv amount0 35010051 amount1 87113937 defaultMinAmount 0
2023/07/07 23:16:58 Added to position: position id 79 amount0 …
```
=> feat: add add-to-position/withdraw position cl script 

networks/osmosis-1/upgrades/v16/mainnet/guide.md
Closes: #XXX
v16 upgrade guide
=> chore: v16 upgrade guide

networks/osmosis-1/upgrades/v16/v16_binaries.json
Closes: #XXX
*(or)*
*(or)*
*(example:)*
=> chore: set correct binary name for v16

CHANGELOG.md, x/concentrated-liquidity/swapstrategy/zero_for_one.go
Fix some print lines that made it to production
=> Delete printlns that made it to prod

tests/localosmosis/scripts/setup.sh
Closes: #XXX
This is needed for FE e2e quote testing
=> chore: increase initial amounts for one localosmosis acc

osmoutils/accum/accum_test.go
Just some basic usage of some helpers in the test file
=> Cleanup osmoutils tests a bit

x/ibc-hooks/README.md
Warn ibc hooks users about the pfm bug 
N/A
=> Warning on ibc-hooks docs

x/concentrated-liquidity/README.md
Closes: #XXX
Adds docs for liquidity depths calculation. 
Thanks @mars-protocol for providing and organizing necessary information used in this doc.
=> Add docs for liquidity depths calculation

simulation/executor/mock_tendermint.go
Closes: #XXX
If you were to run the following test locally, you would notice the sim panics with no good logs as to why:
```
func TestFullAppSimulation(t *testing.T) {
// -Enabled=true -NumBlocks=1000 -BlockSize=200 \
// -Period=1 -Commit=true -Seed=57 -v -timeout 24h
osmosim.FlagEnabledValue = true
osmosim.FlagNumBlocksValue = 50
osmosim.FlagBlockSizeValue = 5
osmosim.FlagCommitValue = true
osmosim.FlagVerboseValue = true
osmosim.FlagPeriodValue = 10
osmosim.FlagSeedValue = 8301782359513712590
osmosim.FlagWriteStatsToDB = true
fullAppSimulation(t, true)
}
```
This seed, along with others, get into a state where all validators are kicked from the active set. This isn't really a helpful edge case to test, since if there are no validators, there is no chain! This PR prevents the sim from …
=> chore: prevent kicking all validators during sim run

x/concentrated-liquidity/store.go, x/concentrated-liquidity/swaps.go
The swaps file in CL is plagued with lots of replicated code.
This PR removes some replicated code for setup and getting the next initialized tick.
The code repetition in this file is a serious problem for maintaining this.
=> CL: Continue removing duplicate swap code

.github/workflows/test.yml, Makefile, tests/e2e/configurer/base.go, tests/e2e/configurer/chain/chain.go, tests/e2e/configurer/chain/commands.go, tests/e2e/configurer/chain/node.go, tests/e2e/configurer/chain/queries.go, tests/e2e/containers/containers.go, tests/e2e/e2e_setup_test.go, tests/e2e/e2e_test.go, tests/e2e/helpers_e2e_test.go, tests/e2e/scripts/hermes_bootstrap.sh
Closes: #XXX
Changes CI to use self hosted runners for E2E
Also added some perf changes, some required due to parallel tests actually working since we have more CPU power
=> feat: self hosted e2e tests

LICENSE
This is an overdue change, it corrects the owner per signed IP agreements.
=> Update LICENSE owner to Osmosis foundation

x/valset-pref/simulation/sim_msgs.go, x/valset-pref/valpref-module/module.go
Closes: #XXX
enable valset simulator. Will turn it off if there is unregulated sim breaks
=> feat: Enable ValSet simulator 

x/valset-pref/simulation/sim_msgs.go, x/valset-pref/valpref-module/module.go
Reverts osmosis-labs/osmosis#5966
=> Revert "feat: Enable ValSet simulator "

.github/workflows/protocol-docs.yml, .gitignore, docs/protocol/book.toml, docs/protocol/src/SUMMARY.md, docs/protocol/src/core_dex.md, docs/protocol/src/dex/concentrated.md, docs/protocol/src/dex/cosmwams.md, docs/protocol/src/dex/cosmwasm.md, docs/protocol/src/dex/stableswap.md, docs/protocol/src/dex/weighted.md, docs/protocol/src/ecosystem.md, docs/protocol/src/governance.md, docs/protocol/src/osmosis.md, docs/protocol/src/smartcontracts.md, docs/protocol/src/staking.md
Closes: #XXX
Inspired by https://protocol.penumbra.zone/main/index.html and https://osmosis.gitbook.io/o/, this adds infrastructure for an up-to-date in-repository protocol documentation.
This is meant to fill in the gap of missing a place where we breakdown the Osmosis's big picture in an easy-to-consume manner with just the right amount of technical detail.
The target readers are ourselves as well as anyone else interested in the Osmosis protocol.
The deployed version can be found here: https://protocol.dev-osmosis.zone/
- thanks @niccoloraspa for helping with domain name assignment
I'm hoping that all of us continue updating this incrementally to arrive at a solid Osmosis protocol summary similar to Penumbra's.
- Tested on my personal fork and deployed to DO instance via the GitHub …
=> docs: Osmosis protocol book

.github/workflows/contracts.yml
=> Use PR path filter for Cosmwasm CI

.github/mergify.yml, CHANGELOG.md
Closes: #XXX
Backport label for v17. Converted changelog to v17.0.0
=> chore: v17 backport label & changelog

x/authenticator/types/authenticators.go
Closes: https://github.com/osmosis-labs/osmosis/issues/6078
Create initial authenticator types
Discuss trade offs
=> [AccAbs] Initial types

networks/osmosis-1/upgrades/v17b/testnet/testnet_v17b_binaries.json
Closes: #XXX
Adds cosmovisor binaries for v17b testnet upgrade
=> chore: add v17b cosmovisor binaries

x/tokenfactory/README.md
Adds docs for before send hook added to v17.
Does not need test
=> Add docs to tokenfactory

x/superfluid/keeper/stake.go
Closes: https://github.com/osmosis-labs/osmosis/issues/6110
partialSuperfluidUndelegate and partialUndelegateCommon are unused part of code. 
As mentioned in original issue, this PR removes these unused code. 
=> Remove unused code for superfluid

x/poolmanager/router.go
Closes: #6091
This is a light PR that wires up the thoroughly tested `trackVolume` function to swap logic.
Since our core swap tests are at the pool level (as opposed to pool manager), this change is quite difficult to test at the level of abstraction it's at. Given how straightforward of a change it is (and how well unit-tested `trackVolume` is), I believe it is appropriate to cover this behavior indirectly through volume-splitting tests at the gauge level.
=> [VS Incentives]: Wire up volume tracking to swap logic

networks/osmosis-1/upgrades/v18/mainnet/guide.md, networks/osmosis-1/upgrades/v18/v18_binaries.json
=> chore: v18 cosmovisor

networks/osmosis-1/README.md, networks/osmosis-1/upgrades/v18/v18_binaries.json
Closes: #XXX
- Updated cosmovisor binaries
- Updated docs
- [] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?
=> [v18.0.0] Add missing cosmovisor binaries and update release docs

chain.schema.json
Closes: #XXX
update version numbers
=> add v17 and v18 to chain.schema.json

CHANGELOG.md, app/upgrades/v18/upgrades.go, app/upgrades/v18/upgrades_test.go, x/concentrated-liquidity/incentives.go, x/incentives/keeper/distribute.go, x/incentives/keeper/hooks.go, x/lockup/keeper/lock.go, x/superfluid/keeper/stake.go
Closes: #XXX
Cherry picks v18 fix + upgrade handler to main.
=> Cherry pick v18 fix to main

app/apptesting/superfluid.go, app/upgrades/v19/upgrades_test.go, x/superfluid/keeper/synthetic_lock_wrapper.go
Adds test case for v19 upgrade handler.
Will add more according || relevant test cases and checks if this has not been merged by the time I wake up tmrw morning.
This PR adds tests
=> Add test case for V19 Upgrade Handler

x/poolmanager/router.go
Progress towards: #6155
This PR adds a simple getter for osmo volume.
N/A – this is a very simple getter.
=> [VS Incentives]: Implement getter for osmo pool volume

.github/workflows/test.yml, x/poolmanager/keeper_test.go, x/poolmanager/router_test.go, x/poolmanager/taker_fee.go
Closes: #XXX
Adds a test (based on @AlpinYukseloglu previous work) that tests the full flow from swap to after epoch end hook.
=> test: full test for taker fee

CHANGELOG.md
=> chore: v19 changelog

.github/workflows/test.yml
Try changing back to self hosted E2E runners
=> change-back-to-self-hosted

CHANGELOG.md, app/upgrades/v19/constants.go, app/upgrades/v19/upgrades.go, app/upgrades/v19/upgrades_test.go
This reverts commit bd09d4437cffa5a91e97cede01db953c1dd4bbed.
=> Revert "Add fix for prop 597 code issue (#6279)"

.golangci.yml, x/tokenfactory/keeper/createdenom_test.go, x/tokenfactory/types/msgs_test.go
This PR lints the token factory. 
=> chore: lint tokenfactory

app/upgrades/v10/upgrades_test.go, app/upgrades/v12/upgrade_test.go, app/upgrades/v13/upgrade_test.go, app/upgrades/v15/upgrade_test.go, app/upgrades/v16/upgrades_test.go, app/upgrades/v17/upgrades_test.go, app/upgrades/v18/upgrades_test.go, app/upgrades/v19/upgrades_test.go, app/upgrades/v4/upgrade_test.go, app/upgrades/v9/prop214_test.go, app/upgrades/v9/upgrade_test.go
This PR Lints the tests in the app folder. 
=> lint app folder

x/superfluid/keeper/concentrated_liquidity_test.go, x/superfluid/keeper/epoch_test.go, x/superfluid/keeper/grpc_query_test.go, x/superfluid/keeper/migrate_test.go, x/superfluid/keeper/msg_server_test.go, x/superfluid/keeper/stake_test.go, x/superfluid/types/msg_test.go
This PR applies the linter to the superfluid staking module. 
=> lint superfluid module

x/poolmanager/client/cli/query.go
Closes: #XXX
Adds pool manager params query to the CLI
Tested against mainnet and it works
=> chore: add pool manager params query to cli

x/txfees/README.md
Closes: #XXX
I spent some time trying to figure out how funds in the fee collector got sent to stakers. I didn't realize that the fee collector lived in the authtypes module in the sdk, which now makes more sense. I added a small comment in the README that makes this clearer.
=> chore: add module explanation to txfees readme

.github/workflows/go-mod-auto-bump.yml, .github/workflows/go-mod-auto-update-instructions.yaml
=> fix(CI): comment instruction link

go.mod, go.sum
=> chore: osmomath and osmoutil tags from branch

CHANGELOG.md
Closes: #XXX
Updating changelog
=> chore: v19.1.0 changelog

proto/osmosis/cosmwasmpool/v1beta1/model/pool.proto, x/cosmwasmpool/README.md, x/cosmwasmpool/model/pool.go, x/cosmwasmpool/model/pool.pb.go, x/cosmwasmpool/model/store_model.go
Closes: #6316
Better docs for cw pool models
=> docs(cwpool): better document pool models

tests/e2e/initialization/config.go
Closes: #XXX
Used to create a USDC<>OSMO pool to test the feature in which protocol fees are denominated in USDC.
Uploaded this image to dockerhub and am successfully using it on https://github.com/osmosis-labs/osmosis/pull/6442
=> e2e: add USDC to val account in init image

app/keepers/keepers.go, x/authenticator/ante/authenticator.go, x/authenticator/integration_test.go, x/authenticator/keeper/keeper.go, x/authenticator/types/keys.go
Fix transient store issue with auto increment of the store
=> fix: transient store for auto increment

.github/workflows/gosec.yml
Closes: #XXX
[GoSec action](https://github.com/osmosis-labs/osmosis/blob/main/.github/workflows/gosec.yml) has incorrect [branch names](https://github.com/osmosis-labs/osmosis/blob/main/.github/workflows/gosec.yml#L5) in events that trigger the workflow field. It has only ran [once](https://github.com/osmosis-labs/osmosis/actions/workflows/gosec.yml). This PR changes the branch names used in the workflow.
NOTE: this PR does not test wether the action works correctly, it only fixes branch names
See "NOTE"
=> dev-ux: fix branch name in gosec workflow

x/authenticator/README.md, x/authenticator/authenticator/passkey.go, x/authenticator/authenticator/passkey_test.go, x/authenticator/authenticator/util.go
Closes: #XXX
- adding passkey authentictor
- Added unit test that validates
=> feat: passkey authenticator

app/keepers/keepers.go, x/authenticator/authenticator/spend_limits.go, x/authenticator/authenticator/spend_limits_test.go, x/authenticator/integration_test.go
Register authenticators and refactor spend limit so it can be registered 
modified a test that is failing because of an issue with the authz implementation. This will be addressed soon
=> Register authenticators

cosmwasm/Cargo.lock, go.mod, go.sum, osmomath/decimal.go, osmomath/decimal_test.go, osmomath/sdk_math_alias.go, osmomath/sqrt_big_test.go, osmomath/sqrt_test.go, simulation/simtypes/random/sdkrand.go, x/concentrated-liquidity/math/precompute.go, x/concentrated-liquidity/math/tick.go, x/gamm/keeper/pool_service.go
Closes: #6466
Renames `PrecisionDec` to `DecPrecision` and `PrecisionBigDec` to `BigDecPrecision`
trivial
NA
=> osmomath: rename `Precision(Big)Dec` to `(Big)DecPrecision`

x/authenticator/ante/ante.go, x/authenticator/authenticator/all_of.go, x/authenticator/authenticator/any_of.go, x/authenticator/authenticator/passkey.go, x/authenticator/authenticator/passkey_test.go, x/authenticator/authenticator/signature_authenticator.go, x/authenticator/authenticator/spend_limits.go, x/authenticator/authenticator/util.go, x/authenticator/iface/iface.go, x/authenticator/post/post.go, x/authenticator/testutils/generic_authenticator.go, x/authenticator/testutils/max_value_authenticator.go, x/authenticator/testutils/stateful_authenticator.go, x/authenticator/types/account_authenticators_test.go
Fix bug reported by Zellic about >128 msgs
all necessary tests have been addapted to pass
=> [AccountAbstraction] use int instead of int8 as msgIndex

x/authenticator/types/msgs.go
MsgAddAuthenticator shouldn't validate data for specific authenticators
all existing tests should pass
=> Remove bad validation

CHANGELOG.md
Closes: #XXX
Updating changelog for 19.2.0
=> chore: changelog for 19.2.0

x/pool-incentives/keeper/distr_test.go
Closes: #6576
This PR validates that pool incentives allocation of minted tokens to group gauges functions as expected.
=> [VS Incentives] pool incentives allocation to group gauges test

osmoutils/osmoassert/assertions.go, x/incentives/keeper/hooks_test.go
Progress towards #6559
Adding more group distribution tests. The test description explains the goals of each test
The remaining test vectors are to be added after https://github.com/osmosis-labs/osmosis/issues/6581 is complete
=> [VS Incentives]: more group distribution tests

go.mod, go.sum, osmoutils/coinutil/coin_math.go, osmoutils/coinutil/coin_math_test.go, x/epochs/go.mod, x/epochs/go.sum, x/ibc-hooks/go.mod, x/ibc-hooks/go.sum, x/incentives/keeper/distribute.go, x/incentives/keeper/distribute_test.go, x/incentives/keeper/hooks_test.go, x/pool-incentives/keeper/distr_test.go
=> rename(osmoutils/coins): rename `coins` package to `coinutil`

x/pool-incentives/keeper/distr_test.go
Closes: #6577
Simple PR to add group gauge tests for both update and replace incentive record methods.
=> [VS Incentives]: test pool incentive records with groups

app/upgrades/v20/upgrades.go, app/upgrades/v20/upgrades_test.go, x/incentives/keeper/distribute.go, x/incentives/keeper/hooks.go, x/pool-incentives/keeper/distr.go, x/pool-incentives/types/constants.go
Closes: #6443
Adding logs to assist with debugging
- Trivial reword with existing test coverage
=> [VS Incentives] Add Group distribution logs to support debugging

.github/mergify.yml
Closes: #XXX
v20 mergify config
=> chore: v20 mergify backport config

.vscode/launch.json, .vscode/tasks.json, CONTRIBUTING.md, Makefile, go.sum, scripts/debug_builder.sh, scripts/debugger.sh, x/ibc-hooks/go.sum
Closes: #XXX
This PR adds configurations, scripts and docs for running and debugging an Osmosis node with VS Code.
What it does:
- Adds a task to build osmosis with debug symbols
- Runs a vs code background task that starts a delve server and attaches to the Osmosis node process ID
- Attaches VS code project to delve and allows you to set breakpoints
- Tested locally
=> dev-ux: debug Osmosis node with delve and VS Code

Makefile, tests/localosmosis/README.md
Closes: #XXX
Just a minor improvement on localosmosis docs that I myself would find useful in the future
=> Misc: Improve localosmosis docs

networks/osmosis-1/upgrades/v20/mainnet/guide.md, networks/osmosis-1/upgrades/v20/mainnet/v20_binaries.json, networks/osmosis-1/upgrades/v20/testnet/guide.md, networks/osmosis-1/upgrades/v20/testnet/v20_binaries.json
Closes: #XXX
Adds the guide templates for upgrading both testnet and mainet. Also creates the cosmovisor json for testnet (v19.0.0-rc0).
=> chore: v20 testnet guide templates

Makefile
Partially Closes: https://github.com/osmosis-labs/osmosis/issues/6494
Why does make file have so much low accessibility right now
We have sufficient amount of commands in our makefile that would help us improve QOL, just that the accessibility towards the commands is pretty bad, and we often times don't utilize the commands we have to our best. 
I think a part of this stems from Makefile not being able to display available commands, like we do with the osmosis binary, where cobra would display available commands. 
This PR proposes to add a somewhat similar UX with Makefile, where we display availabe commands for each category. 
This PR only includes the `proto` category as an example, **upon this PR being approved and agreed upon, planning to make further PR for all the other available …
=> [dev-ux] Make Makefile more usable

go.mod, go.sum, x/authenticator/authenticator/message_filter.go, x/authenticator/authenticator/message_filter_test.go, x/authenticator/authenticator/spend_limits.go
Add an authenticators that allows users to filter specific messages
simple unit tests
=> [Account Abstraction] Message filter authenticator

SECURITY.md
=> [typo] Update SECURITY.md

x/gamm/types/msg_swap.go, x/poolmanager/types/msg_swap.go, x/txfees/keeper/txfee_filters/arb_tx.go
It didn't work for pool manager
=> Fix arb tx filter

x/poolmanager/README.md
Closes: #XXX
We lack documentation on how taker fee works, which is apparent by the amount of questions we have received on this front offline. 
This PR introduces a basic explanation via examples, as well as how one would extrapolate the taker fee data from the tx fee data.
=> chore: add taker fee docs

cosmwasm/contracts/crosschain-swaps/README.md
Closes: #Self
So people are more clear on XC swaps failures.
Just read the code and IBC specs.
=> docs: failures of xc swaps documented

chain.schema.json
Closes: #XXX
Update chain registry for v20.1.1
Manual inspection
=> Update chain registry for v20.1.1

scripts/multinode-local-testnet.sh
Closes: #XXX
Updates the multinode testnet script with the 4th node and prometheus configuration
=> chore: update multinode testnet script (4th node + prometheus)

x/authenticator/ante/ante.go, x/authenticator/types/params.go
Closes: #XXX
Change variable to correct, so node can compile
=> chore: fix compliation issue missing var

.github/workflows/check-state-compatibility.yml
Update state check CI to v20 branch. Will backport this to v20.x.
I will automate this so we don't have to change this on every new development branch.
=> Update state check CI to v20

.github/workflows/check-state-compatibility.yml
Parse the correct branch in state compatibility check.
Manual check
=> Update state compatibility check

osmomath/sqrt_big_test.go, osmomath/sqrt_test.go
=> chore: unnecessary type arguments infertypeargs

chain.schema.json, networks/osmosis-1/README.md, networks/osmosis-1/upgrades/v20/mainnet/guide.md, scripts/release/create_binaries_json/create_all_binaries_json.sh, scripts/release/update_chain_registry/update_chain_registry.py
Closes: #XXX
Update docs for `v20.2.1`
Manual inspection
=> [chores 🧹] Update docs for v20.2.1

.github/workflows/build-push-sqs.yml
This change adds a pipeline to build and push sqs docker images. This will be removed once SQS is split to its own repo.
This is new, I need to merge to main to register the workflow. This workflow is based on the existing one. This should work and there is 0 impact to existing workflows.
=> chore: added pipeline for building and pushing sqs-dev and prod images

.github/workflows/build-push-sqs.yml
This change fixes the sqs-build-and-push pipeline now that I've had time to test.
1. Fixes the logic to recognize when there is a branch push.
2. Fixes the tag recognition logic.
3. Adds sqs-latest tag for watchtower updating.
Pushing a tag sqs-vx.x.x, pushing a branch sqs-v1.x.
- [no] Does this pull request introduce a new feature or user-facing behavior changes?
=> fix: Fix tag trigger, and tag setting logic for SQS pushes, push sqs-latest tag as well for watch tower.

CHANGELOG.md, x/txfees/keeper/txfee_filters/arb_tx.go, x/txfees/keeper/txfee_filters/arb_tx_test.go, x/txfees/keeper/txfee_filters/export_test.go
Closes: #XXX
See arb example via the affiliate swap contract:
https://celatone.osmosis.zone/osmosis-1/txs/315EB6284778EBB5BAC0F94CC740F5D7E35DDA5BBE4EC9EC79F012548589C6E5
This PR enables the detection of such arbs to charge a higher arb fee.
- Added unit test
=> feat: enable arb filter for affiliate swap messages

CHANGELOG.md, cmd/osmosisd/cmd/root.go, x/txfees/types/options.go
Closes: #XXX
Backports the adaptable fee market config
=> refactor: enable eip1559 mempool by default (backport #6897)

CHANGELOG.md
Closes: #XXX
Updates changelog for the recent releases
=> chore: update changelog for v20.2.2 - v20.4.0

.github/workflows/check-state-compatibility.yml
Manual backport due to Merfigy not working correctly with `v20.x`
Manual check. 
Check that it's working in this PR
=> Fix state-check CI

app/ante.go, app/app.go, app/keepers/keepers.go, app/keepers/modules.go, app/modules.go, app/upgrades/v21/constants.go, app/upgrades/v21/upgrades.go, go.mod, go.sum
Closes: #XXX
Block sdk is not ready for this release. This PR unwires it. It should be ready by v22.
=> chore: unwire block sdk

go.mod, go.sum, osmomath/go.mod, osmoutils/go.mod, tests/cl-genesis-positions/go.mod, tests/cl-go-client/go.mod, x/epochs/go.mod, x/ibc-hooks/go.mod
Closes: #XXX
*(or)*
*(or)*
*(example:)*
=> update to v16.x

CHANGELOG.md, README.md
Closes: [#6879]
429 are non-errors. 
This PR aims to fix few broken links (404) reported in the linked issues. 403 or 429 are prbly safe to ignore.
This change is a trivial documentation fix without any test coverage.
=> chore: fix broken links

.github/workflows/test.yml, x/concentrated-liquidity/fuzz_test.go, x/concentrated-liquidity/keeper_test.go
Closes: #XXX
Changes CI to run go tests race detector
Existing CIs are passing
=> chore: Run Test CI with race detector

x/concentrated-liquidity/lp_test.go
PR #6922 has automatically merged but I haven't edited the test yet.
=> minor: fix test

x/authenticator/post/post_test.go, x/authenticator/types/authenticators.go
Adding unit tests to post handler 
- `cd x/authenticator`
- `go test -v ./... -cover`
=> feat: add unit tests to post handler

.github/mergify.yml
Closes: #XXX
Adds v21.x label for backporting
=> chore: backport v21x label

CHANGELOG.md, x/txfees/types/options.go
Closes: #XXX
A simple bump from 1m to 2m gas as the definition of high gas.
=> feat: change high gas from 1m to 2m

README.md
In the sentence: "Bonding curves, while have found its primary use case in decentralized exchange mechanisms,"
You might want to rephrase it to: "Bonding curves, while having found their primary use case in decentralized exchange mechanisms,"
This adjustment ensures grammatical correctness by using "having found their" instead of "while have found its."
=> fixing gramatical correctness Update README.md

.github/workflows/e2e-full.yml, .github/workflows/test.yml
Closes: #XXX
Accidentally disabled e2e tests on main by upgrading this. Instead of looking into it, will just revert the upgrade.
=> fix: revert set output

.github/workflows/build-push-sqs.yml
This is merging in pipeline to build and push v20x sqs images on tag. 
=> fix: added build-push-sqs to v20x

cmd/osmosisd/cmd/root.go
Closes: #XXX
These values were previously only able to be set via flags. This adds the config values to the app.toml to make them simpler to set.
=> fix: add app.toml configs for wasm

ingest/sqs/README.md, ingest/sqs/pools/delivery/http/pools_handler.go, ingest/sqs/router/delivery/http/router_handler.go
Closes: #XXX
This PR modifies the endpoints to have prefixes by resource. Additionally, it documents every endpoint for future integrators.
Tested locally.
=> refactor/docs(SQS): endpoints

.github/workflows/build-push-sqs.yml
Closes: #XXX
Running the pipeline from branch currently does not work:
https://github.com/osmosis-labs/osmosis/actions/runs/7117846865
This PR fixes it
=> refactor/fix: build push sqs pipeline from branch

ingest/sqs/CHANGELOG.md, ingest/sqs/pools/ingester/redis/pool_ingester.go, ingest/sqs/router/usecase/optimized_routes.go, ingest/sqs/router/usecase/router.go, ingest/sqs/router/usecase/router_usecase.go
Closes: #XXX
Make the log levels smarter to make debugging simpler in production. Also, add sqs-specific changelog.
A separate changelog is better because we are planning to eventually move the read side into the separate repo. Also, we aren't directly following the chain release cycle.
=> refactor/chore(SQS): adjust log levels & changelog

x/tokenfactory/keeper/before_send_test.go
Closes: #XXX
Adds before send test where we test if the bank keeper wired to token factory keeper is correct. 
=> Add token factory test for testing bank keeper wired to token factory keeper

ingest/sqs/domain/mocks/pool_mock.go, ingest/sqs/router/usecase/optimized_routes_test.go, ingest/sqs/router/usecase/route/route.go
Closes: #XXX
Removed taker fee charge during merge 🤦 
This PR fixes it. Will add tests tomorrow 
```
make sqs-quote-compare
ingest/sqs/scripts/quote.sh "http://localhost:9092"
chain_amount_out: token_out_amount: "1228449"
sqs_amount_out: "1228449"
```
=> fix(SQS): charge taker fee

Makefile, ingest/sqs/domain/mocks/pools_usecase_mock.go, ingest/sqs/domain/mvc/pools.go, ingest/sqs/domain/mvc/router.go, ingest/sqs/domain/router.go, ingest/sqs/pools/delivery/http/pools_handler.go, ingest/sqs/pools/usecase/pools_usecase.go, ingest/sqs/router/delivery/http/router_handler.go, ingest/sqs/router/usecase/router_usecase.go, ingest/sqs/scripts/healthcheck.sh, ingest/sqs/scripts/quote.sh, ingest/sqs/scripts/validate_cl_state.sh, ingest/sqs/system/delivery/http/system_http_handler.go
Closes: #XXX
Various SQS queries and scripts for debugging sqs.
The scripts exist to perform healthcheck and validate that the concentrated liquidity pool state matches chain. We should extend it to add to CI in the future.
=> feat(SQS): queries and state validations scripts

.gitignore, cosmwasm/contracts/crosschain-swaps/README.md, ingest/README.md, networks/osmosis-1/upgrades/v4/cosmovisor.md, networks/osmosis-1/upgrades/v5/guide.md, networks/osmosis-1/upgrades/v7/guide.md
fix some typos in readme && replaced in all doc,wish can make doc more succint for new developer.
*(or)*
*(or)*
*(example:)*
=> fix: typos in some readme

SECURITY.md
Just a small typo fix. The word "Explanation" was misspelled.
=> chore: fixed typo

.github/workflows/generate-docs.yml
Closes: #XXX
Changes existing generate docs CI to create PR weekly so that we can have up to date docs. 
=> Make docs CI run weekly

.github/workflows/build-push-sqs.yml
Closes: #XXX
Fixes the tag pattern
=> chore: fix sqs tag pattern

networks/osmosis-1/upgrades/v21/mainnet/guide.md, networks/osmosis-1/upgrades/v21/mainnet/v21_binaries.json
Closes: #XXX
Placeholder for v21 guide and cosmovisor binaries. Must replace TODO items once the upgrade is ready to be proposed.
=> chore: v21 upgrade binaries and guide

networks/osmosis-1/upgrades/v21/mainnet/guide.md
Adds block height and proposal for v21 software upgrade
=> Add block height/proposal for v21

Makefile, ingest/sqs/domain/mocks/pool_mock.go, ingest/sqs/domain/route_test.go, ingest/sqs/domain/router.go, ingest/sqs/pools/usecase/pools_usecase_test.go, ingest/sqs/router/usecase/pools/routable_balancer_pool.go, ingest/sqs/router/usecase/pools/routable_concentrated_pool.go, ingest/sqs/router/usecase/pools/routable_result_pool.go, ingest/sqs/router/usecase/pools/routable_stableswap_pool.go, ingest/sqs/router/usecase/pools/routable_transmuter_pool.go, ingest/sqs/router/usecase/quote.go, ingest/sqs/router/usecase/quote_test.go, ingest/sqs/router/usecase/route/route.go, ingest/sqs/router/usecase/route/route_test.go, ingest/sqs/scripts/quote.sh
Closes: #XXX
Relevant PR: https://github.com/osmosis-labs/osmosis-frontend/pull/2547
- Tested with a manual test on a node
=> feat: add price impact to sqs

x/twap/logic.go
Mild Heap performance improvement for TWAP
=> Make more TWAP internal ops mutative

go.mod, go.sum, ingest/sqs/domain/cache/cache.go, ingest/sqs/domain/cache/cache_test.go, ingest/sqs/router/usecase/export_test.go, ingest/sqs/router/usecase/optimized_routes.go, ingest/sqs/router/usecase/optimized_routes_test.go, ingest/sqs/router/usecase/router_usecase.go, ingest/sqs/router/usecase/router_usecase_test.go, ingest/sqs/sidecar_query_server.go, osmomath/math.go, osmomath/math_test.go
Closes: #XXX
Implements caching of ranked routes by order of magnitude of token in.
Tested with locust against mainnet node. See below.
=> feat: implement ranked route cache

.github/labeler.yml, .github/workflows/labeler.yml
Closes: #7008 
This pull request updates the Actions labeler version to v5.0 and updates the `labeler.yml` file to be compatible with the v5.0 config file structure.
The new config file matches the existing functionality, and in the future it can be updated to take advantage of the new features from the v5.0 actions/labeler.
* Since this workflow runs on `pull_request_target` it needs to be tested with a pull request to a branch with the updated workflow.
* Thankfully, it was possible to manually test this with within my fork, and I ran through a few cases here: https://github.com/umbr4g3/osmosis/pull/1/files
* I modified specific files within my PR to trigger the action, and it added the expected labels.
* Additionally, reviewers …
=> chore: Update Actions labeler and labeler config to v5.0

chain.schema.json
- Updates the chain version info to the latest, v21
=> Update chain.schema.json to v21

x/protorev/keeper/posthandler.go
Closes: #XXX
Remove more duplicate event emits
Stems from this:
https://github.com/cosmos/cosmos-sdk/blob/15259ccd2249d2f3f413e0de7b8e27fe4cc6169a/types/context.go#L299
=> refactor: remove more event emits

ingest/sqs/domain/url.go, ingest/sqs/middleware/middleware.go, ingest/sqs/router/usecase/router_usecase.go
Closes: #XXX
Adds prometheus metrics for sqs cache hits and misses
=> feat(SQS): prometheus metrics for cache hits and misses

x/incentives/keeper/distribute.go
Closes: #XXX
This is pretty insignificant compared to previous optimizations but applying this improvement anyways
Synched through epoch
=> refactor: small reallocation opt is CL distributions

app/upgrades/v12/upgrades.go
=> fix: main build

x/poolmanager/router.go, x/poolmanager/taker_fee.go
These end up costing ~10 seconds of time in a 20000 block sync. (Out of 1.2 hours w/ IAVL v2)
=> Remove some unneeded NewCoin checks, which do denom validation

x/incentives/keeper/distribute.go, x/incentives/keeper/iterator.go, x/incentives/keeper/iterator_test.go, x/lockup/types/lock.go
See: https://github.com/osmosis-labs/osmosis/pull/7192
=> updates (#7192)

.vscode/launch.json, cmd/osmosisd/cmd/root.go
Fixes this: https://github.com/osmosis-labs/osmosis/pull/7180
Backported from: https://github.com/osmosis-labs/osmosis/pull/7183
=> fix e2e stemming from CLI config overwrite

.github/workflows/check-state-compatibility.yml, .github/workflows/e2e-full.yml, .github/workflows/test.yml
Reverts osmosis-labs/osmosis#7166
=> Revert "Update github actions"

CHANGELOG.md, x/concentrated-liquidity/incentives.go, x/concentrated-liquidity/spread_rewards.go
Closes: #XXX
Add PoolID to the collect CL incentives and rewards events data, so it is easier to index rewards receivers w.r.t poolID.
=> add poolID to CL incentives events 

ingest/sqs/router/delivery/http/router_handler.go
Closes: #XXX
fixes parsing of the tokenIn for sqs http queries. specfically, tokenfactory tokens are getting excluded by the regex. using the built in `sdk.ParseCoinNormalized()` seems to be a more ideal option
not covered by existing test
=> fix coin parsing in sqs router query

go.mod, go.sum
Closes: #7114 
updates ledger-cosmos-go dependency to v0.12.4 to fix bug with newest ledger cosmos app
tested by signing tx with ledger on cli
=> fix cli ledger signing

.vscode/launch.json, x/txfees/keeper/txfee_filters/arb_tx.go, x/txfees/keeper/txfee_filters/arb_tx_test.go
Backports the arb fitler from v21.1.x
=> refactor: arb filter for new authz exec swap (#7210)

.github/workflows/go-mod-auto-update-instructions.yaml
Closes: #XXX
Go mod update instruction CI has been broken for a while, this fix fixes the problem in CI
=> Fix go mod update instruction CI

osmoutils/cache_ctx.go, x/epochs/types/hooks.go, x/superfluid/keeper/epoch.go
Delete this code which was to be removed in next release.
=> Delete code that is queued for next release

.github/mergify.yml
Closes: #XXX
Adds backport label logic for v22.x
=> chore: mergify v22.x backport label

CHANGELOG.md
=> Update Changelog for v21.x

CHANGELOG.md
Updates CHANGELOG for v21 and v22
=> Update Changelog for v21 and v22

tests/e2e/e2e_setup_test.go
Closes: #XXX
*(or)*
*(or)*
*(example:)*
=> chore: Variable is no longer used

networks/osmosis-1/upgrades/v22/mainnet/guide.md, networks/osmosis-1/upgrades/v22/mainnet/v22_binaries.json
Closes: #XXX
Adds v22 guide along with binaries for cosmovisor.
=> chore: v22 guide and cosmovisor

networks/osmosis-1/upgrades/v22/mainnet/guide.md
Adds upgrade information after proposal generated.
=> Add in Upgrade Proposal details

go.mod, go.sum
Closes: #XXX
Pointing to the right branch in the `sqs` repo per https://github.com/osmosis-labs/sqs/blob/v22.x/CONTRIBUTING.md#branch-management
=> chore: update sqs deps to point to `sqs/osmosis-main` branch

ingest/sqs/pools/ingester/pool_ingester.go
Closes: #XXX
Previous change that utilized spot price caused truncation to zero, leading to a panic. This PR fixes it.
=> chore: fix sqs ingest bug due to division by zero panic

x/cosmwasmpool/README.md
Update missing part on `cosmwasmpool` doc about setting response data.
N/A
=> Update `cosmwasmpool` doc

Dockerfile
Update golang version in Dockerfile to 1.21
=> Update golang version in Dockerfile to 1.21

x/authenticator/README.md
Add documentation to CosmWasm authenticator.
=> add cosmwasm authenticator doc

CHANGELOG.md
Closes: #XXX
*(or)*
*(or)*
*(example:)*
=> chore: add changelog for v22.0.2

CHANGELOG.md, x/concentrated-liquidity/incentives.go, x/concentrated-liquidity/incentives_test.go
Closes: #XXX
Removes event emission due to questional state compatibility.
=> chore: remove event

CHANGELOG.md, cmd/osmosisd/cmd/root.go
Updates changelog for v22.0.5 release
=> chore: v22.0.5 changelog

go.mod, go.sum, osmomath/go.mod, osmomath/go.sum, osmoutils/go.mod, osmoutils/go.sum, x/epochs/go.mod, x/epochs/go.sum, x/ibc-hooks/go.mod, x/ibc-hooks/go.sum
Closes: #XXX
Tagged v23 branch for our sdk fork and utilized said tag in all go mods.
=> chore: update sdk fork

ingest/sqs/pools/ingester/pool_ingester.go
Exclude white whale pool that broke sqs
=> fix: exclude white whale pool

ingest/sqs/pools/ingester/pool_ingester.go
Closes: #XXX
*(or)*
*(or)*
*(example:)*
=> remove ww code id from router

ingest/sqs/pools/ingester/pool_ingester.go
Closes: #XXX
Follow up to prod incident with white whate pools
- Silently skip any pool conversion error or panic during ingest
- Emit telemetry
- Skip white whale code ID
=> feat(sqs): skip panics or errors in sqs pool ingest; skip whitewhate code id

CHANGELOG.md
Closes: #XXX
Preps changelog for v23.
Still have open Q about https://github.com/osmosis-labs/osmosis/pull/7400/files
It bumps cometbft but we replace it with our fork.
=> chore: v23 changelog

go.mod, go.sum, osmoutils/go.mod, osmoutils/go.sum, x/epochs/go.mod, x/epochs/go.sum, x/ibc-hooks/go.mod, x/ibc-hooks/go.sum
Closes: #XXX
Tags comet fork, moving from Nicolas' branch to osmo-v23/v0.37.4 branch. Same commit though.
=> chore: tag comet fork for v23

x/incentives/types/msgs_test.go
Removes the test that's breaking CI on main (the validation corresponding to this was intentionally removed)
=> [fix]: Remove broken ValidateBasic test

.github/workflows/test.yml
Closes: #XXX
Add docker auth via `osmo-bot` to avoid rate-limiting on pulls
Check workflow running
=> ci: add docker authentication

networks/osmosis-1/README.md
add v21 and v22 description in the upgrade path
=> Fill latest releases in Readme

ingest/sqs/pools/ingester/pool_ingester.go, x/concentrated-liquidity/incentives.go, x/concentrated-liquidity/swaps.go, x/concentrated-liquidity/types/events.go, x/concentrated-liquidity/types/telemetry.go, x/incentives/keeper/distribute.go, x/incentives/types/telemetry.go, x/pool-incentives/keeper/keeper.go, x/pool-incentives/types/telemetry.go
Closes: #XXX
Added Prometheus counters and logs for incentives and SQS flows which we recently spent considerable time debugging recently.
Additionally, fixed an old counter name that was causing pains for @alessandrolomanto 
Lastly, moved CL telemetry placeholders into a separate file for consistency
=> feat(observability): telemetry counters for incentives and sqs

cmd/osmosisd/cmd/root.go
Closes: #XXX
We are missing these CLI commands. They are useful for creating a pure IAVL v1 database. 
I have used these CLI commands when testing IAVL v1.
=> chore: add snapshot and pruning cli

app/upgrades/v16/upgrades.go, app/upgrades/v16/upgrades_test.go, x/protorev/keeper/developer_fees.go
Pretty simple deadcode deletion. We said delete it in a subsequent release.
=> Delete code slated for removal

x/concentrated-liquidity/genesis_test.go, x/concentrated-liquidity/incentives_test.go, x/concentrated-liquidity/position_test.go, x/concentrated-liquidity/query_test.go
Closes: #6350
Not that big of a win, I mostly just did this to close the issue!
=> Constant fold NewDec calls in CL query tests

go.mod, go.sum, osmoutils/observability/helpers.go, x/concentrated-liquidity/incentives.go, x/concentrated-liquidity/swaps.go, x/concentrated-liquidity/telemetry.go, x/concentrated-liquidity/types/telemetry.go, x/epochs/types/hooks.go, x/epochs/types/hooks_test.go, x/epochs/types/telemetry.go, x/incentives/keeper/distribute.go, x/incentives/keeper/hooks.go, x/incentives/types/telemetry.go, x/mint/keeper/hooks.go, x/pool-incentives/keeper/keeper.go, x/pool-incentives/types/telemetry.go, x/protorev/keeper/epoch_hook.go, x/superfluid/keeper/hooks.go, x/twap/listeners.go, x/txfees/keeper/hooks.go, x/txfees/types/telemetry.go
Closes: #XXX
- Adds counters for txfees epoch flow
- Adds counters for epoch hook panics
- Cleans up and simplifies the existing counters
- Removes superfluous logs
- Adds detailed docs
=> feat/refactor/docs(observability): epoch hook, txfees epoch, existing metric clean up

app/upgrades/v21/upgrades.go, app/upgrades/v24/constants.go, app/upgrades/v24/upgrades.go, app/upgrades/v24/upgrades_test.go, x/authenticator/ante/pubkey.go, x/authenticator/authenticator/authentication_data.go, x/authenticator/authenticator/signature_authenticator.go, x/authenticator/post/post.go
Adding upgrade handler for authenticator module and tests
- `cd ./app/upgrades/v24/`
=> feat: add upgrade handler for authenticator module

.github/mergify.yml
Closes: #XXX
Single label for backporting to two branches
=> chore: iavl v1 branch mergify

x/authenticator/authenticator/all_of.go, x/authenticator/authenticator/any_of.go, x/authenticator/authenticator/signature_authenticator.go, x/authenticator/types/account_authenticators.go
validation should extend to sub-authenticators
all tests should pass.
=> Validate sub-authenticators on AllOf and AnyOf

x/txfees/keeper/hooks.go
Small PR to reduce some duplicate logic in telemetry. Theres more redundancy here as well that it would be nice to reduce
=> DRY some telemetry logic in txfees

app/upgrades/v24/upgrades.go, app/upgrades/v24/upgrades_test.go, x/authenticator/keeper/msg_server.go
Remove artificial reuqirement for first authenticator that is no longer needed.
This PR also drive-by fixes the max feeless gas for authenticators cause I already had that change in my branch
=> Remove requirement over first authenticator

app/keepers/keepers.go, tests/osmosisibctesting/chain.go, x/authenticator/authenticator/all_of.go, x/authenticator/authenticator/any_of.go, x/authenticator/authenticator/composite.go, x/authenticator/integration_test.go
Allow authenticators to support compound signatures. This enables features like multisigs and cosigner. 
All existing tests should pass. Added a small test for allOf compound sig.
TODO: More tests are needed
=> Add support for compound signatures

x/authenticator/ante/ante.go
Closes: #XXX
Small nit for casting uint ID to string
=> chore(aa): remove cast during  uint to string conversion

CHANGELOG.md, x/concentrated-liquidity/tick.go, x/concentrated-liquidity/types/events.go
This reverts commit b58efcabb92154b0743d5eb8344721a399ea0cef.
Closes: #XXX
*(or)*
*(or)*
*(example:)*
=> Revert "feat: tick init/deinit for CL (#7627)"

CHANGELOG.md, x/concentrated-liquidity/tick.go, x/concentrated-liquidity/types/events.go
This reverts commit ea4238e01115b9363e6e86a158994072f78e260f.
Closes: #XXX
*(or)*
*(or)*
*(example:)*
=> Revert "feat: tick init/deinit for CL (#7622) (#7628)"

x/authenticator/authenticator/composition_test.go, x/authenticator/testutils/spy_authenticator.go
Add tests to cover sub authenticators id construction and call params
=> [Smart Account] Composite authenticator sub auth calls & id tests

x/txfees/keeper/mempool-1559/code.go, x/txfees/keeper/mempool-1559/code_test.go, x/txfees/keeper/mempool-1559/state_compatible_update_logic.go
Closes: #XXX
Moves the EIP printlns to debug
=> chore: move EIP logs to debug

app/posthandler.go, x/authenticator/ante/ante.go, x/authenticator/ante/circuit_breaker.go, x/authenticator/ante/circuit_breaker_test.go, x/authenticator/post/post.go, x/authenticator/post/post_test.go
Added tests to the post handler
- `cd x/authenticator/post`
- `go test -v -cover ./...`
```
=== RUN   TestAuthenticatorPostSuite
=== RUN   TestAuthenticatorPostSuite/TestAutenticatorPostHandlerFailConfirmExecution
=== RUN   TestAuthenticatorPostSuite/TestAutenticatorPostHandlerReturnEarly
=== RUN   TestAuthenticatorPostSuite/TestAutenticatorPostHandlerSuccess
--- PASS: TestAuthenticatorPostSuite (0.11s)
--- PASS: TestAuthenticatorPostSuite/TestAutenticatorPostHandlerFailConfirmExecution (0.05s)
--- PASS: TestAuthenticatorPostSuite/TestAutenticatorPostHandlerReturnEarly (0.03s)
--- PASS: TestAuthenticatorPostSuite/TestAutenticatorPostHandlerSuccess (0.03s)
PASS
coverage: 88.0% of statements
ok  	github.com/osmosis-labs/osmosis/v23/x/authenticator/post	0.177s	coverage: 88.0% of statements …
```
=> chore: adding tests to the post handler function

tests/e2e/initialization/init.Dockerfile
use go 1.21 on the e2e init image
=> Setting init image for e2e to go 1.21

.github/workflows/test.yml, tests/e2e/initialization/init.Dockerfile
There are issues with building the e2e image with go 1.21. This attempts to fix it
=> Using alpine18 as there are issues with 19

go.mod, go.sum, osmomath/go.mod, osmoutils/go.mod, tests/e2e/configurer/chain/commands.go, x/epochs/go.mod, x/ibc-hooks/go.mod, x/superfluid/keeper/hooks_test.go
Closes: #XXX
Ensuring tests still pass with some of the changes we made to our fork.
1. We can no longer expect logs in the response and need to parse the response itself https://github.com/osmosis-labs/cosmos-sdk/commit/99c0a54c54a0b17c2ab8893f053759e8185623ec
2. We can no longer expect validator distribution on every block, and need to take into account that we now distribute every 50 blocks https://github.com/osmosis-labs/cosmos-sdk/commit/3d440de123e416f111d7bdd3126b421d1c4f391d
=> chore: bump sdk to current

x/authenticator/ante/circuit_breaker.go, x/authenticator/authenticator/cosmwasm.go
Closes: #XXX
this PR adds one more check to the circuit breaker ante handler, that is to make sure that there is at least 1 selected authenticator
=> feat: add selected authenticator check to circuit breaker

go.mod, go.sum, osmomath/go.mod, osmoutils/go.mod, x/epochs/go.mod, x/ibc-hooks/go.mod
Closes: #XXX
Bumps sdk fork. The changes are highlighted in the changelog PR that is currently open.
=> chore: update cosmos sdk fork

CHANGELOG.md
Closes: #XXX
Fixes/updates changelog in preparation for minor release.
=> chore: updates to changelog

go.mod, go.sum
Upgrade minor version of PFM
All tests should pass
=> Minor version upgrade

x/authenticator/authenticator/all_of.go, x/authenticator/authenticator/any_of.go, x/authenticator/authenticator/composite.go, x/authenticator/authenticator/composition_test.go
Make the composite authenticator code easier to understand by inlining it.
This was requested in yesterday's code review session. 
=> Simplify composite authenticators

go.mod, go.sum, osmomath/go.mod, osmoutils/go.mod, x/epochs/go.mod, x/ibc-hooks/go.mod
Closes: #XXX
Adds back regex denom performance PR from sdk fork that got reverted while testing.
=> chore: bump sdk to add regex denom perf

go.mod, go.sum, osmomath/go.mod, osmoutils/go.mod, x/epochs/go.mod, x/ibc-hooks/go.mod
Closes: #XXX
Updates sdk fork for IAVL v0 v23 branch.
=> chore: bump sdk fork for IAVL v0 branch

app/ante.go
Fees should be deducted after authentication. This gives the spend limit the ability to track fees
all existing tests should pass
=> deduct fees after auth

networks/osmosis-1/upgrades/v24/mainnet/guide.md
Updates info in guide after V24 proposal live
=> Update Proposal and Block for V24

CHANGELOG.md
=> chore: adding v23.0.11 changelog

x/poolmanager/taker_fee.go
Address a minor TODO removing some extra taker fee CPU work.
I think this is non-breaking but I don't want to invest time in testing this.
=> Address a taker fee todo

ingest/sqs/ingester.go
Closes: #XXX
Fixing production incidents around transmuter pools. Realized that CW pool model is not updated on swaps. As a result, we incorrectly detect CW pool updates and fail to push liquidity updates correctly.
We need to find a different way to detect their mutations. As a temporary workaround, we push all CW pools in each block.
- Manual test on node
=> feat: push all CW pools into SQS each block

cmd/osmosisd/cmd/root.go
Closes: #XXX
Just noticed some dead code while investigating something else, confirmed with Roman that it is not needed.
=> chore: remove dead code

go.mod, go.sum
update osmomath to latest commit
main is failing on:
```
make install
Go version: 1.22
GOWORK=off go install -mod=readonly -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=osmosis -X github.com/cosmos/cosmos-sdk/version.AppName=osmosisd -X github.com/cosmos/cosmos-sdk/version.Version=osmomath/v0.0.11-22-g9e327b629 -X github.com/cosmos/cosmos-sdk/version.Commit=9e327b629aab8f19f7ed768b34813bb5ad918b7a -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger" -w -s' -trimpath github.com/osmosis-labs/osmosis/v24/cmd/osmosisd
x/concentrated-liquidity/math/tick.go:47:30: undefined: osmomath.MonotonicSqrtMut
make: *** [Makefile:152: install] Error 1
```
=> chore: update osmomath dep

x/smart-account/keeper/msg_server.go
Closes: #8091 
don't limit authenticators. There's no top level iteration anymore
all existing tests should pass.
=> [SmartAccounts] fix: don't limit authenticators. There's no top level iteration anymore

networks/osmosis-1/upgrades/v25/mainnet/guide.md, networks/osmosis-1/upgrades/v25/mainnet/v24_binaries.json, scripts/release/create_binaries_json/create_all_binaries_json.sh
=> chore: release notes for v25

scripts/multinode-local-testnet.sh
Closes: #XXX
*(or)*
*(or)*
*(example:)*
=> chore: comment is old

x/gamm/client/cli/tx.go
Closes: #8233
This CLI for some reason requires input via a file, I just added back the proposal flag which is state compatible and should fix the problem.
=> fix: cli for set scaling factor

networks/osmosis-1/upgrades/v25/mainnet/v24_binaries.json, networks/osmosis-1/upgrades/v25/mainnet/v25_binaries.json
Add v25 docs:
- Cosmovisor binaries json
=> Updated cosmovisor json for v25.0.0

x/tokenfactory/client/cli/tx.go
=> chore: added the MsgsetDenomMetadata in cli

x/superfluid/keeper/stake.go
very simple change to use the correct function name in the log
=> Fix bad text in log

x/smart-account/ante/ante.go, x/smart-account/ante/circuit_breaker_test.go, x/smart-account/authenticator/manager.go, x/smart-account/authenticator/signature_authenticator.go, x/smart-account/authenticator/signature_authenticator_test.go, x/smart-account/authenticator/spend_limits_test.go, x/smart-account/integration_test.go, x/smart-account/keeper/keeper.go, x/smart-account/post/post_test.go, x/smart-account/simulation/helpers.go
Closes: #XXX
Just committing some spelling errors I came across as I was auditing the smart accounts module.
=> nits: typological errors

SECURITY.md
This pull request added language to security.md to notify reporters that to collect a bounty the reporter must go through KYC
- [X ] N/A
=> Update SECURITY.md for conditions on collecting bug bounty

CHANGELOG.md, go.mod, go.sum, osmoutils/go.mod, osmoutils/go.sum, x/epochs/go.mod, x/epochs/go.sum, x/ibc-hooks/go.mod, x/ibc-hooks/go.sum
Updating the v25.x branch with the latest changes from cometbft, we will release after this branch v25.0.1
Relevant PRs:
- https://github.com/osmosis-labs/cometbft/pull/65
- https://github.com/osmosis-labs/cometbft/pull/66
=> chore: update cometbft with latest changes

CHANGELOG.md
=> chore: update changelog for cometbft mempool fixes

go.mod, go.sum, osmoutils/go.mod, osmoutils/go.sum, x/epochs/go.mod, x/epochs/go.sum, x/ibc-hooks/go.mod, x/ibc-hooks/go.sum
Closes: #XXX
Update cometbft with latest mempool fixes see:
- https://github.com/osmosis-labs/cometbft/pull/69
- https://github.com/osmosis-labs/cometbft/pull/67
=> chore: update cometbft with latest mempool fixes

CHANGELOG.md, cmd/osmosisd/cmd/root.go
Closes: #XXX
Overwrites `flush_throttle_timeout` to 10ms and `peer_gossip_sleep_duration` to 50ms.
=> chore: overwrite `flush_throttle_timeout` and `peer_gossip_sleep_duration` to 10ms and 50ms respectively

CHANGELOG.md
- Update changelog for v25.0.3
=> chore: update changelog for v25.0.3

x/superfluid/README.md, x/superfluid/keeper/grpc_query.go, x/superfluid/keeper/grpc_query_test.go, x/superfluid/keeper/stake.go, x/superfluid/keeper/stake_test.go, x/superfluid/keeper/twap_price.go, x/superfluid/keeper/twap_price_test.go
Adds some docs for the non-pool superfluid feature
ND
=> [NonPoolSuperfluid] docs

networks/osmosis-1/upgrades/v11/testnet/guide.md, networks/osmosis-1/upgrades/v12/testnet/guide.md, networks/osmosis-1/upgrades/v13/testnet/guide.md, networks/osmosis-1/upgrades/v15/testnet/guide.md, networks/osmosis-1/upgrades/v17/testnet/guide.md, networks/osmosis-1/upgrades/v20/testnet/guide.md, networks/osmosis-1/upgrades/v22/mainnet/guide.md
Closes: #8341
This PR fixes broken links by updating links to point valid URLs, please see #8341 for more information.
You can find test workflow results [here](https://github.com/deividaspetraitis/osmosis/actions/runs/9379347109/job/25824143110).
=> Fix: broken links

.github/workflows/generate-docs.yml, .github/workflows/go-mod-auto-bump.yml, .github/workflows/update-comet-version.yml
Closes: #XXX
Follow up to #8162 so we can run an action to update our comet fork as well
=> chore: Create CI for bumping comet version via GA

x/smart-account/ante/ante.go, x/smart-account/post/post.go
From our smart account audit one of the informational fixes was to fix this error as the selectedAuthenticator will return nil here, so we log the user defined selectedAuthenticator
=> fix: error log in post and ante handler

app/upgrades/v16/upgrades.go, app/upgrades/v16/upgrades_test.go, app/upgrades/v3/forks.go, app/upgrades/v9/upgrades.go, tests/simulator/sim_test.go, x/txfees/keeper/feedecorator.go
Closes: #XXX
These are all the remaining unforking TODOs that I am assigned.
=> chore: address some unforking TODOs

x/smart-account/README.md
Document confusion brought up in the audit. 
no tests needed
=> [SA] Docs about api guarantees

x/tokenfactory/keeper/bankactions.go, x/tokenfactory/keeper/keeper.go, x/tokenfactory/keeper/msg_server_test.go
Cleaning up some functions (no commits today) :smiling_face_with_tear: 
```
go test ./... -v -cover
```
=> chore: cleaning up some functions

app/app.go, ingest/indexer/domain/asset.go, ingest/indexer/domain/cold_start_manager.go, ingest/indexer/domain/ingester.go, ingest/indexer/domain/keepers.go, ingest/indexer/service/client/pubsub_client.go, ingest/indexer/service/indexer_streaming_service.go, ingest/indexer/service/writelistener/bank_write_listener.go, ingest/indexer/service/writelistener/bank_write_listener_test.go, ingest/sqs/ingester.go, ingest/sqs/sqs_config.go
Closes: #XXX
Ref: https://linear.app/osmosis/issue/IND-42/boilerplate-for-tracking-modified-data-and-perform-incremental-push
- Creating separate indexer streaming service for DexScreener
- Starting to do a POC for detecting state changes in the bank module for total supply
=> feat: Indexer service wiring

go.mod, go.sum, osmoutils/go.mod, x/epochs/go.mod, x/ibc-hooks/go.mod
Closes: #XXX
Bumps comet to `v0.37.4-v25-osmo-8`
=> chore: bump comet branch w/ cons improvements

ingest/indexer/domain/errors.go, ingest/indexer/domain/ingester.go, ingest/indexer/domain/mocks/token_supply_publisher_mock.go, ingest/indexer/service/writelistener/bank_write_listener.go, ingest/indexer/service/writelistener/bank_write_listener_test.go
Closes: #XXX
Token supply write listener unit tests
=> test: token supply write listener

go.mod, go.sum, osmoutils/go.mod, x/epochs/go.mod, x/ibc-hooks/go.mod
Closes: #XXX
Bumps comet to fix error with block part selection.
=> fix: comet bump

app/app.go, go.mod, go.sum
Updating the decoder utilized in check tx with one that caches transactions with a queue like implementation.
=> perf: CheckTx with Caching Tx Decoder

cmd/osmosisd/cmd/module_hash_by_height.go, cmd/osmosisd/cmd/root.go
Query that exposes the per module hash at a given height, which is useful for debugging app hashes.
=> feat: v25.x module hash by height

Makefile
Closes: #XXX
Allows for quick sdk and comet replaces with a build or install.
`make install SDK_HASH=d958d4441808e5380a127b2bbdc8334896d3f0bc COMET_HASH=2bc0d7f67988cded40648c2c6a47d9cae0c5f7c8`
`make build SDK_HASH=d958d4441808e5380a127b2bbdc8334896d3f0bc COMET_HASH=2bc0d7f67988cded40648c2c6a47d9cae0c5f7c8`
=> feat: sdk comet build/install quick replace

ingest/indexer/domain/token_supply.go, ingest/indexer/service/indexer_streaming_service.go, ingest/indexer/service/writelistener/bank_write_listener.go
Indexer project
- Added common filtering logic for token supply data publishing. Fixed a typo bug in topic id.
=> feat: added common filtering logic for token supply data publishing. Fixed a typo bug in topic id.

go.mod, go.sum
=> chore: fix CI on v25.x

app/app.go, ingest/common/domain/block_pools.go, ingest/common/domain/keepers.go, ingest/common/writelistener/cfmm_write_listener.go, ingest/common/writelistener/cfmm_write_listener_test.go, ingest/common/writelistener/concentrated_write_listener.go, ingest/common/writelistener/concentrated_write_listener_test.go, ingest/common/writelistener/cosmwasmpool_write_listener.go, ingest/common/writelistener/cosmwasmpool_write_listener_test.go, ingest/indexer/service/indexer_streaming_service.go, ingest/indexer/service/writelistener/bank_write_listener.go, ingest/sqs/domain/ingester.go, ingest/sqs/domain/mocks/sqs_ingester_mock.go, ingest/sqs/ingester.go, ingest/sqs/pools/transformer/alloy_transmuter.go, ingest/sqs/pools/transformer/export_test.go, ingest/sqs/pools/transformer/orderbook.go, ingest/sqs/pools/transformer/pool_transformer.go, ingest/sqs/pools/transformer/pool_transformer_test.go, ingest/sqs/pools/transformer/taker_fee.go, ingest/sqs/service/sqs_streaming_service.go, ingest/sqs/service/sqs_streaming_service_test.go, ingest/sqs/sqs_config.go
Progress towards https://linear.app/osmosis/issue/IND-12/pool-level-ingester
- Creates shared `ingester/common` and `ingester/common/domain` packages for reuse between `sqs` and `indexer` ingesters
=> refactor(indexer): create ingest/common package

ingest/indexer/domain/block.go, ingest/indexer/domain/pool.go, ingest/indexer/domain/token_supply.go, ingest/indexer/domain/transaction.go, ingest/indexer/service/client/pubsub_client.go
Added a default field "ingested_at" for every message published. This will be useful for observability metrics in future
=> feat: (indexer) added ingested_at field for every message published

ingest/indexer/service/blockprocessor/pair_publisher.go
Closes: #XXX
There was a bug in pair publishing logic that would result in deadlock.
It was fixed by switching from channels to a wait group that is handled more carefully.
=> fix(indexer): concurrency bug in pair publish

x/gamm/keeper/gas_test.go, x/ibc-hooks/sdkmodule.go, x/lockup/keeper/gas_test.go
Closes: #XXX
Remove some unforking TODOs
=> Remove some unforking TODOs

Dockerfile, Dockerfile.cosmovisor
=> Fix cosmovisor docker build, fix docker warnings

.golangci.yml, x/txfees/keeper/feedecorator.go, x/txfees/keeper/feedecorator_test.go
RIP this was not guarded under CheckTx
=> Height gate an accidental fork

CHANGELOG.md, ingest/sqs/sqs_config.go
Closes: #XXX
Disable sqs config by default
I did not test but this seems to be the reason based on following references.
=> chore: disable sqs by default in app.toml

go.mod, go.sum, ingest/sqs/pools/transformer/orderbook_test.go
Closes: #XXX
We updated `sqsdomain` [here](https://github.com/osmosis-labs/sqs/pull/396/files) but did not increase it on the `osmosis` side.
This PR applies the fix
- Tested locally
=> fix: update sqsdomain for orderbook

x/smart-account/authenticator/authentication_request.go
Removed all UNFORKING TODOs from smart account module
Module will function the same as before
- `cd ./x/smart-account`
- `go test ./... -cover`
=> chore: remove UNFORKINGTODO from smart account module

x/smart-account/authenticator/message_filter_test.go
Adding test cases to demonstrate the message filter when applied to the limit order cosmwasm contract call
=> feat: add cosmwasm limit order message filter examples

app/keepers/keepers.go, x/ibc-rate-limit/ics4_wrapper.go
TODOs were reviewed and are ok to remove
=> Remove ibc unforking todos

app/keepers/modules.go
Remove unforking todos that are ok
=> Remove unforking todos that are ok to remove

app/apptesting/test_suite.go, cmd/osmosisd/cmd/testnet.go, simulation/simtypes/action.go, tests/e2e/initialization/node.go, x/superfluid/keeper/hooks_test.go, x/superfluid/keeper/intermediary_account.go, x/superfluid/keeper/slash_test.go, x/txfees/module.go
What is the purpose of the change
In preparation for the v0.50 upgrade we left some UNFORKINGTODO around the code base to verify some functionality, this PR removes and an answers a few of those questions.
=> chore: remove more UNFORKINGTODOs

.github/mergify.yml
Adding mergify backport tag for tag A:backport/v26.x
=> chore: add mergify backport on tag action

ingest/indexer/service/indexer_streaming_service.go
This commit addresses some minor adjustments required when running the ingesters under v26.x
- Transaction message type retrieval
- Transaction events retrieval
Tested using in-place testnet. Will perform more thorough testing using v26 testnet.
=> feat: changes required to make ingesters working in v26.x 

go.mod, go.sum
=> chore: update sqsdomain to v0.19.0

go.mod
Closes: #XXX
Adding some more context
=> comments for cosmossdk.io/store

tests/localosmosis/README.md
Suggestions on README update in `tests` folder after going thru the doc and carry out some tests using `localosmosis` testnet.
=> feat: readme update in 'tests' about user key and pool creation

CHANGELOG.md
Closes: #XXX
Adds missing changelog from our external PRs that we have merged
=> misc: Add missing CHANGELOG

go.mod, go.sum, ingest/sqs/pools/transformer/pool_transformer_test.go, ingest/sqs/pools/transformer/taker_fee_test.go
=> sqsdomain tag update

tests/e2e/initialization/node.go
- Currently to generate the upgrade handlers for e2e tests we have errors in the pipeline, that due to our signing code being incorrect, this PR fixes the signing issue.
https://github.com/osmosis-labs/osmosis/actions/runs/11015672372/job/30590367513?pr=8724
- `make e2e-docker-build-e2e-init-chain`
- `make e2e-docker-build-e2e-init-node`
- update here to debug => https://github.com/osmosis-labs/osmosis/blob/main/tests/e2e/containers/config.go#L30
- `make test-e2e-debug`
=> fix: e2e initialisation signing issue

.github/mergify.yml
Add mergify backport tag for tag A:backport/v27.x
=> feat: backport tag in mergify

CHANGELOG.md, go.mod, go.sum
Bump github.com/osmosis-labs/sqs/sqsdomain => 0.27.0
=> chore: bump sqsdomain to v0.27.0

.markdownlintignore
Closes: #XXX
Fixes broken lint, adds local osmosis readme to markdownignore
=> Fix lint, Add local osmosis readme markdownignore

.github/workflows/push-dev-docker-images.yml
Allow to have a preview docker build manually from arbitrary tags when needed
=> Add workflow dispatch condition to dev docker build

.github/mergify.yml
=> chore: add v28 backport to mergify

go.mod, go.sum
Bumping sqsdomain to a tagged version and making sure that sqs main is not point to a branch
see https://github.com/osmosis-labs/sqs/releases/tag/sqsdomain%2Fv0.28.0-rc1
=> chore: update to tagged sqsdomain

go.mod, go.sum
=> chore: update to tagged ibc-hooks and epochs

scripts/release/create_upgrade_guide/create_upgrade_guide.py
Closes: #XXX
Fix the utility script to generate the upgrade guide for releases 
=> Fix upgrade guide script for releases 

networks/osmosis-1/upgrades/v28/mainnet/guide.md, networks/osmosis-1/upgrades/v28/mainnet/v28_binaries.json
Add v28 binaries json and upgrade guide
=> chore: added v28 guide

proto/osmosis/gamm/poolmodels/stableswap/v1beta1/stableswap_pool.proto, proto/osmosis/tokenfactory/v1beta1/tx.proto, x/concentrated-liquidity/incentives.go, x/epochs/keeper/epoch.go, x/gamm/pool-models/stableswap/stableswap_pool.pb.go, x/incentives/keeper/hooks_test.go, x/tokenfactory/types/tx.pb.go
Fix spell checked issues causing CI to fail
=> chore: spellchecking

go.mod, go.sum
Applying hotfix from block-sdk fork https://github.com/osmosis-labs/block-sdk/pull/1
=> build: use forked block-sdk patch

CHANGELOG.md, app/keepers/keepers.go, app/upgrades/v15/upgrades.go, go.mod, go.sum
Closes: #XXX
Bumping pfm to latest version
=> chore: upgrade pfm to latest version

.github/mergify.yml
=> chore: update mergify for v29

x/protorev/keeper/rebalance.go
Use GetPoolType instead of getting entire pool when only type is needed.
State breaking because it changes gas in protorev.
=> refactor(protorev): optimize pool access in CalculateUpperBoundForSearch

x/ibc-rate-limit/README.md
Updates the broken link to a working link to maintain correct navigation.
=> fix dead link in README.md

CHANGELOG.md, go.mod, go.sum
Bump ibc-go to the latest version
=> chore: bump ibc-go to v8.7.0

CHANGELOG.md, go.mod, go.sum, osmoutils/go.mod, osmoutils/go.sum
Reverting the async pruning fix for v29
=> chore: revert async pruning fixes

networks/osmosis-1/upgrades/v29/mainnet/guide.md, networks/osmosis-1/upgrades/v29/mainnet/v29_binaries.json
=> V29 docs update

CHANGELOG.md, go.mod, go.sum, osmomath/go.mod, osmomath/go.sum, osmoutils/go.mod, osmoutils/go.sum, x/epochs/go.mod, x/epochs/go.sum, x/ibc-hooks/go.mod, x/ibc-hooks/go.sum
Closes: #XXX
Fix pagination of proposals when using a key
- "curl "http://localhost:1317/cosmos/gov/v1/proposals?pagination.limit=100&pagination.key=AAAAAAAAAjA="
vs
- curl "https://lcd.osmosis.zone/cosmos/gov/v1/proposals?pagination.limit=100&pagination.key=AAAAAAAAAjA="
=> chore: add fix for pagination of proposals

CHANGELOG.md, go.mod, go.sum
=> chore: bump wasmd version

CHANGELOG.md, x/txfees/keeper/mempool-1559/code.go
Increase min base fee in mempool-1559 to match #9454.
=> fix: mempool-1559 min base fee to match consensus min fee

networks/osmosis-1/upgrades/v30/mainnet/guide.md, networks/osmosis-1/upgrades/v30/mainnet/v30_binaries.json
=> Add v30 docs
