osmosis-labs/osmosis

tests/cl-go-client/README.md, tests/cl-go-client/main.go, x/concentrated-liquidity/grpc_query.go, x/concentrated-liquidity/lp.go, x/concentrated-liquidity/tick.go
Closes: #XXX
Liquidity net in direction query was breaking in some cases due to a failing current square root price check.
Apparently, the pool's current square root price did not translate to the current tick correctly.
This is because we used an inaccurate `ApproxSqrt` function in initialization. Instead, this change initializes the current square root price by using our internal math functions to translate it from the current tick.
On quick test, was unable to reproduce the problem anymore.
Also, added some debug logs to the query for easier debugging if the error persists. …
=> fix(CL): invalid sqrt price initialization breaking liquidity net in direction query

x/ibc-hooks/client/cli/query.go
adding this line is not necessary:
[`cmd.Short = fmt.Sprintf("Querying commands for the %s module", types.ModuleName)`](https://github.com/osmosis-labs/osmosis/blob/main/x/ibc-hooks/client/cli/query.go#L32)
because the above already has:
[`Short:                      fmt.Sprintf("Querying commands for the %s module", types.ModuleName),`](https://github.com/osmosis-labs/osmosis/blob/main/x/ibc-hooks/client/cli/query.go#L38)
=> remove redundant line

.github/CODEOWNERS, x/concentrated-liquidity/fees.go
Closes: https://github.com/osmosis-labs/osmosis/issues/4415
Auto assigns designated group of people as reviewers depending on the module responsibilities.
For example, a change to CL module gets auto-assigned to people who have signed up for CL reviews beforehand.
Add codeowners for auto-assignment
*(or)*
*(or)*
*(example:)*
- Does this pull request …
=> Add codeowners for auto-assignment

tests/localosmosis/state_export/scripts/testnetify.py
This PR optimizes and fixes the replace function used in `testnetify` to handle both dictionaries and lists as input, ensuring a more flexible and efficient implementation. 
The previous version of the replace function had a bug where it did not handle the case when the input was a list. The optimized version now addresses this issue.
```bash
Chain ID: localosmosis
Moniker:  val
📝 Opening /osmosis/state_export.json... (it may take a while)
Traceback (most recent call last):
File "/osmosis/testnetify.py", line 381, in <module>
main()
File "/osmosis/testnetify.py", line 257, in main
replace_validator(genesis, old_validator, new_validator)
File "/osmosis/testnetify.py", line 51, in replace_validator
replace(genesis, old_validator.hex_address, new_validator.hex_address)
File …
```
=> [localosmosis] Fix bug in replace function

.dockerignore, .github/workflows/push-dev-docker-images.yml, .github/workflows/push-docker-images.yml, CHANGELOG.md, Makefile, tests/localosmosis/README.md, tests/localosmosis/docker-compose.yml, tests/localosmosis/state_export/docker-compose.yml, tests/localrelayer/docker-compose.yml
This PR updates our Docker base image to the latest `alpine:3.17` and adds the `tests/` folder to the `.dockerignore`.
- Update Docker base image to `alpine:3.17` 
- Add the `tests/` folder to `.dockerignore`
```bash
make docker-build-alpine
```
works as expected.
=> [chores] Update alpine docker base image to alpine:3.17

CHANGELOG.md, app/app.go, app/config.go, app/modules_test.go, app/test_helpers.go, cmd/osmosisd/cmd/root.go, tests/simulator/osmosis_helper.go
Closes: #4865 
*This pull request removeswasmEnabledProposals []wasm.ProposalType arg from NewOsmosisApp and update related files calling the function*
- *Remove wasmEnabledProposals []wasm.ProposalType from NewOsmosisApp*
=> Remove wasmEnabledProposals []wasm.ProposalType from NewOsmosisApp

.dockerignore
Changing the `.dockerignore` I think broke `e2e` scripts: https://github.com/osmosis-labs/osmosis/actions/runs/4669893927/jobs/8268946162
This PR reverts the changes.
- Revert `.dockerignore` changes
=> Revert dockerignore changes

x/concentrated-liquidity/msg_server.go, x/concentrated-liquidity/msg_server_test.go
Closes: #XXX
Currently we have a check in the CreatePool in the CL msg server, where we check if the given denom0 and denom1's denom meta data exists on chain. 
Unfortunately, we do not have all the denom metadata of ibc tokens registered on chain, thus this check needs to be removed. 
- Remove Denom metadata check upon CL Pool Creation
Deletes existing tests 
=> fix: Remove Denom metadata check upon CL Pool creation

app/upgrades/v16/upgrades.go, x/concentrated-liquidity/fees_test.go, x/concentrated-liquidity/pool_test.go, x/concentrated-liquidity/swaps_test.go, x/concentrated-liquidity/types/params.go
Closes: #XXX
- Sets default Params in CL Keeper in Upgrade handler, modifies default swap fee to 0.02.
Also made this issue https://github.com/osmosis-labs/osmosis/issues/4899 to have further discussions on how we want to handle default swap fees and migration for the pools that does not have swap fees that are allowed in the CL Keeper.
Set Param for CL Keeper in Upgrade handler, modify default swap fee to 0.02
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end deployment with …
=> Set Param for CL Keeper in Upgrade handler, modify default swap fee to 0.02

.github/workflows/changelog-entry-reminder.yml, CHANGELOG.md
Closes: #XXX
Adds workflow where the CI would fail upon not having CHANGELOG entry in the PR. 
The check can be skipped when labeled manually `no changelog`.
Add CHANGELOG Workflow
Tested via this PR
=> Add CHANGELOG Workflow

tests/cl-genesis-positions/edit_localosmosis_genesis.go
Closes: #XXX
The PR #4912 added a new data struct that broke an assumption of a currently merged script.
This fixes that issue.
=> fix: patch data struct

x/concentrated-liquidity/math/tick_test.go
Closes: #XXX
This PR adds additional realistic tick to sqrt price as well as price to tick tests.
=> chore: add tick tests

x/concentrated-liquidity/math/tick_test.go
Closes: #XXX
We are going with the exponent of price one of 6 and tick spacing of 100.
This test ensures that the numbers make sense at various price levels
=> test: add tick tests with exponent at price one of 6 and tick spacing  of 100 at various price levels

x/tokenfactory/types/msgs.go
Closes: #XXX
Fixes `MsgSetBeforeSendHook` msg type being returned. 
I feel like we should remove these annoying boilerplates in the near future :( 
Fix `MsgSetBeforeSendHook` msg type
No tests are needed for this change
=> Fix `MsgSetBeforeSendHook` msg type

.dockerignore
There are currently 3 markdown files in the root of a project, I just thought it would be nice to add it to `.dockerignore`
minor
=> docker: add `.md` files to `.dockerignore`

CHANGELOG.md, x/protorev/keeper/emit.go, x/protorev/keeper/emit_test.go, x/protorev/keeper/posthandler.go, x/protorev/keeper/posthandler_test.go, x/protorev/keeper/rebalance.go, x/protorev/keeper/rebalance_test.go, x/protorev/keeper/routes.go, x/protorev/protorev.md, x/protorev/types/events.go
- Adds protorev-specific event emission when the module successfully backruns to make it easier to index for tracking, research, and visualization purposes.
- Emits a protorev_backrun event upon successful backrunning of a transaction. Emits details about 1) user denoms, 2) pool points remaining, 3) profit and denom, 4) amount in and out to execute trade, and 5) tx_hash
- All tests current tests pass after changing input params necessary for event
- Added unit test for the added event
- Added event section to protorev.md and added the protorev_backrun event type and attrs.
=> Protorev: Backrun event emission

x/concentrated-liquidity/incentives.go, x/concentrated-liquidity/types/expected_keepers.go, x/pool-incentives/keeper/keeper.go, x/pool-incentives/keeper/keeper_test.go
[Closes: #4916](https://github.com/osmosis-labs/osmosis/issues/4916)
Our current implementation of reward splitting assumes that the longest lockup duration is the last one in the array of durations placed in state. While this is currently true, it is technically possible for this to be updated such that the last duration is not the longest, since we are not guaranteed that the list is sorted.
n/a
-added tests
=> [CL][Incentives]: Modify logic for getting lockup durations to be guaranteed to get longest duration

x/concentrated-liquidity/lp.go, x/concentrated-liquidity/lp_test.go
Closes: #4987 
We were not checking the owner of a position when calling the withdraw function. This PR adds the relevant logic and test.
- Adds check that provided owner is the owner of the position being withdrawn
- Adds a test to the currently existing `TestWithdrawPosition` that attempts to withdraw a position with a non-owner account.
Relevant test added to lp_test.go
=> bug[CL]: check owner when withdrawing position

app/upgrades/v16/concentrated_pool.go, tests/e2e/e2e_test.go, x/concentrated-liquidity/types/constants.go, x/concentrated-liquidity/types/params.go, x/poolmanager/router_test.go
Closes: #4899 
After speaking with Johnny, we decided on an initial set of authorized swap fees we can launch with. This can always we changed later via governance. The fees are as follows:
.01%
.05%
.1%
.2%
.3%
.5%
Additionally, there was a question on migrating future pools that do not fall into one of these above fee categories. There is no logic in the migration link function that requires the cl pool being linked to have the same swap fee as the balancer pool, so this so be a non issue.
- Adds authorized swap fees as a const
- Sets DefaultParams to the authorized swap fees set in the const 
- How …
=> [CL]: default swap fees

x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/fees.go, x/concentrated-liquidity/genesis.go, x/concentrated-liquidity/incentives.go, x/concentrated-liquidity/position.go, x/concentrated-liquidity/tick.go, x/superfluid/keeper/slash_test.go
Closes: #4984 
Adds a check to `TestPrepareConcentratedLockForSlash` that ensure:
* If run, the fee and incentive accum properly reflect the slashed value
* If error, the fee and incentive accum does not change
- Makes fee accumulator and uptime accumulator getter method from the CL module public
- Adds fee and reward accum checks to `TestPrepareConcentratedLockForSlash`
=> test: add incentive and fee accum check

tests/e2e/configurer/chain/commands.go, tests/e2e/containers/containers.go, x/concentrated-liquidity/tick.go, x/concentrated-liquidity/tick_test.go, x/concentrated-liquidity/types/constants.go
Closes: #[4850](https://github.com/osmosis-labs/osmosis/issues/4850) & https://github.com/osmosis-labs/osmosis/issues/4947
Add gas cost while initializing ticks
Add gas cost of 10_000 while initializing ticks
- tested withe minGasConsumed
=> refactor: charge gas for initialized ticks 

x/gamm/simulation/sim_msgs.go, x/valset-pref/simulation/sim_msgs.go
Closes: #XXX
In Go, the global rand variable is seeded by a default source, which is an implementation of a Source interface defined in the math/rand package. This source is based on the current time in nanoseconds and the process ID, and it is initialized the first time the math/rand package is imported.
In the simulator, we create a custom-seeded rand so that the simulator runs are deterministic.
This PR attempts to fix non-determinism by removing the use of global rand and using a simulator seeded rand. …
=> remove global rand seed from the simulator

x/superfluid/keeper/export_test.go, x/superfluid/keeper/migrate.go, x/superfluid/keeper/migrate_test.go, x/superfluid/keeper/msg_server.go
Closes: #4977 
We ended up splitting up the locked migration logic into three separate routes:
* Migration of superfluid delegated
* Migration of superfluid undelegating
* Migration of normal locked/unlocking
These three routes each had their own function calls, but was routed through a single router function. This PR introduces individual table driven tests for each of these functions, as well as the `ValidateSharesToMigrateUnlockAndExitBalancerPool` helper function.
- Renamed `MigrateLockedPositionFromBalancerToConcentrated` to `RouteLockedBalancerToConcentratedMigration`
- Added general test for the router function
- Added three separate tests for each function the router routes to
- Added test for validation helper function
- Does this pull request introduce a new feature or …
=> tests: individual table driven test for migration methods

tests/e2e/configurer/chain/commands.go
Closes: #4774 
We should be cautious when setting gas to auto in a testing environment. Without any checks in place, we will have nothing to tell us that a certain action is utilizing more gas than our maximum calculations tell us it should take.
The current gas value in e2e is 400000. We added a max gas of 600000 for createPosition, because we could initialize a maximum of two ticks in this process, each adding 100000 gas charge. With similar logic, we could un-initialize a maximum of two ticks in withdraw position. Withdraw position also runs `claimsRewards` and `claimFees` when the entire position is removed, increasing gas even more. This makes withdrawing an entire position potentially one of the most expensive operations in CL.
It is important to note that, when withdrawing only a …
=> tests[CL]: change withdraw gas from auto in e2e

x/concentrated-liquidity/README.md, x/concentrated-liquidity/client/cli/tx.go, x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/fees_test.go, x/concentrated-liquidity/keeper_test.go, x/concentrated-liquidity/model/msgs.go, x/concentrated-liquidity/model/pool.go, x/concentrated-liquidity/msg_server.go, x/concentrated-liquidity/msg_server_test.go, x/concentrated-liquidity/pool.go, x/concentrated-liquidity/pool_test.go, x/concentrated-liquidity/types/errors.go, x/concentrated-liquidity/types/events.go, x/gamm/README.md, x/gamm/keeper/msg_server.go, x/gamm/types/events.go, x/poolmanager/README.md, x/poolmanager/create_pool.go, x/poolmanager/create_pool_test.go, x/poolmanager/export_test.go, x/poolmanager/types/errors.go, x/poolmanager/types/events.go
Clickup link: 
https://app.clickup.com/37420681/v/dc/13nzm9-18987/13nzm9-35107
This PR introduces minor additions / changes relating to MsgCreateConcentratedPool:
* Test additions / refactors
* In-line comment additions / changes
* Documentation grooming
* Replace manual errors for custom error types
* Drive by changes
- CL, Poolmanager, and GAMM readme.md edits
- Pool created event source switched from gamm to poolmanager
- Event emission removed from CreatePool in gamm's msgServer (its already emitted in CreatePool within poolManager which all calls get routed through)
- Various test additions
Tests were added to cover any logic in the MsgCreateConcentratedPool path that was not already covered. …
=> [CL Message Audit]: MsgCreateConcentratedPool

tests/cl-genesis-positions/edit_localosmosis_genesis.go
Closes: #XXX
The CL script runs through position creation, many of which fail. These position IDs are skipped. The script then attempts to use the length of positions + 1 to set the last position ID to, but this is incorrect. We should instead use the last largest position ID and add one to this instead.
=> fix: last position ID bug

CHANGELOG.md, x/incentives/module.go, x/incentives/simulation/operations.go, x/lockup/module.go, x/superfluid/module.go, x/superfluid/simulation/operations.go
Closes: #4184 
As discussed in https://github.com/osmosis-labs/osmosis/pull/4768, we donot necessarily have to use bankKeeper from cosmos-sdk instead we can keep the interface and use simtypes.BankKeeper. So this PR changes everything related to stakingTypes.BankKeeper to simtypes.BankKeeper.
This change is already covered by existing tests.
=> [Simulator] Change stakingTypes.BankKeeper to simtypes.BankKeeper

x/concentrated-liquidity/swapstrategy/one_for_zero_test.go
Closes: #XXX
Conflicts that were undetected in-between PR merges by CI. This fixes Go tests on main
=> fix(ci): merge conflcit in calc amounts causing test failures

wasmbinding/stargate_whitelist.go
Closes: https://github.com/osmosis-labs/osmosis/issues/5048
The queries for EstimateSinglePoolSwapExactAmountOut and EstimateSwapExactAmountOut were declared as request, not response. 
Changed response type declaration to the correct one
All tests should pass
=> Fixed bad stargate query declaration

x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/incentives.go, x/concentrated-liquidity/incentives_test.go, x/concentrated-liquidity/position.go, x/concentrated-liquidity/position_test.go
Closes: #5038
Currently, there is a bug where we assume that the largest uptime is one of the supported uptimes. This PR fixes it to allow fungification after 1ns charge period passes.
Additionally, this PR adds tests to make sure that we cannot overclaim after fungification
=> fix/test: get largest uptime from params when fungifying

x/concentrated-liquidity/math/math_test.go
Closes: #XXX
Came up in discussions with @czarcas7ic . Trying to find the relationship between sqrt price and amount proportions and why liquidity 0 is not equal to liquidity 1 when amount proportions are equal to price.
Current understanding:
The invariant must hold that both tokens are contributing to the liquidity equally. For non-full range, the distance between P_c and P_l or P_c and P_h is not proportional to the price because these are virtual reserves that might not be proportional to the price itself.
However, in the full range, having the amounts ration equal to price leads to same liquidities because all reserves are accounted for.
- Does this pull request introduce a new feature or user-facing behavior …
=> test: TestGetLiquidityFromAmounts

tests/cl-go-client/main.go, tests/localosmosis/scripts/nativeDenomPoolA.json, tests/localosmosis/scripts/setup.sh, x/concentrated-liquidity/position.go, x/concentrated-liquidity/position_test.go, x/concentrated-liquidity/types/errors.go, x/gamm/README.md, x/gamm/keeper/migrate.go, x/gamm/keeper/migrate_test.go, x/gamm/types/key.go, x/gamm/types/key_test.go, x/superfluid/keeper/msg_server_test.go, x/twap/listeners_test.go
ClickUp Checklist:
https://app.clickup.com/37420681/v/dc/13nzm9-19527/13nzm9-36307
This PR includes changes made from the internal audit of MsgMigrateSharesToFullRangeConcentratedPosition.
- Updated cl go client script to use same denoms as the pool being created
- @AlpinYukseloglu also realized that the only reason this was working was because we weren't checking denoms in createPosition itself
- Changes one of the GAMM pools that is created in localosmosis to match the denoms of the CL pool.
- This is to allow us to create a canonical connection between a GAMM and CL pool to further test messages (such as this migration message)   
- Adds defense in depth to check coin inputs for `CreateFullRangePosition`
- Expands existing tests
- Adds test for `GetPoolIdFromShareDenom`
- Does this …
=> [CL Message Audit]: MsgMigrateSharesToFullRangeConcentratedPosition

app/upgrades/v15/export_test.go, app/upgrades/v15/upgrade_test.go, x/concentrated-liquidity/fees_test.go, x/concentrated-liquidity/incentives_test.go, x/concentrated-liquidity/keeper_test.go, x/concentrated-liquidity/msg_server_test.go, x/concentrated-liquidity/pool_test.go, x/concentrated-liquidity/swaps_test.go, x/gamm/keeper/gas_test.go, x/gamm/keeper/grpc_query_test.go, x/gamm/keeper/keeper_test.go, x/gamm/keeper/pool_service_test.go, x/gamm/keeper/pool_test.go, x/poolmanager/create_pool_test.go, x/poolmanager/router_test.go, x/protorev/keeper/keeper_test.go
This PR eliminates double imports in Osmosis' tests.  It works toward the goal of being able to lint tests by default, and should help with maintenace and upgrades, too. 
* eliminate double imports
- Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? no: it's not worthy
=> style: eliminate double imports in tests

app/upgrades/v15/upgrade_test.go, app/upgrades/v16/upgrades_test.go, app/upgrades/v4/upgrade_test.go, app/upgrades/v9/upgrade_test.go, tests/e2e/e2e_test.go, x/concentrated-liquidity/fees_test.go, x/concentrated-liquidity/incentives_test.go, x/concentrated-liquidity/lp_test.go, x/concentrated-liquidity/position_test.go, x/lockup/keeper/grpc_query_test.go, x/lockup/keeper/lock_test.go, x/tokenfactory/keeper/admins_test.go
Eliminate ineffectual assignments from Osmosis tests. 
=> ineffectual assignments

x/tokenfactory/keeper/before_send_test.go
Remove ioutil because it is deprecated
=> use os.ReadFile instead of ioutil.ReadFile

tests/e2e/e2e_setup_test.go, tests/e2e/e2e_test.go, tests/ibc-hooks/ibc_middleware_test.go, wasmbinding/test/custom_query_test.go, x/concentrated-liquidity/fees_test.go, x/concentrated-liquidity/incentives_test.go, x/concentrated-liquidity/lp_test.go, x/concentrated-liquidity/position_test.go, x/concentrated-liquidity/store_test.go, x/gamm/client/cli/cli_test.go, x/gamm/keeper/pool_service_test.go, x/gamm/keeper/pool_test.go, x/gamm/pool-models/balancer/marshal_test.go, x/gamm/pool-models/balancer/pool_test.go, x/gamm/pool-models/balancer/util_test.go, x/incentives/client/cli/cli_test.go, x/incentives/types/msgs_test.go, x/lockup/types/msgs_test.go, x/poolmanager/types/routes_test.go, x/superfluid/keeper/migrate_test.go, x/superfluid/keeper/unpool_test.go, x/superfluid/types/msg_test.go, x/tokenfactory/types/msgs_test.go, x/twap/api_test.go, x/twap/client/query_proto_wrap_test.go, x/twap/listeners_test.go, x/twap/logic_test.go
Closes: #XXX
This PR removes unused code in tests.
* remove unused constants, variables, and functions in osmosis' tests.
=> style: remove unused code in tests

CHANGELOG.md, x/twap/types/genesis.go, x/twap/types/genesis_test.go
Closes: #5041
More context: https://osmosis-network.slack.com/archives/C027ELA290B/p1682692206195569
Currently, our validation for `TwapRecord`s in `InitGenesis()` is stricter than it should be.
If there is a twap error, it expects both "p0" spot price and "p1" spot price to be zero.
However, that is not the guarantee from the core logic:
https://github.com/osmosis-labs/osmosis/blob/b101d06dc867400e4309877ccf559f09c89edda3/x/twap/logic.go#L53-L64
In the core logic above, if "p0" gets a twap error but "p1" does not, "p0" is set to zero but  "p1" isn't.
Therefore, we should change our init genesis logic to match the core's constraints.
- make the change
- add tests
- Refactored test cases …
=> fix(x/twap): genesis issue blocking edge net set up

.github/dependabot.yml
Dependabot can ensure that github actions aren't out of date.  I noticed several that are, but instead of manually fixing the actions, dependabot will do it faster and more reliably over time. 
* use dependabot to check for updates to `github-actions`
If change was successful, we should see dependabot make several PR's after this is merged. 
=> check github actions with dependabot

CHANGELOG.md, x/gamm/pool-models/internal/cfmm_common/lp.go
=> Clarify error message when you try to completely exit a pool

.github/pull_request_template.md
I've never found the brief changelog section of The PR template useful, so this PR deletes that. Thoughts?
N/A
=> Remove a section of PR template

osmoutils/accum/prefix.go, x/concentrated-liquidity/swaps.go
We were spending a lot of time in accumulator key formatting, for basically doing sprintf's with constants. This PR fixes that.
It also highlights a bug in the docs before (that ideally should get fixed prelaunch)
Also converts one `Add` to an `AddMut`
=> Speedup accumulator prefix keys

x/concentrated-liquidity/math/precompute.go, x/concentrated-liquidity/math/tick.go
Using Roman's CL benchmark as a guide, this PR provides a slight speedup to the CL math. (~8%)
I suggest we completely make `tickIndex` an `int64`, and `TickExponent` an int64, both of which will imo simplify the code, and together provide another 5% speedup.
=> Speedup some of the swap logic by doing more pre-computation in tick math

osmomath/decimal.go, osmomath/int.go
Closes: #5163 
<del>Marks helper functions in `osmomath` with `t.Helper()`. </del>
Disables thelper warnings for some functions. Reason for not marking those functions with `t.Helper()`: https://github.com/osmosis-labs/osmosis/issues/5163#issuecomment-1545983797
=> osmomath: disable thelper for some helper functions

x/poolmanager/types/codec.go
Closes: #XXX
Missed adding the new messaged to codec and interface registrations. This PR fixes it
=> fix: add split route message to codec and interface registration

x/concentrated-liquidity/swaps.go, x/concentrated-liquidity/swaps_test.go
Closes: #XXX
This PR adds a more explicit check and a more descriptive error in swaps when there are no positions created.
=> refactor: more discriptive error when no liquidity in swaps

x/concentrated-liquidity/README.md
Closes: #XXX
Fixes some readme errors ottersec pointed out during review.
=> fix[CL]: Readme

.vscode/tasks.json, Makefile, app/apptesting/test_suite.go, app/upgrades/v13/upgrade_test.go, app/upgrades/v15/upgrade_test.go, tests/ibc-hooks/ibc_middleware_test.go, wasmbinding/test/custom_msg_test.go, wasmbinding/test/custom_query_test.go, wasmbinding/test/messages_test.go, wasmbinding/test/queries_test.go, wasmbinding/test/store_run_test.go, x/ibc-rate-limit/ibc_middleware_test.go, x/tokenfactory/keeper/before_send_test.go
Closes: #XXX
This PR fixes a lot of local environment pains for me on WSL.
In particular, I cannot run WASM related tests with `make test-unit `due to some permissioning issue.
This is the best solution I've found after countless hours of debugging.
In particular, it detects if the system is a WSL, and then sets `SKIP_WASM_WSL_TESTS` environment variable to true. Next, the Go tests read that environment variable and skip the problematic tests.
I also added a task so that I can set up some key bindings for running unit tests.
=> chore: skip wasm tests in wsl and add a vs code task

.vscode/settings.json
Just following the guidelines here:
* https://golangci-lint.run/usage/integrations/
This should make it easier to work with golangci-lint in vscode. 
If your editor is faster, then this PR is doing its job
=> chore: update golanci-lint settings

x/concentrated-liquidity/bench_test.go
Closes: #XXX
We need to commit so that the positions propagate to IAVL instead of sitting in cache for the benchmark to be accurate.
=> chore: commit at the end of benchmark

app/upgrades/v15/upgrade_test.go, osmomath/go.mod, osmomath/go.sum, osmoutils/go.mod, osmoutils/go.sum, tests/cl-genesis-positions/go.mod, tests/cl-go-client/go.mod, tests/cl-go-client/go.sum, tests/e2e/e2e_setup_test.go, tests/e2e/e2e_test.go, tests/ibc-hooks/ibc_middleware_test.go, wasmbinding/query_plugin_test.go, x/concentrated-liquidity/lp_test.go, x/epochs/go.mod, x/epochs/go.sum, x/ibc-hooks/go.mod, x/ibc-hooks/go.sum
Works toward: #5061 
* #5127 began to become pretty unruly, and it seemed best to remove some things from it (the not-challenging, not 
type assertion things)
This code should pass all tests.
To my knowledge, we don't want a PR like this one to hit the changelog.
=> chore: lint tests and sync for app, osmomath, tests, and wasmbinding

x/pool-incentives/keeper/grpc_query.go, x/pool-incentives/keeper/grpc_query_test.go
Closes: #XXX
While investigating our external gauge query for compatibility with CL gauges, I noticed that the query was completely untested (which slowed me down). This PR adds robust tests for this query and makes minor fixes to godocs. 
- Tests are in `grpc_query_tests.go`
=> [x/pool-incentives][tests]: Add tests for external gauge query

x/concentrated-liquidity/position.go, x/concentrated-liquidity/position_test.go, x/concentrated-liquidity/simulation/sim_msgs.go
Closes: #4733
We currently store the following KVStores:
`Owner | Pool ID | Position ID -> Position ID`:
```
addr1|1|1->1
addr1|1|2->2
addr1|2|3->3
addr2|1|4->4
addr2|1|5->5
```
As well as `Pool ID | Position ID -> Position ID` like so:
```
1|1->1
1|2->2
2|3->3
1|4->4
1|5->5
```
Storing the position ID in both the key and value is redundant and requires at a minimum 8 bytes. We instead change this to a single byte []byte{1} to represent that the key is present. If we need to determine a position ID that belongs to a pool ID, we can simply parse the keys rather than values like before.
=> perf: change KVStore value from posID to boolean byte

x/concentrated-liquidity/README.md
Closes: #5241
This PR adds a section called **Incentive Creation and Querying** to the CL README, explaining that gauge-related logic should be use for creating and querying internal and external incentives.
=> [CL][Docs] Expand incentives README to mention gauge logic

x/concentrated-liquidity/README.md
Closes: #5240
This PR adds a section on reward splitting to the CL README.
=> [CL][Docs] Add README section on reward splitting 

CHANGELOG.md, x/concentrated-liquidity/incentives.go, x/concentrated-liquidity/incentives_test.go, x/concentrated-liquidity/types/expected_keepers.go, x/gamm/keeper/pool.go, x/gamm/keeper/pool_test.go
Closes: #5192
This PR implements a bug fix for reward splitting where all Balancer shares were counted towards reward splitting liquidity when only bonded shares should have been.
It also implements a helper in GAMM that was necessary to retrieve total pool shares while avoiding import cycles.
- Tests for the new helper are in gamm's `pool_test.go`
- Tests for reward splitting fix are in `incentives_test.go`
Where is the change documented? 
> README missing section on reward splitting. Created issue here: #5240
=> [CL][bugfix] Update reward splitting logic to only use bonded balancer amounts

x/concentrated-liquidity/fees.go, x/concentrated-liquidity/fees_test.go
Closes: #XXX
Brought up by otter sec.
Reinvest dust fees into pool accumulator. Currently, we simply lose the truncation dust. However, a better way would be to put them back into the global pool accumulator.
Added test case
=> refactor: reinvest dust fees into pool accumulator

x/concentrated-liquidity/swaps.go, x/concentrated-liquidity/swapstrategy/one_for_zero.go, x/concentrated-liquidity/swapstrategy/swap_strategy.go, x/concentrated-liquidity/swapstrategy/swap_strategy_test.go, x/concentrated-liquidity/swapstrategy/zero_for_one.go, x/concentrated-liquidity/tick.go
Closes: #XXX
This PR is a follow-up to: https://github.com/osmosis-labs/osmosis/pull/5177
Similarly to swap out given in, this PR optimizes in given out and liquidity for full range query.
Now, there is no need for some obsolete API on the compute swap strategy. As a result, the API and tests are removed.
=> perf: iterator improvements for swap in given out and liquidity for full range query

CHANGELOG.md, x/concentrated-liquidity/README.md
This pull requests fixes incorrect variable usage for the equation to calculate the price of a concentrated liquidity pool tick.
Previously, the equation is
$$ p(i) = 1.0001^t $$
However, the variable `i` should be replaced with `t` which is used in the right hand side of the equation, and thus should be
$$ p(t) = 1.0001^t $$
=> fix: concentrated liquidity price tick equation variable

.github/dependabot.yml, CHANGELOG.md
Closes: #5227 
Adds labels to dependabot to avoid adding them manually 
Minor 
Changelog
=> Auto add changelog and backport labels to dependabot 

x/concentrated-liquidity/bench_test.go
Closes: #4597 
Benchmark | Iterations | Time
-- | -- | --
BenchmarkGetTickLiquidityNetInDirection-10 | 43 | 27575030 ns/op
BenchmarkGetTickLiquidityNetInDirection-10 | 45 | 27375894 ns/op
BenchmarkGetTickLiquidityNetInDirection-10 | 43 | 26541238 ns/op
BenchmarkGetTickLiquidityNetInDirection-10 | 46 | 27896807 ns/op
BenchmarkGetTickLiquidityNetInDirection-10 | 44 | 27972892 ns/op
<br class="Apple-interchange-newline">
Benchmark | Iterations | Time
-- | -- | --
BenchmarkGetTickLiquidityNetInDirection-10 | 4 | 285060562 ns/op
BenchmarkGetTickLiquidityNetInDirection-10 | 4 | 259781604 ns/op
BenchmarkGetTickLiquidityNetInDirection-10 | 4 | 273009479 ns/op
BenchmarkGetTickLiquidityNetInDirection-10 | 4 | 259881292 ns/op
BenchmarkGetTickLiquidityNetInDirection-10 | 4 | 277734042 ns/op
<br …
=> bench: GetTickLiquidityNetInDirection & GetTickLiquidityForFullRange

app/apptesting/test_suite.go, x/concentrated-liquidity/bench_test.go
Our Prior CL benchmarks weren't using LevelDB, so could be giving erroneous data.
We should assume that in practice, the LevelDB read times will become far higher than what we observe in these isolated tests.
=> Use leveldb for benchmarks

x/concentrated-liquidity/bench_test.go, x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/pool.go, x/concentrated-liquidity/pool_test.go, x/concentrated-liquidity/tick.go
Closes: #XXX
Removing repeated defense-in-depth sanity check. We should be checking pool existence much earlier in the execution flow.
Old:
New:
With 100k positions and 180k ticks traversed:
```
go test -bench . -run BenchmarkSwapExactAmountIn -timeout=30m -v -count=3
goos: linux
goarch: amd64
pkg: github.com/osmosis-labs/osmosis/v15/x/concentrated-liquidity
cpu: Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
BenchmarkSwapExactAmountIn
BenchmarkSwapExactAmountIn-4                           1        2412393389 ns/op
BenchmarkSwapExactAmountIn-4                           1        2406438654 ns/op
BenchmarkSwapExactAmountIn-4                           1        2307147354 ns/op
```
=> perf: remove repeated pool exists check

x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/genesis.go, x/concentrated-liquidity/keeper_test.go, x/concentrated-liquidity/swaps.go, x/concentrated-liquidity/tick.go, x/concentrated-liquidity/tick_test.go, x/concentrated-liquidity/types/errors.go
Closes: #XXX
Please see the summary of performance improvements in this prototype PR: https://github.com/osmosis-labs/osmosis/pull/5287
This is the first change that focuses only on avoiding refetching ticks.
The final benchmark and pprof graph with all 3 changes is attached to #5287.
=> perf: avoid refetching ticks during swaps; parse from iterator value

x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/fees.go, x/concentrated-liquidity/fees_test.go, x/concentrated-liquidity/keeper_test.go, x/concentrated-liquidity/lp_test.go, x/concentrated-liquidity/swaps.go, x/concentrated-liquidity/tick.go, x/concentrated-liquidity/tick_test.go
Closes: #XXX
This is a third improvement identified in:
https://github.com/osmosis-labs/osmosis/pull/5287
Thi improvement focuses on removing the need for refetching and reunmarshaking fee accumulator on every swap step.
We only need to fetch it once, get its value every time a tick is crossed and update at the very end of the swap.
Drive-by changes:
- remove awkward abstraction called `ChargeFee`. I think it is clearer to add to the accumulator directly
- replace `ChargeFee` with `AddToFeeAccumulator` helper in tests
Since this is the last improvement identified, this is the flame graph as of [this commit]([116170d](https://github.com/osmosis-labs/osmosis/pull/5298/commits/116170d047f825c6ba7dedf6a827eeb587d39ae8))
Comparison to commit from yesterday: …
=> perf: remove repeated fee accumulator unmarshaling in swaps

x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/fees.go, x/concentrated-liquidity/fees_test.go, x/concentrated-liquidity/incentives.go, x/concentrated-liquidity/incentives_test.go, x/concentrated-liquidity/keeper_test.go, x/concentrated-liquidity/lp_test.go, x/concentrated-liquidity/swaps.go, x/concentrated-liquidity/tick.go, x/concentrated-liquidity/tick_test.go, x/concentrated-liquidity/types/errors.go
Closes: #XXX
This is a second improvement identified in:
https://github.com/osmosis-labs/osmosis/pull/5287
It focuses around:
- removes repeated proto unmarshaling inside the loop as we cross ticks in `updateUptimeAccumulatorsToNow`
- repeated uptime accumulator fetching and unsmarsharling. Instead, we fetch them once at the top and operated on the accumulators passed into methods as a slice. In Go, slice elements are mutated as long as they are edited directly via slice instead of copied to a local variable.
- Added new tests where applicable
Added strict tests to ensure that the parameter `uptimeAccums` are mutated in:
=> perf: remove repeated pool unmarshaling and uptime accum refetching overhead in swaps

tests/e2e/initialization/config.go
- v16 upgrade changes protorev to pay dev account after every trade, instead of tracking it in a kvstore and paying out on a weekly basis
- This PR adds a dev account to the ProtoRev module in e2e test to properly test that the v16 upgrade sends left over dev funds tracked in the kvstore to the dev account during the upgrade.
- Testing will happen in a future PR that implements protorev's v16 upgrade.
- No new documentation added
=> update e2e genesis config for protorev module

tests/e2e/containers/config.go, tests/e2e/e2e_test.go
- In a previous PR, we changed e2e genesis config for protorev v16 upgrade testing: https://github.com/osmosis-labs/osmosis/pull/5312
- This PR bumps the previousVersionOsmoTag and previousVersionInitTag to the docker container tag output by the backport merge
- Removes a no longer used test for protorev upgrade
- N/A
=> bump previousVersionInitTag, remove no longer used protorev upgrade test

x/concentrated-liquidity/incentives.go, x/concentrated-liquidity/incentives_test.go, x/concentrated-liquidity/types/export_test.go, x/concentrated-liquidity/types/params.go, x/concentrated-liquidity/types/params_test.go
This PR fixes the discount rate bound check that was supposed to ensure invalid discount rates could never be put into a proposal. It also fixes the lower level check that was meant to ensure that if an invalid discount rate does get through, it does not allow for draining of funds.
- Added test case & logic to `incentives_test.go`
=> [CL][bugfix] Fix discount rate bound check

x/concentrated-liquidity/bench_test.go, x/concentrated-liquidity/incentives_test.go
Helps get more attention on relevant parts of test that matters. (In this process, noticed some tests that weren't doing anything)
-  bench_test: Removes some repeated code
-  incentives_test: Make a helper for `setupBalancerPoolWithFractionLocked`
-  incentives_test: Remove `Err` and `ErrorIs` / `ErrorContains` duplicate checks. just do the more specific check
-  incentives_test: TestPrepareBalancerPoolAsFullRange split out moving pool error tests
=> [CL] Delete more test code

x/concentrated-liquidity/math/math.go
Closes: #5073
This PR removes the unnecessary additional roundup in `CalcAmount1Delta`. The effective impact is minimal (as `MulRoundup` only rounds the last digit while `Ceil` rounds up to the next int), but still an appropriate change to make. 
This change does not affect rounding behavior enough to warrant a boundary test as the additional roundup was extraneous – all rounding-related test cases continue to pass.
=> [CL]: Remove double rounding in `CalcAmount1Delta`

tests/cl-go-client/main.go
Closes: #XXX
@jonator mentioned that script breaks due to not accounting for tick spacing. This fixes it
Tested locally and can create positions with no issues
=> fix: tick spacing with cl go client script for creating positions

x/concentrated-liquidity/incentives.go
Closes: #5362
This PR fixes a bug where `calcAccruedIncentivesForAccum` was mutating the passed in incentive records. While this does not break anything in its current state, it's an important misalignment between spec and implementation
This bug was caught by the tests in #5359 and is thoroughly tested there. Isolating the issue to help with reviewability.
=> [CL][bugfix]: Make calc accrued incentives nonmutative

x/concentrated-liquidity/lp.go, x/concentrated-liquidity/types/events.go, x/superfluid/keeper/concentrated_liquidity.go, x/superfluid/types/events.go
Closes: #XXX
Made to make sure that FE and data have all the info needed. This is likely not be needed since newPositionId is returned from the message. However, we decided to include this in advance in case we later find out that this is useful in events.
=> refactor: new position id in events for add to position

app/upgrades/v16/upgrades.go, x/twap/export_test.go, x/twap/keeper.go, x/twap/logic.go, x/twap/store.go, x/twap/types/genesis.go
Closes: #5343 
We currently create a CL pool and create a position all within the same block in the upgrade handler. This causes the last error time to get set to now (this is default behavior when we create a pool) AND the spot prices are set when we create a position. This causes a genesis check to pop. 
This PR nils out the last error time in the upgrade handler for the CL pool's twap record
Nicco tested out this branch with mainnet state and ran the upgrade handler and no longer receives the twap error.
=> fix: twap record upgrade handler

x/concentrated-liquidity/position.go, x/concentrated-liquidity/position_test.go
Closes: [#5052](https://github.com/osmosis-labs/osmosis/issues/5052)
In deletePosition, we delete from multiple indexes. However, there is only one error case covered by tests - PositionIdNotFoundError
added test
=> Internal Review][CL][deletePosition]: test edge cases where one of the indexes does not exist

.github/workflows/changelog-entry-reminder.yml, .github/workflows/required_labels.yml
Closes: #5270 (Rework)
Do not require changelog and state machine labels for markdown only changes by using following steps:
- Detect the changed files by using this workflow https://github.com/tj-actions/changed-files
- Skip the step to check changelog and return success results for `changelog` and `required label` checks incase only markdown changes. 
- If the PR contains file other than *.md, it will function as current behaviour
This change was tested on my forked repository and be verified as follows:
- See: https://github.com/tungbq/osmosis/pull/4/checks
- Case 01: Only markdown changes: 
- Case 02: Normal changes: 
=> feat: do not require changelog and state machine labels for markdown only changes

x/concentrated-liquidity/swaps.go
Closes: #5379
During functional fungification tests, it came up that SwapInGivenOut (surprisingly) tracks the wrong denom for fees, leading to a panic being triggered when rewards are claimed. This PR fixes this by changing fees to always track the input denom.
Thanks to @czarcas7ic for helping narrowing down the source of the bug and the needed fix.
Tests for this functionality are in a separate PR on functional tests, as the abstractions set up in that PR makes this significantly simpler to test. This change was confirmed to fix the core issue against those tests and is being pushed separately to get breaking changes as early as possible.
=> [CL][bugfix]: Fix SwapInGivenOut to track fees with the correct denom

CHANGELOG.md, x/superfluid/types/msgs.go
Closes: #XXX
Delete the wrong check in `ValidateBasic` of  `MsgUnlockAndMigrateSharesToFullRangeConcentratedPosition`
=> [Superfluid] Delete wrong check in `ValidateBasic` of `MsgUnlockAndMigrateSharesToFullRangeConcentratedPosition`

x/cosmwasmpool/README.md
Closes: #XXX
Adding documentation on how I'm planning to handle code id management via gov props.
We briefly discussed this approach via comments in: https://github.com/osmosis-labs/osmosis/pull/4810
Would like to converge on this before I spend time implementing.
=> docs(x/cosmwasmpool): code id whitelist via gov props

x/concentrated-liquidity/incentives_test.go, x/concentrated-liquidity/keeper_test.go, x/concentrated-liquidity/lp_test.go, x/concentrated-liquidity/position_test.go
Closes: #XXX
This PR adds a parameter to `SetupPosition` that allows for dust amount to be added to the funded amount. This should likely be on by default (as the helper is meant to abstract away funding the account & never fail to fund), but I left it as an option as it seems some tests lean on this quirk to test insufficient balances.
=> [CL][tests]: Add option to handle rounding in position setup helper

scripts/mutation-test.sh
Closes: #XXX
The mutation script allows users to specify specific modules to run mutation tests on. These tests still take a really long time, and many times a user might just want to run on a specific file. This modification allows for this. For example:
```
./mutation-test.sh "concentrated-liquidity" "../x/concentrated-liquidity/incentives.go"
```
This runs mutation tests on just incentives.go file and nothing else.
=> feat: run mutation script on specific files

x/superfluid/keeper/migrate.go, x/superfluid/keeper/migrate_test.go, x/superfluid/keeper/synthetic_lock_wrapper.go
Closes: #XXX
While creating E2E tests for CL, @ThanhNhann from Notional discovered the following bug:
In the `migrateSuperfluidUnbondingBalancerToConcentrated` method, we call createSyntheticLockup https://github.com/osmosis-labs/osmosis/blob/41af9f9708ad25053b9a4a5660affd0ff1bae7b0/x/superfluid/keeper/migrate.go#L169-L173 at the very end in an unlocking status. This is so that if, after their migration their validator gets slashed, they will also still get slashed approppriatly.
The bug is, in `createSyntheticLockup` https://github.com/osmosis-labs/osmosis/blob/41af9f9708ad25053b9a4a5660affd0ff1bae7b0/x/superfluid/keeper/synthetic_lock_wrapper.go#L42-L55 we use the unbondingTime parameter as the unbonding duration for the synth lock. So even if the user had 4 mins left, their synth lock …
=> fix: sf unbonding migration patch

CHANGELOG.md, cmd/osmosisd/cmd/root.go, x/tokenfactory/types/params.go
Closes: [#5440](https://github.com/osmosis-labs/osmosis/issues/5440)
The current default mempool max gas per tx value is the old 25M value:
[osmosis/cmd/osmosisd/cmd/root.go](https://github.com/osmosis-labs/osmosis/blob/c6697a5e4b2ccdf216f213a33db7e97b0dd46399/cmd/osmosisd/cmd/root.go#L151)
Line 151 in [c6697a5](https://github.com/osmosis-labs/osmosis/commit/c6697a5e4b2ccdf216f213a33db7e97b0dd46399)
max-gas-wanted-per-tx = "25000000" 
Along with localosmosis instances, this apparently impacts edgenet? So transactions that exceed the 25M limit fail:
[osmosis/x/tokenfactory/types/params.go](https://github.com/osmosis-labs/osmosis/blob/c6697a5e4b2ccdf216f213a33db7e97b0dd46399/x/tokenfactory/types/params.go#L16)
Line 16 in [c6697a5](https://github.com/osmosis-labs/osmosis/commit/c6697a5e4b2ccd …
=> [fix] Reduce tokenfactory gas fee

app/keepers/keepers.go, x/tokenfactory/keeper/before_send.go, x/tokenfactory/keeper/keeper.go, x/tokenfactory/types/expected_keepers.go
Closes: #XXX
Previously we had the design in token factory where we would be injecting wasm keeper to the hook interface, while as this PR changes the wasmKeeper to nest within the TokenFactory keeper.
Existing tests passes
=> Change token factory wasm keeper from hook to keeper

x/concentrated-liquidity/swaps.go, x/concentrated-liquidity/swapstrategy/one_for_zero.go, x/concentrated-liquidity/swapstrategy/one_for_zero_test.go, x/concentrated-liquidity/swapstrategy/swap_strategy.go, x/concentrated-liquidity/swapstrategy/swap_strategy_test.go, x/concentrated-liquidity/swapstrategy/zero_for_one.go, x/concentrated-liquidity/swapstrategy/zero_for_one_test.go, x/concentrated-liquidity/tick.go
Closes: #XXX
Tick iterator setup for both swap directions had an off by one error that made pools vulnerable to being forced into invalid tick iterator states. This PR patches both of these bugs, tests the changes, and cleans up the code (since implementing the fix rendered `InitializeTickValue` unnecessary).
All the new/amended tests can be found in the respective swap strategy test files (`zero_for_one_test.go` and `one_for_zero_test.go`).
I had a local repro hitting this specific case for the second bug at a higher level of abstraction with swaps but did not want to block this PR on manually calculating the test vectors. Will include this test in a future PR with functional tests.
=> [CL]: Fix two critical tick iterator-related bugs

x/incentives/keeper/distribute_test.go, x/incentives/keeper/gauge.go, x/incentives/keeper/gauge_test.go, x/incentives/types/expected_keepers.go, x/incentives/types/keys.go, x/pool-incentives/keeper/genesis.go, x/pool-incentives/keeper/genesis_test.go, x/pool-incentives/keeper/grpc_query.go, x/pool-incentives/keeper/grpc_query_test.go, x/pool-incentives/keeper/keeper.go, x/pool-incentives/keeper/keeper_test.go, x/pool-incentives/types/key.go
Closes: #XXX
This problem was called out during the review in:
https://github.com/osmosis-labs/osmosis/pull/5459#discussion_r1223386216
For the new "NoLock" type gauge we would create a pool id <> gauge it link in the `x/pool-incentives` module.
However, that link is currently used for determining which gauge is internally incentivized.
For example, in balancer, if there is a pool id <> gauge id link present, some queries assume that the gauge id is meand for internal incentives.
By utilizing the same store index with the new "NoLock" gauge, the external incentives query ended up being broken.
To fix this, a completely new store index was introduced for the "NoLock` gauge. This store index is used for both external and internal "NoLock" gauges.
However, for internal "NoLock" gauges we …
=> refactor/fix: external vs internal pool id and gauge id links for "NoLock" gauge

x/concentrated-liquidity/event.go, x/concentrated-liquidity/lp.go
This PR refactors the emitLiquidityChangeEvent to use struct params to follow golang best practices
This is linked to https://github.com/osmosis-labs/osmosis/issues/5485#issuecomment-1584878204 and is a refactor proposal that could serve as a base for future refactoring. 
This change is already covered by existing tests in `lp_test.go`.
=> refactor: emitLiquidityChangeEvent To Use Struct Params

Makefile, tests/cl-go-client/README.md, tests/cl-go-client/main.go, tests/localosmosis/scripts/setup.sh
Closes: #XXX
This PR modifies the script to add the ability to create external incentives via gauges and wait for an epoch so that it is converted into an incentive record.
=> feat/docs: CL external incentives tool

x/concentrated-liquidity/math/precompute.go, x/concentrated-liquidity/math/tick.go, x/concentrated-liquidity/types/constants.go
This PR uses pre-computation for price to tick, and (at least to me) feels like it simplifies the code.
This also surfaces questions for the bucket index definition that I think we should be handling in a follow-up PR
=> Use more precomputation for price to tick

osmoutils/accum/accum.go, osmoutils/accum/prefix.go, x/concentrated-liquidity/incentives.go, x/concentrated-liquidity/position.go, x/concentrated-liquidity/types/keys.go, x/concentrated-liquidity/types/keys_test.go, x/concentrated-liquidity/types/keyspace.md
We have key malleability concerns with the accumulator key choices, if the accumulator name contains a `/` (which we do). Requires nuanced arguments that can easily be invalidated in the future to argue no bug. Hence we make this less brittle, by changing the appending to `||`. 
Furthermore fixes a bug if the accumulator name ever began with `pos/`. 
Fixes bugs for the iterators on User Positions
Also contains some other notes of mine, that seem time inefficient to branch out.
<TODO>
=> Note accum key factor potential bugs/pit falls

CHANGELOG.md, wasmbinding/query_plugin_test.go, wasmbinding/stargate_whitelist.go
Closes: #XXX
Gamm v2 spot price qurey has been marked deprecated, whilst we have created a new query for spot price in the pool manager. 
We did not deprecate it in stargate whitelist though, having the old query still in stargate whitelist. 
This PR submits a change so that we use the new query for spot price in stargate whitelist. 
=> fix:  add pool manager spot price query to stargate whitelist

proto/osmosis/concentrated-liquidity/tx.proto, x/concentrated-liquidity/lp.go, x/concentrated-liquidity/lp_test.go, x/concentrated-liquidity/types/tx.pb.go
Closes: https://github.com/osmosis-labs/osmosis/issues/5238
Previously, the min amount fields in AddToPosition were corresponding to the min amount of the total liquidity of the position. 
This PR implements the change to use min amount field instead to use min amount field for the amount that is being added. 
Made fix to according tests
=> fix: use min_amount field in AddToPosition Msg  correspond to amount being added

osmomath/binary_search.go, x/concentrated-liquidity/invariant_test.go
Progress towards: #5428
This PR implements the following two test helpers for tracking global CL invariants:
1. `assertTotalRewardsInvariant`: claims all spread rewards and incentives for all positions and ensures claim amounts are correct relative to pool balances
2. `assertWithdrawAllInvariant`: withdraws all positions from all pools and ensures state is updated correctly
Please note that the individual balances are not directly checked for `assertWithdrawAllInvariant` as it's difficult to track exactly how much was claimed due to fees vs. withdrawn amount. Regardless, as long as global invariants hold, we guarantee that the pool-side balance was updated correctly.
This change introduces test helpers.
=> [CL][tests]: Extract global invariant helpers from functional tests

app/apptesting/cosmwasmpool.go, app/apptesting/test_suite.go, app/test_helpers.go, x/cosmwasmpool/cosmwasm/msg/transmuter/transmuter_test.go, x/cosmwasmpool/model/pool_test.go, x/cosmwasmpool/pool_module_test.go, x/cosmwasmpool/whitelist_test.go
CI tests are failing intermittently for cosmwasmpool tests. The working theory is that the issue is due to parallelism where different tests try to write the same contracts to cache, which means that the bytecode can be corrupted when some of the tests read during a partial write.
(Thanks to Simon Warta for helping figure this out)
This change ensures each instance of the app used in tests has its own custom (temp) directory 
Tests should consistently pass
=> Use custom directories for each test instance

x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/swaps.go, x/concentrated-liquidity/swaps_test.go
This PR:
- renames `ss.spreadRewardGrowthGlobal` to `ss.globalSpreadRewardGrowthPerUnitLiquidity`
- Adds `globalSpreadRewardGrowth` into swapState, rather than tracking it in the core swap loop
- Adds swaps strategy into swapstate, lowering # of arguments needed for code de-duplication across swap types
- Combines debug log emission
This is all generally in the theme of trying to make it easier to get attention on the part of this code that matters.
=> Move more logic into swap state

x/concentrated-liquidity/README.md, x/concentrated-liquidity/swaps.go, x/concentrated-liquidity/swapstrategy/one_for_zero.go, x/concentrated-liquidity/swapstrategy/one_for_zero_test.go, x/concentrated-liquidity/swapstrategy/swap_strategy.go, x/concentrated-liquidity/swapstrategy/swap_strategy_test.go, x/concentrated-liquidity/swapstrategy/zero_for_one.go, x/concentrated-liquidity/swapstrategy/zero_for_one_test.go
Closes: #XXX
Documenting the definitions of tick, bucker and range as per latest discussions.
Reviewed the swap code and made the renames that made sense to me per definitions
=> chore/docs: tick, bucket, range definitions and renames

CHANGELOG.md, x/incentives/client/cli/tx.go, x/incentives/keeper/gauge.go, x/incentives/types/constants.go, x/incentives/types/msgs.go, x/incentives/types/msgs_test.go
Closes: #XXX
- fix cli for createGauge 
- add gas cost that scales linearly y with coins to add 
- tested CreateGauge and checked gas consumption
n/a
=> [fix] Fix CreateGauge CLI and add gas cost to create gauge 

.github/workflows/cleanup-cache.yaml
This pull request adds a workflow for cleaning up caches created by a branch when a pull request is closed. The workflow addresses the issue of limited cache usage options due to branch scope restrictions, which can result in caches from the default branch being created and deleted frequently. By automating cache cleanup, this workflow helps manage cache storage and prevent cache thrashing.
For more details please refer to: 
- https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries
- https://github.com/actions/gh-actions-cache
- https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#managing-caches
Where is the …
=> Add cache cleanup workflow

x/concentrated-liquidity/invariant_test.go, x/concentrated-liquidity/range_test.go
Closes: #XXX
This PR extracts independent test related changes from #5541 to reduce clutter/diff.
=> [CL]: Extract invariant and range test changes from bugfix PR

CHANGELOG.md, x/tokenfactory/keeper/createdenom.go, x/tokenfactory/keeper/createdenom_test.go, x/tokenfactory/keeper/genesis_test.go
This pull request fixes the `x/tokenfactory` genesis import reset `x/bank` existing denom metadata, say, `x/bank` genesis has the metadata of **facotory/osmos1.../testtoken** with `{Display: test}`, `x/tokenfactory` init genesis phase will replace it with the empty disply, more details as follows:
Before `x/tokenfactory` init genesis, the `x/bank` set metadata as:
```
{
Name:        "Mint Token",
Symbol:      "MTK",
Description: "The custom token of the test subspace.",
DenomUnits: []*banktypes.DenomUnit{
{Denom: "factory/cosmos1y54exmx84cqtasvjnskf9f63djuuj68p7hqf47/uminttoken", Exponent: uint32(0), Aliases: nil},
{Denom: "minttoken", Exponent: uint32(6), Aliases: []string{"minttoken"}},
},
Base:    "factory/cosmos1y54exmx84cqtasvjnskf9f63djuuj68p7hqf47/uminttoken",
Display: "minttoken", …
```
=> fix: fix `x/tokenfactory` genesis import denoms reset `x/bank` existing denom metadata

.github/workflows/test.yml
Make golang tests only run if theres a state machine affecting change. This should help CI bottlenecks for docs-only PR's
=> Make go tests only run if relevant

x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/position_test.go
Closes: #XXX
Previous PR broke main
=> chore: fix conflict

tests/e2e/e2e_test.go
PacketForwarding tests are intermitently failing. Example: https://github.com/osmosis-labs/osmosis/actions/runs/5316311889/jobs/9625698638?pr=5579#step:9:794 
My first guess is that this is because hermes takes longer to relay the packets than the maximum of one minute. This PR raises it to 2 minutes. 
Will run E2E tests on this PR a few times before merging to see if the error pops up again. We should still keep an eye for it after this is merged. 
=> wait longer for balance checks

x/concentrated-liquidity/tick.go, x/concentrated-liquidity/tick_test.go
Closes: #XXX
Found a bug in the liquidity net in direction query. It was discovered while implementing token in quote estimation (similar to how we do it on frontend) for https://github.com/osmosis-labs/osmosis/pull/5567
The core of the bug is that when swapping zero for one, it would exclude the start tick due to reverse iterator's upper end being exclusive.
Additionally, in the zero for one direction, it would redundantly return the current tick's liquidity net value which is redundant. When swapping one for zero, current liquidity already includes liquidity net of the current tick. Therefore, we should avoid returning it.
This might be related to the fee issues @jonator is experiencing on the front end.
=> fix/test: GetTickLiquidityNetInDirection start tick and tests

x/concentrated-liquidity/swaps.go, x/concentrated-liquidity/swaps_test.go
Progress towards: #5573
Applying the same fix for swap in given out as was done in #5526
The cross tick test suite is to be expanded to cover swap in given out in a future PR
=> fix: zero for one tick crossing bug for swap in given out

CHANGELOG.md, x/tokenfactory/keeper/keeper.go, x/tokenfactory/keeper/keeper_test.go, x/tokenfactory/types/expected_keepers.go
This pull request fixes the account number of `x/tokenfactory` is wrongly set by genesis since `CreateModuleAccount` only stores the module account with default account number 0, and it it also missing an update to `global_account_number` inside `x/auth`. 
To solve it, `CreateModuleAccount` should call `AccountKeeper.GetModuleAccount` instead of `AccountKeeper.SetModuleAccount`, or it lost to set account number properly, see:
https://github.com/cosmos/cosmos-sdk/blob/main/x/auth/keeper/keeper.go#L252
- Added unit test that validates the account number of `x/tokenfactory` module account is correctly set
=> fix: fix the account number of `x/tokenfactory` module account

x/concentrated-liquidity/README.md
Follow-up to #5581
There was some confusion around definitions in  #5581. Leaving a more detailed explanation of every term to alleviate any concerns or misalignment in definitions
=> docs(CL): tick crossing, full range, min and max ticks

.github/workflows/test.yml
This pull request improves the `go tests` GitHub Actions workflow.
Key changes:
1. Refactored the 'get-diff' action to execute only once, reducing redundant operations.
2. Moved the conditional checks for `GIT_DIFF` to the job level
3. Changed cache key as `{{matrix.go_version}}` is not defined
4. Parallelize tests as in https://github.com/cosmos/cosmos-sdk/blob/main/.github/workflows/test.yml
Run the workflow in my fork: https://github.com/niccoloraspa/osmosis/actions/runs/5345580730
Times might be different due to:
- not using cache
- different GitHub plan 
=> [ci] Paralleze go tests github actions

go.mod, go.sum, osmoutils/accum/accum.go, osmoutils/accum/accum_test.go, osmoutils/store_helper.go, x/concentrated-liquidity/incentives.go, x/concentrated-liquidity/incentives_test.go, x/concentrated-liquidity/position_test.go, x/concentrated-liquidity/spread_rewards.go
This PR removes proto deserialization from `accum.HasPosition` calls. This is technically a performance improvement, but its pretty negligible (.5% speedup in our CL tests)
The computation for proto serialization doesn't cost gas, hence this is state compatible.
Whats nice is it removes the error from this code, which has essentially been a dead code branch throughout our codebase. (Every test required NoError for this, and the only way to get an error was to write something of the wrong protobuf type, which we should be guaranteed by key structuring doesn't apply)
This is covered by the existing tests.
=> Remove proto deserialization from HasPosition

osmoutils/ibc.go
After huckleberry, IBC redacts emitted events if the ack is a failure. This means that the user cannot see those. To get around that, we can add the error context to the logs as well.
Eventually we can fix this properly with error-events in the sdk
all tests pass
=> Backport: Emited IBC errors should also be logged

.github/workflows/delete-workflow-runs.yml
In our repository, we have accumulated a significant number of old workflow runs over time. These outdated runs often create confusion and may reference non-existing actions or outdated configurations:
To address this issue and improve the overall clarity of our Actions, this pull request introduces a new workflow that performs weekly deletion of old workflow runs.
This workflow (based on: https://github.com/Mattraks/delete-workflow-runs/) runs at 00:00 UTC every Sunday and allows manual triggering with customizable options:
- Manually tested the workflow in my fork: https://github.com/niccoloraspa/osmosis/actions/runs/5358786103/jobs/9721545804
I would suggest to test this in the repository with the `dry-run` option enable.
=> [ci] Add github action to remove old workflow runs

tests/e2e/initialization/config.go
Closes: #XXX
We need our init image to fund the e2e accounts with enough DAI to create the DAI osmo pool for e2e. We were operating on incorrect assumptions for DAI precision previously. 
This was tested locally with v16 (using this as the init image) and passed the previously failing test.
=> fix: change dai amount e2e

x/concentrated-liquidity/swaps_test.go
Closes: #XXX
This PR reproduces a case where an infinite loop is triggered in swap logic, which can presumably be used to trigger a chain halt by bringing the pool bring to a small enough tick on any pool the chain swaps against in begin/end block. The exact root of this is currently still being investigated but likely has to do with our good old friend tick iterator logic.
N/A
=> [CL]: Reproduce infinite loop in swap logic

app/apptesting/concentrated_liquidity.go, x/concentrated-liquidity/math/math_test.go, x/concentrated-liquidity/math/tick.go, x/concentrated-liquidity/math/tick_test.go, x/concentrated-liquidity/range_test.go, x/concentrated-liquidity/spread_rewards_test.go, x/concentrated-liquidity/swaps_test.go, x/concentrated-liquidity/tick_test.go
This PR bundles a couple of changes to the clmath tests.
- Converts the clmath tests to use `testing.T` instead of suite.
- Reduces compilation time for clmath tests from 700ms to 120ms.
- There were helpers for price to tick conversions happening inside of apptesting, and these were doing the wrong thing
-  This has been moved out of apptesting, into tick_test.go, with new names to reflect this is something that needs to be fixed
- Fixed the invocations inside of keeper-level tests
=> Reduce clmath test compilation time, fix discrepancy in rounding

app/upgrades/v16/upgrades.go, app/upgrades/v16/upgrades_test.go, tests/e2e/configurer/chain/commands.go, tests/e2e/configurer/upgrade.go
Closes: #XXX
The community pool now has the DAI it needs to create the first position, so the logic for swapping is now removed.
Additionally, since we send funds via the community pool, the community pool entry in feePool within the distribution module must also be manually set. This was discovered via state exported testnets.
=> fix: modify v16 upgrade handler

x/incentives/client/cli/tx.go
Closes: #XXX
Fix create gauge CLI param count requirement.
Also, though, I was getting this error:
`Error: pool id should not be set for duration distr condition`
Perhaps the args should be a range of 2-3, then the pool ID value is set to 0 (as that error requires) if it is not set in CLI. Otherwise, omitting the pool ID as that message suggests causes an exception. IMO it would be more intuitive than knowing to set the ID to 0.
- Run make install, then ensure the CLI command works
Example:
`osmosisd tx incentives create-gauge gamm/pool/2 10000000uion 0 --from val --keyring-backend test --chain-id localosmosis --duration 168h  --epochs 12 --fees 100000uosmo`
=> CLI fix: `create-gauge` exact args

x/concentrated-liquidity/math/tick.go, x/concentrated-liquidity/math/tick_test.go
Fixes some testing errors in these tests, as pointed out in #5650
Part of this was moving error catching cases out of test only code, into the actual exported API.
=> Fix testing errors in tick tests

app/apptesting/gamm.go, app/apptesting/test_suite.go, osmoutils/accum/accum_test.go, x/gamm/keeper/migrate_test.go, x/poolmanager/create_pool_test.go, x/poolmanager/keeper_test.go, x/poolmanager/router_test.go, x/superfluid/keeper/concentrated_liquidity_test.go
Some small driveby apptesting changes, nothing in this PR really matters though.
Does mild speedups by:
- reusing decimals for preparing balancer pools
- no longer gets time.Now on every reset
- no longer generate new accounts on every reset call
=> Driveby apptesting changes I made, while looking at other testing things

x/concentrated-liquidity/position.go, x/superfluid/keeper/grpc_query.go
Closes: #XXX
The state entry for lock to position ID is not updated at the exact moment the lock matures. Because of this, when we query a users sf position by checking the lock ID associated with it in store, we need to also check if the respective lock ID still exists. If it doesn't that means it used to exist but no longer does, and we can assume the lock is now mature.
=> fix: cl sf positions per user per pool query

x/superfluid/keeper/grpc_query.go
Closes: #XXX
Our SF per position per pool for CL query was too strict, in that if a lock was associated with a positions, it HAD to be superfluid. There are cases in which locks are associated with positions that are not superfluid staked. For instance, users migrating staked gamm shares that they intend to let mature so they can create non full range positions.
=> fix: pass through non sf locks in query

.github/workflows/check-state-compatibility.yml
This PR does some small chores on the state-compatibility CI:
-  add an `-L` option to follow redirects when requesting the latest snapshot info. We change some things on our backend and we need to add this option.
- We now use the addrbook from our public nodes rather than the one from chainlayer
- Update the `tendermint node ID` for the archive node, with the one from the new node
=> [🪛 CI improvements] chores on state-compatibility CI

x/concentrated-liquidity/keeper_test.go, x/concentrated-liquidity/position_test.go, x/concentrated-liquidity/range_test.go
Closes: #5428
This PR adds the remaining test vectors from #5428. No new issues were encountered while implementing these, but the existing infinite loop bug was hit by two test vectors that are left commented out in this PR.
- Added test cases can be found in `position_test.go`
- A few minor fixes were made to testing logic in `range_test.go`
=> [CL][tests]: Add all remaining intended test vectors from original tracking issue

tests/e2e/e2e_test.go
Closes: #XXX
When setting up the e2e parallel tests, I did not check the `e2e-short` command. The only two issues were:
- E2E short was starting so fast that it didn't give the nodes time to spin up before starting the first test, causing an error
- One of the E2E short tests were changed to use chainB, when chainB does not exist for E2E short tests, so this was changed back to chainA
It also appears that sometimes, the E2E long would also error running the first test without the sleep, so for now I am adding it there and will further diagnose the issue post CL
=> fix: e2e short

.github/workflows/e2e-initialization-instructions.yaml
Closes: #4351 
This pull request introduces a new GitHub action. The action triggers whenever a pull request modifies the 'tests/e2e/initialization' module. It then automatically posts a comment on the PR, guiding the contributor through the necessary steps they need to follow, such as backporting changes and updating Docker images.
This change aims to facilitate and expedite the contribution process, particularly when changes are made to the initialization module. While the current configuration suits our needs, the action's triggers and the message it posts can be customized to adapt. I'm not sure I fully understood the requirements.
This change is a trivial rework / code cleanup without any test coverage. However, the action's effectiveness can be manually verified by creating a test …
=> [🪛 CI improvements] Add e2e init instructions action

x/concentrated-liquidity/fuzz_test.go, x/concentrated-liquidity/keeper_test.go, x/concentrated-liquidity/math/tick.go, x/concentrated-liquidity/math/tick_test.go, x/concentrated-liquidity/position_test.go, x/concentrated-liquidity/swaps.go, x/concentrated-liquidity/tick_test.go, x/concentrated-liquidity/types/errors.go
Closes: #XXX
Parallelized fuzz test suite that supports swapping around ticks
Run parallel randomized fuzz suite
```bash
go test -timeout 30m -run TestFuzz_Many github.com/osmosis-labs/osmosis/v16/x/concentrated-liquidity -v -count=1
```
Run specific seed
```bash
go test -timeout 30m -run TestFuzz_GivenSeed github.com/osmosis-labs/osmosis/v16/x/concentrated-liquidity -v -count=1
```
=> test: parallel fuzz swap test suite

.github/workflows/generate-docs.yml
Closes: #XXX
In https://github.com/osmosis-labs/osmosis/pull/5627 we have added CI run for generating docs, with an attachment of a succesful workflow. (https://github.com/mattverse/osmosis/actions/runs/5374789925 and https://github.com/mattverse/osmosis/pull/15).
However, I have noticed that I have created a PR off of the incorrect version, thus creating this PR with the working version 
that matches https://github.com/mattverse/osmosis/pull/14
Correct code has been used
=> Fix generate docs CI

x/incentives/client/cli/tx.go
Closes: #XXX
issue: unable to create external no-lock gauge because the lockupType is hardcoded to "ByDuration"
https://github.com/osmosis-labs/osmosis/blob/main/x/incentives/client/cli/tx.go#L90
tested on localosmosis
=> [fix] Fix no-lock gauge CLI 

x/concentrated-liquidity/fuzz_test.go
Closes: #XXX
**Main focus:** add swaps in given out to fuzz swap suite
- Try to integrate it as an inverse relationship swap
* `tokenOut` returned from out given in is used as input to in given out
- Noticed some oddity where amountIn given as input to "out given in" and amount in returned from "out given in" do not match in some edge cases
* Conclusion: seems like a test setup error that is acceptable. Explained further in comments
Secondary change:
- fixed using the correct source of randomness to be able to run the suite from a deterministic seed
=> test(CL): add swaps in given out to fuzz suite and fix deterministic randomness

app/keepers/keepers.go, app/modules.go
Closes: #XXX
Any querying for packet foward middle ware right now returns an error of 500. (Confirmed via cli that this is an error resulting from GRPC itself, not GRPC Gateway).  
Confirmed locally that this fix applies correct fix
```
matt@MacBook-Pro build % ./osmosisd q ibc-transfer params 
receive_enabled: true
send_enabled: true
```
Tested in local environment
=> Fix app wiring for packet foward keeper for v15.x

x/concentrated-liquidity/LICENSE.md
Adds a business source license to x/concentrated-liquidity
Notable items:
- Lets Osmosis governance govern permissions for this
- The precise definition of who the Osmosis DAO is a bit under-specified. (E.g. what happens if theres a fork)
- Ideally this gets adapted later on to more cleanly specify Osmosis chain forks have permission for this, e.g. #5597 
- converts the code to GPL after 2 years
- "Standard" BSL is 4 years
=> Add Business Source License from @NickPullman

wasmbinding/stargate_whitelist.go
Removes two queries that weren't intended to be state machine versioned from the stargate whitelist.
=> Remove Pools and LiquidityNetInDirection queries from wasmbinding list

CHANGELOG.md, cmd/osmosisd/cmd/root.go, cmd/osmosisd/cmd/stargate-query.go
Something I have added for QOL, usually when I need this I would fmt.Println manually to see the bytes marshaled. Also, this can be used for further stargate query testing, where right now, we don't have any way to create the data bytes used in the stargate query itself.
I have attempted to create this using pb.go files and reflections, but would need further investigation and digging around, thus punting this for now
```
(base) matt@172 build % ./osmosisd debug proto-marshalled-bytes "/cosmos.bank.v1beta1.Query/Balance" bank QueryBalanceRequest "osmo1t7egva48prqmzl59x5ngv4zx0dtrwewc9m7z44" stake
bank
QueryBalanceRequest
[10 43 111 115 109 111 49 116 55 101 103 118 97 52 56 112 114 113 109 122 108 53 57 120 53 110 103 118 52 122 120 48 100 116 114 119 101 119 99 57 109 55 122 52 52 18 5 …
```
=> Add debug command for conversion to proto marshalled bytes

x/concentrated-liquidity/pool.go
Closes: #XXX
Must use correct equality check for the error when running the unbonding query
=> fix: unbonding query error check

Makefile, go.mod, go.sum, osmoutils/slice_helper.go, osmoutils/slice_helper_test.go, tests/cl-go-client/main.go
Closes: #XXX
Adds both spread reward and incentive claiming to the cl script. For both rewards:
- Selects a single random account
- Retrieves all of that address's position IDs
- Selects a random subset of those position IDs
- Claims for all those position IDs
=> feat: add reward/incentive claiming to cl script

go.mod, go.sum, osmoutils/osmocli/parsers.go, x/concentrated-liquidity/client/cli/query.go
Closes: #XXX
Adds liquidity net in direction, pool accumulator rewards, and tick accumulator queries to CLI.
Also, adds boolean parsing to osmocli.
=> chore: add missing cli queries CL

x/concentrated-liquidity/client/query_proto_wrap.go, x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/incentives.go, x/concentrated-liquidity/incentives_test.go, x/concentrated-liquidity/position.go, x/concentrated-liquidity/position_test.go, x/concentrated-liquidity/tick.go, x/concentrated-liquidity/types/errors.go
Closes: #XXX
Pool incentives query was not updating uptime accumulators to now while the tick query was. This resulted in the global accum being smaller than the tick accum, which should not be possible.
This would not take place in state, but the query being this way lead to unnecessary debugging.
=> fix: update pool uptime accum to now in query

x/concentrated-liquidity/README.md
This PR fixes a typo in the concentrated liquidity README, there was first a capital Y which should be a capital y
This change is a trivial rework without any test coverage.
no
no
=> fix cl readme typo

networks/osmosis-1/upgrades/v16/mainnet/guide.md, networks/osmosis-1/upgrades/v16/v16_binaries.json
Closes: #XXX
Updating cosmovisor with new binaries
=> chore: cosmovisor hashes and v16.1.0 tag updates

scripts/get_validators_csv.py
A perennial problem we've ran into is just getting a CSV of all validators and making it into a google sheets
This PR at least automates the creation of the CSV based on live stake distribution.
=> add validator csv creator script

Makefile
Closes: #XXX
With so many submodules in our directory, updating sdk dependency as of right now causes alot of manual edits + go mod tidy runs in each directory. 
(./go.mod ./osmoutils/go.mod ./osmomath/go.mod ./x/epochs/go.mod ./x/ibc-hooks/go.mod ./tests/cl-genesis-positions/go.mod ./tests/cl-go-client/go.mod) are all the dependency change one would have to make to resolve the conflicts. 
This PR Adds a new command in the Makefile `make update-version` which runs through all the go.mods (in root directory + sub module) and runs go mod tidy as well. 
QOL improvement.
Tested locally and checked running this command changes all necessary parts of go.mod in our directory + changes according go.sum properly as well
=> Add Make Command to Update SDK Dependency 

CHANGELOG.md, x/lockup/keeper/synthetic_lock.go
Fixes the superfluid_delegations query
TODO: Writeup issue in github, and do a more thorough fix after
https://github.com/osmosis-labs/osmosis/commit/b2aaef405395c8837c326cd022173d661d6fba9d#diff-12e60a1d3fca14ffd11e0438d0639722c4db098b813e02506eff07505c9ff0cbR60
=> Fix the superfluid query

x/lockup/keeper/grpc_query.go, x/lockup/keeper/lock.go, x/lockup/keeper/lock_test.go, x/lockup/keeper/msg_server.go, x/lockup/keeper/synthetic_lock.go, x/lockup/keeper/synthetic_lock_test.go, x/superfluid/keeper/grpc_query.go, x/superfluid/keeper/migrate.go, x/superfluid/keeper/stake.go, x/superfluid/types/expected_keepers.go, x/valset-pref/types/expected_interfaces.go, x/valset-pref/validator_set.go
Followup to #5831 , make the API more clearly indicate the problem of this needs to return found.
I do think later on we may just want to make !found => error, but that would be state breaking.
So for now making the API add `found`, and marking TODO's for us to clean up in a follow-up state breaking update.
Please verify that all queries adjusted are not in the stargate whitelist.
=> Make GetSuperfluidLockByLockId more cleary indicate if its found or not

networks/osmosis-1/upgrades/v16/mainnet/guide.md, x/superfluid/README.md
Closes: #5843
- Fixed the broken links found by either updating them to valid sites, or removing references. 
- I removed the `State` links as per [this comment](https://github.com/osmosis-labs/osmosis/pull/5728#issuecomment-1617447863)
Should we ignore the `CHANGELOG.md` file from being checked? 
It has "broken links", but I'm not sure if makes sense to try to update them. They are already in the public-facing changelogs so this wouldn't really help with anything.
If we ignore it, it should be as simple as adding `--exclude-path 'CHANGELOG.md'` to the lychee-action. I tested this locally and it ignored the CHANGELOG correctly. Not sure if we should be doing `./**/CHANGELOG.md` for CI runs though. But i believe it should work as-is since it would be in the root folder, and `./CHANGELOG.md …
=> Docs: Fix Broken Links (Jul 15, 2023)

go.mod, go.sum, osmoutils/accum/accum.go, osmoutils/accum/accum_helpers.go, osmoutils/accum/accum_test.go, osmoutils/accum/export_test.go, x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/genesis.go, x/concentrated-liquidity/genesis_test.go, x/concentrated-liquidity/incentives.go, x/concentrated-liquidity/incentives_test.go, x/concentrated-liquidity/spread_rewards.go, x/concentrated-liquidity/spread_rewards_test.go, x/concentrated-liquidity/swaps.go, x/concentrated-liquidity/tick.go, x/concentrated-liquidity/tick_test.go
Component of #5845 
State compatible component of removing some unneeded store re-gets!
After this, we should be able to then remove some unneeded re-gets for accumulators :)
No new tests, safety of this should be covered by existing tests + resyncing on mainnet.
=> Make accumulator objects more consistently pointers throughout

x/concentrated-liquidity/position_test.go
Closes: https://github.com/osmosis-labs/osmosis/issues/5854
This test is a final sanity check to  ensure that negative interval accumulation (that is `DecCoins`) do not panic when serialized or deserialized
Added test
=> test: validate negative interval accumulation does not panic when serialized

.goreleaser.yaml
This PR introduces the `.goreleaser.yaml` configuration file and sets up the release process for the project osmosisd. 
Goreleaser is a popular tool used in the Go ecosystem to automate the build and release workflow for Go projects. It simplifies the process of building binaries, creating archives, generating checksums, and publishing releases across multiple platforms and architectures.
The `goreleaser.yaml` file included in this PR defines the configuration for the release process of `osmosisd`. 
Let's summarize the key elements of the configuration:
1. **Project Information:**
- `project_name`: Specifies the name of the project as `osmosisd`.
2. **Environment Variables:**
- Specifies the needed environment variables
3. **Builds:**
The configuration defines four build targets, each …
=> Improve our release process with goreleaser

CHANGELOG.md, x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/lp.go, x/concentrated-liquidity/msg_server.go, x/concentrated-liquidity/position.go
- This PR exports the `createPosition` method in the Concentrated Liquidity module so other modules (in particular ProtoRev) have access to the method in its testing suite.
- N/A
- Added changelog entry
=> Export createPosition method in CL module

x/gamm/client/cli/tx.go
This pull request corrects the sample json returned by the create-pool cli command for stableswap pool creation. Exit-fee field value is 0.01 while Stableswap pool type cannot be created with a non-zero exit fee.
This change is already covered by existing tests. This PR doesn't change any logical part.
=> Correct sample json exit-fee field value for stableswap pool creation on CLI command description

tests/e2e/initialization/config.go, tests/e2e/initialization/v17.go
Closes: #XXX
We are creating canonical CL pools for a list of gamm pools in the v17 upgrade handler. In order to test if these pools properly get created / linked / SFS, we must modify the v16 init image to create the pools (similar to how we have done it in the past for the stride pool and the v16 CL pool)
Tested against the following PR 
https://github.com/osmosis-labs/osmosis/pull/5895
=> chore: v16 e2e init image updates

chain.schema.json
Tracked in: https://github.com/osmosis-labs/osmosis/issues/5904
This PR updates the chain-registry by:
- Adding information about the latest release 
- Adding binaries to all previous versions
One important caveat. I have added references to our fork in the module versions:
```json
"cosmos_sdk_version": "osmosis-labs/cosmos-sdk@0.45.0-rc1.0.20230703010110-ed4eb883f2a6",
"consensus": {
"type": "tendermint",
"version": "informalsystems/tendermint@0.34.24"
},
"cosmwasm_version": "osmosis-labs/wasmd@0.31.0-osmo-v16"
```
This seemed more correct to me but we can change this.
Trivial changes
=> Update chain-registry to v16.1.1 and add binaries to all previous releases

networks/osmosis-1/README.md, scripts/release/create_all_binaries_json.sh, scripts/release/create_binaries_json.py, scripts/release/requirements.txt
Tracked in: [#5904](https://github.com/osmosis-labs/osmosis/issues/5904)
This pull request introduces post-release automation to the project by adding a new script, `create_binaries_json.py`. The script is designed to generate cosmovisor binaries JSON files based on either a tag or a checksum. 
I have added extended documentation to the `scripts/release/create_binaries_json.py` script.
The changes included in this PR are as follows:
- `scripts/release/create_binaries_json.py`: script performs the actual generation of cosmovisor binaries JSON files. 
- `scripts/release/requirements.txt`: dependencies required for the `create_binaries_json.py` script.
- `scripts/release/create_all_binaries_json.sh`: script facilitates the creation of cosmovisor binaries JSON files for all the latest minor …
=> Add script to generate cosmovisor binaries json and list osmosis upgrades

cmd/osmosisd/cmd/root.go
Closes: #XXX
https://github.com/osmosis-labs/osmosis/assets/40078083/071ccd6c-2df2-4ac9-8207-57cd7738e77c
No more typing every. single. cli. cmd.
For bash:
```
echo '. <(osmosisd enable-cli-autocomplete bash)' >> ~/.profile
source ~/.profile
```
For zsh:
```
echo '. <(osmosisd enable-cli-autocomplete zsh)' >> ~/.zshrc
source ~/.zshrc
```
Tested locally for zsh, would be nice if someone could test for bash.
=> chore: auto complete cli

.github/workflows/release.yml, .gitignore, .goreleaser.yaml, Makefile
Tracked in: https://github.com/osmosis-labs/osmosis/issues/5904 
This PR focuses on improving the release process through Goreleaser.
Main changes:
1. Updated .goreleaser.yml to match the previous release structure.
2. Added release targets to the Makefile:
- `release`: This target performs a release using Goreleaser. It expects the `GITHUB_TOKEN` as an environment variable. It should never be run manually but always via the GitHub Action.
- `release-dry-run`: This target simulates a release without publishing the artifacts. It allows testing the release process without actually creating a new release.
- `release-snapshot`: This target creates a snapshot release without validation or publishing. It can be useful for quickly generating snapshots for testing purposes.
3. Added a release …
=>  Add goreleaser commands to Makefile and create a Github Action to run goreleaser

CHANGELOG.md, x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/fuzz_test.go, x/concentrated-liquidity/incentives.go, x/concentrated-liquidity/incentives_test.go, x/concentrated-liquidity/spread_rewards.go, x/concentrated-liquidity/spread_rewards_test.go, x/concentrated-liquidity/tick.go
This PR is simplifying the `GetTickInfo` code, by moving the initialization logic to its own function. Furthermore, we only get the pool once, removing repeated gets in every function this would otherwise call. (Saving a net of 2 GetPool operations). This has an added benefit of removing messiness from the test code, where it attempted to generate test cases with invalid pool ID's.
The remainder of this PR is cleaning up tests.
The "TestGetInitialSpreadRewardGrowthOppositeDirectionOfLastTraversalForTick" was extremely messy, so just re-wrote the edge case that idt even makes sense to test into its own function, and made the main test use standard helpers.
=> CL: Initialize tick minor gas optimization & cleanup

cmd/osmosisd/cmd/config.go, cmd/osmosisd/cmd/init.go, cmd/osmosisd/cmd/osmo-test-5-assetlist.json, cmd/osmosisd/cmd/osmosis-1-assetlist.json, cmd/osmosisd/cmd/root.go
Closes: #XXX
This PR introduces two separate but similar features:
1. When using the CLI, you can now input base denoms (uosmo, ucro, uwbtc, etc) and it will get replaced with the corresponding ibc denom
2. When CLI outputs are displayed in the console, ibc denoms can now be replaced with corresponding ibc denom
In the client.toml, the user can enable input and/or output human readable denoms.
The CLI does this by first attempting to retrieve the most up to date asset list for the corresponding network (osmosis-1 or osmo-test-5). If github is down, it falls back to a recent asset list json I added to the cmd folder (the bulk of the file diff)
A drive by change I made that is somewhat related to this PR is we weren't actually writing our custom client.toml file to the config folder! This …
=> feat: input/output human readable denoms in CLI

osmoutils/sumtree/tree_test.go
Closes: #XXX
Our tree test has been having some random failures that go away with a re-run. The most latest example is https://github.com/osmosis-labs/osmosis/actions/runs/5719776897/job/15498413011?pr=5895
This has been hard to debug since we don't use a seed value to run this test so the random values used are unknown. This PR adds a seed value that gets printed, so the next time the test fails, we can utilize this seed to be able to further debug.
N/A
=> fix: add seed to failing tree test

tests/simulator/state.go
Closes: #XXX
Another random sim error we have been getting has been due to us allowing the simulator to start with zero validators. This fixes that.
Sim seed I noticed this on (3112372204317306856) now passes.
=> fix: prevent sim from starting with zero validators

.github/workflows/test.yml
Closes: #XXX
This PR introduces concurrency control in our GitHub Actions to reduce CI time.
By grouping workflows via the `group` key and setting `cancel-in-progress` to true, we prevent redundancy in runs triggered by multiple commits to the same branch.
Docs on concurrency: https://docs.github.com/en/actions/using-jobs/using-concurrency
Explanation on the chosen group key `${{ github.workflow }}-${{ github.head_ref || github.run_id }}`:
- ${{ github.workflow }} avoid collision between future workflows in https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
- ${{ github.head_ref || github.run_id }} cancels in-progress jobs or runs on pull_request events only as in …
=> [CI] Add concurrency options to test workflow

.github/workflows/build.yml, .github/workflows/check-generated.yml, .github/workflows/check-state-compatibility.yml, .github/workflows/contracts.yml, .github/workflows/push-dev-docker-images.yml
This PR extends the changes made in https://github.com/osmosis-labs/osmosis/pull/5955 
to all others GitHub actions that are triggered by pushed to a development branch.
=> [ci] Add concurrency options to GitHub Actions

CHANGELOG.md, app/keepers/keepers.go, x/protorev/keeper/epoch_hook_test.go, x/protorev/keeper/hooks_test.go, x/protorev/keeper/keeper.go, x/protorev/keeper/keeper_test.go, x/protorev/keeper/posthandler_test.go, x/protorev/keeper/rebalance.go, x/protorev/keeper/rebalance_test.go, x/protorev/keeper/routes_test.go, x/protorev/protorev.md, x/protorev/types/constants.go, x/protorev/types/expected_keepers.go
This PR introduces a fix to `protorev` to update the binary search range in the case where it is too gas intensive to search over the hard-coded range. This is particularly useful for Concentrated Liquidity pools where moving across several ticks is very expensive. By determining if a route has an CL pools in it, we can bound the upper input amount by figuring out the maximum input amount respecting a maximum number of ticks. We do so across all CL pools and use this as our maximum input amount on the entire route.
Note, `MaxTicksMoved` is currently hard coded, but we plan to update that in a follow up PR. This will be configurable by the `DeveloperAccount`.
- *Added unit tests for `TestFindMaxProfitRoute` that test liquid and …
=> fix(ProtoRev): Updating Binary Search Range with CL Pools

CHANGELOG.md, tests/e2e/configurer/base.go, tests/e2e/configurer/chain/node.go, tests/e2e/containers/containers.go
Closes: #XXX
An example of the concurrent map write error https://github.com/osmosis-labs/osmosis/actions/runs/5754011094/job/15607044536
Adds a mutex to prevent this from happening
There are random times (rare, maybe 1 in 100, both locally and in CI) when a docker container just wont start. While this isn't the best fix, this deletes the faulty container and attempt to recreate it instead of just failing on the spot.
An example of this happening https://github.com/osmosis-labs/osmosis/actions/runs/5719951506/job/15498941705
=> fix[e2e]: e2e failure fixes

cmd/osmosisd/cmd/config.go, cmd/osmosisd/cmd/root.go
Closes: #XXX
This update parses inputs and flags for regular denoms as well as mutates the coin value to its base exponent
Example:
* `10.45atom` input will automatically change to `10450000ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2`
* `uakt` will change to `ibc/1480B8FD20AD5FCAE81EA87584D269547DD4D436843C1D20F15E00EB64743EF4`
* `12000000uscrt` will change to `12000000ibc/0954E1C28EB7AF5B72D24F3BC2B47BBB2FDF91BDDFD57B74B99E133AED40972A`
Tested locally, but more testing would be appreciated to see if there are any further edge cases. Remember, the following values in the client.toml must be changed to "true" to get this feature:
```
human-readable-denoms-input = true
human-readable-denoms-output = true
```
=> feat[CLI]: transform normal denom to base denom and modify value

CHANGELOG.md, tests/e2e/initialization/config.go
Closes: #XXX
Epoch is currently set to 1 minute. There are two tests that wait for an epoch to pass before continuing in the e2e test suite. This means we could potentially have to wait up to a minute to continue the test. There is no need for this, so we should just speed up the epoch duration more.
Built locally, and tested against the currently open e2e PR against main
=> chore[e2e]: faster epoch

.github/workflows/check-generated.yml
In our check-generated CI job, make it not run if not needed.
(It just runs make proto-gen && make run-querygen)
Also only setuip go after we pass git diff.
=> Add a file ignore for check generated running

tests/simulator/state.go
Closes: #XXX
We were not using the seeded random value when determining number of validators. This makes each run have a different number of validators, sometimes failing the non determinism check. See:
https://github.com/osmosis-labs/osmosis/actions/runs/5798085879/job/15715067009
https://github.com/osmosis-labs/osmosis/actions/runs/5799915139/job/15720939362?pr=5949
Run a single seed, see that it no longer has differing values for the number of validators for the run
=> fix: sim val number being non deterministic

CHANGELOG.md, cmd/osmosisd/cmd/change_environment.go, cmd/osmosisd/cmd/root.go, tests/e2e/e2e_test.go
Closes: #XXX
https://github.com/osmosis-labs/osmosis/assets/40078083/265cf085-7861-4bd9-a1dc-246cfc33e55e
Getting started with osmosis is not very user friendly. The set-env command was a step in the right direction, but it still doesn't feel useable out of the box.
With this PR, a user can go from having no .osmosisd folder to querying the chain with a single command. 
Additionally, it fills out the chain-id in the client.toml, so the only flag a user should have to pass in is gas flags (you could 100 percent add this as well, but I wasn't quite sure what default gas values should be used).
Edit: last minute addition, allows you to add a chain ID to the set-env for localnet. If no chainID for localnet is provided, it default to localosmosis chain ID.
Tested against mainnet, testnet, and …
=> feat: improve set-env CLI cmd

CHANGELOG.md, app/apptesting/concentrated_liquidity.go, app/upgrades/v16/upgrades.go, app/upgrades/v17/upgrades.go, x/concentrated-liquidity/lp_test.go, x/concentrated-liquidity/pool_test.go, x/concentrated-liquidity/position.go, x/concentrated-liquidity/position_test.go, x/concentrated-liquidity/swaps_tick_cross_test.go, x/concentrated-liquidity/types/cl.go, x/gamm/keeper/migrate.go, x/gamm/keeper/migrate_test.go, x/gamm/types/expected_keepers.go, x/lockup/keeper/lock_test.go, x/superfluid/keeper/concentrated_liquidity.go, x/superfluid/keeper/concentrated_liquidity_test.go, x/superfluid/keeper/export_test.go, x/superfluid/keeper/grpc_query_test.go, x/superfluid/keeper/migrate.go, x/superfluid/keeper/migrate_test.go, x/superfluid/keeper/msg_server.go, x/superfluid/keeper/msg_server_test.go, x/superfluid/types/expected_keepers.go
Progress towards: #5984
Refactoring full range position creation to return 1 struct instead of 4 values.
=> refactor: reduce number of returns for creating full range position

x/tokenfactory/client/cli/tx.go
Simply to add the `mint-to-address` and `burn-from-address` into the examples of the CLI for mint and burn tokenfactory messages.
=> fixed mint and burn message examples to include the to and from addresses

app/upgrades/v17/constants.go
Closes: #XXX
We were previously checking if errors.Is gammtypes.ErrInvalidMathApprox, but we needed to be more specific with the error type.
Passed the state exported testnet done in osmosis-ci repo
=> fix: specify error in upgrade handler

CHANGELOG.md, x/gamm/keeper/migrate.go, x/gamm/keeper/migrate_test.go, x/superfluid/keeper/export_test.go, x/superfluid/keeper/migrate.go, x/superfluid/keeper/migrate_test.go, x/superfluid/keeper/msg_server.go, x/superfluid/types/expected_keepers.go, x/superfluid/types/migration.go
Progress towards: https://github.com/osmosis-labs/osmosis/issues/5984
Reduces the number of returns in superfluid migration to eventually enable a linter, restricting it from happening.
=> refactor: reduce the number of returns in superfluid migration

CHANGELOG.md, Makefile
Closes: #XXX
This PR adds a `install-with-autocomplete` Makefile command, which adds the autocomplete to your profile. If using bash, a separate package must be installed in order to get it to work, which this does as well. 
I considered just adding this to the `install` command, but I don't think we should be adding things to people's profiles as the default method. Although I do think the majority of people will want to use this method in place of the usual install.
This has been tested on:
1. Mac using zsh
2. Mac using bash
3. Linux using bash
And all have worked!
=> chore: add CLI autocomplete to makefile

.golangci.yml, CHANGELOG.md, app/upgrades/v15/export_test.go, app/upgrades/v15/upgrade_test.go, app/upgrades/v15/upgrades.go, simulation/executor/mock_tendermint.go, simulation/executor/util.go, simulation/simtypes/txbuilder.go, tests/e2e/configurer/upgrade.go, tests/e2e/initialization/chain.go, tests/e2e/initialization/init.go, x/concentrated-liquidity/client/cli/tx.go, x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/incentives.go, x/concentrated-liquidity/pool.go, x/concentrated-liquidity/simulation/sim_msgs.go, x/downtime-detector/client/cli/query.go, x/gamm/simulation/sim_msgs.go, x/incentives/client/cli/tx.go, x/poolmanager/create_pool.go, x/poolmanager/export_test.go, x/protorev/client/cli/query.go, x/protorev/keeper/rebalance.go, x/superfluid/keeper/export_test.go, x/superfluid/keeper/migrate.go, x/superfluid/keeper/stake.go, x/tokenfactory/keeper/createdenom.go
Closes: #6016 
Enable unused parameters (`unparam`) linter in golangci and fix warnings
NA
NA
=> golangci: enable unused parameters linter

Makefile, cmd/osmosisd/cmd/root.go
Closes: #XXX
Forcing the Makefile to use bash instead of sh broke a CI step. This changes it back to how it was, and modifies the autocomplete step to be compatible with sh.
Tested on mac with zsh and bash, and on linux with bash
=> fix: don't force makefile to use bash

CHANGELOG.md, simulation/executor/legacyconfig.go, x/concentrated-liquidity/bench_test.go, x/concentrated-liquidity/lp.go, x/concentrated-liquidity/lp_test.go, x/concentrated-liquidity/math/tick.go, x/concentrated-liquidity/math/tick_test.go, x/concentrated-liquidity/model/pool.go, x/concentrated-liquidity/position.go, x/concentrated-liquidity/types/cl.go, x/superfluid/keeper/slash.go, x/superfluid/types/expected_keepers.go
Progress towards: https://github.com/osmosis-labs/osmosis/issues/5984
This PR continue removing too many returns to later enable a revive linter.
This PR:
- Combines several returns into one struct for `UpdatePosition`
- Removes redundant price returns from `TicksToSqrtPrice` function
=> refactor: reduce the number of returns in tick conversions and update position

app/ante.go, x/authenticator/ante/authenticator.go
Closes: #6077 
This pull request is the first step towards abstracting the signature verification for acoounts 
There are no tests as we expect this functionality to change drastically in soon
- generate a transaction e.g bank send e.g
```sh
user1=$(osmosisd keys show user1 -a --keyring-backend=test --home=$HOME/.osmosisd)
val=$(osmosisd keys show validator -a --keyring-backend=test --home=$HOME/.osmosisd)
osmosisd tx bank send $val $user1 1000valtoken --from validator --chain-id testing --keyring-backend test --fees 1000stake -b block -y --generate-only > bank-send.json
```
- replace the auth info and signatures info with this:
auth info
```
"auth_info": {
"signer_infos": [
{
"public_key": {
"@type": "/cosmos.crypto.secp256k1.PubKey",
"key": "ApNE+TkLxJVav083Ol4g3Q+kGFVOrUQj2ekZr2l9UYa6" …
```
=> feat(ante): removing sigverify ante in favor of authenticator ante

Makefile, app/app.go, app/upgrades/v17b/constants.go, app/upgrades/v17b/upgrades.go, tests/e2e/e2e_test.go
Closes: #XXX
v17b is branched off v17x current state, but with a no-op upgrade handler under the tag v17b.
If e2e passes, this shows that v17b upgrade handler executed successfully. 
=> fix: add no-op upgrade handler

networks/osmosis-1/upgrades/v17/v17_binaries.json
Closes: #XXX
Updates sha256 for v17 binaries.json to the correct ones
*(or)*
*(or)*
*(example:)*
=> Update sha256 for v17 binaries.json

x/authenticator/ante/authenticator.go, x/authenticator/types/authenticators.go
Closes: #6080
This abstracts the signature verification into a struct that can be used to verify auth, this is the first authenticator and will be built upon to allow account abstraction
There are no tests as we expect this functionality to change soon.
- start a node with `user1` and `user2` in the genesis
- generate a transaction e.g bank send e.g
```sh
user1=$(osmosisd keys show user1 -a --keyring-backend=test --home=$HOME/.osmosisd)
val=$(osmosisd keys show validator -a --keyring-backend=test --home=$HOME/.osmosisd)
osmosisd tx bank send $val $user1 1000valtoken --from validator --chain-id testing --keyring-backend test --fees 1000stake -b block -y --generate-only > bank-send.json
```
- replace the auth info and signatures info with this:
auth info
```
"auth_info": {
"signer_infos": [ …
```
=> feat(secp256k1 auth): implementing secpk256k1 authenticator

x/concentrated-liquidity/math/tick.go
We were computing a constant, that we already were pre-computing. Just use pre-computed constants.
All tests passing shows this is state compatible.
This is pretty minor.
=> Minor speedup to TickToPrice (and related functions)

CHANGELOG.md, app/upgrades/v18/constants.go, app/upgrades/v18/upgrades.go, app/upgrades/v18/upgrades_test.go, x/concentrated-liquidity/incentives.go, x/incentives/keeper/distribute.go, x/incentives/keeper/hooks.go, x/lockup/keeper/lock.go, x/superfluid/keeper/stake.go
Closes: #XXX
Needs to be cherry-picked onto `main`
*(or)*
*(or)*
*(example:)*
=> candidate fix for v18

CHANGELOG.md, x/incentives/keeper/distribute.go, x/superfluid/keeper/stake.go
State compatible epoch speedup from v18 to main. This should be backported to other feature releases
=> State compatible epoch speedup from v18

x/incentives/keeper/distribute.go
Skip the linear time lockSum compute for spam gauges.
I checked it was state compatible on v16.x. It speeds up another ~45 seconds off the compute time on my test machine. (compute time = 2.5 minutes, commit time = 2.5 minutes)
(This is a nice speedup on test machine. For nodes with more state, commit time increases a lot, unrelated to this PR. So this may be super low impact for them)
=> Further epoch speedup, by making spam gauges not increase linear-time compute

CHANGELOG.md, x/concentrated-liquidity/incentives.go
Closes: #XXX
Backport from v18.x
Covered by existing tests and taken directly from the `v18.x` branch.
=> refactor: allow zero qualifying balancer shares in CL incentives

x/superfluid/abci.go, x/superfluid/keeper/epoch.go
Catch panics if they occur during superfluid distributions, so we would not risk a chain halt.
=> panic catch superfluid errors

CHANGELOG.md, app/upgrades/v19/constants.go, app/upgrades/v19/upgrades.go, x/lockup/keeper/lock.go
Repairs the superfluid synth denom stores. We set them here: https://github.com/osmosis-labs/osmosis/blob/dev/fix_v19/x/lockup/keeper/synthetic_lock.go#L161
=> v19 superfluid fix

x/lockup/keeper/synthetic_lock.go
Fix a TODO inside of synthetic lock. Check out this PR when we introduced this new API: https://github.com/osmosis-labs/osmosis/pull/5833
=> handle a TODO in synth lock

CHANGELOG.md, proto/osmosis/tokenfactory/v1beta1/tx.proto, x/tokenfactory/keeper/msg_server.go, x/tokenfactory/types/tx.pb.go
Closes: https://github.com/osmosis-labs/osmosis/issues/6147
Previously token factory events were emitting wrong attribute for mintTo and burnFrom, this PR fixes it 
=> Fix tokenfactory events

CHANGELOG.md, osmomath/sqrt.go, osmomath/sqrt_big_test.go, osmomath/sqrt_test.go
Closes: #6045
To raise the minimum spot price in CL, we need to implement a MonotonicSqrt function on osmomath.BigDec to support higher precision.
See design document: https://app.clickup.com/37420681/v/dc/13nzm9-22453/13nzm9-45853
Copied tests from regular MonotonicSqrt.
```
goos: linux
goarch: amd64
pkg: github.com/osmosis-labs/osmosis/osmomath
cpu: 12th Gen Intel(R) Core(TM) i7-1260P
│  reg.bench   │     big.bench      │
│    sec/op    │   sec/op     vs base   │
MonotonicSqrt-16          386.8µ ± 19%
MonotonicSqrt_BigDec-16                  470.0µ ± 2%
geomean                   386.8µ         470.0µ       ? ¹ ²
¹ benchmark set differs from baseline; geomeans may not be comparable
² ratios must be >0 to compute geomean
```
=> feat: monotonic sqrt big dec

x/lockup/keeper/lock.go
Correctly account for the separator in the v19 logic
=> Correctly account for the separator

.github/workflows/test.yml
Maybe im misunderstanding, but I don't think this does anything. Its installing golang outside of docker. (And costs 3 minutes!)
=> e2e remove setup go step

CHANGELOG.md, x/incentives/keeper/distribute.go, x/incentives/types/keys.go, x/superfluid/keeper/epoch.go, x/superfluid/keeper/epoch_test.go
Closes: #6229
Fixing edge case panic when no full range liquidity while updating osmo multiplier in SF after epoch end.
See this for context: https://github.com/osmosis-labs/osmosis/issues/6229
Localosmosis
=> Fix panic edge case in superfluid AfterEpochEnd hook by surrounding CL multipler update with ApplyFuncIfNoError

x/cosmwasmpool/genesis.go, x/cosmwasmpool/genesis_test.go, x/pool-incentives/keeper/genesis.go
This removes the code for an export bug found by exporting cosmwasm pools, this will not be an issue on mainnet as there are no cosmwasm pools, another fix will need to be applied to fix the export and gauges for cosmwasm pools.
See: https://github.com/osmosis-labs/osmosis/issues/6230
This change is a trivial rework / code cleanup without any test coverage. Tests we're ommited to enable state export
=> fix: error genesis export for cosmwasm pool for incorrect interface

.github/workflows/lint.yml, .golangci.yml, app/upgrades/v17/upgrades.go, tests/e2e/configurer/chain/queries.go, tests/e2e/e2e_test.go, x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/math/precompute.go, x/concentrated-liquidity/simulation/sim_msgs.go, x/concentrated-liquidity/swaps.go, x/concentrated-liquidity/swaps_test.go, x/gamm/simulation/sim_msgs.go, x/incentives/keeper/distribute.go, x/superfluid/keeper/epoch.go, x/twap/client/cli/query.go, x/twap/export_test.go, x/twap/store.go
Closes: #https://github.com/osmosis-labs/osmosis/issues/6111, https://github.com/osmosis-labs/osmosis/issues/5984
One of the previous PRs broke linter in CI. As a result, we have a lot of local failures. This PR fixes all of them
Additionally, it adds a new arg check linter via `revive`
Lastly, it also removes a `depguard` linter. This linter configures an allow and a deny list of imports. Currently, we don't have that configured and there are numerous failures. Personally, I don't see it as something useful. If someone wants it, please configure it in a separate PR.
No changelog label is set as no exported API is broken.
=> chore(lint): fix all linter issues; add return check; re-enable in CI

.github/workflows/test.yml
This reverts commit 1e156281a883c8e96711ca01a800a66978ea3795.
Closes: #XXX
Self-hosted runners are causing e2e failures. Reverting
=> Revert "change-back-to-self-hosted (#6221)"

app/keepers/keepers.go, app/keepers/modules.go, app/modules.go, x/authenticator/keeper/keeper_test.go, x/authenticator/types/keys.go
Closes: #6126
Wiring authenticator module into node
Run:
- `make install`
- `osmosisd tx authenticator`
Expected output
```bash
authenticator transactions subcommands
Usage:
osmosisd tx authenticator [flags]
Flags:
-h, --help   help for authenticator
Global Flags:
--chain-id string     The network chain ID
--home string         directory for config and data (default "/home/ghost/.osmosisd")
--log_format string   The logging format (json|plain) (default "plain")
--log_level string    The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
--trace               print out full stack trace on errors
```
=> [Account Abstraction ] Feat/authenticator module wire

x/concentrated-liquidity/math/tick.go, x/concentrated-liquidity/math/tick_test.go
Closes: #XXX
In https://github.com/osmosis-labs/osmosis/issues/6246, it was proposed to keep the V1 function for the purposes of displaying 1:1 conversions with the new version via Go test.
Here, we will remove the Go test and the old version
=> refactor(CL): remove CalculatePriceToTickDecV1 function

x/tokenfactory/keeper/before_send.go
Integrating token factory in different apps I have seen that the error handling for **callBeforeSendListener** is a little bit difficult to debug because any error it throws is overwritten by "gas meter hit maximum limit", I suggest to wrap the original error inside the ErrTrackBeforeSendOutOfGas.
=> feat: token factory defer explict error handling

.github/workflows/test.yml
This reverts commit 16163e7640efa8e5e5552117cb8505f9f3dfe64c.
Closes: #XXX
Re-enable self hosted to speed up e2e CI. Thanks @niccoloraspa for fixing.
=> Revert "Revert "change-back-to-self-hosted (#6221)" (#6242)"

.github/workflows/check-broken-links.yml
Closes: #6274
Previously, we added logic to automatically close older "broken link" issues when a new run happened, that is because the new run would contain any-and-all broken links and therefore the previously created issue should be closed.
After more investigation, I see that the `days-before(-issue)-close` description states:
> The idle number of days before closing the stale issues or the stale pull requests (due to the stale label).
So, while it was `0`, we did set `days-before(-issue)-stale: -1`, meaning the issue would never be marked as `Stale`. My **hypothesis** is that since is wasn't marked as stale, the closing didn't take effect. So by updating the action to mark the issue as `Stale` same-day, and closing same-day it will do what we expect.
The [action's …
=> Fix broken link issue closure step not closing older issues

tests/e2e/e2e_test.go
Closes: #https://github.com/osmosis-labs/osmosis/issues/6259
See investigation analysis in: https://github.com/osmosis-labs/osmosis/issues/6259
Summary of the problem:
The taker fee e2e tests asynchronously set taker fee for both chains A and B.
Due to asynchrony, twap tests sometimes ran before and other times after taker fee being set.
However, geometric twap depends on specific swap amounts to function without jitter.
To work around the issue, taker fee is now set deterministically on chain B while chain A has zero taker fee.
As a result, concentrated liquidity tests that depend on non-zero taker fee now use chain b and geometric twap tests that depend on taker fee not being set use chain A.
Tested by running e2e in CI muliple times. Also, tested by completely removing the taker fee …
=> fix(e2e): remove taker fee non-determinism affecting geo twap in e2e

CHANGELOG.md, app/upgrades/v19/constants.go, app/upgrades/v19/upgrades.go, app/upgrades/v19/upgrades_test.go
Proposal 597 broke the cfmm-gamm pool links, due to the governance logic not behaving as expected (replacing a list of instead of fixing it)
Proposed for this to be included in the v19 upgrade due to urgency at hand.
=> Add fix for prop 597 code issue

.github/workflows/build.yml
Don't run rebuild CI jobs for test-only changes.
These jobs are testing prod binaries, which should not include test compilation.
=> Don't rebuild binaries for test-only changes

tests/e2e/configurer/chain/chain.go, tests/e2e/configurer/chain/commands.go, tests/e2e/e2e_test.go, tests/e2e/helpers_e2e_test.go
Helps remove some of the code repetition as well, we can probably get a lot of this moved to helpers.
* Parallelize some repetitive components within CL code
* Parallelize CL param change proposals
* Move TickSPacingProp to its own parallelizable test
* Lower polling wait time from 2s to 1s
* Lower expedited prop wait time by 1 block
* Make more propsals expedited
* Eliminate redundant skipIBC's
* Remove Stableswap test from depending on upgrade (it no longer does)
* Delete some replicated code for validator votes on a proposal.
* Combine some BankSends together
=> Parallelize some E2E operations within CL E2E test

tests/e2e/containers/config.go, tests/e2e/initialization/node.go
Closes: #XXX
Approx 30s speedup from changing the consensus settings. 
NOTE: When backporting this to v18, we should only backport the node.go changes.
Tested locally and passes CI
=> e2e: fast blocks

CHANGELOG.md, app/keepers/modules.go, x/poolmanager/client/cli/tx.go, x/poolmanager/client/proposal_handler.go, x/poolmanager/client/rest/tx.go
Closes: #XXX
The "denom pair taker fee" prop CLI was not enabled. Also, the CLI that the DAO contract can use to set denom pairs was also not activated. This does both.
Locally installed and now see the CLI entry.
=> fix: enable taker fee cli

x/lockup/keeper/lock.go
The purpose of this change is to reduce the verbosity of the logs generated during the initialization of the x/lockup module. Currently, there are many log lines that are not particularly useful in normal operations.
(small sample)
```
...
4:43PM INF Setting accumulation entries for locks for gamm/pool/837/superbonding/osmovaloper1zlymlax05tg9km9jyw496jx60v86m454a3xf3m, there are 1 distinct durations
4:43PM INF Setting accumulation entries for locks for gamm/pool/837/superunbonding/osmovaloper1sjllsnramtg3ewxqwwrwjxfgc4n4ef9ua8h4lf, there are 1 distinct durations
4:43PM INF Setting accumulation entries for locks for gamm/pool/840/superbonding/osmovaloper103s29j7dyc3utljce802m38p2kk89taj0r2hxa, there are 1 distinct durations
...
```
This PR updates the logging level from INFO to DEBUG to …
=> [x/lockup] reduce log verbosity on `InitializeAllLocks()` 

CHANGELOG.md, tests/e2e/e2e_cl_test.go, x/concentrated-liquidity/math/math_test.go, x/concentrated-liquidity/math/tick.go, x/concentrated-liquidity/math/tick_test.go, x/concentrated-liquidity/model/pool_test.go, x/concentrated-liquidity/query.go, x/concentrated-liquidity/query_test.go, x/concentrated-liquidity/swaps.go, x/concentrated-liquidity/swaps_test.go, x/concentrated-liquidity/swaps_tick_cross_test.go, x/concentrated-liquidity/types/constants.go
Closes: #6046
This PR finalizes `BigDec` tick to sqrt price conversion infrastructure, making all relevant CL `math`  functions to be ready to support the new extended [10^-30, 10^-12) price range at the lower end.
It maintains backwards compatibility with `v19.x` and earlier release lines by returning an error here:
https://github.com/osmosis-labs/osmosis/blob/b335df5a3113f7c545d2792d67891ef0d5debbdf/x/concentrated-liquidity/math/tick.go#L257-L267
This would make swap or LP logic error consistently with `v19.x` and earlier releases if the current tick /  spot price falls under the original minimum.
The linked check is to be removed in a subsequent PR.
- For each changed function, added unit tests at the new price range and the edges.
- Removed obsolete price …
=> refactor: state-compatible big decimal tick to sqrt price conversions

CHANGELOG.md, osmoutils/osmoassert/assertions.go, x/concentrated-liquidity/math/math.go, x/concentrated-liquidity/math/math_test.go, x/concentrated-liquidity/swapstrategy/one_for_zero_test.go
Closes: #6351 
See #6351 for detailed context.
Our current order of math operations in `CalcAmount0Delta` was causing error blow-up. This was noticed pre-CL launch but was deemed as acceptable due to occurring infrequently.
By lowering our min spot price to 10^-30, the frequency of this error occurring was increased to an unacceptable degree.
The core of the issue is that `a / (b * c)` amplifies the error when b and c are both small. Division by extremely small numbers has such an effect.
By changing the order of operations to `a / b / c `, we reduce the error amplification and resolve the problem encountered.
The test added on this branch reproduces the edge case (expected results are estimated in Python).
Made changes to the new test helper in `osmoassert` as a drive-by change
Where is …
=> fix(CL): error blow up in CalcAmount0Delta causes OverChargeSwapOutGivenInError when swapping zero for one

CHANGELOG.md, x/tokenfactory/keeper/createdenom.go, x/tokenfactory/keeper/createdenom_test.go, x/tokenfactory/keeper/genesis_test.go
Closes: #6343 
This pull request sets the name, symbol and display fields of a denom metadata when denom is created by the tokenfactory module.
- *Extended unit tests of genesis and createdenom to reflect reproducing the bug being fixed by this change*
=> fix: set name, display and symbol of denom metadata in tokenfactory's CreateDenom

CHANGELOG.md, x/cosmwasmpool/client/cli/tx.go
The previous `create-pool` command expect contract's instantiate msg to have certain structure which might not be the case for every cosmwasmpool. So this update is to allow passing instantiate msg raw json string directly to the cli.
Manually verify change by running the command
=> Make cosmwasmpool's create pool cli generic

chain.schema.json, scripts/release/update_chain_registry/requirements.txt, scripts/release/update_chain_registry/run.sh, scripts/release/update_chain_registry/update_chain_registry.py, scripts/release/update_chain_registry/utils/go_mod.py, scripts/release/update_chain_registry/utils/versions.py
Closes: #XXX
This PR introduces a new script `update_chain_registry.py` aimed at automating the post-release updates to the chain schema. Currently, this script is designed to work only for major releases.
- Add `update_chain_registry.py` in `scripts/release` folder.
- Update chain schema for v19.0.0 using the new script.
The `scripts/release` folder already contains automation scripts for various tasks:
- `create_upgrade_guide.py` for generating upgrade guides.
- `create_binaries_json.py` for generating the cosmovisor JSON with binaries information.
The new `update_chain_registry.py` script will be a valuable addition to this suite of automations.
- This script will be integrated into the release CI pipeline, allowing for seamless and automatic updates to the chain schema post-release.
- …
=> [Post-Release Automation] Add script to update chain registry on a major release

tests/e2e/helpers_e2e_test.go
Closes: #XXX
The following method was introduced to run methods in parallel and block progress until finished:
https://github.com/osmosis-labs/osmosis/blob/9c3ca88f0a1cf23746166aa77be01fc4938b37c8/tests/e2e/helpers_e2e_test.go#L154-L163
The problem is, we didn't add a wg.Wait()
=> fix: add wait for e2e go routine

chain.schema.json
To fix chain.schema.json, the v19 height must be a number, not a string
(see that this PR failed checks https://github.com/cosmos/chain-registry/pull/2826)
(Checks failed: does this really need changelog update?)
=> fix: chain.schema.json v19 height

app/ante.go, tests/osmosisibctesting/chain.go, x/authenticator/ante/authenticator.go, x/authenticator/authenticator/interface.go, x/authenticator/authenticator/signature_authenticator.go, x/authenticator/integration_test.go, x/authenticator/keeper/keeper.go, x/authenticator/stateful_authenticator_test.go, x/authenticator/types/account_authenticators_test.go
Closes: https://github.com/osmosis-labs/osmosis/issues/6082
The fee payer needs to be authenticated with low gas. This ensures that a malicious user cannot force validators to spend compute on authenticating expensive txs if there isn't anyone to pay the fee.
Added a test for this. All other tests pass.
We should add many more tests for all of this feature. Ref #6377
=> [AccountAbstraction] FeePayer handling

CHANGELOG.md, app/apptesting/gamm.go, tests/e2e/initialization/config.go, tests/mocks/cfmm_pool.go, tests/mocks/cl_pool.go, tests/mocks/pool.go, tests/mocks/pool_module.go, x/concentrated-liquidity/model/pool.go, x/concentrated-liquidity/model/pool_test.go, x/concentrated-liquidity/pool.go, x/concentrated-liquidity/swaps_test.go, x/cosmwasmpool/model/pool.go, x/cosmwasmpool/model/pool_test.go, x/cosmwasmpool/model/store_model.go, x/cosmwasmpool/pool_module.go, x/gamm/keeper/pool_service.go, x/gamm/keeper/pool_service_test.go, x/gamm/pool-models/balancer/pool.go, x/gamm/pool-models/stableswap/pool.go, x/gamm/pool-models/stableswap/pool_test.go, x/poolmanager/types/pool.go, x/superfluid/keeper/migrate_test.go
Progress towards: https://github.com/osmosis-labs/osmosis/issues/6064
This PR is an incremental step towards implementing a 36 decimal spot price query.
The proposal and demo of what the end result would roughly look like can be seen here: https://github.com/osmosis-labs/osmosis/pull/6371
The goal is to incrementally break APIs in a state-compatible manner while backporting them to `v19.x`
The assumptions made:
- x/twap will continue to support only 18 decimal prices and not function correctly for pools with smaller spot price
- x/gamm pools will continue to support 18 decimal spot price only. Fixing/changing them is outside of scope.
=> refactor: break PoolI.SpotPrice API to return BigDec

CHANGELOG.md, x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/fuzz_test.go, x/concentrated-liquidity/keeper_test.go, x/concentrated-liquidity/position_test.go, x/concentrated-liquidity/range_test.go, x/concentrated-liquidity/spread_rewards_test.go, x/concentrated-liquidity/swaps.go, x/concentrated-liquidity/swaps_test.go, x/concentrated-liquidity/swaps_tick_cross_test.go, x/concentrated-liquidity/swapstrategy/swap_strategy.go, x/concentrated-liquidity/swapstrategy/swap_strategy_test.go, x/concentrated-liquidity/swapstrategy/zero_for_one.go, x/concentrated-liquidity/types/constants.go
Closes: #6355
State-compatible API change to the priceLimit swaps API needed to support the extended price range.
To be backported and validated on a v19.x node.
=> refactor(CL): convert priceLimit API in swaps to BigDec

CHANGELOG.md, x/concentrated-liquidity/math/math.go, x/concentrated-liquidity/math/math_test.go, x/concentrated-liquidity/python/clmath.py
Closes: #6353
This effort was started with the goal of testing CL `math` at low price level to make sure that there are no unexpected error blow-ups or rounding behavior at the extended price level.
While working on this, I noticed that there were small rounding direction issues in:
`GetNextSqrtPriceFromAmount0InRoundingUp`. They ended up being more apparent at the lower min spot price range. As a result, the fix is added here.
Additionally, in follow-up to https://github.com/osmosis-labs/osmosis/pull/6352, I realized that dividing by a bigger sqrt price first and smaller second leads to a more accurate result in `CalcAmount0Delta`. This is consistent with how Uniswap does it. See here: 
https://github.com/Uniswap/v3-core/blob/412d9b236a1e75a98568d49b1aeb21e3a1430544/contracts/libraries/Sq …
=> refactor/test(CL): Stricter rounding behavior in CL math methods; unit tests at low price level

CHANGELOG.md, scripts/empty_upgrade_handler_gen.sh, tests/e2e/README.md, tests/e2e/containers/config.go, tests/e2e/e2e_test.go, x/txfees/keeper/feedecorator.go, x/txfees/keeper/feedecorator_test.go
Closes: #XXX
Txfees collected in non osmo should be swapped to osmo at epoch and sent to the community pool. The taker fee feature implemented a new module account that collects non osmo funds, swaps them, and sends the to stakers instead. This module account was mistakenly used in the txfees logic instead of the old community pool txfees collector.
Very low impact from this bug, and simply swapping the module accounts fixes this.
=> bug: send non osmo txfees to community pool instead of stakers

CHANGELOG.md, go.mod, go.sum, osmoutils/coins/coin_math.go, osmoutils/coins/coin_math_test.go
Closes: #XXX
Reimplemented the same functionality 3 times while working on volume splitting.
Realized that upstream SDK supports a subset of these but not all.
I think it still makes sense to have them in our osmoutils for the speed of iteration and exhaustive support
- Added tests
=> feat(osmoutils): coin math helpers

CHANGELOG.md, x/txfees/keeper/feedecorator.go, x/txfees/keeper/feedecorator_test.go
Closes: #XXX
I was mistaken/confused on what we were doing prior to the taker fee upgrade. I thought we were sending non osmo txfees to the community pool, when in reality, it was always getting swapped to osmo and sent to stakers. Will prove here:
From v17, we send non osmo txfees to the NonNativeFeeCollector https://github.com/osmosis-labs/osmosis/blob/ea8b7410e66f4aa7f360e1ce09e7b0cfd5e6e4bf/x/txfees/keeper/feedecorator.go#L250-L256
The NonNativeFeeCollector swaps to osmo and sends to the fee collector in the epoch hook here https://github.com/osmosis-labs/osmosis/blob/ea8b7410e66f4aa7f360e1ce09e7b0cfd5e6e4bf/x/txfees/keeper/hooks.go#L17-L48
So this value being FeeCollectorForStakingRewards was correct.
=> revert: bug: send non osmo txfees to community pool instead of stakers

x/poolmanager/client/cli/tx.go
Closes: #XXX
CLI had an extra required value that is not actually needed. This PR removes that mistake.
Johnny tested the CLI and it now works:
```
{"body":{"messages":[{"@type":"/osmosis.poolmanager.v1beta1.MsgSetDenomPairTakerFee","sender":"osmo19mywfjzj324w5ukf7ss6jak0dg9hnljfp0rfx4","denom_pair_taker_fee":[{"denom0":"uosmo","denom1":"ibc/D176154","taker_fee":"0.002000000000000000"},{"denom0":"ibc/4ABB","denom1":"ibc/2108F","taker_fee":"0.000000000000000000"}]}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[],"gas_limit":"350000","payer":"","granter":""}},"signatures":[]}
```
=> fix: set denom pair taker fee CLI

.github/workflows/check-state-compatibility.yml
Closes: #6459
Context in issue. I think this is failing the state compact check on v19.x
Tested that this returns some data:
```
wget -q -O - https://osmosis.fra1.digitaloceanspaces.com/osmosis-1/snapshots/v19/snapshots.json
```
=>  fix(CI): state compat snapshots version

CHANGELOG.md, x/pool-incentives/keeper/genesis.go
Closes: #6230
Context is in issue plus here: https://osmosis-network.slack.com/archives/C029XNL2L9G/p1695150489576199
This change is intended for v19.x backport only. The proper fix is to be created in a subsequent PR via https://github.com/osmosis-labs/osmosis/issues/6122
=> fix(poolincentives): band-aid state export fix for cwpool gauges

chain.schema.json, networks/osmosis-1/README.md, networks/osmosis-1/upgrades/v19/mainnet/guide.md, networks/osmosis-1/upgrades/v19/v19_binaries.json, scripts/release/create_binaries_json/create_all_binaries_json.sh, scripts/release/update_chain_registry/update_chain_registry.py, scripts/release/update_chain_registry/utils/versions.py
This PR:
- Updates the chain registry schema with latest `19.1.0` minor release 
- Updates cosmovisor binaries to use `19.1.0`
- Updates network upgrade docs to use `19.1.0`
- Updates the chain registry script to  handle minor release updates
Trivial/Docs changes.
=> V19.1.0/post release chores

proto/osmosis/authenticator/models.proto, x/authenticator/ante/authenticator_test.go, x/authenticator/authenticator/interface.go, x/authenticator/authenticator/signature_authenticator.go, x/authenticator/authenticator/spend_limits.go, x/authenticator/integration_test.go, x/authenticator/keeper/keeper_test.go, x/authenticator/keeper/msg_server.go, x/authenticator/types/models.pb.go, x/authenticator/types/msgs.go
- Added initial test cases for the ante handler
- Updated the checks in the msg_server.go
- Added comments to the proto file model
```
user1=$(osmosisd keys show user1 -a --keyring-backend=test)
pubkey=$(osmosisd keys show user1 -p --keyring-backend test | jq -r .key)
echo "y" | osmosisd keys add newKey1 --keyring-backend test 
pubkey1=$(osmosisd keys show newKey1 -p --keyring-backend test | jq -r .key)
echo "y" | osmosisd keys add newKey2 --keyring-backend test 
pubkey2=$(osmosisd keys show newKey2 -p --keyring-backend test | jq -r .key)
osmosisd tx authenticator add-authenticator SignatureVerificationAuthenticator $pubkey1 --from user1 --chain-id testing --keyring-backend test --fees 1000stake -b sync -y
sleep 4
osmosisd tx authenticator add-authenticator …
```
=> feat: improve msg server, test aute handler

CHANGELOG.md, wasmbinding/stargate_whitelist.go
Closes: #XXX
Adds pool manager query params to stargate whitelist. 
This is essential for contracts to be able to query pool creation fee. 
Params from other modules are already whitelisted so adding this should not be problematic
=> Add stargate whitelist for pool manager params

CHANGELOG.md, app/apptesting/gamm.go, app/apptesting/test_suite.go, app/upgrades/v16/upgrades_test.go, app/upgrades/v17/upgrades_test.go, tests/mocks/pool_module.go, x/concentrated-liquidity/pool.go, x/concentrated-liquidity/pool_test.go, x/cosmwasmpool/pool_module.go, x/gamm/keeper/grpc_query.go, x/gamm/keeper/grpc_query_test.go, x/gamm/keeper/pool_service.go, x/gamm/keeper/pool_service_test.go, x/gamm/keeper/swap_test.go, x/gamm/pool-models/balancer/pool_suite_test.go, x/gamm/types/constants.go, x/poolmanager/client/query_proto_wrap.go, x/poolmanager/router.go, x/poolmanager/router_test.go, x/poolmanager/types/expected_keepers.go, x/twap/api_test.go, x/twap/listeners_test.go, x/twap/logic.go, x/twap/types/expected_interfaces.go, x/twap/types/twapmock/amminterface.go, x/twap/types/utils.go, x/txfees/keeper/feetokens.go, x/txfees/keeper/grpc_query.go, x/txfees/types/expected_keepers.go
Progress towards: https://github.com/osmosis-labs/osmosis/issues/6064
This PR aims to continue the progress toward introducing a BigDec spot price query.
It should be state-compatible. The current clients are not expected to be broken because we truncate the spot price to 18 decimals before returning.
In the subsequent PR, a new spot price query is to be introduced that returns a 36-decimal spot price.
- To be backported to v19.x and tested on a node
=> feat: make PoolModuleI CalculateSpotPrice API  return BigDec

CHANGELOG.md, go.mod, go.sum, osmomath/go.mod, osmomath/go.sum, osmoutils/go.mod, osmoutils/go.sum, osmoutils/store_helper.go, tests/cl-genesis-positions/go.mod, tests/cl-genesis-positions/go.sum, tests/cl-go-client/go.mod, tests/cl-go-client/go.sum, x/epochs/go.mod, x/epochs/go.sum, x/gamm/keeper/migrate.go, x/ibc-hooks/go.mod, x/ibc-hooks/go.sum
Closes: #XXX
Removes redundant param
=> refactor(osmoutils): remove redundant ctx param from DeleteAllKeysFromPrefix

CHANGELOG.md, x/incentives/keeper/gauge.go
Closes: #XXX
Removes redundant param. Will backport and test for state compatibility
=> refactor(incentives): remove redundant param from CreateGaugeRefKeys

app/keepers/authz.go, app/keepers/keepers.go, app/modules.go, x/authenticator/README.md, x/authenticator/ante/authenticator.go, x/authenticator/authenticator/all_of.go, x/authenticator/authenticator/any_of.go, x/authenticator/authenticator/composition_test.go, x/authenticator/authenticator/manager.go, x/authenticator/authenticator/signature_authenticator.go, x/authenticator/authenticator/spend_limits.go, x/authenticator/authenticator/spend_limits_test.go, x/authenticator/iface/iface.go, x/authenticator/iface/result.go, x/authenticator/integration_test.go, x/authenticator/keeper/keeper.go, x/authenticator/keeper/keeper_test.go, x/authenticator/post/post.go, x/authenticator/testutils/generic_authenticator.go, x/authenticator/testutils/max_value_authenticator.go, x/authenticator/testutils/stateful_authenticator.go, x/authenticator/types/account_authenticators.go, x/authenticator/types/account_authenticators_test.go, x/authenticator/utils/track.go
This is a solution to ensure authenticators work properly with authz. A similar solution can be implemented for ICA or any other module that allows message execution without validating it via authenticators.
Alternative solutions:
* fork authz so the same implementation is cleanner
* let authz bypass authenticator checks
* Remove authz mesages and create an authenticator that uses authz grants and verifies them the same way 
The last one is probably the cleanest solution but mixes authentication and authorization (which is something we don't all agree on) and breaks anyone that's currently using Exec (though migrating should be easy and in the meantime we can have a version of exec similar to what we do in this PR)
Added a test specifically to test spend limit with authz
Where is the …
=> [AccountAbstraction] Making authz aware of authenticators

go.mod, go.sum, osmomath/decimal_test.go
Closes: #6469 
* Check that using precision exceeding `PrecisionBigDec` will panic `ChopPrecision`
* Use `osmomath.ConditionalPanic` in decimal tests where applicable
Only tests were modified
NA
=> osmomath: ChopPrecision exceeds limit test

app/apptesting/test_suite.go, x/incentives/keeper/distribute_test.go, x/incentives/keeper/export_test.go, x/incentives/keeper/gauge.go, x/incentives/keeper/gauge_test.go, x/incentives/types/expected_keepers.go, x/pool-incentives/keeper/keeper.go, x/pool-incentives/keeper/keeper_test.go, x/pool-incentives/types/errors.go
Closes: #6401
Implements and tests `initGaugeInfo` helper per issue requirements.
Removed volume splitting policy param from proposed design due to no need.
Added `GetInternalGaugeIDForPool` helper in pool incentives.
Added `PrepareAllSupportedPools` test helper in test-global scope since it was helpful across modules.
Added `deepCopyGaugeInfo` and `addGaugeRecords` in the incentives module test scope. I expect them to be useful in future tests as well.
- Unit tested all new additions
=> [Volume Splitting] feat: implement initGaugeInfo helper

.github/workflows/go-mod-auto-bump.yml
Closes: #6550
Changes a logic for parsing latest target's commit in go.mod auto update workflow
trivial, same logic works for parsing main's latest commit in the same workflow
minor, N/A
=> dev-ux: fix go.mod auto update workflow bug

.goreleaser.yaml
This PRs removes darwin binaries from our goreleaser config
This change can be verified as follows:
```bash
cd <OSMOSIS_REPO>
docker run -e COSMWASM_VERSION=v1.2.3     -v /var/run/docker.sock:/var/run/docker.sock     -v `pwd`:/go/src/osmosisd     -w /go/src/osmosisd ghcr.io/goreleaser/goreleaser-cross:v1.20.5 releas
e --clean --skip-publish --skip-validate
osmosis@test:~/release/osmosis$ ls dist/
artifacts.json  metadata.json                       osmosisd-19.2.0-linux-arm64.tar.gz     osmosisd-darwin-arm64_darwin_arm64    osmosisd-linux-amd64_linux_amd64_v1  sha256sum.txt
config.yaml     osmosisd-19.2.0-linux-amd64.tar.gz  osmosisd-darwin-amd64_darwin_amd64_v1  osmosisd-darwin-universal_darwin_all  osmosisd-linux-arm64_linux_arm64
```
Binaries are built but not added to the release. We …
=> [goreleaser] Remove darwin binaries from goreleaser.yml

chain.schema.json, networks/osmosis-1/README.md, networks/osmosis-1/upgrades/v19/mainnet/guide.md, networks/osmosis-1/upgrades/v19/v19_binaries.json, scripts/release/create_binaries_json/create_all_binaries_json.sh
This PR:
- Updates the chain registry schema with latest `19.2.0` minor release 
- Updates cosmovisor binaries to use `19.2.0`
- Updates network upgrade docs to use `19.2.0`
Trivial/Docs changes.
=> v19.2.0 chores

x/poolmanager/create_pool_test.go, x/poolmanager/router.go, x/poolmanager/router_test.go, x/txfees/keeper/hooks.go
Closes: #6573
We have several swap helpers. As a result, we missed adding call to `trackVolume` to some of them.
This PR adds the check to `SwapExactAmountIn` and `SwapExactAmountInNoTakerFee`. It tests them both.
For the future, I propose we remove `SwapExactAmountInNoTakerFee` and instead create a whitelist for no fee payers: https://github.com/osmosis-labs/osmosis/issues/6572
In the current PR, I also made `RouteExactAmountIn` call `SwapExactAmountIn` to reduce code duplication.
Having low-level swap logic such as tracking volume and charging taker fees be called in `SwapExactAmountIn` and all other methods call it reduces the changes of missing adding new logic in the future.
- Added tests that `SwapExactAmountIn` and `SwapExactAmountInNoTakerFee` track volume
Where is the change …
=> [VS Incentives] refactor(poolmanager): trackVolume in swap exact amount in

x/incentives/keeper/distribute_test.go, x/incentives/keeper/gauge.go, x/incentives/keeper/gauge_test.go, x/incentives/keeper/genesis_test.go, x/incentives/keeper/hooks_test.go, x/pool-incentives/keeper/distr_test.go
Closes: #6581
See #6581 for details.
We would like to sync weights on group creation to make sure that the given pools are valid and have the volume
Updated tests, including an additional test case where CreateGroup fails due to lack of volume in one of the pools.
=> [Volume Splitting] refactor: sync weights on group creation

x/incentives/keeper/msg_server_test.go
Closes: #XXX
The test failure was not caught by CI in PR due to being added by a concurrent PR. This fixes CI on main
=> fix: test failure on main stemming from group test

x/incentives/keeper/hooks_test.go
Progress towards: https://github.com/osmosis-labs/osmosis/issues/6559
Adds test for group epoch distribution. This test focuses on volume being updated across epochs.
Made some refactors to other tests to address a rounding off-by-one issue in estimating test amounts that came up.
=> [VS Incentives]: distribution test for changing volume between epochs

app/apptesting/concentrated_liquidity.go, x/concentrated-liquidity/position_test.go, x/incentives/keeper/hooks_test.go
Closes: #6559
This finalizes the planned tests for the incentive epoch end hook with groups.
Focuses on 2 tests:
1. Creating groups in-between distributions
2. Changing volume by swaps as opposed to setting it with a setter directly
=> [VS Incentives]: remaining after epoch group test vectors

x/incentives/keeper/distribute.go, x/incentives/keeper/distribute_test.go, x/incentives/keeper/hooks_test.go, x/incentives/types/errors.go
Closes: #6602
See issue for details. This PR implements a fallback mechanism to previous weights if volume fails to sync.
If there is no volume at the time of group creation, this will still continue to fail. 
- Added unit test to each method in the call stack of the group distribution flow
=> [VS Incentives] fallback to previous weights if no volume

app/apptesting/incentives.go, app/upgrades/v20/export_test.go, app/upgrades/v20/upgrades.go, app/upgrades/v20/upgrades_test.go, x/incentives/keeper/group_test.go, x/incentives/keeper/hooks_test.go
Closes: #6603
Our current mechanism for incentivizing pairs of the same denom first directs incentives to CL gauges. Then, CL module retroactively pipes the eligible amounts to balancer based on its liquidity relative to CL.
On main, we already removed the retroactive mechanism from CL module. However, on-chain CL gauges continue to receive all rewards a denom pair is entitled to.
We should update all distribution records to detect CL gauges and associate Group gauges in their place.
This is done by introducing an upgrade handler method `createGroupsForIncentivePairs`
This method converts pool incentive distribution records from concentrated gauges to group gauges.
The expected update is to convert concentrated gauges to group gauges iff
- migration record exists for the concentrated pool …
=> [VS Incentives]: upgrade handler redirects pool incentives distribution records to groups

x/incentives/types/msgs.go, x/incentives/types/msgs_test.go
Closes: #6592
We temporarily disable non-perpetual group creation at the message server level until we implement the necessary logic for this.
Since we just disable at the validate basic level, we add a check just to the validate basic test.
=> [VS Incentives]: disable non perpetual group gauge creation

x/incentives/keeper/group.go, x/incentives/keeper/group_test.go, x/incentives/types/errors.go
Closes: #XXX
We prevented duplicate pool IDs in the validate basic of create group, but we decided it should also live in the createGroup method itself, in the event createGroup gets called outside of the message server. 
Added a default error case, in which any call the createGroup with duplicate pool IDs should error.
=> [VS Incentives]: prevent duplicate pool IDs in create group

app/upgrades/v20/upgrades.go, app/upgrades/v20/upgrades_test.go, x/pool-incentives/keeper/distr.go, x/pool-incentives/types/constants.go
Closes: #XXX
Fix upgrade handler bugs where the gauge ID of zero that represents community pool is not handled correctly.
Validated that gauge ID of zero record is indeed present on mainnet and such a gauge does not exist
=> [VS Incentives] fix upgrade handler bug with zero ID community pool gauge

CHANGELOG.md, wasmbinding/stargate_whitelist.go
Closes: #6585
this PR will enable smart contracts to fetch osmosis's module accounts.
* that said, let us know if this code change is not considered trivial *
Where is the change documented? 
- [ x] N/A
=> add auth.moduleaccounts to the stargate whitelist

x/concentrated-liquidity/README.md
Updated changes in 
https://github.com/osmosis-labs/osmosis/blob/main/x/concentrated-liquidity/README.md#deducing-the-quantity-of-tokens-x-and-y-for-a-tick-range
=> Update typos/equations in CL Readme.md

x/valset-pref/README.md, x/valset-pref/export_test.go, x/valset-pref/keeper.go, x/valset-pref/keeper_test.go, x/valset-pref/msg_server.go, x/valset-pref/types/errors.go, x/valset-pref/validator_set.go, x/valset-pref/validator_set_test.go
Closes: #XXX
Finishes the val set pref unbonding PR, mainly adds test cases, minor refactoring and better code documentation included. 
Note that this PR is pointed towards  `dev/valset-pref-unbond-issues` branch, not the main branch
=> Finish ValSet Pref Unbonding

CHANGELOG.md, go.mod, go.sum, osmomath/math.go, osmomath/math_test.go, osmomath/pow_bench_test.go, x/gamm/pool-models/balancer/pool_suite_test.go
Closes: #XXX
Limits the number of Pow iterations:
To make sure that we don't hit the loop iteration bound too often
under normal conditions, this change was backported to v19.x (mainnet at the time of writing)
and tested for no app-hash over 10000 blocks.
```
go test -benchmem -run=^$ -bench ^BenchmarkSlowPowCases$ github.com/osmosis-labs/osmosis/osmomath -count=6
goos: linux
goarch: amd64
pkg: github.com/osmosis-labs/osmosis/osmomath
cpu: 12th Gen Intel(R) Core(TM) i7-1260P
BenchmarkSlowPowCases-16              76          14897602 ns/op         3760805 B/op     168182 allocs/op
BenchmarkSlowPowCases-16              78          14858077 ns/op         3760792 B/op     168181 allocs/op
BenchmarkSlowPowCases-16              79          15163556 ns/op         3760784 B/op     168181 …
```
=> refactor(osmomath): limit pow iterations in osmomath

x/pool-incentives/keeper/genesis.go
Closes: #XXX
Learned today that we should not have any log lines (at least info log lines) in the export logic. Otherwise, it gets written to the json and messes it up.
=> fix: remove log line

Makefile
This adds two new options to make to build and install a dev binary that then allows debugging, which then allows VS Code/Goland to attach to a running process.
This change is a trivial addition to make, not sure how to add tests for this, but I did build it and successfully attach Goland to the running process.
=> Add debug build options to make

x/pool-incentives/keeper/grpc_query.go, x/pool-incentives/keeper/keeper.go
Closes: #XXX
We recently got rid of silently skipping errors in the incentivized pools query. We did not take into consideration gauge 0, which distributes to the community pool. This fix skips gauge 0.
Without fix on state exported testnet
```
osmosis# osmosisd q poolincentives incentivized-pools
Error: rpc error: code = Unknown desc = rpc error: code = Internal desc = gauge with ID (0) not found: unknown request
```
With fix
```
root@ale-roman-state-comp:~/osmosis# ./build/osmosisd q poolincentives incentivized-pools
incentivized_pools:
- gauge_id: "29899"
lockable_duration: 1209600s
pool_id: "833"
- gauge_id: "35532"
lockable_duration: 86400s
pool_id: "1066"
- gauge_id: "35532"
lockable_duration: 1209600s
pool_id: "674"
- gauge_id: "33257"
lockable_duration: 86400s
pool_id: "1076"
- …
```
=> fix: skip community pool for incentivized pools query

x/authenticator/authenticator/all_of.go, x/authenticator/authenticator/any_of.go, x/authenticator/integration_test.go
Ensuring AnyOf and AllOf have sub-authenticators, the sub-authenticators are registered (both when adding and when initializing), and defensively returning false for an empty all-of
all existing tests should pass
=> [AccountAbstraction] Validating AnyOf and AllOf

x/authenticator/ante/ante.go
> When specifying a separate fee payer address the feePayerAuthenticated flag never becomes true as account.Equals(feePayer) always fails, the fee payer won't be a signer of a message even if they signed the transaction.
This PR checks that the fee payer has been authenticated and ensures the tx fails otherwise. 
All existing tests should fail.
TODO: add a test specific to a custom (bad) fee payer
=> [AccountAbstraction] Simple remediation of custom fee payer skipping authenticatation

x/authenticator/utils/track.go
> Since the accounts authenticators are based in the first signer, I think it would allow for a malicious account authenticator to essentially skip the other signer if they wanted. The authz module has a check to prevent messages with multiple signers from being dispatched, should there be a similar check before using an account authenticator?
This PR adds validation to ensure a message only has one signer. 
all existing tests should pass
=> [AccountAbstraction] Validating that there is only one signer per message

.vscode/settings.json, scripts/compare_git.py
Closes: #XXX
When creating a release, its important to check if any commits are missing from the feature branch. This script returns the delta between two branches. It is also smart enough to link a PR and its backport as the "same" PR and does not include it in its delta.
Used to check diff between main and v20.x
```
scripts % python3 compare_git.py
Enter the release branch name: v20.x
Enter the main branch name (default: main): 
Commits present in main but missing in v20.x:
c9e9b1004 Improve localosmosis docs (#6679)
6da6b231e auto: update Go import paths to v20 on branch main (#6688)
eec71f86b Test/max tick test (#6661)
bac369861 chore(deps): bump tj-actions/changed-files from 39.2.1 to 39.2.2 (#6675)
```
And conversely, check commits in v20.x but not main
```
scripts % python3 …
```
=> chore: compare branch diffs script

.github/workflows/release.yml
These steps include a cleanup procedure at the end of the release process to prevent the permission error found here: https://github.com/osmosis-labs/osmosis/actions/runs/6550289656/job/17789063555
The cleanup is necessary to ensure that the runner is left in a clean state. Otherwise, subsequent GitHub Actions that attempt to check out a reference could fail due to permission issues, as evidenced in the linked run.
=> Add cleanup step to release GitHub Action

Makefile
This PR modifies the Makefile to change the `VERSION` argument to `SDK_VERSION` in the update-sdk-version target.
This avoids overwriting the `VERSION` variable set before.
```
#!/usr/bin/make -f
VERSION := $(shell echo $(shell git describe --tags) | sed 's/^v//')
```
This was the cause of the bug showing empty `osmosisd version` in previous builds. 
You can check that it's working using:
```make
make update-sdk-version SDK_VERSION=v0.45.1-0.20230523200430-193959b898ec
```
=> Replace VERSION with SDK_VERSION in Makefile target 

tests/osmosisibctesting/chain.go, x/authenticator/authenticator/spend_limits.go, x/authenticator/integration_test.go
Closes: #XXX
When getting the price for a coin using the Twap strategy, sla.twapKeeper.GetArithme
ticTwapToNow is called to calculate the price
The issue is that the error check is inverted, causing the error to be ignored and an
empty price to be returned instead
run tests
- `cd x/authenticator`
=> chore: return error from twap

CHANGELOG.md, cmd/osmosisd/cmd/change_environment.go, cmd/osmosisd/cmd/root.go
Closes: #4527
Add list-env for CLI
=> list-env CLI command

go.mod, go.sum
use a version of pfm that includes https://github.com/cosmos/ibc-apps/pull/105
=> Fix bad PFM error

x/authenticator/ante/ante.go
Closes: #XXX
allow selectedAuthenticators indices to  be negative
> The ante handler for the Authenticator allows users to specify which authenticator to
use for any message. Every account has a registered list of authenticators which can
be used. The users specify the Authenticator index for the Authenticator to be used.
- `cd x/authenticators`
=> chore: handle negative selected authenticators

CHANGELOG.md, go.mod, go.sum, osmoutils/cosmwasm/helpers.go, x/cosmwasmpool/types/expected_keepers.go
Fix `{overflow}` bug when querying cosmwasmpool spot price.
This is caused by [mapping sdk gas to wasmvm gas](https://github.com/osmosis-labs/wasmd/blob/v0.31.0-osmo-v16/x/wasm/keeper/gas_register.go#L244) which normal gas limit will likely cause overflow due to high number.
The fix is to use `queryGasLimit` from wasmkeeper to keep the vm gas under `uint64`.
Verified that querying spotprice from transmuter v2.0.0 cosmwasmpool has no issue.
=> fix: `{overflow}` bug when querying cosmwasmpool spot price

CHANGELOG.md, x/valset-pref/types/codec.go
Add a codec we forgot to add.
Please close / just redo the PR if I did this wrong
=> Add forgotten redelegation codec

CHANGELOG.md, x/concentrated-liquidity/types/errors.go
Closes: #XXX
When slippage bound is hit during LP, the error message is confusing. This PR improves it.
=> fix: improve error message for slippage bound when LPing

x/txfees/keeper/txfee_filters/arb_tx.go
Lets just sanity check that swapInDenom for non-authz
=> Try respect authz

x/concentrated-liquidity/lp.go
Closes: #XXX
Smarter error message when LP ranges get out of range near bounds due to significant price movements. Prompted by the TIA launch
=> fix: LP error message improvements when zero liquidity

x/authenticator/authenticator/all_of.go, x/authenticator/authenticator/any_of.go, x/authenticator/authenticator/composition_test.go, x/authenticator/testutils/generic_authenticator.go
>The Authenticator interface implements a ConfirmExecution handler, which is executed by the post-handler. This can be used to enforce transaction rules, or validate any post transaction changes. The ConfirmExecution handler can reject a transaction if any rules are violated
> The ConfirmExecution handler for these authenticators iterate over executedAuths and invoke ConfirmExecution for the Sub-Authenticators. However, executedAuths is never actually set anywhere
We remove executed auths in favour of `authenticator.Track`
- Review code
- Run tests
=> fix: remove executedAuths in favor of using the Track function  

Makefile, scripts/makefiles/build.mk
This pull request introduces two changes to the `build.mk` file in the `scripts/makefiles` directory. 
1. It replace the usages of `check_version` target to `build-check-version`.
2. It adds an end-of-file (EOF) blank line at the end of the file.
NOTE: `check_version`  got renamed to `build-check-version` in #6776
=> ci: fix missing target `check_version` and add eof blank line

x/poolmanager/router.go
This pull request improves code readability of module x/poolmanager by change 
```go
routeStep := types.SwapAmountOutRoutes(route)
if err := routeStep.Validate(); err != nil {
return osmomath.Int{}, err
}
```
to
```go
if err := types.SwapAmountOutRoutes(route).Validate(); err != nil {
return osmomath.Int{}, err
}
```
because "routeStep" variable has define as `routeStep := types.SwapAmountOutRoutes(route)` , but redefined following with `for i, routeStep := range route {}` , that looks confusing
=> refactor: change validate routes code inline

x/authenticator/ante/ante.go, x/authenticator/ante/ante_test.go, x/authenticator/ante/fees.go, x/authenticator/ante/pubkey.go, x/authenticator/ante/pubkey_test.go
Test the public key ante handler and fix issue with setting incorrect public key
Added a test case to ensure issue is fixed
- `cd /x/authenticator/ante`
- `go test -v -cover ./...`
=> fix: ensure pubkey ante handler works as expected

CHANGELOG.md, x/tokenfactory/keeper/before_send.go, x/tokenfactory/keeper/before_send_test.go, x/tokenfactory/types/constants.go, x/tokenfactory/types/errors.go
Closes: #XXX
Adds gas metering to BlockBeforeSend.
Add relevant test cases. 
=> fix: Add gas metering to BlockBeforeSend

CHANGELOG.md, cosmwasm/contracts/crosschain-swaps/src/ibc_lifecycle.rs
=> fix typo in message

.dockerignore
Closes: #XXX
CI for pushing e2e images to docker have been failing recently on main. (cref:https://github.com/osmosis-labs/osmosis/actions/runs/6740991117/job/18324888461)
Digging down the root cause, I have saw a log in our CI failure saying: "scripts/makefiles/build.mk: No such file or directory".  This led me to thinking that maybe docker can't access the Makefiles under scripts/Makefile, and confirmed this was the case after noticing scripts folder under docker ignore. 
This PR removes scripts from docker ignore
=> Fix CI for Pushing E2E Images to Docker

x/concentrated-liquidity/swapstrategy/swap_strategy.go
remove following continuous repetition code:
```go
if priceLimit.GTE(types.MinSpotPriceBigDec) {
// Truncation is fine since previous Osmosis version only supported
// 18 decimal price ranges.
sqrtPriceLimit, err := osmomath.MonotonicSqrt(priceLimit.Dec())
if err != nil {
return osmomath.BigDec{}, err
}
if err != nil {
return osmomath.BigDec{}, err
}
return osmomath.BigDecFromDec(sqrtPriceLimit), nil
}
```
=> remove continuous repetition code

CHANGELOG.md, wasmbinding/stargate_whitelist.go
Closes: #XXX
Adds EstimateTradeBasedOnPriceImpact to stargate whitelist so that contracts can query estimation on the price impacts.
=> Add EstimateTradeBasedOnPriceImpact to stargate whitelist

app/apptesting/concentrated_liquidity.go, app/apptesting/pool_manager.go, x/concentrated-liquidity/fuzz_test.go, x/concentrated-liquidity/incentives_test.go, x/concentrated-liquidity/invariant_test.go, x/concentrated-liquidity/keeper_test.go, x/concentrated-liquidity/lp_test.go, x/concentrated-liquidity/position_test.go, x/concentrated-liquidity/range_test.go, x/concentrated-liquidity/spread_rewards_test.go, x/concentrated-liquidity/swaps_test.go, x/concentrated-liquidity/tick_test.go
Closes: #XXX
This PR moves CL test helpers into the `apptesting` package so that these heleprs can be reused in SQS.
This is partial transfer of https://github.com/osmosis-labs/osmosis/pull/6785 where the CL apptesting suite is already in-use
=> chore: CL apptesting helpers for SQS

x/poolmanager/export_test.go, x/poolmanager/router.go, x/poolmanager/router_test.go, x/poolmanager/taker_fee.go
Closes: https://app.clickup.com/t/86a1af4tp
This PR converts some poolmanager taker fee calc methods to functions. In https://github.com/osmosis-labs/osmosis/pull/6785, these are used in SQS calculations directly.
=> refactor(SQS): convert poolmanager taker fee calc methods to functions

.github/mergify.yml
Closes: #XXX
Current automerge mergify rules have 1 >= approvals. 
Although there might be instances where we don't need 2 >= approval for merging depending on the PR, I think this should not be the case with auto merge
=> Change mergify rules to 2 >= Approvals for Automerge

x/concentrated-liquidity/swaps.go
concentrated pool should use `types.ConcentratedGasFeeForSwap` instead of `gammtypes.BalancerGasFeeForSwap`
fix the wrong value used by concentrated pool module. Although the value of `gammtypes.BalancerGasFeeForSwap ` is equal to `types.ConcentratedGasFeeForSwap`. But this may lead to potential risk if the value of `gammtypes.BalancerGasFeeForSwap ` is different from `types.ConcentratedGasFeeForSwap` in the future.
=> fix: concentrated pool should use types.ConcentratedGasFeeForSwap

CHANGELOG.md, wasmbinding/stargate_whitelist.go
fix wrong response type used by DenomMetadata query and add missing DenomsMetadata query
=> fix: wasm set whitelist query

x/authenticator/authenticator/any_of.go, x/authenticator/authenticator/composition_test.go
This change represent the final iteration in the `AnyOf` authenticator.
We check all authenticators in confirm execution, as we expect that any authenticator added to an `AnyOf` will either always return true, or have some rules that need to be checked in the ConfirmExecution.
- `cd ./x/authenticators`
- `go test -cover ./... -v -test.run TestAggregatedAuthenticatorsTest/TestAnyOfAuthenticator`
=> chore: check all authenticators for anyOf in ConfirmExecution

x/txfees/keeper/mempool-1559/code.go
After merging this, I think we should push this to more validators
=> Tune 1559 params

x/txfees/keeper/mempool-1559/code.go
Fixes 1559 comments to align with changes in #6844
=> Fix 1559 comments to align with new tuned params

app/app.go, app/keepers/keepers.go, x/txfees/keeper/feedecorator.go, x/txfees/keeper/keeper.go, x/txfees/keeper/mempool-1559/code.go
Plumbs the data directory path based on the homedir through the txfees Keeper to be joined with the Backup filename in the EipState
```
$ ls ~/.osmosisd/data/
application.db  blockstore.db  cs.wal  eip1559state.json  evidence.db  priv_validator_state.json  snapshots  state.db  upgrade-info.json
```
Fixes #6856
=> fix: fixes eip1559state.json reading/writing

.github/workflows/e2e-initialization-instructions.yaml
Recently I've seen several instances where go mod update instruction CI would be failing:
https://github.com/osmosis-labs/osmosis/actions/runs/6846633458/job/18613544135?pr=6867
This PR grants writing permission for the PR to fix the current error occuring. 
=> fix failing CI for go mod update instructions

CHANGELOG.md, app/upgrades/v21/upgrades.go
Closes: #XXX
Right now, protrorev pays a taker fee on it's backruns. There is no need for this as this profit goes back to the protocol anyway.
=> feat: protorev no taker fee

x/txfees/keeper/mempool-1559/code.go
move tryPersist lock after json.Marshal to reduce the locking time
=> refactor: tryPersist locks after json marshal success

CHANGELOG.md, x/txfees/keeper/txfee_filters/arb_tx.go, x/txfees/keeper/txfee_filters/arb_tx_test.go, x/txfees/keeper/txfee_filters/export_test.go
Closes: #XXX
Manual Backport of @p0mvn work on affiliated swap messages PR https://github.com/osmosis-labs/osmosis/pull/6890/files
=> feat: enable arb filter for affiliate swap messages (backport #6890)

CHANGELOG.md, cmd/osmosisd/cmd/root.go, x/txfees/types/options.go
Closes: #XXX
Enable adaptive fee market by default
Tested by setting up the config and observing that the setting is set
=> refactor: enable eip1559 mempool by default in config

go.sum, proto/osmosis/poolmanager/v1beta1/query.yml, x/poolmanager/client/grpc/grpc_query.go, x/txfees/keeper/mempool-1559/code.go
Update the EIP-1559 constants to ease resets.
The last spamming that affected users seems to me to have had 4 root causes of issue:
- The reset interval happened right after epoch, resulting in 7 extra minutes of pain. (Every 1000 blocks) Make this 50% less likely by making it every 2000 blocks
- The value reset to .0025, requiring 4 minutes to get back to old value
- Keplr fee settings were too low (other integrators were set. The keplr chain registry bot was not updated to latest integrator suggested numbers)
- Large time with only non-1559 validator proposals
So (3) should get independently fixed, which should've been the root cause of most user pain outside of (4).
(4) should be fixed by increasing number of 1559 nodes, and lowering block times.
This PR lowers the probability of …
=> Update the eip1559 constants

x/txfees/keeper/txfee_filters/arb_tx.go, x/txfees/keeper/txfee_filters/arb_tx_test.go
arb filter was not properly deserializing the messages leading to a panic (referencing empty route array position) on other messages.
added a test
=> better checks for affiliate swap contract in arb filter

CHANGELOG.md, x/poolmanager/router.go
Refer to [PR #6766](https://github.com/osmosis-labs/osmosis/pull/6766), get pool denoms info by `k.GetTotalPoolLiquidity` will lead to:
1. fetching pool module once again(one more io op) which already known as `k.poolModules` range iterator
2. filtering denom by `coins.AmountOf(denom).GT(osmomath.ZeroInt())` is odd, although there is no pool with zero amount token
This change is already covered by existing tests, such as *TestListPoolsByDenom*.
=> refactor: improve ListPoolsByDenom filter logic

cmd/osmosisd/cmd/root.go
Closes: #XXX
When running `osmosisd`, there were two entries for rollback and rosetta:
```
rollback                rollback cosmos-sdk and tendermint state by one height
rollback                rollback CometBFT state by one height
rosetta                 spin up a rosetta server
rosetta                 spin up a rosetta server
```
This removes the duplication.
=> fix: remove duplicate cli cmd entries

app/upgrades/v21/upgrades.go
Closes: #XXX
The min deposit ratio needs to be manually set in the upgrade handler. This was found in v0.47 unfork testing.
=> fix: v21 upgrade min dep ratio set

go.mod, go.sum, tests/cl-genesis-positions/go.mod, tests/cl-genesis-positions/go.sum, tests/cl-go-client/go.mod, tests/cl-go-client/go.sum, x/epochs/go.mod
Closes: #XXX
E2E is not compiling from this upgrade. It works locally, but I don't think the overhead of understanding what is going on is worth the time, so just reverting it.
=> fix: revert pfm from 7.1.2 to 7.1.1

x/cosmwasmpool/client/query_proto_wrap.go
Closes: #XXX
Noticed in unfork QA, we left out the codeID in the response of querying `ContractInfoByPoolId`
=> fix(cwpool): add code id in query

app/app.go, go.mod, go.sum, ingest/sqs/chain_info/ingester/redis/chain_info_ingester.go, ingest/sqs/chain_info/repository/redis/redis_chain_info_repository.go, ingest/sqs/chain_info/usecase/chain_info_usecase.go, ingest/sqs/domain/mvc/chainInfo.go, ingest/sqs/ingester.go, ingest/sqs/sidecar_query_server.go, ingest/sqs/system/delivery/http/system_http_handler.go, x/mint/keeper/hooks_test.go
Closes: #XXX
Adds healthcheck endpoint that returns the following:
- grpc Gateway status: Pings the status endpoint of the provided endpoint (address + port) returns down when status endpoint is unreachable
-  lastestHeight status: checks and returns if redis is synced to latest height of the chain
- Redis status: checks and returns redis status
WIP
=> Add healthcheck endpoint to sqs 

CHANGELOG.md, x/valset-pref/validator_set.go
Closes: #XXX
Withdraw rewards in valset was utilizing the valset as the source of truth, while the UI displays all pending rewards. This changes the withdraw rewards method to consider all validators the user is delegated to, instead of strictly the validator set pref.
=> fix(valset): withdraw rewards

ingest/sqs/middleware/middleware.go, ingest/sqs/router/delivery/http/router_handler.go
Closes: #XXX
Implements a prometheus counter and a histogram that allows computing all of the values listed here in Grafana:
https://app.clickup.com/37420681/v/dc/13nzm9-25273/13nzm9-51693
From the histogram, we can get the average request time and RPS.
By having labels, we can plot counters for each endpoint.
Removing latency logs since we don't need them anymore (replaced by metrics)
Tested on node.
=> feat(SQS): prometheus metrics for latency and rps

ingest/sqs/system/delivery/http/system_http_handler.go
Closes: #XXX
Changes to return 501 upon node not being synced for `GetHealthStatus` Endpoint so that load balancers can properly remove unsynchronized nodes from rotation.
=> (SQS) Return 501 upon node not being synced

.vscode/launch.json, ingest/sqs/chain_info/repository/redis/redis_chain_info_repository.go, ingest/sqs/chain_info/usecase/chain_info_usecase.go, ingest/sqs/domain/errors.go, ingest/sqs/domain/mvc/chainInfo.go, ingest/sqs/system/delivery/http/system_http_handler.go
Closes: #XXX
This PR improves the `/healthcheck` endpoint with the following:
- fails if the node is still synching
- fails if the height has not been updated for more than 30 seconds. This can happen if the node goes into endless peering.
Tested locally against v20 mainnet
=> refactor(SQS): improve healthcheck

.github/workflows/labeler.yml
This reverts commit 622f7e9e5324ffb9332a3b006f17c43f40307af2.
Closes: #XXX
https://github.com/osmosis-labs/osmosis/pull/6997 breaks labeler CI: https://github.com/osmosis-labs/osmosis/pull/7002
We need to update https://github.com/osmosis-labs/osmosis/blob/main/.github/labeler.yml to adhere to the new format. Reverting for now.
Breakage: https://github.com/osmosis-labs/osmosis/actions/runs/7097421984/job/19337031693?pr=7002
=> Revert "chore(deps): bump actions/labeler from 4.3.0 to 5.0.0 (#6997)"

app/app.go, app/keepers/keepers.go, app/modules.go, app/upgrades/v21/upgrades.go, wasmbinding/test/messages_test.go, x/gamm/keeper/gas_test.go
Closes: #XXX
Found by @mattverse, we need to continue referencing bank as a pointer due to it's use in hooks.
I also modified ConsensusParamsKeeper to do the same, although I don't think its required.
Need follow on PR to address testing
=> fix: use pointers for bank and consensus

ingest/sqs/chain_info/usecase/chain_info_usecase.go
Closes: #XXX
Was caught in chaos testing with @gzukel .
Erroring in the case where there is no last update time present would cause instabilities with the healthcheck.
Returning the latest observed height in such a case should make the healthcheck more robust
Tested by chaos testing
=> fix(SQS): healtcheck returning 200 due to time update not present

go.mod, ingest/sqs/chain_info/repository/redis/redis_chain_info_repository.go, ingest/sqs/domain/json/sqs_json.go, ingest/sqs/domain/router.go, ingest/sqs/pools/repository/redis/redis_pools_repository.go, ingest/sqs/router/repository/redis/redis_router_repository.go, ingest/sqs/router/usecase/routertesting/parsing/mainnet_pools.go, ingest/sqs/router/usecase/routertesting/parsing/mainnet_pools_test.go, ingest/sqs/system/delivery/http/system_http_handler.go, ingest/sqs/tokens/usecase/tokens_usecase.go
Closes: #XXX
Based on profiling, JSON unmarshaling is a big bottleneck in SQS. Accordingly, we switch the library to a more performant one - https://github.com/json-iterator/go
Based on the new profile, the overall share of the unmarshaling is not as large as before.
Additionally, load testing shows an improvement.
Old load testing:
New load testing:
Old profile (incomplete):
New profile:
=> refactor(SQS): switch to a more performant JSON lib

.github/workflows/e2e-full.yml, .github/workflows/test.yml
Closes: #XXX
I didn't notice this on main, but the v21.x branch was building without the excludeIncrement tag in CI. I looked into it and this is because the Build e2e image step isn't explicit with this. I already patched this on v21.x via my last backport, but thought this should probably be on main too.
=> fix: add build tag to CI job

Dockerfile
This PR fixes the alpine image usage in the builder step of the Dockerfile.
Run:
```bash
make docker-build-alpine
```
=> Pin alpine version in docker builder image

cmd/osmosisd/cmd/root.go, ingest/sqs/README.md, ingest/sqs/domain/mvc/router.go, ingest/sqs/domain/router.go, ingest/sqs/ingester.go, ingest/sqs/router/delivery/http/router_handler.go, ingest/sqs/router/repository/redis/redis_router_repository.go, ingest/sqs/router/usecase/router_usecase.go, ingest/sqs/sidecar_query_server.go, ingest/sqs/sqs_config.go
Closes: #XXX
This PR focuses on the following:
- stops clearing cache on every block. Instead, any updates will simply be overwritten. Additionally, routes are to be expired every 10 minutes and recomputed on demand.
- Now, routes are persisted across blocks and only recomputed when expired in Redis
- Adds the config to tweak the expiry
- Adds query for cached routes
Th infrastructure configuration is updated: https://github.com/osmosis-labs/osmosis/pull/7061
- Manually tested
- Ran pools comparison CI: https://github.com/osmosis-labs/infrastructure/actions/runs/7160319038/job/19494559775
- Load tested and saw no performance degradation but also no improvement. The improvement will come once I add the ability to persist optimal routes in subsequent PR. The goal of this is to minimize the …
=> feat: avoid clearing route cache every block; cache expiry; query for cached routes

.vscode/launch.json, ingest/sqs/router/README.md, ingest/sqs/router/usecase/export_test.go, ingest/sqs/router/usecase/optimized_routes.go, ingest/sqs/router/usecase/optimized_routes_test.go, ingest/sqs/router/usecase/router_usecase.go
Closes: #XXX
This is a refactor to support future improvements of routes caching.
The end goal is to cache ranked routes for each order of magnitude of token in for a given denom in and denom out.
This refactor enables integrating this cache once implemented.
Additionally, it cleans up some mainnet state tests.
=> refactor/test: prepare for ranked route caching; clean up mainnet tests

x/poolmanager/taker_fee.go, x/protorev/keeper/rebalance.go
Looking at the IAVL v2 benchmarks, loading params for taker fees _somewhat_ appears to be a 2% CPU consumption for the entire state machine. (Its a bit hard to reliably tell, since I don't have the binary for better views)
This PR anyways stops loading all of the params, and thereby should improve CPU / native speed, and will improve gas.
Validity of this change should be covered by default taker fee already being tested
=> Don't load all poolmanager params every swap

x/incentives/keeper/distribute.go, x/lockup/types/lock.go
Some state compatible speedups for lowering Epoch CPU usage!
- Removes an expensive log line for every single lock
- Removes two Heap allocations from the core loop taking CPU time here
Its not the easiest to gather quite what the speedup percentage for the whole system is, and not even for CPU time as a whole. It seems minor, e.g. I'd expect this to be shaving like 500ms off epoch, but could be more impactful. Very not simple to tell.
=> Lower Epoch CPU usage

ingest/sqs/router/usecase/export_test.go, ingest/sqs/router/usecase/optimized_routes_test.go, ingest/sqs/router/usecase/router_usecase.go, ingest/sqs/router/usecase/router_usecase_test.go
Closes: #XXX
Filters out duplicate pool ID routes that have been causing lower quality split quotes due to SQS not accounting for state updates.
Before:
After:
- Added unit test
- Manual test on dev node
=> refactor(SQS): filter out duplicate pool ID routes

CHANGELOG.md, x/incentives/keeper/distribute.go, x/incentives/keeper/iterator.go
The IAVL v2 benchmarks were showing Memory allocation as a significant chunk of the CPU time. (NOTE: CacheKV and DB overheads that are mainly applying to us in production are not shown in these benchmarks)
So looking at golang code, the capacity of a large slice grows by a factor of `1.25` every grow. So in the case where this is full / near full (most of the time), this would grow 3 or 4 times. `1.25**3 = 1.95`, which involves expensive memcopies on top of extra allocations.
Hence this speeds up the relevant logic.
From the IAVL v2 benchmarks, this is ~30% of the CPU time of the Distribute function!
=> x/incentives: Lower Epoch allocation overhead

.github/workflows/e2e-full.yml, .github/workflows/test.yml, Dockerfile, scripts/makefiles/e2e.mk
Closes: #XXX
Ironically, cache was increasing our run times by almost 3 minutes. The cache needs to get reset on essentially every commit, so caching this doesn't make much sense in the first place (maybe cache the parts that don't change like wasmvm DL but that is another conversation).
This removes the cache.
=> perf: remove cache e2e

CHANGELOG.md, osmomath/decimal.go
State compatible logic to speedup the Log base 2 code, which appears in TWAPs.
This causes CPU usage for many wasm contracts, and EndBlock in updating TWAPs. Will further work to having this get computed when interpolating records for arithmetic TWAPs.
This PR takes the log2 code on my machine from:
```
BenchmarkLog2-12              7803            261769 ns/op           85620 B/op       1641 allocs/op
```
to
```
BenchmarkLog2-12    	    9193	    143944 ns/op	   43454 B/op	     605 allocs/op
```
So almost halving the CPU time, halving the I/O writes, and drastically reducing the number of allocs!
Not seeing any other obvious wins, beyond changing data type/algorithm as the bottleneck is now mulmut
=> Speedup log2 code

go.mod, go.sum
Closes: #XXX
-  v18.x of viper isn't compatible with our node
See:
- https://github.com/spf13/viper/releases
The issue stems from here:
- https://github.com/cosmos/cosmos-sdk/blob/main/server/util.go#L294-L296
on main
- `make install`
- `osmosisd init hope`
on this branch
- `make install`
- `osmosisd init hope`
=> chore: fix viper

Makefile, app/keepers/authz.go, app/upgrades/v21/constants.go, app/upgrades/v21/upgrades.go, app/upgrades/v22/contants.go, app/upgrades/v22/upgrades.go
Closes: #XXX
I took some time to debug the e2e tests on the `feat/smart-accounts` branch. Some points of note:
1. When running the e2e tests locally with the following command `make test-e2e-debug` the IBC tests & the UPGRADE tests must be set to run otherwise the environment is not setup correctly and the tests fail early. I'm assuming this is a separate/known issue with the e2e tests? @ValarDragon 
2. I have added the boilerplate v22 upgrade directory but this is not functional at present. In order to show the tests are passing I'm adding the authenticator module to our v21 upgrade code for now. When running the tests against the v22 upgrade code we run into the following error: @PaddyMc @ValarDragon @nicolaslara  I'm assuming this is a slight configuration issue?
```
failed to load …
```
=> fix: e2e tests for smart accounts

x/gamm/client/cli/query.go
This pr fixed the duplicate subcommand `osmosisd query gamm pool`
This change is already covered by existing tests, such as *TestQueryTestSuite*.
=> fix(x/gamm): remove duplicate `query gamm pool` subcommand

ingest/sqs/router/usecase/pools/routable_transmuter_pool.go, osmoutils/coin_helper.go, x/cosmwasmpool/model/pool.go, x/gamm/keeper/pool.go, x/gamm/pool-models/balancer/pool.go, x/gamm/pool-models/stableswap/pool.go, x/gamm/simulation/sim_msgs.go, x/twap/listeners_test.go, x/twap/logic_test.go
Complete TODO of `CoinsDenoms`. I have replaced all reference using with `coins.Denoms()`
```go
// TODO: Get this into the SDK https://github.com/cosmos/cosmos-sdk/issues/12538
func CoinsDenoms(coins sdk.Coins) []string {
denoms := make([]string, len(coins))
for i, coin := range coins {
denoms[i] = coin.Denom
}
return denoms
}
```
=> refactor: using coins.Denoms() from sdk instead of osmoutils

osmomath/binary_search.go, x/gamm/pool-models/stableswap/amm.go
Make more components of the stableswap math faster / less heap intensive. 
Pretty low magnitude win right now. (At best 5 seconds in a 20000 block sync, likely lower)
=> More stableswap mutative operations

CHANGELOG.md, osmoutils/cache_ctx.go
As of SDK unfork, we are double emitting events in CacheCtx.Write() for ApplyFuncIfNoError(). We fixed that the SDK didn't write these events in SDK v0.45. (We couldn't do it in the SDK, as that behavior would interfere with IBC. We tried!)
So we now remove our workaround here.
This is state compatible as it only affects events.
=> Stop double emitting events for CacheCtx.Write()

cmd/osmosisd/cmd/change_environment.go, cmd/osmosisd/cmd/root.go, scripts/makefiles/localnet.mk
Closes: #XXX
Fixes localosmosis and `app.toml` generation
There were two problems:
1. Using environment name `localosmosis` as opposed to path `$HOME/.osmosisd-local` for config path
2. Broken `app.toml` config due to SQS
This fixes both issues and allows localosmosis to work
Tested locally
=> refactor: fix localosmosis and config generation in app.toml

x/txfees/keeper/mempool-1559/code.go
This PR updates mempool 1559 params to update a little slower. Its reasoned about, due to low gas usage txs on mainnet being observed to be around 30M gas, so were not lowering fast enough, and were spiking too fast.
As a comparable ETH block time (15s) is 2.5x slower than us, and they update at a maximum +- of 12.5%. Under spam we are currently updating at `(1 + (50/70)/10)**2.5 = 18.8%` upwards. We currently update at 0% usage for 15 seconds at -23%. However we do not see 0% usage, we instead see usage around 20-40M, so lets say 30M. That puts us at `(1 + (-40/70)/10)**2.5 = -13.7%` . 
So we see this asymmetrical upwards increase in our real settings. Lets assume that 30M is userflow/relayers, who are getting inputted Keplr's much higher gas numbers.
I suggest changing this target block …
=> Update mempool 1559 params

CHANGELOG.md, x/lockup/types/lock.go
State compatible speedups to SumLocksByDenom code.
I expect this to reduce epoch CPU time by 4 seconds. (maybe a bit more with garbage collector reductions)
This entire for loop should later get eliminated with #7119, but that can come later / after being more certain around state compat.
=> Speedup SumLocksByDenom

x/incentives/keeper/distribute.go
Speeds up the core loop of the epoch.
- Removes coins.Sort() which actually creates a copy of the slice due to complex runtime reasons.
- Removes AmountOfNoDenomValidation runtime eq checks
- Removes allocations in the Quo operation
This is an expected 7 second CPU time speedup on the Epoch code.
=> Speedup core loop of epoch

.vscode/launch.json, CHANGELOG.md, cmd/osmosisd/cmd/init.go, cmd/osmosisd/cmd/root.go
Closes: #XXX
Faster block times are desired. As a result, we lower the commit timeout from 5s to 4s.
Additionally, we overwrite the existing config.toml values when the binary is used.
While working on this, found unrelated bug during `osmosisd init`: https://github.com/osmosis-labs/osmosis/issues/7179
Tested:
`osmosisd init test`
`osmosisd start`
`osmosisd init test --home=custom`
`osmosisd start test --home=custom`
=> refactor: auto-set timeout-commit to 4s for faster block times

x/incentives/keeper/distribute.go, x/incentives/keeper/iterator.go, x/incentives/keeper/iterator_test.go, x/lockup/types/lock.go
Closes: #XXX
This speeds up epoch by avoiding copying stemming from period locks
New:
Old:
Synched over epoch + 150 blocks.
=> perf: avoid copy of period locks in epoch

x/poolmanager/types/keys.go, x/poolmanager/types/keys_test.go, x/twap/types/keys.go
Reduce some sprintf overheads
This is a pretty micro-optimization. It likely has more impact for txs than epoch. In epoch it shaves like 100ms (there are way better things to shave time on there)
=> Reduce sprintf overhead in code showing up during sync profiles

.vscode/launch.json, x/txfees/keeper/txfee_filters/arb_tx.go, x/txfees/keeper/txfee_filters/arb_tx_test.go
Closes: #XXX
Detect this: https://celatone.osmosis.zone/osmosis-1/txs/8D20755D4E009CB72C763963A76886BCCCC5C2EBFC3F57266332710216A0D10D
=> refactor: arb filter for new authz exec swap

CHANGELOG.md, x/poolmanager/create_pool.go, x/poolmanager/types/pool.go
makes a maximum pool ID of 100 billion - 1
This lets us make allocations for certain keys more efficient, that legacy use string formatting instead of uint64 representation.
At $1 to create a pool, this costs too much to ever be an issue. Let alone the $10 to $100 range governance currently seems to be in the mind of.
=> Add maximum pool ID

x/incentives/keeper/distribute.go, x/incentives/keeper/iterator.go, x/incentives/keeper/iterator_test.go
Re-use a slice to save on allocations.
Tested for state compatability on mainnet
=> x/epochs: Use a scratch slice to reduce epoch allocations

CHANGELOG.md, cmd/osmosisd/cmd/root.go
Closes: #XXX
Previous PR that created config overwrite caused `app.toml` values being dropped when starting up `osmosisd`. This PR fixes the issue by creating a new viper copy that loads the `config.toml` values while preserving the original contents.
Tested locally
=> fix: config overwrite ignores app.toml values

CHANGELOG.md, cmd/osmosisd/cmd/root.go
Closes: #XXX
Backporting https://github.com/osmosis-labs/osmosis/pull/7233
=> fix: backport config overwrite fix to v21.x

ingest/sqs/chain_info/repository/redis/redis_chain_info_repository.go, ingest/sqs/chain_info/usecase/chain_info_usecase.go, ingest/sqs/domain/mvc/chainInfo.go
Closes: #XXX
Sometimes the node gets stuck and does not make progress.
However, it returns 200 OK for the status endpoint and claims to be not catching up.
This has caused the healthcheck to pass with false positives in production.
As a result, we need to keep track of the last seen height and time to ensure that the height is
updated within a reasonable time frame.
Will test in stage
=> fix(SQS): healthcheck false positive when node is stuck

CHANGELOG.md, cmd/osmosisd/cmd/root.go
Closes: #XXX
This PR fixes bug where osmosisd fails with non-zero code if fails to overwrite the file due to permissions:
https://github.com/cometbft/cometbft/blob/fe45483be36ebfea7e172a3ad949e8fe09a8fd95/libs/os/os.go#L83
=> fix: config overwrite fails with exit code 1 if wrong permissions

CHANGELOG.md, app/keepers/keepers.go
Update the metadata length to 10200, to enable longer summaries and titles for gov proposals
see:
https://github.com/osmosis-labs/cosmos-sdk/blob/osmo/v0.47.5/x/gov/keeper/proposal.go#L17-L32
&&
https://github.com/osmosis-labs/cosmos-sdk/blob/osmo/v0.47.5/x/gov/keeper/keeper.go#L222-L229
- start a node and submit a gov transaction with longer metadata
```bash
BASE64_METADATA=$(echo -n '{
"authors": [""],
"details": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa …
```
=> chore: update gov metadata length from 256 to 10200

tests/e2e/configurer/chain/chain.go, tests/e2e/configurer/config/constants.go, tests/e2e/containers/config.go
Closes: #XXX
Two required changes:
1. Pre v21, our pre upgrade logic expected slow blocks, and post upgrade had fast blocks. Now, both pre and post upgrade have fast blocks. This logic requires the image to be built with the ignoreSequence tag, otherwise the tx spam causes the e2e suite to get caught up. I manually built a v21.2.1 image with the tag, uploaded to docker up, and changed here.
2. Because blocks are faster, the upgrade handler was not getting triggered due to miscalculation of how long 1 block was equal to. This sets the upgrade block height large enough to allow for a full gov cycle.
=> e2e: use new image and extend blocks for upgrade

.github/workflows/go-mod-auto-bump.yml, scripts/update-go-mod.sh
Closes: #XXX
Right now, we have an action we manually trigger by putting in a branch, and github will update the osmosis related go mods of every occurrence of those dependencies. 
The issue is, even if this action is run on, say v21.x, it will use the dependencies from main.
What this change does is, it uses the dependencies on whatever branch the action is being called on, which is (in my opinion) the desired behavior.
=> fix: go mod update action targets branch it is called on

CHANGELOG.md, x/concentrated-liquidity/pool.go, x/concentrated-liquidity/swaps.go
Speedup the CL check for if a pool is initialized.
Right now we do a very expensive iterator call. This technically saves gas for user swaps, but this is really small (at not all commensurate with the CPU costs it induces)
More pressingly, this is a notable delay to block processing time, due to occurrence in:
- Protorev (iterators always hit IAVL right now)
- TWAP
- Swaps
Notice that SpotPrice is 0 iff there is no position in the pool. You can convince yourself of this by looking at:
- AddPosition: https://github.com/osmosis-labs/osmosis/blob/dev/speedup_cl_spotprice_and_swap/x/concentrated-liquidity/lp.go#L110-L116
- InitializeLogic: https://github.com/osmosis-labs/osmosis/blob/dev/speedup_cl_spotprice_and_swap/x/concentrated-liquidity/lp.go#L558
- Withdraw Position: …
=> Speedup CL spot price check and swap by removing an iterator

CHANGELOG.md, x/poolmanager/taker_fee.go
Currently chargeTakerFee is expensively loading all the pool manager params. This lowers what it loads to be the minimum amount (which may still be too large in general) but should lower costs a bit.
This reduces gas costs by at least 10k gas per swap, potentially more.
Speedup `chargeTakerFee` which is too gas expensive and CPU intense. We need to further revisit this later, though these terms may be less bad after the fee tracker changes. (This, plus the fee tracker changes has the potential to 5x reduce this overhead. Not expecting it to be _that_ good though, and still think this needs rethinking)
This should be covered by existing tests
=> Reduce taker fee param loading

CHANGELOG.md, app/keepers/keepers.go, x/txfees/keeper/feetokens.go, x/txfees/keeper/feetokens_test.go, x/txfees/keeper/keeper.go, x/txfees/types/expected_keepers.go
Closes: #https://github.com/osmosis-labs/osmosis/issues/6783
Previously CL pools were not supported in tx fee module, as we were calculated sp via gamm keeper. 
This PR changes it to use pool manager keeper instead for sp calculation
=> Support CL pools in TX Fee module

x/cosmwasmpool/model/pool_test.go
Closes: #XXX
Expand test to make sure that gas charged before and after calling the relevant method is not dropped
=> test: gas charge for the Query method

CHANGELOG.md, x/txfees/types/options.go
With the raise of block gas to 300M, these can be relaxed, and will solve some integrator pain.
=> Raise mempool config gas per tx's defaults

x/concentrated-liquidity/total_liquidity.go, x/cosmwasmpool/pool_module.go
Closes: #XXX
CW pools don't always return coins in a sorted list. When adding a non sorted list of coins, the method panics. This is a quick fix. Tested on private testnet and it works now.
=> fix: total liquidity query

tests/e2e/e2e_test.go
Closes: #XXX
Makes E2E no longer run in parallel. This is temporary while we address the more important performance issues.
=> chore: e2e non parallel

CHANGELOG.md, go.mod, go.sum, osmoutils/go.mod, osmoutils/go.sum, x/epochs/go.mod, x/epochs/go.sum, x/ibc-hooks/go.mod, x/ibc-hooks/go.sum
Closes: #XXX
As per CWA-2023-004, bump wasmvm version from v1.5.0 to v1.5.1
=> fix: update wasm vm as per CWA-2023-004

go.mod
Closes: #XXX
Updating SQS dependency with the most recent changes.
In particulate, it fixes the key separator issue that overlapped with tokenfactory denom key separator.
Tested on local node in testnet environment
=> fix: update sqsdomain dep with taker fee key separator fix

ingest/sqs/pools/ingester/pool_ingester.go
Closes: #XXX
Pools sometimes have garbage tokens in balances. We need to filter them out for convenience in SQS.
=> fix: remove tokens from balances that are not in the pool

CHANGELOG.md, cmd/osmosisd/cmd/stargate-query.go, wasmbinding/export_test.go, wasmbinding/query_plugin.go, wasmbinding/stargate_whitelist.go
Closes: #XXX
This PR uses a sync pool to unmarshal responses of protobuf objects in stargate queries.
We were previously utilizing pointers, which under heavy load can result in nondeterminism.
This code was backported to v21 and tested against mainnet.
Previously, we were able to app hash nodes within 10 minutes of spam. With this change, the node has been running for 1 hour with no issues.
=> fix(StargateQueries): use a sync pool when unmarshalling responses of protobuf objects 

.github/workflows/build.yml, Dockerfile
Improve build CI to read version from `go.mod` rather than hardcoding it
=> [Fix 🔨] Use go mod in build ci

Makefile, scripts/hooks/pre-commit.sh, scripts/makefiles/lint.mk
Similar to [cosmos/cosmos-sdk#19075](https://github.com/cosmos/cosmos-sdk/pull/19075)
We often forget to run lint or check the result of linting before we push the commits
This pr adds a git pre-commit hook for linting new changes code, this will prevent contributors from pushing their commits without linting, and reduce the times of re-run ci.
After you clone the repository, just simply run `make setup-pre-commit`
=> chore(Makefile): add `setup-pre-commit` target to init git hook

CHANGELOG.md, x/gamm/types/gov.go
Closes: #XXX
*(or)*
*(or)*
*(example:)*
=> fix: Update gov type for Set-Scaling-Factor

x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/incentives.go, x/concentrated-liquidity/incentives_test.go, x/concentrated-liquidity/types/events.go
Closes: #XXX
This PR shows that there is a chance of incentives being truncated due to large liquidity value.
We observed this in pool 1423 where both tokens have 18 decimal precision.
In such a case, the incentive record is updated correctly, not the global pool accumulator. The reason the pool accumulator is not updated is that it is a per unit of liquidity value (divided by liquidity). This division leads to truncation to zero.
It has been determined that no funds are at risk. The incentives are eventually distributed if either:
a) A long time without an update to the pool state occurs (at least 51 minutes with the current pool setup configuration)
b) Current tick liquidity becomes smaller
We confirmed that other pools are highly unlikely to be affected by setting a breakpoint with a …
=> test/feat: incentive accumulator truncation

x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/incentives.go, x/concentrated-liquidity/swaps.go, x/concentrated-liquidity/types/events.go
Closes: #XXX
Would like to set up telemetry detecting spread factor truncation for further analysis
=> feat: telemetry for spread factor truncation

x/protorev/keeper/rebalance.go
Closes: #XXX
This error log pops up many times on all nodes. It is normal for this to occur, and should instead be only shown in debug logs.
=> chore(protorev): change error log to debug

x/incentives/keeper/distribute.go, x/superfluid/keeper/epoch.go, x/superfluid/keeper/epoch_test.go, x/superfluid/keeper/hooks.go, x/superfluid/keeper/stake.go, x/superfluid/keeper/stake_test.go
State compatibly de-duplicate get intermediate account fetches. On its own, this isn't much of a savings (20ms with and w/o fast nodes -- not sure why theres cache hits in IAVL v1 and fast nodes off TBH). The hope is that this can be used with an additional filter to cheapen more expensive loops going on in both methods. The latter may not be state compatible, hence making two PR's.
This also removes getting the BondDenom from the core loop, saving another 60ms
=> De-duplicate fetching intermediate accounts

x/superfluid/keeper/epoch.go
This PR removes an unneeded balance fetch if there is no delegation for a superfluid intermediary account. Its not-obvious to be fully sure of time savings, but it currently appears that removing this second ApplyFuncIfNoError, and skipping the balance check should be saving us ~700ms in IAVL v1 no fast nodes, and 150ms in IAVL v0. (This data should be in the parent CacheCtx, as its sent tokens in withdraw delegation rewards for pools with superfluid delegations. So any time spent in IAVL in this Get Balance call should be what we save. This isn't true if there's simply too few rewards to distribute, but I'd hope that distribution errors in such cases, and so isn't what we see.)
This is not state compatible due to edge cases.
=> perf: Remove unneeded balance fetch in superfluid distribution

app/keepers/keepers.go
`contractKeeper` is nil when `CosmWasmAuthenticator` is created, delay registering `CosmWasmAuthenticator` until `contractKeeper` is properly initialized.
=> Fix nil contractKeeper for CosmWasm authenticator

x/twap/store.go, x/twap/types/keys.go
Previously we were unmarshalling the value of all records we prune, and paying lots of time in re-formatting keys.
Instead we can gather all the data we need from the key we iterate over (and save us expensive unmarshals - .3s to .5s depending on GC). We also skip one key formatting, since thats the representation we are already iterating over (.12s to .21s depending on GC). We skip time formatting in the second key format (30ms AKA .03s) We could save more in the second key formatting w/ more code complexity.
I'd estimate we're adding .05s of overhead, which we should measure.
The net change of this should be between .42s to .72s off of epoch, and be state compatible.
IAVL v0 relevant pprof (ignore %)
IAVL v1 no fast nodes relevant pprof (ignore %)
The database I/O savings would have to …
=> Speedup TWAP pruning logic

x/incentives/keeper/distribute.go, x/lockup/types/lock.go
This PR moves the `err := checkBigInt(amtIntBi)` check from a hot loop, into one-time checking it on LockSum and noticing that it implies consistency that the hot loop is safe.
Nicely I noticed that we can also use len(bi.Bits()) instead of .BitLen() which saves a lot of CPU time. If we get this into the SDK, should save 1 full second off of Osmosis epoch, and speed up all math hot loops.
=> perf: Move an overflow check out of hot loop

app/upgrades/v23/upgrades.go
Closes: #XXX
This PR introduces a custom testnet migration logic to migrate all pools.
Additionally, it allows for `edgenet` chain ID for our internal testnet. It is expected to work the same as mainnet
=> chore: custom v23 upgrade logic for testnet, introduce edgenet

.github/workflows/check-state-compatibility.yml, .github/workflows/e2e-full.yml, .github/workflows/release.yml, .github/workflows/test.yml
This PR aims to enhance our CI/CD pipeline by transitioning from `self-hosted` runners to `buildjet` runners.
It also add the following minor improvements include:
- **Dynamic GO Version Configuration**: Eliminate the hardcoding of the `GO_VERSION` variable. Previously configured as:
```yaml
- name: 🐿 Setup Golang
uses: actions/setup-go@v5
with:
go-version: ${{env.GO_VERSION}}
```
Now, the Go version is dynamically determined from the `go.mod` file, ensuring consistency with our project's requirements:
```yaml
- name: 🐿 Setup Golang
uses: actions/setup-go@v5
with:
go-version-file: go.mod
```
- **Action Updates**: Upgraded certain actions to their latest versions.
Additionally, this PR changes the formatting to improve readability
This has been tested in …
=> Add buildjet runners

tests/e2e/e2e_test.go
Closes: #XXX
Adds back concurrency, bringing execution time down from 9m to 7.
I have run it 12 times in a row and it has passed every time.
=> chore: add back parallel e2e

app/app.go
Closes: #XXX
Noticed in testing that after epoch, the old validators would repopulate. The chain still ran because our validator has majority power, but caused longer blocks due to waiting for validators to time out. This removes the last two store entries for validators that were missed.
Tested in v23 testing.
=> fix: remove all vals from testnet state

tests/e2e/initialization/config.go
Closes: #XXX
When testing v23 > v24 e2e, I saw that v23 initialization was panicking due to a zero time value for InternalUptime. This starts by setting all defaults, and then overrides the one param required. 
Built image locally, tested and it works.
=> fix: e2e init genesis default values for uptime incentives

x/incentives/client/cli/tx.go, x/incentives/types/msgs.go
Closes: #XXX
This PR fixes a `create-gauge` CLI issue that initialized the `duration` field to `NoLock` gauges to 0. It also removes the `ValidateBasic` check that prevents nonzero durations from being set on `NoLock` guages, which somehow slipped through even though it was flagged in an earlier issue.
The changes will be manually QA'd on localosmosis/edgenet
=> [fix]: Fix gauge CLI and `ValidateBasic` to work with uptimes

app/app.go
Closes: #XXX
When using the latest height for the upgrade, there is a panic right after the upgrade is applied due to having Comet votes for previous block from many validators.
As a result, we should run with modified state for a few blocks before actually applying the upgrade
=> fix: upgrades for in-place testnet

x/protorev/keeper/rebalance.go
Really minor (only because protorev is dominated by wasted CL iterators) speedup to protorev's binary search, by removing two extra heap allocs per hot loop.
=> Minor protorev allocation speedup

x/poolmanager/taker_fee.go, x/poolmanager/types/keys.go
A driveby fix for improving the key formatting of taker fee keys. I was surprised to see this was taking .1% of state machine exec time. (Mostly due to too many calls w/ protorev, but still shocking regardless)
This just lowers the heap allocs here.
=> [performance]: Better key formatting in taker fee

x/protorev/keeper/routes.go
We were spending about .5% of state machine processing time on double-unmarshalling pools, during protorev route building. (In a 500 block sync, this was costing us 1.3 seconds)
We need a better solution for overall reducing the number of wasted unmarshals -- we will still be doing a lot, and this is a general theme of where our wasted blocksync time is going. However this gives us an easy 1.3 seconds back.
=> [perf]: Stop double-unmarshalling pools in protorev route building

CHANGELOG.md, x/concentrated-liquidity/lp.go
This removes one unneeded iterator call in CL CreatePosition It removes two unneeded iterator calls in CL addToPosition
This appears to be an approximately 10% speedup to both operations. (.2% impact to state machine processing time)
This is the same idea as #7258 and should be covered by existing tests. I left a code comment for why we can't do this same idea to WithdrawPosition.
=> Remove iterator calls in two CL operations

x/concentrated-liquidity/incentives.go
Very minor performance improvement. This was mostly to get the code comment for this off my local machine / not conflate things in an upcoming PR for #7536
=> Use some more mutative operations in uptime accumulator operations

osmomath/decimal.go, x/concentrated-liquidity/math/tick.go
Some quick speedups to CL's TickToPrice and PriceToTick. We need to update the osmomath version to get the more significant speedups in backports.
=> Speedup CL: TickToPrice

x/txfees/keeper/feedecorator.go, x/txfees/keeper/feetokens.go
Pretty minor speedups to txfees. This is taking a pretty small amount of time in profiles, but driveby noticed it, hence PR'ing slight improvements. THere are better improvements via reducing the number of math ops in a state breaking change, which we should eventually do.
Also made some slight speedups to relevant ops in upstream SDK, which we should get on next math version bump. (https://github.com/cosmos/cosmos-sdk/pull/19467, https://github.com/cosmos/cosmos-sdk/pull/19466)
=> Minor state compatible speedups to txfees

osmomath/decimal.go
State compatible, minor, speedups to BigDec.
Analogues of these SDK PR's: https://github.com/cosmos/cosmos-sdk/pull/19466 https://github.com/cosmos/cosmos-sdk/pull/19467
=> Minor bigdec speedups

x/superfluid/keeper/epoch.go
Closes: #XXX
There was likely an issue with mergify, we got rid of the nil return in the sf epoch hook that silences the error logs and instead emits a debug log.
It is in main, however, due to a different fix that Dev merged.
=> fix: superfluid error log suppression

CHANGELOG.md, x/poolmanager/router.go, x/protorev/keeper/rebalance.go, x/protorev/types/expected_keepers.go
Closes: #7521  
Removes taker fee from protorev swap estimation code, improving speed and correctness.
This difference is not really covered by tests right now. I could write new tests, but seems advisable to wait until #7555.
=> perf: Remove TakerFee from protorev estimation

x/gamm/keeper/pool_service.go
Closes: #XXX
This log is spam and does not to notify all node operators of it's occurrence.
=> chore: move JoinPoolNoSwap error log to debug

.github/mergify.yml
Closes: #XXX
For just this release, we are maintaining two separate branches; one for v23 and one for v23 with IAVL v1. Then in v24, IAVL v1 will be mandatory. This backport label will help with keeping the branches in sync
=> chore: add mergify for iavl v1 branch of v23.x

CHANGELOG.md, go.mod, go.sum, osmomath/go.mod, osmomath/go.sum, osmoutils/accum/accum_test.go, osmoutils/go.mod, osmoutils/go.sum, osmoutils/sumtree/legacy/v101/tree_test.go, osmoutils/sumtree/tree_test.go, osmoutils/wrapper/tmdb.go, x/epochs/go.mod, x/epochs/go.sum, x/ibc-hooks/go.mod, x/ibc-hooks/go.sum
Closes: #XXX
Backport only to v23.x-iavl-v1, close PR for v23.x once this is merged
=> feat: iavl v1

go.mod, go.sum, osmomath/go.mod, osmomath/go.sum, osmoutils/accum/accum_test.go, osmoutils/go.mod, osmoutils/go.sum, osmoutils/sumtree/legacy/v101/tree_test.go, osmoutils/sumtree/tree_test.go, osmoutils/wrapper/tmdb.go, x/epochs/go.mod, x/epochs/go.sum, x/ibc-hooks/go.mod, x/ibc-hooks/go.sum
Closes: #XXX
Bumps IAVL version, which fixes IAVL grow issue.
When backporting, close PR to v23.x and only backport to v23.x-iavl-v1
=> fix: iavl grow

CHANGELOG.md, x/cosmwasmpool/client/cli/tx.go
Closes: #XXX
The CLI logic did not allow providing only one of code ID and bytecode but the state-machine logic required only one to be set.
https://testnet.mintscan.io/osmosis-testnet/proposals/176
=> fix: cw pool migration prop

go.mod, go.sum, osmomath/decimal.go, osmomath/decimal_test.go, osmomath/rounding_direction.go, osmomath/sqrt.go, x/concentrated-liquidity/fuzz_test.go, x/concentrated-liquidity/lp.go, x/concentrated-liquidity/lp_test.go, x/concentrated-liquidity/math/math.go, x/concentrated-liquidity/math/tick.go, x/concentrated-liquidity/model/pool.go, x/concentrated-liquidity/model/pool_test.go, x/concentrated-liquidity/swapstrategy/swap_strategy.go, x/gamm/pool-models/balancer/pool.go, x/gamm/pool-models/stableswap/amm.go, x/gamm/pool-models/stableswap/pool.go
Closes: #7540 
Lower number of heap calls that appear in CL logic / math. We are removing many heap allocations by being more mutative inside of calls to `Dec()` and by introducing a new API `BigDecFromDecMut`, and using that throughout the codebase.
This is covered by existing unit tests, and the state compatability check.
=> perf: Use SDK math v1.3.0 to speedup BigDec casts to/from Dec

CHANGELOG.md, x/cosmwasmpool/gov.go, x/cosmwasmpool/gov_test.go, x/cosmwasmpool/model/pool.pb.go, x/cosmwasmpool/model/store_model.go, x/cosmwasmpool/types/pool.go
Closes: #XXX
Found when testing white whale pool migration on testnet.
We did not update the cw pool model in the state machine.
There should be no serious impact but if pools are migrated using this method today, we would have to maintain old code IDs in the whitelist until the state is fixed via the upgrade handler
- Unit tests
- Testnet
=> fix: cosmwasm pool model code ID migration

go.mod, go.sum
Backport was created before we had split v23.x
Bumps [google.golang.org/grpc](https://github.com/grpc/grpc-go) from 1.61.0 to 1.61.1.
- [Release notes](https://github.com/grpc/grpc-go/releases)
- [Commits](https://github.com/grpc/grpc-go/compare/v1.61.0...v1.61.1)
---
updated-dependencies:
- dependency-name: google.golang.org/grpc dependency-type: direct:production update-type: version-update:semver-patch ...
Closes: #XXX
*(or)*
This change is already covered by existing tests, such as *(please describe …
=> chore(deps): bump google.golang.org/grpc from 1.61.0 to 1.61.1 (#7531)

x/concentrated-liquidity/math/tick.go
This PR condenses a branched code path TickToPrice into just one code path that is more efficient. (note both paths yielded the same exact value)
=> Remove extra code path in TickToPrice

x/concentrated-liquidity/swaps.go, x/concentrated-liquidity/types/expected_keepers.go
Minor protorev speedup, by removing an AllBalances call that happens after protorev has been determined to have non-zero minimum profit.
This is a 30ms speedup on a 2000 bloc syncs in IAVL v1 nfn, so very minor. Just came across it as I am going through the logic.
=> protorev: Remove unneeded AllBalances call

x/concentrated-liquidity/swaps.go
Minor speedup to CL swaps. This is .25s on the latest IAVL v1 nfn sync
=> Minor swap speedup

CHANGELOG.md, x/concentrated-liquidity/pool.go, x/concentrated-liquidity/types/expected_keepers.go
This PR removes the remaining AllBalances call from CL, and removes it from the expected keeper. Resolves a todo from: #7605 and will improve perf / lower Gas for CL TotalPoolLiquidity calls.
=> Remove CL all balances call

CHANGELOG.md, x/concentrated-liquidity/tick.go, x/concentrated-liquidity/types/events.go
Closes: #XXX
Adding events for initializing and deinitializing ticks. This is needed by Numia for computing the APRs.
As a drive-by change, I noticed that we recomputed the spread rewards accumulators and removed the duplicate logic.
- Will run this change on a node since the beginning of v23.x once backported
=> feat: tick init/deinit for CL

CHANGELOG.md, x/concentrated-liquidity/export_test.go, x/concentrated-liquidity/incentives_test.go, x/concentrated-liquidity/keeper_test.go, x/concentrated-liquidity/lp.go, x/concentrated-liquidity/spread_rewards_test.go, x/concentrated-liquidity/tick.go, x/concentrated-liquidity/tick_test.go
Closes: #XXX
Removed duplicate CL spread factor accumulator refetch.
Note that this is already achieved by the call to this:
https://github.com/osmosis-labs/osmosis/blob/0f654ff4f02f328cf46265606b8e48576021554f/x/concentrated-liquidity/tick.go#L122
The above method does exactly the same operation as the removed logic:
https://github.com/osmosis-labs/osmosis/blob/446f987fb0410e8d0711a78b94ca88947399fd07/x/concentrated-liquidity/spread_rewards.go#L142-L149
=> refactor: remove duplicate spread factor accumulator update logic

tests/localosmosis/docker-compose.yml, tests/localosmosis/scripts/setup.sh, tests/localosmosis/state_export/Dockerfile, tests/localosmosis/state_export/docker-compose.yml, tests/localrelayer/docker-compose.yml, tests/localrelayer/scripts/setup_chain.sh
Closes: #XXX
Go is bumped to 1.21. Now local testnet uses 1.21 images as well. Changes are:
- bump go image to 1.21 in `localrelayer` and `localosmosis`
- fix dasel related issues. I'm assuming dasel related errors occured because the newer image probably installs a newer version of dasel which contains breaking changes.
- `localosmosis` runs with no issue.
- when running `localrelayer` hermes throws a transport error.  I'm not sure if this error was there in the previous versions. I'm investigating.
=> Upgrade `local(osmosis|relayer)` go images and dazel

app/keepers/keepers.go, x/authenticator/authenticator/cosmwasm.go, x/authenticator/authenticator/cosmwasm_test.go
Since transient store is removed, there is no need to copy over specific contract state anymore, hence wasm store key ref is not needed for `CosmwasmAuthenticator`
=> remove wasm store key from cosmwasm authenticator

x/twap/store.go
Closes: #XXX
We have been noticing more missed blocks directly after epoch, which is likely a result of us spreading the TWAP module pruning over the blocks after epoch rather than all at once at epoch time. This PR reduces the amount of records pruned per block from 1000 to 200. That translates to pruning 100 complete TWAP records instead of 500.
=> chore: reduce per block prune of TWAP from 1000 to 200

x/authenticator/ante/ante_test.go, x/authenticator/authenticator/composition_test.go, x/authenticator/genesis.go, x/authenticator/integration_test.go, x/authenticator/keeper/genesis_test.go, x/authenticator/keeper/keeper.go, x/authenticator/keeper/keeper_test.go, x/authenticator/keeper/msg_server.go, x/authenticator/keeper/msg_server_test.go, x/authenticator/testutils/spy_authenticator.go, x/authenticator/types/keys.go
@JoseRFelix
> By the way, can we obtain the authenticator id right after a transaction succeeds, maybe by including it in the transaction event logs? At the moment, I need to retrieve the session information separately. It would enhance the user experience if we could store it in local storage as soon as the session is created, avoiding the wait time for a query 
- unit tested on `keeper.AddAuthenticator` returning the right incremental id
- unit tested on `msgServer.AddAuthenticator` ensuring that id is emitted as an event attribute
=> [Smart Accounts] Emit authenticator id on add

x/concentrated-liquidity/math/tick.go, x/concentrated-liquidity/types/errors.go
Reduce the number of sqrt invocations in TickToSqrtPrice. Depending on the way the error goes, we save either 1 or 2 Sqrt calls (before there were always 4).
This is basic from being a binary search. We should do some analysis in the future, to remove the need from computing either boundary sqrt. I think we should be able to get away without having either, and thus just need 1 or 2 comparisons to get which partition we need to be in. (Versus our now 3-4)
=> Reduce Sqrt calls in TickToSqrtPrice

x/lockup/keeper/migration_test.go
Closes: #XXX
Rand value shouldn't be allowed to be zero. We aren't testing if we can or can't lock zero tokens here.
=> fix: prevent rand coin value from locking zero coins

x/protorev/keeper/routes.go, x/protorev/types/errors.go
Make this protorev error constant-interned.
This is a .03% speedup over last benchmark, taking a cumulative of .12s.
=> Make a protorev error a constant

x/concentrated-liquidity/swaps.go
Very small driveby improvement
=> Make one more CL operation mutative

x/authenticator/authenticator/any_of.go, x/authenticator/authenticator/composition_test.go, x/authenticator/authenticator/cosmwasm.go, x/authenticator/testutils/spy_authenticator.go
Making sure that state of sub authenticators in `anyOf` that failed gets reverted even if `anyOf` it self is passed.
This make expectation of authenticator consistent that if the authenticator returns error, it shouldn't update the store in any case rather than depending on parent authenticator result.
- unit tested in `x/authenticator/authenticator/composite_test.go`
=> [Smart Account] Revert state of failed authenticator within anyOf

osmomath/math.go, x/gamm/pool-models/balancer/amm.go, x/gamm/pool-models/balancer/constants.go, x/gamm/pool-models/balancer/pool.go
Make some more balancer Dec operations mutative.
This PR should only:
- make oneDec be a constant not created every time
- use mutative operations on internally allocated Decimals
I expect this to be an ~.05% speedup, so pretty small right now
=> Move some Balancer Dec operations to be mutative

CHANGELOG.md, x/concentrated-liquidity/genesis_test.go, x/concentrated-liquidity/incentives_test.go, x/concentrated-liquidity/keeper_test.go, x/concentrated-liquidity/msg_server_test.go, x/concentrated-liquidity/types/constants.go, x/incentives/keeper/distribute_test.go
This reverts commit f4c546c2b184c9b7843e836655e1c7c388733c34.
Backport of #7651 to v24.x, I forgot to add the backport action to github so doing this manually, it's added now so shouldn't have to worry about this after this PR
=> Revert "perf: reduce supported uptimes (#7651)" (backport #7766)

.github/workflows/push-docker-images.yml
This PR modifies the CI for pushing Docker images to trigger when a `vX.Y.Z-iavl-v1` tag is pushed. To implement this, I added another job that specifically handles cases where `iavl-v1` is present in the tag. The execution of a particular job is determined by the presence of `iavl` in the tag.
```yaml
jobs:
push-docker-images:
runs-on: buildjet-4vcpu-ubuntu-2204
if: ${{ !contains(github.ref_name, 'iavl') }}
...
push-iavl-docker-images:
runs-on: buildjet-4vcpu-ubuntu-2204
if: ${{ contains(github.ref_name, 'iavl') }}
...
```
Tested the workflow logic in another repository stubbing the docker push but just printing the tags.
Test push of `v111.222.333` tag:
https://github.com/niccoloraspa/test-ci/actions/runs/8341900968
Test push of `v111.222.333-iavl-v1` tag: …
=> [ci] Push iavl-v1 docker images on vX.Y.Z-iavl-v1 tags

x/authenticator/authenticator/all_of.go, x/authenticator/authenticator/any_of.go, x/authenticator/authenticator/composite.go, x/authenticator/authenticator/manager.go, x/authenticator/keeper/keeper_test.go
We are unnecessarily iterating over authenticators in many places. This should be O(1).
This PR modifies the implementation of the authentication manager to keep the registered types in a map instead of a list
=> Simplify authenticator manager

go.mod, go.sum, osmoutils/go.mod, x/epochs/go.mod, x/ibc-hooks/go.mod
Closes: #XXX
Updating cometbft to latest osmosis version that contains sync speed improvements
Change log has been added here => https://github.com/osmosis-labs/osmosis/pull/7855/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR91-R96
=> fix: update cometbft to latest version v37.4-v24-osmo-2

cmd/osmosisd/cmd/root.go
Closes: #XXX
The default is 0 and we override to 1500. This causes bad performance on IAVL v1, not to mention we dont even use these snapshots, so it is wasted resources.
=> chore: remove snapshot interval override

go.mod, go.sum
same as https://github.com/osmosis-labs/osmosis/pull/7983#pullrequestreview-1986167127 but for iavl v0
=> added soft-forked-ibc for ASA-2024-007

.github/workflows/push-dev-docker-images.yml
Closes: #XXX
Currently, we do no auto-push docker dev images. This PR attempts to fix this
=> chore: push docker dev images on iavl-v1

x/gamm/README.md
Added clarity around the fee when creating pool. [Some are mistakenly specifying '--fees 100000000uusdc' here.]
Equivalent change to docs site to immediately follow. [link below]
Streamline pool creation.
Added a line describing that it is automated.
- [ no ] Does this pull request introduce a new feature or user-facing behavior changes?
- [ no ] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?
- [ `osmosis/tree/main/x/gamm#create-pool/README.md` ] Specification
- [ `https://github.com/osmosis-labs/docs/blob/main/docs/overview/integrate/pool-setup.md` ] Osmosis documentation site
=> additional context for fee on 'create-pool'

app/ante.go, app/app.go, app/keepers/keepers.go, app/keepers/modules.go, app/modules.go, app/posthandler.go, app/upgrades/v25/constants.go, app/upgrades/v25/upgrades.go, tests/osmosisibctesting/chain.go, x/smart-account/ante/ante.go, x/smart-account/ante/ante_test.go, x/smart-account/ante/circuit_breaker.go, x/smart-account/ante/circuit_breaker_test.go, x/smart-account/ante/limit_fee_payer_test.go, x/smart-account/authenticator/base_test.go, x/smart-account/authenticator/composition_test.go, x/smart-account/authenticator/spend_limits_test.go, x/smart-account/integration_test.go, x/smart-account/keeper/genesis_test.go, x/smart-account/keeper/keeper.go, x/smart-account/keeper/keeper_test.go, x/smart-account/keeper/msg_server.go, x/smart-account/keeper/msg_server_test.go, x/smart-account/post/post.go, x/smart-account/post/post_test.go
The circuit breaker can now be deactivated by any of the controllers, but only activated by gov. 
(drive by, rename authanticator to smartaccount when needed)
tests have been adapted to match this change
=> More restrictive Circuit Breaker Auth

CHANGELOG.md, x/lockup/abci.go
We are running somewhat expensive iterators every block. This PR makes it now once every 30 blocks, reducing the average case load of a block. 
I am a bit surprised no tests broke though,.
=> Don't check for expired locks every single blcok

go.mod, go.sum, osmomath/go.mod, osmoutils/go.mod, osmoutils/go.sum, x/epochs/go.mod, x/ibc-hooks/go.mod
Updating the cosmos-sdk dependency to the v25 tag
- https://github.com/osmosis-labs/cosmos-sdk/releases/tag/v0.47.5-v25-osmo-1
Updating the cometbft dependancy to the v25 tag
- https://github.com/osmosis-labs/cometbft/releases/tag/v0.37.4-v25-osmo-1
=> chore: update cometbft and cosmos-sdk deps

app/upgrades/v25/upgrades.go, app/upgrades/v25/upgrades_test.go, go.mod, go.sum, osmoutils/module_account.go
Ensure the account is properly created for block-sdk to avoid sniping
all tests should pass.
This should be verified on an edgenet
=> Properly create the module account for auction

CHANGELOG.md, x/smart-account/ante/circuit_breaker.go, x/smart-account/keeper/keeper.go, x/smart-account/keeper/params.go
Closes: #XXX
Inspired by https://github.com/osmosis-labs/osmosis/pull/8148
This param retrieval currently gets called 6 times for each tx. This requires unmarshalling all the params from the module, which is very wasteful.
All currently existing tests that test the circuit breaker should behave the same. I will also be setting breakpoints in my QA for v25 on this feature to ensure the behavior is as expected. 
=> perf: isSmartAccountActive param cache

CHANGELOG.md, go.mod, go.sum, osmoutils/go.mod, x/epochs/go.mod, x/ibc-hooks/go.mod
Closes: #XXX
Includes the following state compatible comet changes:
```
* [#35](https://github.com/osmosis-labs/cometbft/pull/35) Handle last element in PickRandom
* [#38](https://github.com/osmosis-labs/cometbft/pull/38) Remove expensive Logger debug call in PublishEventTx
* [#39](https://github.com/osmosis-labs/cometbft/pull/39) Change finalizeCommit to use applyVerifiedBlock
* [#40](https://github.com/osmosis-labs/cometbft/pull/40) Speedup NewDelimitedWriter
* [#41](https://github.com/osmosis-labs/cometbft/pull/41) Remove unnecessary atomic read
* [#42](https://github.com/osmosis-labs/cometbft/pull/42) Remove a minint call that was appearing in write packet delays
* [#43](https://github.com/osmosis-labs/cometbft/pull/43) Speedup extended commit.BitArray()
```
When backporting to v24.x, …
=> perf: state compatible comet perf improvements

CHANGELOG.md, app/upgrades/v25/constants.go, app/upgrades/v25/upgrades.go, app/upgrades/v25/upgrades_test.go
- adding the daodao contract to the circuit breaker controller to the smart account params
https://daodao.zone/dao/osmo1wn58hxkv0869ua7qmz3gvek3sz773l89a778fjqvenl6anwuhgnq6ks7kl/home
=> fix: add circuit breaker controller to smartaccount module

x/smart-account/keeper/msg_server.go, x/smart-account/keeper/msg_server_test.go
Deactivate smart account messages if smart accounts is inactive
added a test. Existing tests should pass. 
=> [SmartAccounts] Deactivate smart accounts messages when smartaccounts is inactive

x/txfees/keeper/mempool-1559/code.go, x/txfees/keeper/mempool-1559/code_test.go
Closes: #XXX
We were seeing the following error recently in many of the blocks in the e2e test suite:
This error occurred any time an updateProposal call was made in which the partialProposalSize was greater than zero. The reason this error was occurring was because, in the EIP code, we set the e.lastBlockHeight in the EIP beginBlocker, however the block-sdk creates transactions prior to the beginBlocker being called, resulting in this error triggering.
We therefore set the block height in the end blocker instead of just the begin blocker. I left the begin blocker set, otherwise we might have an issue where the first block every time creates the error, and it is minimal additional overhead.
E2E no longer shows the error
=> fix: eip 1559 fix for block-sdk

CHANGELOG.md, cmd/osmosisd/cmd/root.go
Closes: #XXX
Overwrites timeout propose from 3s to 2s.
=> chore: overwrite timeout propose from 3s to 2s

x/tokenfactory/client/cli/tx.go
Closes: #7942
As per issue #7942 decription:
> when running osmosid tx tokenfactory the help documentation shows (Costs osmo though!), while since may 2023 this is not the case anymore (https://github.com/osmosis-labs/osmosis/pull/4983).
This MR simply updates docs by removing `(Costs osmo though!)` from the TokenFactory CLI help docs.
=> Update docs for TokenFactory CLI --help

x/cosmwasmpool/client/cli/tx.go
Closes: #XXX
Fixes a typo in the CW pool CLI example. Since this is one of the few forms of concrete CLI documentation we have on instantiating CW pools, it's important it's correct (was painful to debug 😅)
=> [fix]: Fix typo in cw pool CLI example

.github/workflows/check-broken-links.yml
Closes: #7877 
This pull request slows down "check broken links" action by reducing concurent requests to 1 ( default: 128 ).
After this change action will take around 10mins to complete for 1.5k links at the moment ( previously 30sec ) with no failed requests as per [testing](https://github.com/deividaspetraitis/osmosis/actions/runs/9112683030).
=> Fix: Slow down action run time by reducing concurrent operations

go.mod, go.sum, osmoutils/go.mod, osmoutils/go.sum, x/epochs/go.mod, x/epochs/go.sum, x/ibc-hooks/go.mod, x/ibc-hooks/go.sum
Upgrade to IBC v7.4.1, significantly lowering the chain's mempool overhead.
This is only PR'd to v25.x because main is upgrading to SDK v50. (and hence an IBC v8 line branch)
IBC added an event if the ICA host module is disabled. We have it enabled on mainnet, so there is no concern of changing behavior there.
I would like to get this into a patch release soon, with accompanying TM improvements.
=> Upgrade v25.x to IBC v7.4.1

CHANGELOG.md, cmd/osmosisd/cmd/root.go
Overwrites timeout commit from 1.5s to 1s.
=> chore: overwrite timeout commit from 1.5s to 1s

CHANGELOG.md, x/ibc-hooks/wasm_hook.go, x/ibc-rate-limit/ibc_module.go
These codepaths get called in checktx and rechecktx, causing notable overhead. This PR removes these.
We should get this into a patch release to significantly improve our spam resistance
=> Remove wasm times from our antehandler checkTx + recheckTx stack

ingest/sqs/pools/transformer/pool_transformer.go, ingest/sqs/pools/transformer/pool_transformer_test.go
Closes: #XXX
Our SQS integration test suite identified a regression. It stems from the fact that we would truncate the pool liquidity capitalization to zero.
Instead, we should reflect that there is at least some value in the pool by rounding pool liquidity cap up.
Tested against our suite that this change resolves the bug
=> fix: pool liquidity cap rounding edge case

CHANGELOG.md, cmd/osmosisd/cmd/root.go
Closes: #XXX
10ms was causing some validators to have issues, so we are increasing the default overwrite from 10ms to 80ms.
=> fix: inc flush-throttle-timeout overwrite to 80ms

x/smart-account/client/cli/query.go
Closes: #XXX
Exposing the cli command for getting a specific authenticator
```
- make install
- osmosisd q smartaccount authenticator osmo12smx2wdlyttvyzvzg54y2vnqwq2qjateuf7thj 14 --output json --node http://164.92.247.225:26657 | jq
```
=> fix: expose get authenticator to cli

cmd/osmosisd/cmd/init.go
Closes: #XXX
Current `init` command fails with the following error
```
./osmosisd init my-node --chain-id=as
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x104eb6544]
goroutine 1 [running]:
github.com/osmosis-labs/osmosis/v25/cmd/osmosisd/cmd.InitCmd.func1(0x14001e21508, {0x14001a0d5c0, 0x1, 0x2?})
github.com/osmosis-labs/osmosis/v25/cmd/osmosisd/cmd/init.go:205 +0xbf4
github.com/spf13/cobra.(*Command).execute(0x14001e21508, {0x14001a0d5a0, 0x2, 0x2})
github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x14001628908)
github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
github.com/spf13/cobra@v1.8.0/command.go:1039 …
```
=> Fix `init` command with correct Consensus Params

x/smart-account/ante/pubkey.go, x/smart-account/post/post.go, x/smart-account/types/keys.go, x/smart-account/types/msgs.go
Closes: #XXX
Removed some todos based on the audit
=> fix: remove some todos

ingest/sqs/pools/transformer/pool_transformer.go
Closes: #XXX
Due to using a different method for extracting balances for a cw pool (from liquidity rather than bank) and alloyed having 3 assets, a binary search algorithm searching for denom from balances was breaking in SQS dowsntream, preventing the alloyed asset pool from being picked up.
This PR fixes the issue.
The change is committed to `v25.x` here: https://github.com/osmosis-labs/osmosis/pull/8368
Tested on node
=> fix: transmuter balance ingest not sorted

x/smart-account/authenticator/signature_authenticator.go, x/smart-account/keeper/keeper.go
Update documentation for functions based on audit feedback
=> chore: update documentation for functions

CHANGELOG.md, x/ibc-rate-limit/ibc_module.go
Speedup one JSON unmarshal being hit in production codepath
=> perf: Speedup one JSON unmarshal

ingest/indexer/domain/ingester.go, ingest/indexer/service/client/pubsub_client.go, ingest/indexer/service/indexer_streaming_service.go, ingest/indexer/service/writelistener/bank_write_listener.go, ingest/sqs/service/sqs_streaming_service.go
Closes: #XXX
This PR implements proper supply offset handling.
It adds a separate pub/sub API for the supply offsets, assuming that these would be transformed downstream in the indexer pipeline.
Note that supply offset is a pre-launch mystery. For regulatory reasons, we offset developer rewards using supply offsets.
=> feat(indexer): proper supply offset handling

cmd/osmosisd/cmd/root.go
Lower blocktime by another 400ms. Keeping it at 600ms feels more than enough, as thats more than enough for 2 global internet round trips. Furthermore Comet improvements should lower risk of overheads here as well
=> perf: Lower timeout commit to 600ms

x/txfees/keeper/feedecorator.go, x/txfees/keeper/feedecorator_test.go
Closes: #XXX
Limits IBC Transfer messages to the following:
* transferMsg.Size() > 500000 // 500KB
* transferMsg.Memo> 400000 // 400KB
* transferMsg.Receiver > 65000 // 65KB
Limit ICA Send message to the following:
* icaMsg.PacketData.Size() > 500000 // 500KB
* icaMsg.Owner > 65000 // 65KB
I opted to hard code these since adding them to the config would be deprecated in the next release. LMK if you think I should add them as config params.
=> fix: mempool filter ibc spam

.github/workflows/push-docker-images.yml
This PR adds the strategy to build docker images with cosmovisor inside wrapping osmosis binary.
This image has been released to a development docker registry and has been tested in our node deployments.
=> Add missing docker build for cosmovisor-wrapped osmosis binary image

CHANGELOG.md, x/ibc-rate-limit/ibc_module.go
Please note that this is generally, not the best solution, but all we risk is wasted compute getting on-chain at the trade-off of better mempools.
I have whitebox examined, that for Acknowledgement we are gaining nothing. This is running all of PFM's logic and all of the main IBC-go logic. This is not needed for the redundant relay goal.
=> Remove IBC-rate limits descendant recheck calls

app/app.go, ingest/indexer/domain/publisher.go, ingest/indexer/domain/token_supply.go, ingest/indexer/indexer_config.go, ingest/indexer/ingester.go, ingest/indexer/publisher.go, ingest/indexer/service/indexer_streaming_service.go
This pull request added block level ingestion and data publishing. We currently publish chainId, height, block timestamp and gas consumption only, but we can add / remove the attributes as reviewed in this pull request.
This PR will fulfill the dexscreener requirements of /latest-block
=> feat: rename ingester to publisher, added block publishing code

CHANGELOG.md, osmoutils/config_parser.go
Closes: #XXX
Indexer config was reading SQS `is-enabled` value. Fixed here and did more clean ups as a drive-by. Tested locally.
=> fix: indexer config reading sqs enabled value

CHANGELOG.md, cmd/osmosisd/cmd/root.go
With this PR, on "osmosisd init", config group for indexer "osmosis-indexer" and its default, corresponding attributes will be added to app.toml
=> feat: Generate default indexer configs on osmosisd init

CHANGELOG.md
Closes: #XXX
*(or)*
*(or)*
*(example:)*
=> chore: changelog fixes

cmd/osmosisd/cmd/module_hash_by_height.go, cmd/osmosisd/cmd/root.go
Query that exposes the per module hash at a given height, which is useful for debugging app hashes.
=> feat: module hash by height query

go.mod, go.sum, osmoutils/go.mod, x/epochs/go.mod, x/ibc-hooks/go.mod
Closes: #XXX
Bumps comet with mempool improvements
=> chore: comet bump

cmd/osmosisd/cmd/root.go
Closes: #XXX
Noticed from in-place-testnet
=> fix: use AppGenesis instead of GenesisDoc after sdk 50 

go.mod, go.sum, ingest/sqs/CHANGELOG.md, ingest/sqs/pools/transformer/orderbook.go, ingest/sqs/pools/transformer/orderbook_test.go
Precompute and ingest `BidAmountToExhaustAskLiquidity` & `AskAmountToExhaustBidLiquidity` through `OrderbookData`. This reduces the need to iterate all the ticks if the requested amount in is over these threshold based on order direction.
- unit tested for `updateOrderbookInfo` function
- more comprehensive test cases for calculation are already covered in `sqsdomain`
=> SQS Ingester: Add Orderbook amount in to exhaust liquidity

.github/workflows/pprof-auto.yml
Closes: PLAT-258
This pull request introduces a new GitHub Actions workflow to automate the triggering of pprof profiling automation upon the creation of a new tag. The workflow uses the `peter-evans/repository-dispatch` action to send a dispatch event with relevant details, such as commit SHA, tag name, and profiling parameters, to the target repository.
- **GH_TOKEN**: A personal access token with the necessary permissions to trigger repository dispatch events.
- **PPROF_REPO**: The target repository where the pprof automation is configured.
=> Added GH action to trigger pprof automation

cmd/osmosisd/cmd/root_test.go, ingest/indexer/indexer_config.go
Closes: #8491 
This aligns the AppTemplate field name access and the config Field name.
A unit test has been added to verify the app template access existing field in the config.
=> fix: makes the template to use an existing config field

app/app.go, ingest/indexer/domain/transaction.go, ingest/indexer/service/indexer_streaming_service.go
This is a version of transaction ingester which publishes only necessary events to the indexer backend. Untested in main branch and required a full e2e test when main branch is promoted to the next production version. A variation of of this commit is tested v25.x
=> Revised txn ingester for iterating txns in main branch

ingest/indexer/service/client/pubsub_client.go
In current implementation, for every message handled by pubsub client, it blocks program execution while waiting for message publishing to finish. This increases block time when indexer option is enabled. This PR is to address the issue by removing the wait and let the messaging publishing to continue its own execution without blocking the caller.
=> Remove program execution blocking by not waiting for pubsub message publishing

CHANGELOG.md, x/concentrated-liquidity/lp.go, x/lockup/keeper/msg_server.go, x/lockup/types/events.go, x/superfluid/keeper/concentrated_liquidity.go, x/superfluid/keeper/internal/events/emit.go, x/superfluid/keeper/internal/events/emit_test.go, x/superfluid/keeper/msg_server.go, x/superfluid/types/events.go
Closes: #XXX
This PR adds additional events that were missing. The list of events being added are as below
- pool Id addition in 
- MsgAddToPosition 
- MsgAddToConcentratedLiquiditySuperfluidPosition
- locked token amount & denom addition in 
- MsgBeginUnlocking
-  MsgSuperfluidDelegate
-  MsgSuperfluidUndelegate  
- 
=> Add additional events in x/lockup, x/superfluid, x/concentratedliquidity

ingest/indexer/service/blockprocessor/pair_publisher.go
The change is to remove the sorting and maintain the original denom sorting order in constructing the pair-id, which is in the format of {pool-id}-{index of denoms}-{index of denoms}. Tested in v25.x.
=> fix: [indexer] remove sorting in pair publisher and maintain the original denom order

ingest/indexer/service/indexer_streaming_service.go
This fix is applicable to v25.x only. The transaction index counter is currently incremented at ListenDeliverTx and it shouldn't be incremented at ListenBeginBlock.
=> fix: transaction index counter should not be incremented in ListenBeginBlock callback

.github/workflows/push-dev-docker-images.yml
Current Docker dev images push has a race-condition problem because it’s not possible to push Docker images for multiple platforms (`linux/amd64` and `linux/arm64`) at different times, resulting in one of the images being overridden.
=> Fix race condition on osmosis dev images push

CHANGELOG.md, x/concentrated-liquidity/types/cl_pool_extensionI.go
Closes: [#8469](https://github.com/osmosis-labs/osmosis/issues/8469)
Changes return value for pool.GetLiquidity, as it was returning osmomath.LegacyDec thus was not able to be unmarshalled when being returned as result for the query. 
=> Change `LiquidityNetInDirection` return type to sdk math

ingest/indexer/domain/pair.go, ingest/indexer/domain/token_supply.go, ingest/indexer/service/blockprocessor/pair_publisher.go
This commit is to add an additional field multi_asset to indicate that the pool supports >2 tokens. This is to address the dexscreener requirement that for those 2 tokens pool, the pair_id should remain be 1234, not 1234-0-1
=> feat: [indexer] added multi_asset field in the pubsub message for pair

app/app.go, ingest/indexer/service/indexer_streaming_service.go
Closes: #XXX
The pools weren't cleared at the end of every block, overwhelming data ingest. This fixes the problem by resetting pool tracker at the end of every block, to clear tracked pools.
=> fix: indexer etl breakage pushing all pairs every block and overwhelming collections

ingest/indexer/service/indexer_streaming_service.go
Closes: #XXX
When the indexer node cold starts, there is log-lasting ingest process, and it is unclear if the node is stuck or ingest is still in-progress.
This PR adds logs for clear and direct feedback
=> chore(indexer): log start and end of first block ingest

.github/workflows/push-dev-docker-images.yml, .github/workflows/push-docker-images.yml, Dockerfile, Dockerfile.cosmovisor
This change is already covered by existing tests, such as docker based build.
=> Bump alpine versions to get golang 1.22.4 support

tests/e2e/initialization/init.Dockerfile
Fix the e2e test docker image building failure
This change is already covered by existing tests, such as docker build pipeline.
=> e2e docker image: use alpine 1.20 and pick libwasmvm version from go.mod

CHANGELOG.md, x/tokenfactory/keeper/before_send.go, x/tokenfactory/keeper/before_send_test.go
Closes: #XXX
Blocks Setting invalid setting before send hooks
This change added new etest
=> fix: prevent setting invalid before send hook

ingest/indexer/domain/keepers.go, ingest/indexer/service/indexer_streaming_service.go
This PR addresses the issue that in the case of towen_swapped event in CL pools, the tokens_in amount is AFTER spread factor calculation, thus we need to adjust it back to BEFORE spread factor amount before the event data is published to the indexer backend. Tested in v25.x and to be tested in sdk v50.
=> fix: [indexer] adjust token in amount for spread factor for CL pools only

CHANGELOG.md, cmd/osmosisd/cmd/root.go
Reducing block time to 1.5s by reducing timeout_commit to 200ms
=> feat: reduce commit timeout to 500ms to enable faster blocks

x/protorev/client/cli/utils.go, x/protorev/keeper/msg_server.go, x/protorev/keeper/posthandler.go, x/protorev/keeper/protorev.go, x/protorev/keeper/routes.go, x/protorev/keeper/statistics.go, x/protorev/types/errors.go, x/protorev/types/token_pair_arb_routes.go, x/protorev/types/validate.go, x/superfluid/client/cli/tx.go, x/superfluid/keeper/concentrated_liquidity_test.go, x/superfluid/keeper/migrate.go, x/superfluid/keeper/migrate_test.go, x/superfluid/keeper/stake.go, x/superfluid/types/gov.go, x/superfluid/types/msgs.go, x/valset-pref/client/cli/tx.go, x/valset-pref/client/query_proto_wrap.go, x/valset-pref/keeper.go, x/valset-pref/keeper_test.go, x/valset-pref/msg_server.go, x/valset-pref/simulation/sim_msgs.go, x/valset-pref/types/msgs.go, x/valset-pref/validator_set.go
`errors.New` is specifically designed to instantiate a new error with a given message, without any formatting overhead. I think this should be the preferred method when we do not need to format the error string.
On the other hand, it saves a couple function calls and a comparison on the error path, although this is tiny diff...
=> chore(x/protorev): use `errors.New` to replace `fmt.Errorf` with no parameters

tests/localrelayer/scripts/setup_chain.sh
Closes: #8520 
*This pull request fixes the localrelayer test environment by exposing the grpc interface so that relayer can connect to validators*
- *Manually verified the change by starting the localrelayer test environment*
=> Expose the grpc for relayer connection in the localrelayer test environment

cmd/osmosisd/cmd/root.go
Closes: #XXX
Current CLI has duplicated query commands, this PR fixes it. 
=> Fix CLI with duplicated query commands

CHANGELOG.md, x/gamm/pool-models/internal/cfmm_common/lp.go
We saw this was taking a noticeable amount of time in some SQS queries.
This saves ~15% of the relevant time. (Though the better solution will involve re-implementation in SQS for a 10x)
=> perf: Speedup exit pool

x/txfees/keeper/feedecorator.go
we see apphash issues with this code path between blocks `16841115` and block `17004043`, we ignore this code path for the purposes of syncing the node
=> fix: v25 app hash when syncing

x/superfluid/keeper/gov/gov.go
Update a small edge case where we use == instead of the recommended .Equal
- https://github.com/osmosis-labs/osmosis/pull/8564#discussion_r1700892365
- `cd x/superfluid`
=> fix: update == to .Equal

CHANGELOG.md, app/upgrades/v26/constants.go, app/upgrades/v26/upgrades.go, app/upgrades/v26/upgrades_test.go
The current estimate for unauthenticated gas is far to low, the node ran into issues when we tried to execute transaction using fee tokens other than `uosmo` as the was another read from the store.
We increase the unauthenticated gas from 120_000 => 200_000 to enable multiple fee tokens
- 1 run `in-place-testnet`
- `osmosisd q smartaccount params`
- 2 run tests in the v26 upgrade folder
- `cd ./app/upgrades/v26`
=> fix: increase unauthenticated gas to fix fee token issue

x/txfees/keeper/feedecorator.go, x/txfees/keeper/feedecorator_test.go
Closes: #XXX
We added the ibc mempool filter feat directly into v25. This PR brings it into v26 (along with respective checkTx logic to prevent network fork)
Ported over old tests, along with a new test that shows that this check is not run when it is not checkTx.
=> chore: add ibc packet mempool filter to v26

ante/sendblock.go, app/app.go, app/encoding.go, app/modules.go, cmd/osmosisd/cmd/root.go, go.mod
In preparation for the v0.50 upgrade we left some UNFORKINGTODO around the code base to verify some functionality, this PR removes and an answers a few of those questions.
=> chore: remove UNFORKINGTODOs

CHANGELOG.md, x/concentrated-liquidity/keeper.go, x/poolmanager/create_pool.go, x/poolmanager/export_test.go, x/poolmanager/keeper.go, x/poolmanager/keeper_test.go, x/poolmanager/types/expected_keepers.go
Closes: #7337 
Exempts `UnrestrictedPoolCreatorWhitelist` addresses from paying the pool creation fee.
gotest added
=> feat: exempt `UnrestrictedPoolCreatorWhitelist` addresses from pool creation fee

x/txfees/keeper/feedecorator.go
This commit forward-ports the fix about AppHash issue during v25 sync.
See: https://github.com/osmosis-labs/osmosis/pull/8577
Tested in v25.x and already in production in indexer environment.
=> fix: apphash during v25 sync. forward porting it to v26

go.mod, go.sum
During review of https://github.com/osmosis-labs/osmosis/pull/8616
We identified that IAVL should be bumped to v1.3.0
https://github.com/osmosis-labs/osmosis/pull/8616#discussion_r1725538767
This happened, so it's not realistic to have this for v26:
```
Go version: 1.22
GOWORK=off go install -mod=readonly -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=osmosis -X github.com/cosmos/cosmos-sdk/version.AppName=osmosisd -X github.com/cosmos/cosmos-sdk/version.Version=adam/sqs-v26-testing-93-g930687b72 -X github.com/cosmos/cosmos-sdk/version.Commit=930687b72b4d566588a95da4f39a58bdcdb31116 -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger" -w -s' -trimpath github.com/osmosis-labs/osmosis/v25/cmd/osmosisd …
```
=> chore: remove iavl replace directive

cmd/osmosisd/cmd/root.go, ingest/indexer/indexer_config.go, ingest/indexer/service/client/pubsub_client.go
This commit addresses an issue observed where a message getting published using PubSub sdk on the publisher side but such message is not received and read on the consumer side. It is because when the message publishing rate is very low, messages may remain pending and stale within the Pub/Sub SDK. For example, if only one message is published over a span of several minutes, the default DelayThreshold and CountThreshold values are high enough that the message may seem undelivered or lost. To mitigate this, it's essential to reduce the DelayThreshold to a lower value, such as 4 seconds, to ensure timely delivery.
Tested in v25.x. Will be tested in v26.x
=> feat: fine-tune pubsub sdk to avoid idling message at the sdk level

go.mod, go.sum, osmomath/go.mod, osmomath/go.sum, osmoutils/go.mod, osmoutils/go.sum, x/epochs/go.mod, x/epochs/go.sum, x/ibc-hooks/go.mod, x/ibc-hooks/go.sum
Bump sdk to add staking migration improvement see:
https://github.com/osmosis-labs/cosmos-sdk/pull/622
- Direct commit link: https://github.com/osmosis-labs/cosmos-sdk/commit/c88c7c36bf2b1c09b6c18a742bc5060f3cce1ebb
- Direct tag link: https://github.com/osmosis-labs/cosmos-sdk/releases/tag/v0.50.6-v26-osmo-2
=> chore: update cosmos-sdk to v0.50.6-v26-osmo-2

ingest/common/domain/block_pools.go, ingest/common/domain/mocks/pools_extracter_mock.go, ingest/common/domain/pools.go, ingest/common/poolextractor/pool_exractor_test.go, ingest/common/poolextractor/pool_extractor.go, ingest/common/pooltracker/memory_pool_tracker.go, ingest/indexer/domain/pair.go, ingest/indexer/domain/publisher.go, ingest/indexer/service/blockprocessor/block_updates_indexer_block_process_strategy.go, ingest/indexer/service/blockprocessor/full_indexer_block_process_strategy.go, ingest/indexer/service/blockprocessor/pair_publisher.go, ingest/indexer/service/export_test.go, ingest/indexer/service/indexer_streaming_service.go, ingest/indexer/service/indexer_streaming_service_test.go, ingest/sqs/domain/mocks/pools_extractor_mock.go, ingest/sqs/domain/service.go, ingest/sqs/service/blockprocessor/full_sqs_block_process_strategy.go
NOTE TO REVIEWER:
This PR has been reviewed once here with suggestions addressed. 
https://github.com/osmosis-labs/osmosis/pull/8525
This PR changes the way pair object is published. Instead of publishing changed pair data upon block creation to the indexer backend (which is not relevant anyway as pair data is static and doesn't change), this commit will publish newly created pair data with creation details, which includes creation height, block timestamp and transaction hash. This is also one of the recommendation from Dexscreener team, which will allow the newly created pair showing up on their "New Pair" page. 
- Tested with v25.x using production past data with pool_created event emitted during node sync.
- Will require forward porting to v26.x
- Untested in v26.x but will perform it …
=> feat: [indexer][v25.x] publish created pools

CHANGELOG.md, x/poolmanager/taker_fee.go
Fix the nil pointer exception in protorev:
`ERR ProtoRevTrade failed with error: protorev failed due to internal reason: runtime error: invalid memory address or nil pointer dereference module=server`
This error happens as the protorev account is not charged taker fees.
We return sdk.Coin{} => https://github.com/osmosis-labs/osmosis/blob/main/x/poolmanager/taker_fee.go#L137
We should return `sdk.Coin("denom",0)`
Here it's returned => https://github.com/osmosis-labs/osmosis/blob/v26.x/x/poolmanager/router.go#L78
We then call `.Add` on a nil value causing a panic => https://github.com/osmosis-labs/osmosis/blob/v26.x/x/poolmanager/router.go#L87 
Then panic is caught in protorev
- run in place testnet and replay txns from mainnet on the node => https://github.com/PaddyMc/osmosis-txn-replayer …
=> fix: protorev throws a nil pointer

app/app.go, ingest/indexer/service/blockprocessor/block_process_indexer_factory.go, ingest/indexer/service/blockprocessor/block_process_indexer_factory_test.go, ingest/indexer/service/blockprocessor/block_updates_indexer_block_process_strategy.go, ingest/indexer/service/indexer_streaming_service.go
Closes: #XXX
There are 2 fixes here:
1. Missing registration of the kv store keys to push state updates to the streaming listeners
Affects both SQS and ingester. We need to register listeners on the commit multi-store. This was a change in the v50 that was missed.
This was masked due to the following:
* We use two different strategies 1) full block process and 2) updates only and this was affected only 2)  
* When we start-up the node, 1) correctly runs populating the data but 2) never happens
* Due to lack of traffic on testnets this was non-trivial to catch
2. Affects indexer only. We need to correctly process the change sets when received from the stores in ListenCommit
- Tested that change sets now propagate correctly with `v26.x` in-place-testnet
=> fix: ingester change set not propagated due to missing registration

cmd/osmosisd/cmd/root.go
During the testnet upgrade multiple node runners failed to upgrade their nodes as there was an issue when creating a new folder to populated command, this PR leverages the go `os.MkdirTemp()` function to initialise the folder with looser perms and in the `/tmp` folder, allowing it to be created and deleted by all system users.
- https://discordapp.com/channels/798583171548840026/888527640099688458/1280562695740850289
- https://discordapp.com/channels/798583171548840026/888527640099688458/1280566026680926208
- `cd /`
- `osmosisd` <= this won't work on the `v26.0.0-rc3` branch
=> fix: create temp folder with looser perms

CHANGELOG.md, x/smart-account/authenticator/authentication_request.go
Found an issue where checktx would cause the FE to throw an error because check tx will throw an error based on generate sign bytes
if this code path is hit and the txn doen't have any auth data we throw a nil pointer 
https://github.com/osmosis-labs/osmosis/blob/main/x/smart-account/authenticator/authentication_request.go#L253-L257
```
recovered: runtime error: invalid memory address or nil pointer dereference
stack:
goroutine 57378 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x6b
github.com/cosmos/cosmos-sdk/baseapp.newDefaultRecoveryMiddleware.func1({0x702a6a0, 0xa1a68b0})
/home/ghost/go/pkg/mod/github.com/osmosis-labs/cosmos-sdk@v0.50.6-v26-osmo-2/baseapp/recovery.go:74 +0x35
github.com/cosmos/cosmos-sdk/baseapp.newRecoveryMiddleware.func1({0x702a6a0, …
```
=> fix: smart account signing checktx error

CHANGELOG.md, x/smart-account/authenticator/composite.go
Update error message according to logic changes in #8375 
=> fix: update enforce sub-authenticator to be greater than 1 error message

CHANGELOG.md, cosmwasm/contracts/crosschain-registry/Cargo.toml, cosmwasm/contracts/crosschain-swaps/Cargo.toml, cosmwasm/contracts/outpost/Cargo.toml, cosmwasm/contracts/swaprouter/Cargo.toml, tests/ibc-hooks/testutils/contracts/counter/Cargo.toml, tests/ibc-hooks/testutils/contracts/echo/Cargo.toml, x/concentrated-liquidity/testcontracts/contract-sources/counter/Cargo.toml, x/concentrated-liquidity/testcontracts/contract-sources/hooks/Cargo.toml, x/ibc-rate-limit/contracts/rate-limiter/Cargo.toml, x/smart-account/testutils/contracts/echo/Cargo.toml, x/tokenfactory/keeper/testcontracts/contracts/infinite-track-beforesend/Cargo.toml
* Bump rust-optimizer across all of the cosmwasm code in osmosis.
* Learn if the build system for it works how I think it does
This change is already covered by existing tests, and should be closed if it does not pass, or doesn't make sense to the maintainers.
=> chore: bump rust optimizer

ingest/sqs/pools/transformer/taker_fee.go
This commit builds on the work done in [PR 8344](https://github.com/osmosis-labs/osmosis/pull/8344), but specifically on the data ingester for SQS.
Now, the taker fee can be set independently for each trade direction. For example, in a trading pair (A, B), the taker fee for A → B can be P, while the fee for B → A can be Q. With this change, there’s no need to lexicographically sort the pair denominations before storing or retrieving taker fee data. Instead, the taker fee map will now contain two separate entries: one for the pair (A, B) with value P, and another for the pair (B, A) with value Q.
Additionally, adjustments have been made to the sqs-side logic, For more details, refer to [PR 510](https://github.com/osmosis-labs/sqs/pull/510).
Tested in v26 with the following scenario:
1. …
=> feat: uni-directional trading pair taker fee support (sqs ingester)

CHANGELOG.md, networks/osmosis-1/upgrades/v26/mainnet/v26_binaries.json
Adding binaries to network release file
=> chore: updating binary json file

CHANGELOG.md, proto/osmosis/gamm/v1beta1/tx.proto, proto/osmosis/lockup/tx.proto, proto/osmosis/protorev/v1beta1/tx.proto
Ci is broken because of this PR, because after proto generation this commit break build
This reverts commit ba5ecb1b43d2ffd21324ede5c7a7d081a5055f53.
=> Revert "Add missing protobuf definitions (#8600)"

go.mod, go.sum, ingest/sqs/pools/transformer/pool_transformer_test.go, ingest/sqs/pools/transformer/taker_fee_test.go
Bump sqsdomain to v0.26.0
Backported here: https://github.com/osmosis-labs/osmosis/pull/8713
=> Bump sqsdomain on main

x/superfluid/keeper/stake.go
Closes: #XXX
For the grpc query, we used to just log errors and continue. During the sdk v50 upgrade, we for some reason changed to returning errors. This brings back the old logic.
Pre sdk v50 logic for comparison https://github.com/osmosis-labs/osmosis/blob/8c89343e3b09dcba9a0f45ce0ea872fc4d8fe2a8/x/superfluid/keeper/stake.go#L551-L594
=> fix: tally grpc query

CHANGELOG.md, cmd/osmosisd/cmd/root.go
Closes: #8725
This pull request fix issue with temp directories and stops creating multiple temp directories
also gives panic if node is unable to create a temp directory instead of returning node default home directory which leads to erasing of entire node data
=> fix: multiple temp directories on command executions

CHANGELOG.md, x/superfluid/keeper/stake.go
Closes: #XXX
Frontports fix that was in v26.x to main
=> fix: iterate delegations continue instead of erroring

CHANGELOG.md, go.mod, go.sum, osmomath/go.mod, osmoutils/go.mod, x/epochs/go.mod, x/ibc-hooks/go.mod
Closes: #XXX
Replaces the addrbook.json when running in place testnet. Results in logs that go from this:
To this:
=> fix: in place testnet logs

CHANGELOG.md, go.mod, go.sum
Closes: #XXX
- updating cosmwasm vm to latest version
=> chore: update cosmwasm vm

ingest/indexer/domain/mocks/publisher_mock.go, ingest/indexer/service/blockprocessor/full_indexer_block_process_strategy_test.go
This PR adds test cases for the following:
1. Verify that the `PublishAllSupplies` method correctly publishes the token supplies and offsets based on the primed data from the state.
2. Verify that the `ProcessPools` method correctly publishes the full set of pool pairs, regardless of whether they have creation data or not. See also: `block_updates_indexer_block_process_strategy_test::TestPublishCreatedPools`, The difference is `full_indexer_block_process_strategy` always publishes all pool pairs, while `block_updates_indexer_block_process_strategy` only publishes when there is a creation data.
=> feat: [indexer] add test cases to full_indexer_block_process_strategy

ingest/indexer/domain/mocks/pair_publisher_mock.go, ingest/indexer/domain/mocks/publisher_mock.go, ingest/indexer/service/blockprocessor/block_updates_indexer_block_process_strategy.go, ingest/indexer/service/blockprocessor/block_updates_indexer_block_process_strategy_test.go, ingest/indexer/service/blockprocessor/export_test.go, ingest/indexer/service/blockprocessor/full_indexer_block_process_strategy_test.go
This PR adds `TestBlockUpdateIndexerBlockProcessStrategyTestSuite` which verifies the block update indexer strategy for processing created pools. The test suite initializes all supported pools (concentrated, cfmm, cosmwasm) via `s.App.PrepareAllSupportedPools()`, creating pool IDs 1-5. Test cases inject pool creation data and validate expected behavior of the pair publisher.
Scenarios tested:
- Happy path: single pool creation: should perform publishing
- Happy path: multiple pool creation: should perform publishing
- No pool creation: nothing is published
- Pool creation data without a match: nothing is published
=> feat: [indexer] add test cases to block_update_indexer_block_process_strategy

CHANGELOG.md, x/lockup/keeper/genesis_test.go
Closes: #XXX
We have observed  couple of failures in go tests, and this has been due to concurrency issues within testing. 
This fix should fix the issues we have been facing.
=> fix concurrency issue in go test(x/lockup)

ingest/indexer/domain/keepers.go, ingest/indexer/service/export_test.go, ingest/indexer/service/indexer_streaming_service.go, ingest/indexer/service/indexer_streaming_service_test.go
This commit resolves the issue where the priceNative data published to Dexscreener occasionally displayed incorrect values due to potential rounding errors. Instead of relying on the token in/out amounts from the token_swapped event to determine the priceNative value, this commit utilizes on-chain spot price data. This data will be published to the indexer backend and made available through the /events endpoint.
=> feat: publish spot price for token swap event

CHANGELOG.md, go.mod, go.sum, osmomath/go.mod, osmomath/go.sum, osmoutils/go.mod, osmoutils/go.sum, x/epochs/go.mod, x/epochs/go.sum, x/ibc-hooks/go.mod, x/ibc-hooks/go.sum
Bumping cometbft and cosmos sdk to the lastest versions:
comet => https://github.com/osmosis-labs/cometbft/releases/tag/v0.38.12-v27-osmo-1
cosmossdk => https://github.com/osmosis-labs/cosmos-sdk/releases/tag/v0.50.10-v27-osmo-1
=> chore: bump cometbft/cosmos-sdk versions

ingest/indexer/service/indexer_streaming_service.go
This commit addresses two issues and one of them is reported in production:
1. Data duplication - the current implementation includes all events for each transaction in a block, vs only the transaction's events should be included.
2. Failed transaction should be skipped.
Tested in v26.x.
=> feat & fix: fix data duplication issue, skip failed transaction 

CHANGELOG.md, x/superfluid/keeper/epoch.go
When we call the _WithdrawDelegatorRewards_ function, we expect there to be a certain type of error, but this error changed in v50 causing multiple info logs that should be debug logs, making it difficult to understand what's happening with the superfluid epoch.
For v0.50 a function changed to return a different error see:
https://github.com/osmosis-labs/cosmos-sdk/blob/osmo-v27/0.50.10/x/distribution/keeper/keeper.go#L107-L138
old v0.47 see:
https://github.com/osmosis-labs/cosmos-sdk/blob/osmo-v25/v0.47.5/x/distribution/keeper/keeper.go#L83-L103
Run all go tests for superfluid
see (live debug logs):
```
11:14AM ERR no delegation for (address, validator) tuple module=server
11:14AM ERR no delegation for (address, validator) tuple module=server
11:14AM ERR no delegation for (address, …
```
=> fix: superfluid log for error that should be ignored

CHANGELOG.md, go.mod, go.sum, osmoutils/go.mod, x/epochs/go.mod, x/ibc-hooks/go.mod
Bump cometbft => v0.38.15-v27-osmo-2
=> chore: bump cometbft

.github/workflows/push-dev-docker-images.yml
Use the field manually populated when building a dev docker image
Remove slashes from ref names to give us a valid docker tag
=> Remove slash from refs for docker

CHANGELOG.md, cmd/osmosisd/cmd/root.go
Due to an issue with concurrent map writes stemming from the block sdk, we need to revert this PR until we have a patch version of the block sdk, the solution is to "import upstream cosmos-sdk changes to prio-nonce mempool"
see:
https://github.com/skip-mev/block-sdk/pull/355
the halt is sporadic and would not fully halt the chain if validators are using systemd, as systemd would restart the node on fail, the halt looks like this:
```
fatal error: concurrent map writes
goroutine 5967690 [running]:
github.com/skip-mev/block-sdk/v2/block/base.(*PriorityNonceMempool[...]).Remove(0x6fc2fa0, {0x6e9d0e0, 0xc1b5526580?})
github.com/skip-mev/block-sdk/v2@v2.1.5/block/base/priority_nonce.go:468 +0x2a5
github.com/skip-mev/block-sdk/v2/block/base.(*Mempool[...]).Remove(0x1ef601d?, {0x6e9d0e0?, …
```
=> chore: revert optimistic exec

.goreleaser.yaml, scripts/makefiles/release.mk
This PR:
- Removes darwin builds from the `.goreleaser.yaml` as we are no longer publishing them
- Updated `linux-amd64` and `linux-arm64` builds to fetch `libwasmvm` in specific paths
- Remove deprecated `--skip-publish` and `--skip-validate` 
I have tested the build locally on an Ubuntu machine, and it is working. However, it is not working on my ARM MacBook.
I encounter the following warnings during the build process:
```bash
_/GOROOT/src/plugin/plugin_dlopen.go:19: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
library/std/src/sys/pal/unix/os.rs:732: warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking …
```
=> Fix `.goreleaser.yaml and Makefile targets

app/app.go, ingest/sqs/service/sqs_streaming_service_test.go, ingest/sqs/sqs_config.go
Closes: #XXX
Backports https://github.com/osmosis-labs/osmosis/pull/8862 to `v28.x`
This change is already covered by existing tests.
=> Calvin/sqs multi instances support 2 (#8862) ( backport )

CHANGELOG.md, x/smart-account/ante/pubkey.go
=> chore: fix event emission for smart account module

CHANGELOG.md, go.mod, go.sum, osmoutils/go.mod, osmoutils/go.sum
This PR bumps store version to [v1.1.1-v0.50.11-v28-osmo-2](https://github.com/osmosis-labs/cosmos-sdk/releases/tag/store%2Fv1.1.1-v0.50.11-v28-osmo-2) 
=> chore: Bump store dependency version to v1.1.1-v0.50.11-v28-osmo-2

.github/workflows/build.yml, .github/workflows/contracts.yml, app/apptesting/concentrated_liquidity.go
Closes: BE-676 
This PR adds swap in given out test cases for CL pools and is part of https://github.com/osmosis-labs/sqs/pull/604.
=> BE-676 | Add SwapOutGivenInCases for CL pool

CHANGELOG.md, cmd/osmosisd/cmd/forceprune.go
Closes: #XXX
Fixes the `osmosisd forceprune` command
- run `osmosisd forceprune` on main => see error
- run `osmosisd forceprune` on this branch => fixed
=> fix: forceprune logic

Makefile
This fixes this error we see in CI releases with goreleaser:
```
Unable to find image 'ghcr.io/goreleaser/goreleaser-cross:v1.22.11' locally
docker: Error response from daemon: manifest unknown.
See 'docker run --help'.
make: *** [Makefile:219: release] Error 125
```
Tested with `release-test` target.
=> Fix goreleaser cross missing image

CHANGELOG.md, go.mod, go.sum
This changes syncs the main branch with the patch applied to v28.x which fixes an issue with the block-sdk.
=> build: block-sdk import now uses forked version

x/lockup/abci.go, x/lockup/keeper/grpc_query_test.go, x/lockup/keeper/iterator.go, x/lockup/keeper/lock.go, x/lockup/keeper/lock_test.go, x/superfluid/keeper/stake_test.go
This PR limits the number of lockups that can be opened in a single block, within the EndBlock logic
=> Bound the number of lockups that can be opened / block

osmomath/decimal.go, osmomath/decimal_test.go, x/gamm/pool-models/stableswap/amm_test.go
Description
This PR addresses #8007 by improving the constants in the stableswap module and adding a standalone ApproxRoot function to avoid
dependency on osmomath's implementation.
The changes include:
1. Replace calculated constants with exact decimal values
- Replace runtime calculations with high-precision string literals
- Add descriptive comments for each constant
- Improve code readability and precision
2. Add standalone ApproxRoot function
- Copy the root approximation logic directly into the stableswap module
- Remove dependency on osmomath's internal implementation
- Ensure identical functionality and behavior
3. Improved documentation
- Add meaningful comments to all constants
- Document the mathematical meaning and approximate values
- Include string representations for …
=> Improve stableswap constant declarations and add standalone ApproxRoot function

.goreleaser.yaml
This PR adds the `acl: public-read` configuration to the S3 blob settings in the GoReleaser configuration. This setting ensures that all files uploaded to the DigitalOcean Spaces bucket are publicly accessible, allowing users to download the release binaries directly.
=> Added public-read on uploaded binaries

CHANGELOG.md, go.mod, go.sum, osmoutils/go.mod, osmoutils/go.sum
Bump IAVL to fix pruning issues
1. https://github.com/cosmos/iavl/releases/tag/v1.2.5
2. https://github.com/cosmos/iavl/pull/1063
3. https://github.com/osmosis-labs/cosmos-sdk/releases/tag/store%2Fv1.1.1-v0.50.11-v28-osmo-3
=> fix: iavl pruning issue move onto next version if stuck

CHANGELOG.md, x/poolmanager/create_pool.go, x/poolmanager/create_pool_test.go
Prevents the cache from being written to during other execution modes like CheckTx, which can lead to inconsistent state during transaction processing. The cache should only be populated during the final execution phase.
=> fix(poolmanager): only write to cache in finalize execution mode

CHANGELOG.md, go.mod, go.sum, osmomath/go.mod, osmomath/go.sum, osmoutils/go.mod, osmoutils/go.sum, x/epochs/go.mod, x/epochs/go.sum, x/ibc-hooks/go.mod, x/ibc-hooks/go.sum
Currently because we remove the codec entry here => https://github.com/osmosis-labs/osmosis/pull/9026 => we removed the codec and this will brick the query.
This is the error:
```
error(*errors.errorString) *{
s: "no concrete type registered for type URL /osmosis.concentratedliquidity.v1beta1.CreateConcentratedLiquidityPoolsProposal against interface *v1beta1.Content",}
```
from this line:
```
osmosis-labs/cosmos-sdk@v0.50.11-v28-osmo-1/types/query/collections_pagination.go:147
```
fix query:
`osmosisd q gov proposals --output json --page-reverse`
Currently on mainnet this fails:
`osmosisd q gov proposals --output json --page-reverse --node https://rpc.osmosis.zone`
The number of proposals that are ignored is:
855 - 847 = 8
see: https://www.mintscan.io/osmosis/proposals
=> fix: query all proposals codec issue

CHANGELOG.md, go.mod, go.sum
Closes: #XXX
Fixes broken dependency:
```
❯ go mod download
go: github.com/coinbase/rosetta-sdk-go/types@v1.0.0: invalid version: git ls-remote -q origin in /home/deividas/go/pkg/mod/cache/vcs/b533490f0e0edb9a52f10692f73836419bd8db7ac5bda88f3c45fc77ca71fdd7: exit status 128:
ERROR: Repository not found.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```
How to reproduce ( on `main`, `v29.x`  ):
```
go clean -modcache # be aware that it may screw your env because downloaded local copy of missing dep will be removed
go mod download
```
=> BE-727 | Fix missing coinbase/rosetta-sdk-go/types dependency

CHANGELOG.md, cmd/osmosisd/cmd/init.go
Closes: [CHAIN-1041](https://linear.app/osmosis/issue/CHAIN-1041/add-seeds-to-the-init-command)
This pull request updates seeds for the init command.
This change is a trivial rework / code cleanup without any test coverage and can be tested manually:
```
go run cmd/osmosisd/main.go init test --home ./.osmosisd
```
```
❯ cat .osmosisd/config/config.toml | grep seeds
seeds = "4557c0e0d90aa17b9c36b1e89fcb27cf23aa3e4c@seed.osmosis.zone:26656,ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:12556"
```
=> CHAIN-1041 | Update seeds for the init command

CHANGELOG.md, app/upgrades/v30/upgrades.go, app/upgrades/v30/upgrades_test.go
Closes: [CHAIN-1072](https://linear.app/osmosis/issue/CHAIN-1072/migration-transfer-top-of-block-funds-from-module-account-to-community)
Transfer top-of-block auction funds to community pool in v30 upgrade.
- unit tested
- in-place-testnet tested
=> feat: transfer top of block auction funds to community pool

CHANGELOG.md, app/apptesting/txfees.go, tests/e2e/README.md, tests/e2e/configurer/chain/commands.go, tests/e2e/containers/containers.go, tests/e2e/helpers_e2e_test.go, tests/e2e/scripts/hermes_bootstrap.sh, x/txfees/keeper/feedecorator_test.go, x/txfees/keeper/keeper_test.go, x/txfees/types/constants.go
Closes: [CHAIN-1069](https://linear.app/osmosis/issue/CHAIN-1069/migration-increase-default-base-gas-price)
Increase consensus min fee to 0.01 uosmo / gas.
- Updated broken existing tests due to this change. 
- Manually setting lower price than min for sending tx.
=> feat: increase consensus min fee to 0.01 uosmo / gas

CHANGELOG.md, x/txfees/keeper/mempool-1559/code.go, x/txfees/keeper/mempool-1559/code_test.go
Due to changes in #9461 which increased `MinBaseFee`, it makes
- previous `DefaultBaseFee` value obsolete -> updated it to be aligned with updated `MinBaseFee`
- when restarting node, it picks up eip state backup file, which could have `CurBaseFee` outside capped range. -> cap `CurBaseFee` when loaded.
=> fix: update DefaultBaseFee and cap CurBaseFee when loaded

CHANGELOG.md, osmoutils/cosmwasm/helpers.go, x/concentrated-liquidity/pool_hooks.go, x/smart-account/ante/ante.go, x/tokenfactory/keeper/before_send.go
Check gas remaining in the parent context's gas meter for tokenfactory hook.
=> Fix: Check gas remaining in the parent context's gas meter wasm call with gas limit

CHANGELOG.md, app/lanes.go, go.mod, go.sum
Fix previous version of block-sdk that resulted in frequent `failed to insert tx into mempool: pool reached max tx capacity` error due to missing duplicated tx detection.
=> Update block-sdk version with DefaultMempool that keep no duplicated tx

.github/workflows/contracts.yml
Closes: #XXX
From `update-artifacts` v4 onwards we cannot upload files with the same name in the same workflow, it will lead to an error
`Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run`
Example: https://github.com/osmosis-labs/osmosis/actions/runs/17824496020/job/50674361770
*(or)*
*(or)*
*(example:)*
- *Added …
=> fix(ci): artifact conflicts
