osmosis-labs/osmosis

cmd/osmosisd/cmd/airdrop.go
cmd/osmosisd/cmd/root.go

Command that generates a quadratic fairdrop snapshot.json based on a provided cosmos-sdk v0.36 genesis export
Let's use this intermediate snapshot.json as the input into a future command the generates the genesis json (based off desired claim properties)

Add airdrop snapshot command

---

x/gamm/client/cli/cli_test.go
x/gamm/client/cli/flags.go
x/gamm/client/cli/parse.go
x/gamm/client/cli/tx.go
x/gamm/client/testutil/test_helpers.go

Instead of passing in all parameters as CLI flags, you can define them in a pool.json file and pass to the create pool command.
Example:
`$ osmosisd tx gamm create-pool --pool-file="path/to/pool.json" --from mykey`
Where pool.json contains:
```
{
"weights": "4uatom,4osmo,2uakt",
"initial-deposit": "100uatom,5osmo,20uakt",
"swap-fee": "0.01",
"exit-fee": "0.01",
"future-governor": "168h"
}
```
Which is equivalent to:
`$ osmosisd tx gamm create-pool --weights 4uatom,4osmo,2uakt --initial-deposit 100uatom,5osmo,20uakt --swap-fee=0.01 --exit-fee=0.01 --future-governor 168h --from=mykey`

Add CreatePool from JSON to x/gamm CLI

---

x/gamm/types/account.go
x/gamm/types/account_test.go

Fixes an issue that I didn't realize was resolvable in #103 , I thought all interface methods had to be the same in terms of pointer receiver vs regular receiver.

Delete Smooth param change params from pool params when done

---

x/gamm/client/cli/cli_test.go
x/gamm/client/cli/flags.go
x/gamm/client/cli/parse.go
x/gamm/client/cli/tx.go
x/gamm/client/testutil/test_helpers.go

As recommended by @ValarDragon, this removes the ability to use CLI flags for the CreatePool msg.  Instead, it only supports the pool.json method added in #120.
This is done because the CreatePool cli flags were quite confusing and likely to be error prone.

Remove CreatePool CLI flags

---

x/claim/abci.go
x/claim/keeper/claim.go
x/claim/types/keys.go

closes #137 
Currently, the claims module runs `EndAirdrop` every block after the airdrop completion time is over.  This PR adds an in-state bool storing whether the airdrop is completed, and only runs the check once it is completed.

only end airdrop once

---

x/mint/keeper/hooks_test.go
x/mint/keeper/keeper_test.go
x/mint/types/params.go

closes #214
* Adjust the tests in x/mint to not use magic numbers for their expected values
* Make a single test for checking that when the developer address is left blank, funds go to the community pool.

Mint test modifications

---

x/gamm/types/pool.go
x/gamm/types/pool_test.go

`updateAllWeights` method had the receiver as struct, so the `totalWeight` field in the pool was not updated.

change the `updateAllWeights` method to have the pointer receiver

---

x/incentives/keeper/gauge.go
x/incentives/keeper/grpc_query.go

Took arbitrary number `100`, please suggest better number who knows better about this

GetRewardsEst grpc query constraints on end epoch

---

cmd/osmosisd/cmd/root.go

fixes the `keys parse` bug: https://github.com/cosmos/cosmos-sdk/pull/9299

fixed parse

---

x/pool-incentives/client/cli/query.go

This PR adds the cli commands in the pool-incentives module to add the following queries.
- Distribution Info(Guage Ids and weights)
- Module params
- Lockable durations
- Incentivized pools

add pool incentives query cli

---

x/epochs/genesis_test.go
x/epochs/types/genesis.go

This issue is related to issue https://github.com/osmosis-labs/osmosis/issues/150.
This PR adds validation in genesis so that the identifier provided in genesis of the epoch module are all unique.
This ensures that multiple definitions do not conflict, namely checking that their identifiers are distinct.

Add validation for unique epoch identifier

---

x/epochs/types/identifier.go
x/incentives/genesis_test.go
x/incentives/types/params.go
x/mint/genesis_test.go
x/mint/types/params.go

This PR is related to issue https://github.com/osmosis-labs/osmosis/issues/192.
This PR adds validateEpochIdentifier, a funciton for validating the epoch identifier so that it has valid epoch identifier, in the epoch module. Doing so would be necessary in the sense of scalability, as the function itself would be duplicated in every module which needs the process of validating the epoch identifier.

Make validateEpochIdentifier a function defined by x/epochs 

---

scripts/unclaimed_airdrop/get_unclaimed_airdrop.py

This is a simple script intended to go from the balance export, to stats on unclaimed airdrop, but accounting forthe already distributed 20% for folks who haven't done any txs yet.
So it outputs the amount technically unclaimed, and the amount unclaimed including the 20% for folks who haven't done anything yet.
Output when I ran it Aug 16th:
```
unclaimed non-already-distributed balance 27788676.819247 osmo
unclaimed & inactive 34648325.61145 osmo
simple prediction for unclaimed and inactive (div by .8) 34735846.02405875 osmo
```

Add script from going from balance export -> unclaimed airdrop amts

---

app/app.go
x/lockup/keeper/lock.go
x/lockup/keeper/upgrade_test.go

This makes the `v4` upgrade logic delete the old accumulation store (so they then get created correctly during the upgrade), and deletes the min commission update logic that got included in the v3 fork.

Make the upgrade logic delete the old accumulation stores

---

x/lockup/keeper/lock_test.go

Increasing the number of locks we use to get stats for here is blocked on CacheKV store things, which I'm hoping to get tomorrow

Make our test for understanding token locking gas usage give more detail

---

.gitignore
CHANGELOG.md
app/test_helpers.go
go.mod
go.sum
x/incentives/keeper/bench_test.go
x/incentives/keeper/gauge.go
x/lockup/keeper/keeper_test.go
x/lockup/keeper/lock_test.go

This switches us to the SDK branch that fixes the N^2 issues within the CacheKV store (https://github.com/osmosis-labs/cosmos-sdk/pull/24 )
It also adds some scaffolding so that we can test with LevelDB backends, which at some point ended up being necessary due to a memDB bug and makes benchmarks more accurate due to avoiding some weird oddities with the memDB.
(I'm not sure if the memDB bug still gets triggered if we make some insanely high loads, but it definitely seemed like a bug on google's sides, as I traced it back when it applied to a perfectly normal set operation that caused google's BTree to infinitely hang)
Before:
```
BenchmarkDistributionLogicMedium-16            4         270370131 ns/op        96074306 B/op    1334220 allocs/op
```
After:
``` …
```

Switch to SDK branch that lowers epoch time

---

.github/workflows/build.yml
.github/workflows/docker.yml

We were double running every build on prior PRs
cc @faddat

Configure CI to not double run docker/builds

---

x/incentives/keeper/gauge_test.go
x/incentives/keeper/suite_test.go

This PR adds more scaffolding to writing tests for gauges. It also adds simpler tests for testing the distsribute function of a gauge, and removes some duplicate code between perpetual and non-perpetual gauge tests.
As I was reading this code, I noticed we have a lot more test cleanup to do, and better testing to be adding here. I'll start writing it into issues, but wanted to add this quick PR

Gauge test improvements

---

CHANGELOG.md
app/app.go
go.mod
go.sum
x/lockup/genesis.go
x/lockup/keeper/bench_test.go
x/lockup/keeper/grpc_query_test.go
x/lockup/keeper/lock.go
x/lockup/keeper/store.go
x/lockup/keeper/upgrade_test.go

This also switches to a version of the SDK fork, that fixes CacheKVStore speed under unfortunate access patterns.

Switch accumulation store to ResetAllLocks, only remove after unbond complete

---

networks/local/osmosisdnode/Dockerfile

This bug prevents the localnet-start target of Makefile from creating necessary files needed for launch of a local testnet in the proper directory. The reason is that the `build` directory is mounted on `/osmosisd`, but the output directory is set to `.` (current directory) which in the docker file is specified as `WORKDIR /omsosisd`; therefore by the time testnet command finishes and docker exits the output files will be lost.

fixed typo bug in osmosisdnode/Dockerfile

---

.github/workflows/lint.yml
app/params/config.go

This PR edits linter so that it only has err check enabled on PRs and pushes to main

Edit linter: only enable errcheck

---

Makefile
x/incentives/types/query.pb.go

* fixing the image version to the latest released (`@latest` is not good)
* optimizing the `make proto-gen` job by reusing proto containers instead of removing them all the time.

chore: reuse docker containers when generating protobuf files

---

x/incentives/keeper/gauge.go

This PR fixes the bug in the current event emitted in the incentive module.
Converting address to string without using the String() method ignores the process of going through bech32 encoding, consequently emitting events with the wrong address attribute, making it impossible to query based on the incentive events.

Hotfix - Fix event attribute in incentives module

---

CHANGELOG.md
x/incentives/keeper/gauge.go

Removes computational overhead introduced in #501, for fixing printed format of bech32 addresses

Remove linear # of bech32 encodes introduced

---

Makefile
x/incentives/keeper/gauge.go
x/lockup/keeper/lock.go
x/lockup/keeper/msg_server_test.go

Makes make lint match whats in CI.
Also fixes two errors that got added in parallel to #491 being merged

Make `make lint` work

---

CHANGELOG.md
x/pool-incentives/types/gov_test.go
x/pool-incentives/types/record.go
x/pool-incentives/types/record_test.go

Closes: #546 
Validation check for pool-incentive gauge weight will only throw for negative values
______

Pool Incentives: Allow Zero Weight

---

cmd/osmosisd/cmd/testnetify/cmd.go

Quick fix for patching the lint error on main. This got introduced in merging #467, which didn't have the latest linter running on it.
______

Fix lint error on main

---

x/lockup/keeper/grpc_query.go
x/lockup/keeper/grpc_query_test.go

Closes: https://github.com/osmosis-labs/osmosis/issues/558
Current querying methods in the lockup module, specifically in grpc_query.go, iterates over all unlocks when user queried with an empty address. (https://github.com/osmosis-labs/osmosis/blob/main/x/lockup/keeper/grpc_query.go#L37-L47).
This PR fixes it so that whenever a query of an lockup with an empty address has been attempted, the query returns an error.
______

Fix grpc query response for empty address in lockup

---

app/ante.go
app/app.go
cmd/osmosisd/cmd/root.go
x/incentives/keeper/gauge.go
x/incentives/keeper/iterator.go

Closes: #591 
Backports the v4.2.0 fixes to main. I simplified the NewMempoolMaxGasPerTxDecorator decorator substantially, since the fees have been relegated to our own separate ante-handler.
The rest of the changes are essentially direct cherry-picks.
______

Backport v4.2.0 updates to main

---

osmotestutils/cli_helpers.go
x/gamm/client/cli/cli_test.go
x/gamm/keeper/invariants.go
x/gamm/keeper/pool_service_test.go
x/lockup/client/cli/cli_test.go
x/lockup/keeper/gas_test.go

This PR contains the following misc test improvements:
* x/gamm: Deduplicate the FundAccounts coins constant
* x/gamm: Fix staticcheck being angry about unnecessary fmt.Sprintf's
* x/lockup: Fix noise from FundAccount in gas_test
* osmotestutils: Add GetFeeString function
* Replace complex fee cli line with simple osmotestutils call
This osmotestutils should accrue more improvements to testing here. The latency of trying to get improvements into the SDK, then back onto our own repo is far too high.
______

misc test improvements

---

app/app.go

Workaround for https://github.com/cosmos/cosmos-sdk/issues/10591 , https://github.com/provenance-io/provenance/blob/407c89a7d73854515894161e1526f9623a94c368/app/upgrades.go#L86-L122
Just do auth upgrade last.
______

Fix v44 auth upgrade bug

---

docs/LP rewards/proposed_architecture/README.md

WIP spec for the F1 fee distribution logic.
All the details described are AFAIK correct / quite efficient, I just think much better descriptions of them are required

WIP spec for F1 Fee architecture

---

app/app.go
go.mod
go.sum

Closes: #601 
Adds the work from the bech32ibc repository into this one. We should ideally switch to a tagged version of that repository before release.
______

Add bech32ibc20 logic to v5 upgrade

---

x/pool-incentives/types/genesis.go
x/pool-incentives/types/genesis_test.go

Due to added validation on genesis on validating whether distr_info in pool-incentives module is non-negative, the default genesis file currently omits error when starting from the initial state.
This PR adds default genesis for distr_info so that it does not omit error when starting chain from the initial state.
______

Add default params to pool-incentives genesis

---

CHANGELOG.md
app/app.go
cmd/osmosisd/cmd/init.go
go.mod
go.sum
x/claim/abci.go
x/claim/keeper/claim.go

This PR brings with it every change from v5.x with cleaned git history into main. Please check its accuracy with the v5.x commit history. This PR should be merge committed, not squashed.
Backporting FeeTokens work, the v5.0.0 upgrade docs, and v6.x changes are relegated to separate PRs
Log of commits:
- Unity's commit, and my commit(s) are done separately. 
- Need to figure out a strategy here so Matt gets the proper git contribution credit.
- Need to figure out strategy so Unity and czar get contribution credit 
- Separate PR for v6 backports
< Needs to be continued>
______

v5.x backports

---

CHANGELOG.md
cmd/osmosisd/cmd/root.go

Closes: https://github.com/osmosis-labs/osmosis/issues/668
This PR sets SilenceUsage to true when creating a root command for osmosis so that RPC errors for queries and txs do not omit all the help usage commands when facing an error.
______

Add Silence usage to rootCmd

---

docs/overview/osmosis-app/README.md

Fixes typo in osmosis usage documentation.
______
No changelog entry is needed since this PR only fixes a typo in the documentation

fix: slippage spelling for osmosis docs

---

scripts/statesync.sh

This makes state sync work correctly, in a single go.
______

State Sync

---

app/ante.go
app/app.go
app/export.go
app/forks.go
app/keepers.go
app/upgrades/v4/prop12.go
app/upgrades/v4/upgrades.go
go.mod
go.sum
x/claim/keeper/claim_test.go
x/epochs/abci_test.go
x/epochs/genesis_test.go
x/gamm/genesis_test.go
x/incentives/genesis_test.go
x/lockup/genesis_test.go
x/lockup/keeper/admin_keeper_test.go
x/lockup/keeper/msg_server_test.go
x/mint/keeper/keeper_test.go
x/mint/keeper/querier_test.go
x/pool-incentives/genesis_test.go
x/pool-incentives/keeper/distr_test.go
x/txfees/keeper/feedecorator_test.go

This is an alternate design to #696 , I actually like this better. It doesn't involve sweeping breaking changes across the app tests. I think we get the benefits of split up methods, and pointers unless necessary to not use them, without sacrificing usability elsewhere. I think we can get the abstraction we want in a keepers module still, by making a method to go from app -> AppKeepers struct, but not force its use throughout. (This is also really low priority imo)
We are refactoring initializing keepers into five steps, using pointer refs to keepers the whole way through:
* Initializing keepers with special SDK tie-ins", e.g. UpgradeKeeper, ParamsKeeper, CrisisKeeper, CapabilityKeeper.
* Setup upgrade keeper store loaders for new modules
* Initialize all other keepers
* Setup all the …

Make all keepers pointers, use multiple initialization methods

---

CHANGELOG.md
app/keepers.go
x/txfees/handler.go

Add update fee token gov handler to app.go

---

cmd/osmosisd/cmd/init.go
cmd/osmosisd/cmd/root.go

Closes: #XXX
Copy & Paste
______

remove duplicate app.toml code

---

CHANGELOG.md
app/ante.go
app/app.go
cmd/osmosisd/cmd/root.go
x/gamm/types/msg_lp.go
x/gamm/types/msg_swap.go
x/txfees/README.md
x/txfees/keeper/feedecorator.go
x/txfees/keeper/txfee_filters/README.md
x/txfees/keeper/txfee_filters/arb_tx.go

Closes: #723 
This PR adds a mempool filter for arbitrage txs. When its hit, it charges a separate gas price, as specified in the full nodes application config.  This defaults to `0 uosmo` if not set in the app.toml, but the app.toml defaults to `.005uosmo/gas`.
The detection algorithm for arbitrage txs does have some false positives, and likely many false negatives. The false positives are described in the code comments, and I think are pretty miniscule. (Only thing I can see hitting it is a service that batches many users swap / LP positions together. Such a batching service seems like it can maintain connections to folks with lower fees though)
______

Arbitrage tx mempool filter

---

CHANGELOG.md
cmd/osmosisd/cmd/balances_from_state_export.go
osmotestutils/cli_helpers.go
x/pool-incentives/client/cli/tx.go

722 reuse code for parsing integer slices from string

---

app/keepers.go
x/incentives/keeper/keeper.go
x/lockup/keeper/keeper.go
x/lockup/types/expected_keepers.go

Closes: [#716](https://github.com/osmosis-labs/osmosis/issues/716)
Currently keeper in the lockup module and the incentives module are using authkeeper as a struct, importing directly from the cosmos-sdk instead of using them with the usage of `expected_keeper.go`.
This PR suggests change in the lockup module so that it uses accountKeeper interface via expected_keeper. 
Additionally, it was found that accountKeeper was imported in incentives module without any usage. Thus, this PR also includes removing taking in accountKeeper as a parameter for the incentives module keeper, resulting in changes in `app.go` as well.
______

fix: Change usage of account keeper in lockup module, incentives module

---

Makefile

Add build flags for rocksdb to the makefile

add rocksdb option to makefile

---

go.mod
go.sum

Made bech32ibc 0.2.0-rc2, added to go.mod and go.sum. Removed older 0.2.0-rc1 from go.sum.
Allows for use of `--from` flag to create `update-hrp-ibc-record` proposal 
______

create/add fix for --from flag for bech32ibc

---

app/keepers.go

The whole point of the keepers.go refactor was to make the keeper on the app a pointer =)
See line 142, `app.StakingKeeper = &stakingKeeper`. This just makes this section cleaner
______

Make staking keeper passing more idiomatic

---

CHANGELOG.md
Makefile

localtestnet docker image directory was incorrect
Fixes a minor bug in `Makefile`.
______
n/a: only a bug fix

Makefile fix

---

go.mod
go.sum

Incorporates Dev's `dev/cherry-pick-bank-validity-changes` from osmosis' cosmos sdk repo into main. Allows user to send tx to non osmo1 address (making bech32ibc forwarding useable)

change to dev/cherry-pick-bank-validity-changes

---

CHANGELOG.md
go.mod
go.sum

See : https://github.com/osmosis-labs/cosmos-sdk/pull/58
______

Fix bug with rechecking not removing txs w/ old sequence number

---

docs/developing/rocksdb.md

re-open against correct branch

create rocksdb guide

---

CHANGELOG.md
app/ante.go
cmd/osmosisd/cmd/root.go
x/txfees/README.md
x/txfees/keeper/feedecorator.go
x/txfees/keeper/feedecorator_test.go
x/txfees/types/options.go

Closes: #724
- Refactor osmosis mempool filter
- Add separate min gas price option for txes with high gas wanted
I think we should not move `HighGasTxThreshold` parameter into consensus, but leave it just as a node option. If so, it's better to add it to `app.toml`
Do not waste time for choosing words, if something is wrong just said it straightforward, i am OK with that.
______

Add separate min gas price option for txes with high gas wanted

---

app/app.go
go.mod
go.sum
x/gamm/keeper/gas_test.go
x/lockup/keeper/gas_test.go

Closes: #676
Update go.mod once https://github.com/osmosis-labs/cosmos-sdk/pull/59 is approved
______

upgrade to cosmos sdk v0.45

---

.github/dependabot.yml
CHANGELOG.md

Closes: #791 
Change to dependabot config to only upgrade patch version of tendermint
______

Change to dependabot config to only upgrade patch version of tendermint

---

CHANGELOG.md
x/incentives/keeper/gauge.go

Consolidate code between InitGenesis and CreateGauge

---

x/incentives/keeper/gauge.go

Currently, the `SetGaugeWithRefKey` method which is getting called in initGenesis for the incentive module has duplicate code where setGauge would be done twice(at the beginning of the method, at the end of the method). 
This PR removes the duplicate instance of setting gauges.
______

Delete duplicate usage of setGauge at Incentives module InitGenesis

---

cmd/osmosisd/cmd/init.go

Closes: #805 
Backports the automatic addition of seeds to the v3.x series of osmosis so that making archives is easier. 
______

backport seeds to v3.x for consistent directions

---

cmd/osmosisd/cmd/root.go
go.mod

Closes: #792 
IAVL cache configuration, set to 128mb by default
______

Configure iavl cache

---

app/genesis.go
app/upgrades/v7/upgrades.go

Builds on #822 
This ensures the permissioned parameters are set when doing a migration and not coming from genesis
______

Add migration step to make x/wasm permissioned

---

scripts/multinode-local-testnet.md
scripts/multinode-local-testnet.sh

Created by @mattverse and myself
This script creates a multi node local testnet with three validator nodes on a single machine. 
Clone the osmosis repo
Checkout the branch you are looking to test
Make install / reload profile
Give the script permission with `chmod +x multinode-local-testnet.sh`
Run with `./multinode-local-testnet.sh` (allow ~45 seconds to run, required sleep commands due to multiple transactions)
Validator1: `tmux a -t validator1`
Validator2: `tmux a -t validator2`
Validator3: `tmux a -t validator3`
Validator1: `$HOME/.osmosisd/validator1`
Validator2: `$HOME/.osmosisd/validator2`
Validator3: `$HOME/.osmosisd/validator3`
Validator1: `1317, 9090, 9091, 26658, 26657, 26656, 6060`
Validator2: `1316, 9088, 9089, 26655, 26654, 26653, 6061`
Validator3: `1315, 9086, 9087, 26652, …

Multi-node Local Testnet Script

---

CHANGELOG.md
go.mod
go.sum
x/txfees/keeper/feedecorator_test.go

Closes: #XXX
**Background**
This release introduces an upgrade of iavl and the SDK with fast storage implementation that represents a copy of the latest version of the tree with performance improvements. The fast storage nodes are indexed by key on disk as opposed to by hash with the original tree implementation. It allows us to preserve data locality for the latest state, significantly improving iterations and queries. This implementation introduces a negligible overhead for writes.
**Downgrade-re-upgrade protection**
We introduced a downgrade and re-upgrade protection where we guard for potential downgrades of iavl and the subsequent enablement of the fast storage again. This is done so by storing the metadata about the current version of the storage and the latest live state stored. …

Upgrade iavl and sdk with fast storage

---

x/lockup/keeper/iterator.go
x/lockup/keeper/lock.go
x/lockup/keeper/lock_refs.go
x/lockup/keeper/store.go
x/lockup/types/lock.go
x/lockup/types/types.go

This makes the code more structured, and is a precursor to a subsequent commit
of trying to de-duplicate a lot of this logic to reduce API & bug surface
I'm making this a separate PR to make it easy to review method re-shuffles / refactor work, independently from changes into the logic.

Move lock.go functions into iterator.go, lock_refs.go and store.go

---

x/epochs/client/cli/query.go
x/lockup/client/cli/flags.go

Fixes two queries
`osmosisd query lockup total-locked-of-denom gamm/pool/1`
Wont work since it tries to use `1d` as default min duration. Changed default to 86400s.
`osmosisd query epochs current-epoch -h`
Shows weekly as a potential input but its week not weekly. While I was at it I just changed default to day since it is most used.
______

min duration from days to hours, changed weekly to day

---

.dockerignore
CHANGELOG.md
Dockerfile

Addresses #816
This PR introduces a new Dockerfile to build and distribute the `osmosisd` binary.
The Dockerfile uses [multistage build](https://docs.docker.com/develop/develop-images/multistage-build/) process and serves `osmosisd` inside a [distroless base container image](https://github.com/GoogleContainerTools/distroless).
To test the Dockerfile against the latest tag (but any commit will do):
```bash
git clone https://github.com/osmosis-labs/osmosis
cd osmosis
git checkout v6.3.0
docker build -t osmosis:v6.3.0 .
```
Then you can run the container as you normally would do with the binary:
```bash
docker run osmosis:v6.3.0 version 
```
______

Update Dockerfile to use distroless base image

---

cmd/osmosisd/cmd/balances_from_state_export.go
osmoutils/cache_ctx.go
osmoutils/cli_helpers.go
x/gamm/client/cli/cli_test.go
x/lockup/client/cli/cli_test.go
x/pool-incentives/client/cli/tx.go
x/superfluid/keeper/distribution.go

@antstalepresh made a neat method for doing this in a few places in the
superfluid epoch logic. This just refactors it to a standalone method in
osmoutils.
Furthermore, this PR also renames osmotestutils -> osmoutils, which
is a change I've wanted to make for a while.
______

Add a method to osmoutils for having a function write to state if no err

---

go.mod
go.sum
x/claim/keeper/hooks.go
x/lockup/keeper/lock_refs.go
x/superfluid/keeper/hooks.go
x/superfluid/keeper/hooks_test.go
x/superfluid/keeper/intermediary_account.go
x/superfluid/keeper/slash.go
x/superfluid/keeper/slash_test.go
x/superfluid/keeper/stake.go
x/superfluid/spec/08_hooks.md
x/superfluid/spec/11_slashing.md
x/superfluid/types/expected_keepers.go

Makes superfluid slashing work. It now starts from a slash validator hook for a validator.
The superfluid module is then responsible for slashing every intermediate account's underlying delegation,
and the undelegations to that validator.
It does this, by getting all synthetic lockups for the underlying denom the IA represents.
It then slashes each of those synthetic lockups.
THought this was already PR'd earlier 😓 
______

Superfluid slashing code

---

CHANGELOG.md
go.mod
go.sum

Closes: #XXX
The main focus of this upgrade is stability improvements with the IAVL patch of v0.44.3x-osmo-v5.1. The big points are:
- Fixes the "version X was already saved to a different hash" and "insufficient funds" bugs nodes were sometimes seeing after crashes.
- Reduce the RAM overhead during the initial IAVL migration. Node operators should still have 32GB of RAM for all of their mainnet nodes.
- Improving the log messages during migrations
The bugs people were seeing for nodes being saved to a different hash, etc. happen after restoring the node post-crash during commit (the crash could be caused by something else). The bug on restart stems from the long-standing issue that SDK commits are actually not-atomic. This manifested in a failure to flush the latest height when an error …

Upgrade IAVL and SDK with RAM improvements and bug fixes for v6.4

---

scripts/multinode-local-testnet.sh

The current multinode script has the bug that some parts of the genesis would be using `stake` where as some parts would be using `uosmo`, which consequently casuses problems in minting etc. 
This PR adds additional changes to genesis so that all parts of genesis uses uosmo as basedenom.
______

Modify multinode script to have uosmo base in gensis

---

app/keepers.go
x/superfluid/keeper/epoch.go
x/superfluid/keeper/gov/gov.go
x/superfluid/keeper/gov/gov_test.go
x/superfluid/proposal_handler.go

Current gov proposal does not set OsmoEquivilentMultiplier, thus not being able to handle superfluid delegation upon first epoch after gov proposal has passed. 
This PR modifies superfluid/gov to set OsmoEquivilentMultiplier at its initial state
______

Modify superfluid/gov to set OsmoEquivilentMultiplier

---

go.mod
go.sum
x/superfluid/keeper/stake.go
x/superfluid/keeper/stake_test.go
x/superfluid/types/expected_keepers.go

bank supply offsets

---

scripts/multinode-local-testnet.sh

This needs to be changed now that we are no longer using `unbonding_duration`
Also switched to using day epoch. Ran into issues when using min on recent superfluid changes.
______

removed superfluid change, uses 60s day epoch rather than min epoch

---

x/superfluid/client/cli/tx.go
x/superfluid/keeper/stake_test.go

This PR adds go tests and cli for `SuperfluidUnbondLock`.
Testing for SuperfluidUnbondLock covers the following areas: 
1. test SuperfluidUnbondLock does not work before undelegation
2. test SuperfluidUnbondLock makes underlying lock start unlocking
3. test that synthetic lockup being finished does not mean underlying lock is finished
4. test after SuperfluidUnbondLock + lockup time, the underlying lock is finished
______

Add SuperfluidUnbondLock test and cli

---

x/superfluid/keeper/epoch.go
x/superfluid/keeper/hooks.go
x/superfluid/keeper/intermediary_account.go
x/superfluid/keeper/msg_server.go
x/superfluid/keeper/slash.go
x/superfluid/keeper/stake.go
x/superfluid/keeper/stake_test.go
x/superfluid/keeper/superfluid_asset.go
x/superfluid/spec/12_minting.md
x/superfluid/types/events.go
x/superfluid/types/superfluid.go

Closes: #XXX
I want us to keep stake.go methods as having minimal lines for readability, and to push events / other wrapping to other components.
The events for now have been pushed to the message server.
Also improves the SuperfluidDelegateMore events
______

Move events out of stake.go

---

x/lockup/genesis_test.go
x/lockup/keeper/admin_keeper.go
x/lockup/keeper/export_test.go
x/lockup/keeper/grpc_query_test.go
x/lockup/keeper/iterator.go
x/lockup/keeper/lock.go
x/lockup/keeper/lock_refs.go
x/lockup/keeper/lock_test.go
x/lockup/keeper/store.go
x/lockup/keeper/store_test.go
x/lockup/keeper/utils.go
x/lockup/spec/02_state.md

Cref #447 
Basically for a long time, we've known that we've been adding extra keys to bonding locks that are useless. This removes the creation of those useless ref keys, helping reduce the write load of our migration.
We are still deleting all refkeys, even if they don't exist. This is because we shouldn't keep any ref keys in state that aren't valid.
______

Make creation of a bonded lock not create unused time keys

---

app/keepers.go
x/lockup/handler.go
x/lockup/keeper/msg_server.go
x/lockup/keeper/msg_server_test.go
x/superfluid/client/cli/tx.go
x/superfluid/keeper/keeper_test.go

Closes: #XXX
@mattverse 
______

Fix message server init

---

x/superfluid/keeper/synthetic_lock_wrapper.go

Closes: #XXX
smh, trimprefix does not work how we'd expect
______

Fix broken query

---

x/pool-incentives/genesis_test.go
x/superfluid/types/codec.go

https://github.com/cosmos/cosmos-sdk/issues/10870
______

Fix amino codec route

---

app/apptesting/test_suite.go
x/superfluid/keeper/hooks_test.go
x/superfluid/keeper/keeper_test.go

Adds some helpers for testing various functions in a re-usable way in app.go
I think this should probably be paired with more custom functions / integrations in modules, to get a more composable testing framework. This at least does a first step with setting up validators, and epochs across modules.
I am torn on whether it should be suiteI, or an embeddable struct though. I'm leaning towards making it an embeddable struct.
______

Add some helpers for testing to its own package in app

---

go.mod
go.sum

upgrade iavl to v0.17.3-osmo-v4 - fix old height export

---

app/apptesting/test_suite.go
x/superfluid/keeper/distribution_test.go
x/superfluid/keeper/grpc_query_test.go
x/superfluid/keeper/hooks_test.go
x/superfluid/keeper/intermediary_account_test.go
x/superfluid/keeper/keeper_test.go
x/superfluid/keeper/slash_test.go
x/superfluid/keeper/stake_test.go
x/superfluid/keeper/superfluid_asset_test.go
x/superfluid/keeper/twap_price_test.go

Extension for pull https://github.com/osmosis-labs/osmosis/pull/1008.
We should compare this with the interface approach and compare on usability
______

Apptesting: Change Interface to Struct

---

go.mod

* move gorocksdb into the indirect dependencies group.
* mild annotation to help new devs
______

move gorocksdb lib into indirect and annotate go.mod

---

CHANGELOG.md
go.mod
go.sum

With help from @p0mvn , bumping IAVL version to v0.17.3-osmo-v4 in order to prevent app hash errors when syncing from gen.
______

Upgrade IAVL and SDK to v0.17.3-osmo-v4

---

x/lockup/client/cli/flags.go
x/lockup/client/cli/tx.go

add partial unlocking flag for cli

---

CHANGELOG.md
go.mod
go.sum

upgrade iavl to v0.17.3-osmo-v5 with concurrent map write fix

---

CHANGELOG.md
Dockerfile

This repository improves our Dockerfile by:
- Using `base-debian11:nonroot` over `base-debian11` to avoid running container as root
- Uses the `/osmosis` folder as `$HOME` directory for the container
- Statically links `libwasmvm_muslc.a` as in https://github.com/CosmWasm/wasmd/blob/master/Dockerfile
Usage:
```bash
docker run --rm -it -v $HOME/.osmosisd/:/osmosis/ osmolabs/osmosis:v7.0.4 <subcommand>
```
Example:
```bash
docker run --rm -it -v $HOME/.osmosisd/:/osmosis/ osmolabs/osmosis:v7.0.4 init my-moniker
```
You can create an alias to simplify the command:
```bash
alias osmosisd="docker run --rm -it -v $HOME/.osmosisd/:/osmosis/ osmolabs/osmosis:v7.0.4"
```
and then simply:
```
osmosisd init my-moniker 
```
______

Improve Dockerfile

---

x/superfluid/keeper/grpc_query.go
x/superfluid/keeper/grpc_query_test.go

Closes: #[1080](https://github.com/osmosis-labs/osmosis/issues/1080)
This PR introduces the following improvements for grpc_query in the superfluid module.
- Fix bug where non-existent connected-intermediary-account would still return an address
- Fix bug for `total_supefluid_delegations`
______

Superfluid Misc: Improve grpc_query

---

x/superfluid/genesis.go
x/superfluid/genesis_test.go

Genesis import export check for superfluid

---

CHANGELOG.md
x/incentives/module.go
x/lockup/module.go
x/superfluid/module.go

Closes #1093
We already did this on the gamm module before. No other module has new message types.
______

Register message server on osmosis modules

---

.github/workflows/build.yml

Closes: #XXX
Small follow up on #1107
______

Re-enable build matrix on arm64 on darwin, using wasmd 0.24

---

proto/osmosis/incentives/gauge.proto
proto/osmosis/incentives/tx.proto
proto/osmosis/lockup/lock.proto
proto/osmosis/superfluid/genesis.proto
proto/osmosis/superfluid/superfluid.proto
x/incentives/types/gauge.pb.go
x/incentives/types/tx.pb.go
x/lockup/types/lock.pb.go
x/superfluid/types/superfluid.pb.go

Closes: #863 
Moves inline comments in proto files to separate line(s) before so that they're properly shown in the generated `.pb.go` files. Should be a no-op in functionality. First PR so lmk if I missed something. What I did:
- Grepped for all `; //` in `*.proto` files and move those comments to separate lines
- Ran `make proto-all` to format proto files and generate docs
The `make` command made some local edits to `go.sum`, chose not to include them but lmk if I should check them in.
______

Reformat in-line comments in proto files

---

x/gamm/keeper/multihop.go
x/gamm/keeper/pool.go
x/gamm/keeper/swap.go

Makes internal methods with swap fee exposed. Needed for:
- Getting compound swap fee estimates (needed for mempool work)
- Enabling different multihop swap fees
- (Future) work on raised swapfees during chain liveness failures.
This PR also fixes getPoolForSwap usage
______

Refactor some keeper methods, to expose primitives needed for multihop routing

---

x/txfees/keeper/feetokens.go
x/txfees/keeper/feetokens_test.go

This PR handles a possible bug in the txfees module. 
The current test cases could be the most intuitive example, where we created a pool with 100 base denom and 200 foo tokens. If we're using 10 foo tokens as the input fee, we should expect it to be converted to 5 base denom, not 20 base denom. 
This PR also includes deleting ceil for the calculated spot price. Using the same example above that was used for the test case, the user would be required 5.000000000005368710 base tokens, but this would be ceiled and would be required as 6 basetokens.
______

Fix: txfees module

---

CHANGELOG.md
app/config.go
cmd/osmosisd/cmd/root.go
go.mod
go.sum

Closes: #XXX
- upgraded iavl and SDK with the most recent database stability improvements
- changelog updated
______

Database stability improvements

---

x/gamm/keeper/grpc_query_test.go
x/gamm/keeper/keeper_test.go
x/gamm/pool-models/balancer/amm.go
x/gamm/pool-models/balancer/amm_test.go
x/gamm/types/constants.go
x/pool-incentives/keeper/keeper_test.go

Closes: #1155 
* Calculates SpotPrice with ratios to prevent trailing digits from giving incorrect results
* Utilizes constant in x/gamm/types to determine how many significant figures we calculate SpotPrice to (other functions can also use this SigFigs constant now)
* Added a test to show a circumstance in which the 9th digit is greater than 5, and with 8 sigfigs set should remove the 9th digit however still round the 8th digit up
* Added comment to explain why this change was added

Calculate SpotPrice with Ratios and SigFigs

---

CHANGELOG.md
x/lockup/keeper/msg_server.go

Current endtime in logs (MsgBeginUnlocking) is wrong: `0001-01-01 00:00:00 +0000 UTC`  because it is updated inside BeginUnlock and eventManager uses outdated lock, i wanted to return the updated lock from that function but it has many references, a quick fix is to get the lock again.
this also includes verifying the owner conditional before BeginUnlock is executed.
> endtime field could also be added to `MsgBeginUnlockingResponse`.
______

x/lockup: Get updated lock for events

---

.github/workflows/build.yml
.github/workflows/sim.yml
.github/workflows/test.yml
CHANGELOG.md
Dockerfile
go.mod

Closes: #XXX
Update Osmosis to go 1.18
Question: how can we make it also backport?
______

update to go1.18

---

x/gamm/keeper/pool.go
x/gamm/pool-models/balancer/balancer_pool.go
x/gamm/pool-models/balancer/balancer_pool_test.go
x/gamm/types/pool.go

Closes: #1183
Adds comments for all of the pool interface methods.
Deletes some deadcode around the IsActive function / test thats not really achieving much at the moment. It also changes its API to take in ctx directly.
______

Add godocs for pool interface

---

tests/e2e/chain.go
tests/e2e/e2e_setup_test.go
tests/e2e/e2e_test.go

Closes: #1200 
1. Added a second chain
2. Created a constant for human readable chain names
3. Used different values for chainB's osmo/stake balance to ensure the balance query is tracking the correct chain
4. Included chainB in the QueryBalances test
______

second e2e chain with expanded test

---

Makefile

Closes: #XXX
Quick fix for the failing `make-test`. The issue was that there were 4 spaces instead of a tab. 
I thought that another problem is that the CI job does not fail when running make does: https://github.com/osmosis-labs/osmosis/runs/5873348591?check_suite_focus=true
However, that is not a problem because due to spaces, the job was simply not found and makefile returned exit code 0. We just need to be careful and make sure that the makefile is written correctly.
______

fix make test-cover

---

.vscode/settings.json

- JSON prettyify/format
- Add proto formatting settings
______

chore: vscode setting updates

---

docs/core/proto-docs.md
docs/protodoc-markdown.tmpl
scripts/protocgen.sh

This PR adds proto docs in docs/core directory, which is auto-generated whenever we run `make proto-gen`. 
Also modified protocgen.sh file which is triggered by make proto-gen. 
As of now, the proto-docs.md includes all proto documentations except `gamm/pool-models/balancer` 
cref: https://github.com/bufbuild/buf/issues/99#issuecomment-655834414
(Also explains why we’re currently getting no errors when we do `proto-gen`)
We have duplicate symbols in https://github.com/osmosis-labs/osmosis/blob/main/proto/osmosis/gamm/pool-models/balancer/tx.proto#L9  and https://github.com/osmosis-labs/osmosis/blob/main/proto/osmosis/gamm/v1beta1/tx.proto#L9, and as a getaway ( we might need a permanent solution for this), restricted the maxdepth of proto docs generation, which excludes …

Add proto docs

---

.vscode/settings.json

Closes: #XXX
https://github.com/osmosis-labs/osmosis/pull/1221#discussion_r845570324
______

chore: remove testOnSave vs code setting

---

scripts/statesync-rocks.bash
scripts/statesync.sh

NB: Previously, osmosis would apply all snapshots, then crash.
Currently, osmosis applies all snapshots, and stays live.  Because it stays live, these scripts don't work correctly.
I have a machine doing a rocksdb sync now, and hope to prune that but nothing makes tiny snapshots like statesync.
Pursuant to #695 
______

Update state sync scripts

---

app/apptesting/test_suite.go
app/upgrades/v5/whitelist_feetokens.go
app/wasm/queries.go
x/gamm/genesis.go
x/gamm/genesis_test.go
x/gamm/keeper/grpc_query.go
x/gamm/keeper/invariants.go
x/gamm/keeper/multihop_test.go
x/gamm/keeper/pool.go
x/gamm/keeper/pool_service.go
x/gamm/keeper/pool_service_test.go
x/gamm/pool-models/balancer/amm_test.go
x/gamm/pool-models/balancer/balancer_pool.go
x/gamm/pool-models/balancer/balancer_pool_test.go
x/gamm/pool-models/stableswap/pool.go
x/gamm/types/pool.go
x/pool-incentives/keeper/grpc_query_test.go
x/pool-incentives/keeper/keeper_test.go
x/superfluid/keeper/epoch.go
x/superfluid/keeper/hooks_test.go
x/superfluid/simulation/proposals.go
x/superfluid/types/expected_keepers.go

Closes: #1213
- Add `PokePool` to the `Pool` interface
- Rename `GetPool` -> `GetPoolAndPoke`
- Rename `GetPools` -> `GetPoolsAndPoke`
______

refactor: add PokeTokenWeights to Pool interface

---

.github/workflows/lint.yml

Closes: #XXX
Realized we never updated our Github Actions CI lint job to use the canonical `make lint` target.
______

chore: update lint CI job

---

go.mod
go.sum

Closes: https://github.com/osmosis-labs/osmosis/issues/1267
NOTE! I‘m using the proposed PR template for this PR, to demonstrate how it can work
Upgrade zondax/hid to remove build warnings and noise on mac
- upgrade zondax/hid from 0.9.0 to 0.9.1, by referencing [this fix](https://github.com/cosmos/cosmos-sdk/pull/11307) from Cosmos SDK
Please reference the before v.s. after screenshots to see the warnings are gone and build messages are much cleaner. Note that the screenshot diffs are already based on https://github.com/osmosis-labs/osmosis/pull/1266 which removed massive keyring warnings already
Screenshot before this change:
Screenshot after upgrading the lib:
- Is PR targeted against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targe …

upgrade zondax/hid to remove build message warning on macos 12

---

go.mod
go.sum

Closes: https://github.com/osmosis-labs/osmosis/issues/1265
NOTE! I‘m using the proposed PR template for this PR, to demonstrate how it can work
Upgrade keyring to remove build warnings and noise on mac
- upgrade keyring from 1.1.6 to 1.2.1, by referencing [this fix](https://github.com/apache/pulsar-client-go/pull/719) from Apache Pulsar
Please reference the before v.s. after screenshots to see the warnings are gone and build messages are much cleaner.
Screenshot before this change:
Screenshot after upgrading the lib:
- Is PR targeted against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))  (yes)
I tested locally, `make test` passed.
- Does this pull …

upgrade 99designs/keyring to remove build warnings on Macos

---

cmd/osmosisd/cmd/init.go

This pr adds the pbcups seed node to init.go
______

Add seed from pbcups

---

.build.sh
CHANGELOG.md
Makefile
contrib/images/Makefile
contrib/images/rbuilder/Dockerfile
contrib/images/rbuilder/README.md
contrib/images/rbuilder/buildlib.sh

Closes: #1284
This change fixes our `make build-reproducible` Makefile step to generate release binaries. As described in the issue #1284, our current binaries do not have cosm wasm dependencies correctly installed. Wasmvm binaries need to be statically linked.
On initial investigation, I observed that our `rbuilder` is broken when built locally. The version from docker hub that is used by default when local version is not available has not been updated in around a year and does not work with the `main` branch of our repository.
As a result, our `rbuilder` was fixed in this PR by referencing the updated version here: https://github.com/tendermint/images/tree/master/rbuilder
Additionally, it does not make sense to rely on the cosmoshub image (`cosmossdk/rbuilder:latest`). That is not built …

fix: release build scripts

---

x/superfluid/spec/README.md

Fix docs navigation & update diagram's path

---

.github/pull_request_template.md

Closes: https://github.com/osmosis-labs/osmosis/issues/1261
NOTE! I‘m using the proposed PR template for this PR, to demonstrate how it can work
Adding a bit more templating to help smooth the review process, as well as fostering a engineering habit of emphasizing documentations and tests.
- updated PR template with more critical self-check aspects for PR submitters, while trying to keep it simple and lean
- Is PR targeted against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))  (yes)
- Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? …

enrich existing PR template to smooth the review process

---

CHANGELOG.md
osmoutils/cache_ctx.go
x/epochs/spec/05_hooks.md
x/epochs/types/hooks.go
x/epochs/types/hooks_test.go

This PR aims to mitigate the risk of a panic within the epoch logic causing a chain halt (or even a halt of subsequent epoch actions). A subcomponent of #1305 
- Add panic recovery to the epoch hooks
- Improve the panic recovery -> string printing mechanism
* This adds a test case to ensure that: Panics are actually caught in an `x/epochs/hooks_test.go`
We still need to test that this does not notably increase the epoch time. (Due to https://github.com/cosmos/cosmos-sdk/issues/10310 )
I want to understand that issue better, but it may be that the best way to test it is to get this cherry-picked on a v7 branch and just run it. …

Epoch hooks, panic recovery

---

app/app.go
app/upgrades/README.md
app/upgrades/v8/constants.go
app/upgrades/v8/upgrades.go

This PR adds boilerplate for the v8 upgrade handler. Simplifies the logic for upgrade store handler updates. Intended as a precursor for #1301 
- Adds boilerplate for the v8 upgrade handler. I don't think this necessitates an entry in the actual changelog.
This change should be tested in upcoming upgrade handler testing on testnets / in framework. It needs an end to end test to properly test changes to the store loaders.
- How is the feature or change documented? NA

Add upgrade handler for v8

---

CHANGELOG.md
cmd/osmosisd/cmd/forceprune.go

Follow up PR to #1262, it shuffles the logic into functions, so each db opening and closing all happens in a single scope. (And therefore defer closes work as expected)
Beyond DB closing behavior, the logic should be identical 
cc @moniya12
No logic change, just code structure updates to the forceprune command. Also updates variables names from snake case to camel case (matching the rest of the repo)
- Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? no (not needed)

Move forceprune logic into functions, make db open/closes all in a single scope

---

scripts/generate-docs.sh
scripts/generate-proto.sh
scripts/protocgen.sh

Closes: #504
So these 3 scripts for generating protobuf ( [generate-proto.sh](https://github.com/osmosis-labs/osmosis/blob/main/scripts/generate-proto.sh),
[generate-docs.sh](https://github.com/osmosis-labs/osmosis/blob/main/scripts/generate-docs.sh), [protocgen.sh](https://github.com/osmosis-labs/osmosis/blob/main/scripts/protocgen.sh) ) use [go list](https://github.com/osmosis-labs/osmosis/blob/039f686ed40008228db65352ad09d1f38a8f88cb/scripts/protocgen.sh#L11) to get the `cosmos-sdk` dependency in go/pkg/mod. But `go list` doesn't work properly if we have a vendor folder, so I move the vendor folder to a temp folder to run `go list` and then move it back right after running `go list`.

make proto gen scripts compatible with vendor

---

app/app.go
app/export.go
app/keepers/keepers.go
app/keepers/keys.go
app/modules.go
go.mod

Closes: #1319 
- Move appKeepers struct to a different package
- Create new package called `keepers` at `app/keepers`,
- Move logic from `app/keepers.go` to new module
* This change is a trivial rework / code cleanup without any test coverage.

Move appKeepers struct to a different package

---

CHANGELOG.md
cmd/osmosisd/cmd/root.go
go.mod
go.sum

Closes: #XXX
This pull request updates the sdk fork from v0.45.0x-osmo-v7.7 to  v0.45.0x-osmo-v7.8.1.
- fix: add tendermint command (backport https://github.com/osmosis-labs/cosmos-sdk/pull/193)
- feat: support send and recv msg size for gRPC (backport https://github.com/osmosis-labs/cosmos-sdk/pull/170)
- refactor: address snapshot/pruning refactor comments upstream (https://github.com/osmosis-labs/cosmos-sdk/pull/184)

chore: upgrade sdk to v0.45.0x-osmo-v7.8.1

---

x/gamm/pool-models/stableswap/msgs.go
x/gamm/types/errors.go

Closes: #1364 
Add validation check to stableswap's `msg.ValidateBasic()` function linked to in issue #1364.
- Check if initial liquidity supplied to pool has exactly two assets (this will eventually need to be expanded to accommodate multi-asset stableswap pools)
We are currently missing a msgs_test.go file for this (and other functions related to creating pools) to be tested in. Created a new issue for this here: https://github.com/osmosis-labs/osmosis/issues/1384#issue-1222513046

Add initial pool liquidity validation to stableswap msg.ValidateBasic function

---

CHANGELOG.md

Didnt update changelog on v7.x as well when I made the v7.2.1 release

chore: v7.x update CHANGELOG.md

---

app/ante.go
app/upgrades/v8/msg_filter_ante.go
app/upgrades/v8/msg_filter_ante_test.go
x/superfluid/keeper/msg_server.go

Add an AnteHandler decorator that provides (height-gated) message filtering for the v8 upgrade.

feat: add height-gated AnteHandler message filter

---

app/upgrades/v8/unpool_whitelist.go

Add additional pool IDs that have UST, but weren't in the proposal. IMO and interpretation suggests the spirit of the prop was to include pools with UST, not just the ones listed.
Update pool id list
- Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`?  no

Update whitelisted pool IDs

---

.github/workflows/docker.yml
Dockerfile

This PR:
- Use correct libwasm version (`v1.0.0-beta5`) in Dockerfile
- Ports the docker Github Action from main to `v8.x` branch (https://github.com/osmosis-labs/osmosis/blob/main/.github/workflows/docker.yml) 
- Update Dockerfile
- Add Docker Github action
To check:
- Wasm version used in `v8`: https://github.com/osmosis-labs/osmosis/blob/v8.0.0/go.mod#L6
- Corresponding version of `libwasm`: https://github.com/CosmWasm/wasmd#compatibility
- Version used in the Dockerfile: https://github.com/nikever/osmosis/blob/fix/wasmd-version-in-dockerfile/Dockerfile#L13 …

Use correct libwasm version in Dockerfile and backport docker Github Action

---

x/gamm/keeper/msg_server.go
x/gamm/module.go

Closes: #1503 
The upcoming V9 upgrade should be including the gamm generalization, but not stable swap implementations. 
This PR removes(comments out) stable swap inplementation and existing stableswap calls, which was to my surprise only present in `msg_sever.go` and `module.go`. 
- Remove stableswap implementation from gamm module

Disable Stableswap

---

x/txfees/client/cli/tx.go

Can't submit txfees prop without fees flags

bug: tx flags for txfees update prop

---

Dockerfile
x/tokenfactory/genesis.go
x/tokenfactory/keeper/createdenom.go

A problem @czarcas7ic ran into was getting panics on token factory messages, when the genesis wasn't initialized.
- Improve nil handling of token factory InitGenesis
- TODO
- Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? no, still pre-release for token factory
- How is the feature or change documented? not applicable, removes a thing to document tbh

Make token factory handle empty genesis configurations better

---

CHANGELOG.md
Dockerfile
Makefile
tests/localosmosis/Dockerfile
tests/localosmosis/README.md
tests/localosmosis/docker-compose.yml
tests/localosmosis/keys.sh
tests/localosmosis/setup.sh

As it stands, it is not simple to quickly test a change in a local dev environment. This introduces a modified LocalOsmosis that is lightweight and makes it very easy to spin up a local net to test your changes. The docker image also creates a new genesis on build, preventing any issues that have arose in the past from hardcoded genesis files.
The basic process is as follows:
1. Make your local changes
2. Run `make localnet-build`
3. Run `make localnet-start`. Your local network has now started. Query it with your local daemon (i.e `osmosisd status`)
4. Run `make localnet-keys` to add all 10 keys to your keyring
5. Run `make localnet-remove` to remove all block data
This code was tested locally in an arm64 environment
- Does this pull request introduce a new feature or user-facing …

feat: local dev environment

---

app/keepers/keepers.go
x/superfluid/keeper/keeper.go

Closes: #XXX
@czarcas7ic and I ran into issues manually testing #1191 . We both reproduces this test case: https://github.com/osmosis-labs/osmosis/discussions/1543#discussioncomment-2786650
Upon further investigation, it was found that staking keeper was never replaced with superfluid keeper in the gov module so that the new logic could not be used for calculating tally and overriding validator votes by SF stakers.
We need to e2e test this case in a future PR: https://github.com/osmosis-labs/osmosis/issues/1556 …

fix: gov support for superfluid

---

tests/e2e/docker/image_config.go
tests/e2e/e2e_setup_test.go
tests/e2e/e2e_test.go
tests/e2e/e2e_util_test.go

Closes: #XXX
This PR refactors e2e test setup to have an abstraction `chainConfig` that has information about which validators should not be run during initialization. This is a first step toward testing state-sync as we want to postpone running some nodes so that we can test nodes "catching up".
Additionally, this PR extracts a separate package `docker` for managing and storing all information related to docker images.
- create a `chainConfig` struct to encapsulate all configurations related to chains in a single abstraction
* remove global variables `propHeightA`, `propHeightB`, `votingPeriodA`, `votingPeriodB`. Instead, these are part of the `chainConfig` struct
* `skipRunValidatorIndexes` - this is needed to skip certain validators from being run during setup so that we can test …

refactor: e2e setup to be more extensible for state sync

---

CHANGELOG.md
app/upgrades/v9/upgrades.go
go.mod
go.sum

Closes: #XXX
Upgrade SDK with the app version change and set the app version in the upgrade handler
- e2e test for state sync is in progress: https://github.com/osmosis-labs/osmosis/pull/1572
- upgrade itself is verified by the existing e2e test
- needs manual testing

chore: upgrade sdk with app version fix for state-sync

---

.github/workflows/test.yml
x/gamm/client/cli/cli_test.go

I'm losing a ton of time due to waiting for CI. This PR de-duplicates the on-push / pull-request CI contention.
Now we only have CI run on pushes to main and release branches. (With sub-optimal release branch matching)
Also comments out some of the less useless gamm tests. Were trying to eliminate these anyway, cref https://github.com/cosmos/cosmos-sdk/pull/11877
Tests still run on this PR, and they remain running on main.
- Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? CI out of scope of changelog

Make CI only run on pushes to main / release branches. Comment out less useful CLI tests

---

.github/workflows/test.yml

Closes: #1601 
This PR adds experimental GitHub Cache backend API to the `e2e_test` job.
This results in the following speed-up in `Build e2e image` step:
- Build without cache (4m 4s): https://github.com/nikever/osmosis/runs/6622443417?check_suite_focus=true
- Build after the cache it's filled (3m 10s) https://github.com/nikever/osmosis/runs/6622514813?check_suite_focus=true
- AddGitHub Cache backend API to the e2e workflows

[e2e] Add GitHub cache to docker build

---

app/upgrades/v8/forks.go

Closes: #1609
The v8 fork contained parameter changes that were only applicable on the `"osmosis-1"` chainID.
Limiting the `RunForkLogic` to osmosis-1

fix: Only apply v8 fork logic on osmosis-1

---

contrib/images/osmobuilder/Dockerfile

This PR fixes the `osmobuilder` reverting to the build tags to make the version command work https://github.com/cosmos/cosmos-sdk/blob/main/version/version.go
- Update `osmobuilder` Dockerfile

Replace osmobuilder build tags to create releases

---

Makefile

Unify docker container name with the name used by Cosmos SDK.
The container is using the same docker image, so no need to duplicate hanging containers (each of them is few hundreds of MB).
- Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? rather no

chore: unify docker proto container name

---

CHANGELOG.md
app/apptesting/gamm.go
osmomath/sigfig_round.go
x/gamm/pool-models/balancer/amm.go
x/gamm/pool-models/balancer/amm_test.go
x/gamm/types/constants.go

Fixes query bug on mainnet, for pools with an asset with `10**18` precision. We passed all spot prices through 8 sig fig rounding, however our sig fig rounding was incorrect for inputs with value less than 1.
This fixes a bug with spot price being called on values less than 1.
- Fixes SpotPrice rounding on extremely small inputs
This change added a new test for a large input from mainnet, that was returning 0.
I also checked that spot price is not called anywhere in the state machine, except in the cosmwasm bindings.
We will have to ensure that no contract gets uploaded with spot price calls in the v9.x release series, which was also the general plan since contracts should depend on TWAP not spot price. …

Fix spotprice sigfig rounding for small spot prices

---

CHANGELOG.md
go.mod
go.sum
tests/e2e/chain/config.go

Closes: #1697
Fixes the issue with snapshot manager not being configured due to `snapshot-interval` being 0 in `app.toml`
Specifically, upgrades cosmos-sdk fork with this fix: https://github.com/osmosis-labs/cosmos-sdk/pull/236
- Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (es

chore: upgrade sdk with snapshot manager fix

---

x/gamm/pool-models/balancer/amm_test.go

Added randomized testing for balancer pool `JoinPool` and `ExitPool`. The added test generates pool with randomized initial assets, and randomized ratio of assets to join/exit. It then performs the sequential JoinPool ExitPool operations, and check if the number of remaining assets and total number of shares are preserved.
*(or)*
*(or)*
This change added tests and can …

Randomized testing for Join-Exit

---

x/gamm/keeper/pool_service_test.go

This PR adds inverse relationship test to ensure we are guaranteed the same amount returned upon joinpool and exitpool.
*(or)*
*(or)*
*(example:)*
- *Manually verified the …

Add inverse relationship test on JoinPool and ExitPool

---

CHANGELOG.md
x/gamm/pool-models/balancer/amm.go

Another bug, spotted by samczun. Not caught in tests, because it occurs on uneven swap amounts.
For uneven swap amounts, we tend to have tokens remaining after doing an equal ratio swap. For each of the tokens, we do a single asset pool join.
The logic was broken in providing the correct number fo shares for single asset joins. This PR fixes it.
- Breaking down logic for handling uneven swap amounts and unit testing each function separately: https://github.com/osmosis-labs/osmosis/pull/1721
- Test cases for `CalcJoinPoolShares` with uneven swap amounts: https://github.com/osmosis-labs/osmosis/pull/1713 …

Fix second source of (minor) over-LP shares

---

osmoutils/binary_search.go
x/gamm/pool-models/balancer/amm_test.go

Closes: #XXX
in #1721 the logic for tolerating rounding errors in share calculations was introduced. It is also useful for unit tests in concurrent PRs such as #1718 
Since #1721 is large and is likely to take time to review, I'm submitting the desired functionality separately

chore: add ability to tolerate 10^-6% inconsistencies in share calculation test

---

x/gamm/pool-models/balancer/amm_test.go
x/gamm/pool-models/balancer/export_test.go

Closes: #XXX
This is and additional of unit tests for the `calcJoinSingleAssetTokensIn` balancer pool method.
This test was originally added in #1721 . I'm trying to break down that PR into smaller ones
- `go test -timeout 30s -run ^TestCalcSingleAssetJoin$ github.com/osmosis-labs/osmosis/v7/x/gamm/pool-models/balancer`

test: calcJoinSingleAssetTokensIn; validated by Wolfram

---

x/gamm/pool-models/balancer/amm.go
x/gamm/pool-models/balancer/amm_test.go
x/gamm/pool-models/balancer/export_test.go

Closes: #XXX
`CalcJoinPoolShares` has a lot of logic and is hard to test. This PR abstracts away some functionality behind a new `getPoolAssetsByDenom` function and unit tests it.
Originally introduced in #1721. Moving it in its own PR to ease the review process
- `go test -timeout 30s -run ^TestGetPoolAssetsByDenom$ github.com/osmosis-labs/osmosis/v7/x/gamm/pool-models/balancer`

test: extract getPoolAssetsByDenom function from CalcJoinPoolShares and unit test

---

CHANGELOG.md
app/app.go
app/upgrades/v10/constants.go
app/upgrades/v10/fork.go
app/upgrades/v10/upgrades_test.go
go.mod
go.sum

This PR introduces v10 halting logic to the v9 series. It makes a v9 state machine compatible version, that will halt at the upgrade height, and correctly signal cosmovisor to upgrade.
- Add halt at v10 fork height logic
The test attempts running this block height, and it panics then. (as expected)
- How is the feature or change documented? Should be

Add v10 halting logic to v9 (cref #1741)

---

osmomath/math.go
osmomath/math_test.go

Closes: #1752 
We were basically returning Zero Dec when the exponent was zero for `PowApprox` when in fact we should be returning one when any given exponent is zero.
Currently added a simple test case of testing when exponent is one but we should definitely revist osmomath as a while for better testing in a near future.

fix: Change PowApprox to return one when exponent is 0 

---

x/gamm/pool-models/balancer/amm_test.go

Add two additional test cases to `TestCalcJoinPoolShares` where `tokensIn` contains multiple coins where a swap is performed.

chore: additional test cases for TestCalcJoinPoolShares (multi-coin swap)

---

x/gamm/pool-models/balancer/amm_test.go

Closes: #1740
We consistently use 50000 as tokenIn amount in `calcSingleAssetJoinTestCases` unit tests which isn't the best practice
Add the following:
* TokensIn is large relative to liquidity
* with swap fee
* no swap fee
* TokensIn is greater than the pool liquidity
* This is currently not possible because there is a panic in Pow function when we have tokenInAmount >= existing liquidity
* Instead, tested the panic boundary
- `go test -timeout 30s -run ^TestCalcJoinPoolShares$ github.com/osmosis-labs/osmosis/v7/x/gamm/pool-models/balancer`
- How is the feature …

test: add more calcSingleAssetJoinTestCases with varying ratio of tokenInAmount to existing liquidity

---

x/gamm/pool-models/balancer/amm_test.go
x/gamm/pool-models/balancer/balancer_pool.go
x/gamm/types/errors.go

Closes: #XXX
Brought up by @alexanderbez , we should not be using string comparison for comparing errors, even in tests.
This is a small refactor to rely on `errors.Is` and `require.ErrorsAs(...)`

chore: avoid using string comparison for unit testing errors

---

x/gamm/pool-models/balancer/amm.go
x/gamm/pool-models/balancer/amm_test.go

Closes: #XXX
Adds tests for join pool for non even ratio assets, so that the tests hit the side where even join is done to the maximal amount able to, and then do a single pool join for the remaining coins. 
All the results used within this test codes are hand derived, attached in comment the calculations done via wolfram

Tests: Join pool for non-even ratio

---

x/gamm/pool-models/balancer/amm_test.go

Closes: #XXX
Cleaned the easiest of  amm_test.go, using `oneTrillionEvenPoolAssets` for test cases using pool asset that has one trillion pool assets each.
We can probably do much better cleaning her by creating variables for case that has different weights each and creating case for variable with different ratio pool assets, but then would have to go over all the hand derived math, thus skipping for now.

Clean `amm_test.go`

---

go.mod
go.sum

Increase maxApproxRootIterations to 300 in the cosmos sdk fork
Will backport to v10.x

cosmos sdk version inc

---

.github/dependabot.yml

Make dependabot ignore non-patch ibc-go changes, as minor changes are state breaking, and need more deliberation.
- How is the feature or change documented? Not applicable

Make dependabot ignore non-patch IBC-go versions

---

chain.schema.json

Closes: Based on [#425](https://github.com/cosmos/chain-registry/issues/425)
We shouldn't be manually updating the chain registry repo with a PR for every release we do.
This PR adds a chain JSON schema, which will soon have a bot that will automatically update the chain registry repo.
Added a chain JSON schema that will have a bot to automatically update the cosmos chain registry.
The chain repo's schema file maintains
```
"git_repo": "https://github.com/osmosis-labs/osmosis",
"recommended_version": "v10.0.0",
"compatible_versions": ["v10.0.0"],
"binaries": {
"linux/amd64": "https://github.com/osmosis-labs/osmosis/releases/download/v10.0.0/osmosis-10.0.0-linux-amd64",
"linux/arm64": "https://github.com/osmosis-labs/osmosis/releases/download/v10.0.0/osmosis-10.0.0-linux-arm64"
```
In the …

Chain JSON Schema

---

CHANGELOG.md
app/keepers/modules.go
app/upgrades/v9/upgrades.go

Closes: #1710, Supercedes #1711
Adds ICAHost to AppModuleBasic, fixes test by having it skip the problematic line in tests.
* Adds ICAHost to AppModuelBasics
I have not verified the change. This is by module writing standards more correct (though I didn't see this in the IBC upgrade docs)
- Does this pull request introduce a new feature or user-facing behavior changes?  yes
- Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`?  yes
- How is the feature or change documented? Not documented

Add ICAHost to AppModuleBasics

---

.github/labeler.yml

Closes: #1833
Add "C"docs" labels to the following:
```
- x/epochs/specs/*
- x/gamm/specs/*
- x/incentives/specs/*
- x/lockup/specs/*
- x/mint/specs/*
- x/pool-incentives/specs/*
- x/simulation/specs/*
- x/superfluid/specs/*
- x/tokenfactory/specs/*
- x/txfees/specs/*
- x/README.md
- README.md
- CHANGELOG.md
- bug.md
- issue.md
- proto-docs.md
```

Add docs label for any PR that edits a readme or spec folder

---

tests/e2e/README.md
tests/e2e/e2e_setup_test.go
tests/e2e/e2e_test.go

Closes: #XXX
This is a subset of the larger refactor in https://github.com/osmosis-labs/osmosis/pull/1591. Submitting this separately to ease the review process.
Here, we add the ability to disable long-running e2e test components with environment variables. This is useful for testing locally.
Additionally, we plan on enabling long-running e2e tests only on merge to main to speed up the CI in pull requests.
There is some boilerplate to utilize the newly introduced environment variables. This will be simplified in future PRs with the logic from #1591

refactor: e2e - allow disabling long running tests with environment variables

---

.mergify.yml

This change has been made by @ValarDragon from https://mergify.com config editor.

Mergify: Make backports automatically assign PR author

---

go.mod
go.sum

Closes: #XXX
This change updates the SDK dependency. We now use `v0.45.0x-osmo-v9` SDK fork branch for tagging `v10.x` releases.
A decision was made to keep the same branch `v0.45.0x-osmo-v9` for both `osmosis/v9.x` and `osmosis/v10.x` because v10.x is a fork of v9.x.
This PR updates `go.mod` with the tag taken from [`v0.45.0x-osmo-v9`](https://github.com/osmosis-labs/cosmos-sdk/tree/v0.45.0x-osmo-v9)
`v0.45.0x-somo-v9` was created from [`v0.45.0x-osmo-v7-old`](https://github.com/osmosis-labs/cosmos-sdk/commits/v0.45.0x-osmo-v7-old), commit: https://github.com/osmosis-labs/cosmos-sdk/commit/6209434a1de9af5c6c0625509cb1cc64a6e2c3d2
- Does this pull request introduce a new feature or user-facing behavior …

chore: update v10.x sdk to v0.45.0x-osmo-v9.0

---

x/epochs/keeper/abci.go
x/epochs/keeper/abci_test.go
x/epochs/module.go

Move beginblock / end block logic to keeper, per our module writing standards. (Looking forward to one day when we have a template module lol)
- Move epochs.BeginBlocker -> epochskeeper.BeginBlocker

Move epochs begin block code to keeper

---

.github/workflows/add-issue-pr-to-project.yml

Closes: #1529 
Making `Add new issues to project` only run on PRs that are not from a fork. Its currently erroring on every PR from a fork.
This should help folks working on forks to not have constant errors on their PRs
Added in a Github actions rule that checks whether or not someone is running `Add new issues to project` from a fork
If they are, do not run the action.
*(or)*
*(or)*
Opening a PR on a fork of osmosis
- Does this pull request introduce a new feature or user-facing behavior changes? (yes / **no**) …

Make Add new issues to project only run on PRs that are not from a fork

---

CHANGELOG.md
go.mod
go.sum
osmoutils/slice_helper.go
x/epochs/keeper/abci.go
x/epochs/keeper/abci_test.go
x/epochs/keeper/epoch.go
x/epochs/keeper/epoch_test.go
x/epochs/keeper/genesis.go
x/epochs/keeper/keeper_test.go
x/superfluid/keeper/keeper.go
x/superfluid/keeper/keeper_test.go
x/superfluid/keeper/twap_price_test.go

Part of: #1834 
Update the epochs modules tests to be readable, make sense & cover more relevant cases.
As part of this, we remove the prior `SetEpochInfo` API, and solely use a safer `AddEpochInfo` api, that includes relevant entries if they're left blank, and errors if its an invalid configuration
- Remove epochskeeper.SetEpochInfo API, in favor of epochskeeper.AddEpochInfo
- Added unit test that validates expected epoch behavior on begin block
- Open to any other test cases we can think of for edge cases / etc.
- How is the feature or change documented? not …

Fix epochs modules tests

---

tests/e2e/containers/containers.go

Closes: #XXX
#1898 introduced flakiness. Apparently, Hermes sometimes produces errors to stderr when it functions correctly. Therefore, the added logic prevents IBC from functioning correctly.
For some reason, sometimes Hermes does not produce these logs so the CI passes.
This logic is not very useful so can be removed to fix CI. Test locally several times, and it works.

fix: e2e flakiness related to err checking containers

---

x/epochs/keeper/abci_test.go
x/epochs/keeper/epoch_test.go

Closes: #1834 
Adds a table driven test for AddEpochInfo functionality, and a unit test for its behavior on duplicates.
This is part of followup from #1893 
- Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`?no

Write test for AddEpochInfo

---

x/gamm/keeper/genesis.go
x/gamm/keeper/multihop.go
x/gamm/keeper/pool.go
x/gamm/keeper/pool_service.go
x/gamm/keeper/swap.go
x/gamm/pool-models/balancer/balancer_pool.go
x/tokenfactory/keeper/admins_test.go
x/tokenfactory/keeper/createdenom_test.go
x/tokenfactory/keeper/keeper_test.go

Component of: #1835
Ongoing audit of x/gamm module for all AMM-related logic.
Current progress is being tracked in [this document](https://docs.google.com/document/d/1Qz-2Gy2YMQqb_REJ1sC-u7jcG-9-exhM_yFD0S3Nh3Q/edit#).
WIP, will add when complete.
- WIP, will add when complete.

x/gamm: Internal audit and documentation

---

tests/e2e/containers/containers.go
tests/e2e/e2e_setup_test.go
tests/e2e/e2e_util_test.go

Closes: #XXX
This was originally meant to be used for initializing genesis and configs for state-sync nodes and be able to run them after the rest of the chain has started. However, a new design was chosen over this where we have the ability to initialize the configs for a single node, separate from the rest of the chain
As a result, this logic is not needed anymore

e2e: remove unused skipRunValidatorIndexes

---

tests/e2e/containers/config.go

Closes: #XXX
Due to a missing return, the image would get overwritten by incorrect value when running e2e with upgrade tests disabled. This short change fixes it

e2e: fix image choice when upgrade logic is disabled

---

x/lockup/client/cli/query.go
x/lockup/client/cli/tx.go
x/lockup/keeper/grpc_query.go
x/lockup/keeper/invariants.go
x/lockup/keeper/iterator.go
x/lockup/keeper/lock.go
x/lockup/keeper/lock_refs.go
x/lockup/keeper/lock_test.go
x/lockup/keeper/msg_server.go
x/lockup/keeper/synthetic_lock.go

Subcomponent of : #1838 
This PR 
- adds documentations to each lockup methods
- changes order for methods in the `lock.go` file for readibility, 
- rename method name 
- `Unlock` -> `UnlockMaturedLock`, as it was unclear if the unlock method was describing the initiative of unlocking or finishing of unlocking 
- `BreakAllSynthethicLocks` -> `DeleteAllSyntheticLocks`, as BreakAllSyntheticLocks were basically iterating over locks to call `DeleteSyntheticLock` the change is better for naming consistency
This PR does not include any change or refactoring of the logic itself.
Documentation additions, method renaming, file cleanup for x/lockup.
- Is a relevant changelog entry added to the `Unreleased` section …

chore: x/lockup documentation, minor module cleanup

---

tests/e2e/containers/containers.go

Closes: #XXX
This change was originally introduced in #1898. However, in #1898 if "error" was found, the system would fail on the following line:
https://github.com/osmosis-labs/osmosis/blob/8f31b5afdbc9dfdbfbc20045dcb7f7004ae72b53/tests/e2e/containers/containers.go#L101
That started causing issues because some applications such as Hermes log "error" to stderr in the normal mode of operation.  So the change was reverted in #1902
This log proved to be incredibly helpful, making me manually change every PR for debugging. So, a modified version is introduced here. This version does not fail but only logs when "error is encountered. 
- …

e2e: ExecCmd debug log on error

---

CHANGELOG.md
x/gamm/keeper/pool_service.go
x/gamm/keeper/pool_service_test.go

Closes: #1929
Our current implementation of JoinPoolNoSwap only checks for whether the input set of tokens includes the tokens in the pool, but does not have any check that prevents someone from putting in an arbitrary number of arbitrary tokens. Since this is a no-swap/all-asset join, there are no other immediate checks so an invalid input can make it directly to the state-changing JoinPool function.
- Add && tokenInMaxs.DenomSubsetOf(neededLpLiquidity) to x/gamm/keeper/pool_service.go/L203 so that input tokens for a no-swap pool join don’t include denoms that aren’t in the pool:
This change is already covered by existing tests in our GAMM module …

x/gamm: Add check to ensure JoinPoolNoSwap cannot be called with arbitrary denoms

---

.golangci.yml
osmomath/math.go
tests/e2e/containers/config.go
x/gamm/pool-models/balancer/pool.go
x/gamm/pool-models/stableswap/amm.go
x/lockup/keeper/export_test.go
x/lockup/keeper/utils.go
x/mint/simulation/genesis.go
x/tokenfactory/keeper/keeper.go
x/tokenfactory/types/codec.go

Cref: #1897 
Adds the deadcode linter! Roman had a great idea to do this!
- Add deadcode linter. I added a nolint to anything I didn't have certainty around whether it may still be used shortly.

Add deadcode linter

---

x/gamm/pool-models/balancer/pool.go
x/gamm/pool-models/internal/cfmm_common/lp.go

Closes: #1935 
Removes v10 height gating from `CalcJoinPoolShares` since it is no longer necessary now that we are on v10.
- Remove block height check from `CalcJoinPoolShares`
- Remove related broken functions

x/gamm: Delete the height < v10forkheight { use broken code } check

---

CHANGELOG.md
x/lockup/keeper/lock.go
x/lockup/keeper/lock_test.go
x/lockup/keeper/msg_server.go

Sub-component of: #1838
The current `ExtendLockup` API directly takes in the lock object as a pointer as its parameter. This PR changes this existing API to take in lock ID to improve safety for this API
Improve`ExtendLockup` API safety.

x/lock: Fix `ExtendLockup` API 

---

.golangci.yml
x/superfluid/keeper/grpc_query.go

We had literally copies of another query in the superfluid `TotalDelegationByDelegator`, so we simplify this. 
cc @nghuyenthevinh2000, its preferable for maintainance & code complexity to re-use existing queries / logic if possible! (https://github.com/osmosis-labs/osmosis/pull/1539)
- remove some duplicate code

Re-use code in superfluid TotalDelegationByDelegator

---

tests/e2e/e2e_setup_test.go
x/epochs/keeper/epoch_test.go
x/gamm/pool-models/balancer/pool_test.go
x/mint/keeper/hooks_test.go
x/mint/keeper/keeper_test.go
x/mint/simulation/genesis.go
x/mint/types/minter_test.go
x/pool-incentives/keeper/hooks.go
x/superfluid/client/cli/query.go
x/superfluid/keeper/grpc_query.go
x/tokenfactory/types/codec.go

This just keeps our fumpt-ing up to date, and "makes osmo green in Jacob's dev setup"
run gofumpt -w -l .
I did not add changelog notes because it doesn't really seem worthy.

gofumpt matienance

---

.golangci.yml
osmomath/math.go
store/node.go
tests/e2e/containers/config.go
tests/e2e/initialization/chain.go
tests/e2e/initialization/validator.go
x/gamm/keeper/keeper.go
x/gamm/module.go
x/gamm/pool-models/stableswap/amm.go
x/incentives/keeper/gauge.go
x/lockup/keeper/store.go
x/tokenfactory/keeper/bankactions.go

Follow-up to: https://github.com/osmosis-labs/osmosis/issues/1897
We would like to improve the quality of our codebase by trying out components of the [staticcheck](https://staticcheck.io/) linter.
This change introduced `unused` - 1st of the 4 components
Although, we added `deadcode` linter in https://github.com/osmosis-labs/osmosis/pull/1934, `unused` seems to be detecting more unused logic.
In addition to removing the unused code, the following was done:
- disable `unused` and `deadcode` for `x/gamm/pool-models/stableswap` since it is currently in development

lint: enable unused in golangci-lint

---

x/lockup/keeper/bench_test.go
x/lockup/keeper/genesis.go
x/lockup/keeper/genesis_test.go
x/lockup/keeper/lock.go
x/lockup/keeper/synthetic_lock_test.go

Closes: #1275 
Sub-component of #1838 
The method `ResetAllLocks` implies _resetting_ a state, which implies we're deleting an **existing** state, and setting a new value for the state. This method name is misleading, as this method is not resetting an existing state, it's simply initializing a state, as `ResetAllLocks` are used in `InitGenesis`. 
This PR includes renaming `ResetAllLocks` to `InitializeAllLocks`.
This PR also includes renaming `setLockAndResetLockRefs ` to `setLockAndAddLockRefs`, as the intention of the method is not to delete and add lock refs, but simply add lock refs.
- Rename `ResetAllLocks` to `InitializeAllLocks`, rename `setLockAndResetLockRefs ` to `setLockAndAddLockRefs`
- Is a …

chore: Rename `ResetAllLocks`

---

.golangci.yml
tests/e2e/containers/containers.go

Closes: #XXX
Follow-up to: https://github.com/osmosis-labs/osmosis/issues/1897
Enable `gosimple` - subset of `staticcheck` binary

lint: enable gosimple

---

x/gamm/pool-models/balancer/pool.go
x/gamm/pool-models/stableswap/pool.go
x/gamm/types/pool.go

Closes: #1905 
Renames `CalcExitPoolShares` to `CalcExitPoolCoinsFromShares` as discussed in https://github.com/osmosis-labs/osmosis/issues/1905
- Rename `CalcExitPoolShares` in gamm module and update balancer & stableswap implementations accordingly

x/gamm: Rename CalcExitPoolShares to CalcExitPoolCoinsFromShares

---

osmoutils/cli_helpers.go
osmoutils/test_helpers.go
x/gamm/pool-models/balancer/pool_suite_test.go
x/gamm/pool-models/balancer/pool_test.go
x/gamm/pool-models/balancer/util_test.go
x/mint/keeper/genesis_test.go
x/mint/keeper/keeper_test.go

Closes: #1946
Adds a helper function for conditioning on Panics 
Realized that there is already a helper function in `x/gamm/pool-models/balancer/util_test.go` so i just moved that under `osmoutils`
n/a
n/a

test/devux: helper function for assertions conditional on panics

---

.golangci.yml
app/apptesting/gamm.go
app/apptesting/test_suite.go
store/node.go
x/gamm/pool-models/balancer/marshal.go
x/gamm/pool-models/balancer/pool.go
x/gamm/pool-models/balancer/pool_asset.go
x/gamm/pool-models/stableswap/amm.go
x/gamm/pool-models/stableswap/pool.go
x/incentives/client/cli/tx.go
x/pool-incentives/types/expected_keepers.go
x/tokenfactory/keeper/createdenom.go
x/txfees/keeper/feedecorator.go
x/txfees/types/options.go

Closes: #XXX
Follow-up to: https://github.com/osmosis-labs/osmosis/issues/1897
Linter that enforces style rules. A subset of rules from the staticcheck binary.
- disable annoying check requiring "Id" to be "ID"
- ensure that receivers are named consistently
- remove duplicate imports that had different identifiers
- remove redundant types in var declarations
- errors messages are not capitalized
- godoc starts with var name

lint: enable stylecheck

---

proto/osmosis/tokenfactory/v1beta1/authorityMetadata.proto
proto/osmosis/tokenfactory/v1beta1/genesis.proto
proto/osmosis/tokenfactory/v1beta1/params.proto
proto/osmosis/tokenfactory/v1beta1/query.proto
proto/osmosis/tokenfactory/v1beta1/tx.proto
x/tokenfactory/README.md
x/tokenfactory/module.go
x/tokenfactory/types/genesis.pb.go
x/tokenfactory/types/params.pb.go
x/tokenfactory/types/query.pb.go
x/tokenfactory/types/tx.pb.go

Closes: #1914
Auditing the `x/tokenfactory` module
* Revising proto comments
* Revising keeper and types godocs
* Revising tests

chore: x/tokenfactory audit

---

app/modules.go
x/superfluid/abci.go
x/superfluid/module.go

Epochs, txfees, and gamm have no endblock logic. So the prior constraints had no impact.
- Remove some unnecessary logic. 
- Remove the deadcode, to make it clearer superfluid has no endblock logic.
This change is a trivial rework / code cleanup without any test coverage. Just check the following lines to convince yourself of no EndBlock logic:
epochs - https://github.com/osmosis-labs/osmosis/blob/main/x/epochs/module.go#L157-L161
gamm - https://github.com/osmosis-labs/osmosis/blob/main/x/gamm/module.go#L149-L153
txfees - https://github.com/osmosis-labs/osmosis/blob/main/x/txfees/module.go#L162-L167
- How is the …

Remove the EndBlock ordering constraints, that didn't matter before

---

x/gamm/twap/README.md
x/gamm/twap/abci.go
x/gamm/twap/hook_listener.go
x/gamm/twap/keeper.go
x/gamm/twap/module.go
x/gamm/twap/store.go
x/gamm/twap/types/keys.go

This PR adds a stub starting some of the TWAP logic. Has a couple high level notes around where more logic goes.
One of the goals is that it is relatively decoupled from gamm, only having read-only access to a pool, along with getting hooks.
This PR basically includes minimum scaffolding necessary to only have complexity once per pool per block, rather than on every swap.
I'd like to merge this if viewed as acceptable, so we can carry forward with more TWAP experimentation with this boilerplate out of the way in review.
- Add Stub
No core logic / wiring present to test yet. Just stubs for future work / to make this not need to be reviewed in subsequent work. …

Add TWAP stub package

---

CHANGELOG.md
x/gamm/keeper/genesis.go
x/gamm/keeper/grpc_query.go
x/gamm/keeper/pool.go
x/gamm/keeper/pool_service.go

Break off from my simulator work -- Make & Use `GetNexttPoolNumber` API, make the increment and set API's internal. 
This likely will fix some unreported edge cases with queries as well.
- Remove public GetNextPoolNumberAndIncrement method in favor of GetNextPoolNumber

x/gamm : Fix public/private on GetNextPoolNumber API

---

.github/workflows/stalebot.yml

Add a Github Actions job that uses the stale workflow to automatically mark PRs as stale and close them w/o any activity. Feel free to comment on tweaking any values.

chore: add stalebot to CI

---

x/mint/keeper/keeper_test.go

Closes: #1915
- Refactor keeper tests in x/mint
- Refactor `TestMintCoinsToFeeCollectorAndGetProportions` and `TestDistrAssetToDeveloperRewardsAddrWhenNotEmpty`
- This change is a trivial rework / code cleanup without any test coverage.

Refactor keeper tests in x/mint

---

CHANGELOG.md
app/keepers/keepers.go
app/keepers/modules.go
app/modules.go
app/upgrades/v5/upgrades.go
go.mod
go.sum
osmoutils/partialord/partialord_test.go

Closes: #XXX
This PR removes bech32 ibc from the state machine, because it is unmaintained.
*(or)*
*(or)*
*(example:)*
- Does this pull …

remove bech32 ibc

---

x/incentives/client/cli/cli_test.go
x/incentives/client/cli/flags.go
x/incentives/client/cli/query.go
x/incentives/client/cli/tx.go
x/incentives/keeper/distribute.go
x/incentives/keeper/gauge.go
x/incentives/keeper/grpc_query.go

Part of: #1837 
Audit, clean up, and test modifications for the incentives module
This is part 2 of 4:
1. Proto changes
2. CLI fixes
3. Tests
4. All other changes
- Fixes reward estimation query to work as intended (pulls owners lockIDs if not provided)
- Improve / cleanup CLI tests
This change is already covered by existing tests, such as cli_test.go within the incentives module

x/incentives: cli updates

---

x/incentives/keeper/distribute.go
x/incentives/keeper/gauge.go

Closes: #2005
Change `getToDistributeCoinsFromGauges` so that it only iterate through all gauges once.
- How is the feature or change documented?  not documented

improve getToDistributedCoinsFromGauges

---

x/superfluid/keeper/epoch.go

Closes: #1797 
Whenever a pool does not have swaps occur between last epoch and the current epoch, an error message is displayed during epoch. Since we have many pools that this is the case for, there are many error logs which does not help the end user. 
More specifically, we call WithdrawDelegationRewards here
https://github.com/osmosis-labs/osmosis/blob/079bdd496aefea6ad386263b349f2b60f0358738/x/superfluid/keeper/epoch.go#L60-L65
When we make this call to the sdk, we return an ErrEmptyDelegationDistInfo
https://github.com/osmosis-labs/cosmos-sdk/blob/d49b3e7549293d3bdf70c898c7afa58728438338/x/distribution/keeper/keeper.go#L84-L94
This change simply handles the ErrEmptyDelegationDistInfo with a debug log stating that "no swaps occurred in this pool between last epoch and this epoch" …

x/superfluid: no delegation distribution info

---

.github/workflows/release.yml
contrib/images/osmobuilder/Makefile

Backporting of https://github.com/osmosis-labs/osmosis/pull/1644 to `v10.x`

Backport/add release workflow to v10.x

---

tests/e2e/configurer/base.go
tests/e2e/configurer/chain/chain.go
tests/e2e/configurer/chain/commands.go
tests/e2e/configurer/chain/validator.go
tests/e2e/configurer/upgrade.go
tests/e2e/e2e_test.go

Next step in: https://github.com/osmosis-labs/osmosis/issues/1879
Related to: https://github.com/osmosis-labs/osmosis/issues/2039
This change includes the following interconnected parts:
1. Ability to run individual nodes by calling `chainConfig.RunNode(...)`
We need the ability to run each node individually for testing state sync. This refactor implements it.
2. Use the Tendermint RPC client in setup
Switch from relying on CLI during setup to using Tendermint RPC client. It should be more reliable and easier to debug than the CLI. This might help to resolve or mitigate issues in #2039 
3. Reduce code duplication
We used to have code duplicated for waiting for a certain height:
- upgrade containers: https://github.com/osmosis-labs/osmosis/blob/5f17b1941d85e1bf906370327a635733bce2a65f/tests …

refactor(e2e): run individual nodes; rely on rpc client in setup

---

tests/e2e/configurer/chain/commands.go
tests/e2e/containers/containers.go

Closes: #1623
Quick PR to reduce boilerplate in e2e, stemming from CLI.

e2e: Reduce repetitive args for tx creation commands

---

x/gamm/pool-models/balancer/pool_test.go

Closes: #1904 
This PR adds a test that (trivially) checks to make sure that `IsActive` returns true for balancer pools. The primary purpose of this change is to make sure that if IsActive is ever used as an emergency switch, it is not accidentally left off for any or all pools.
I realize that my implementation has more structure than might seem necessary for a test this simple, but given how we intend to add more complex mock tests to cover `IsActive` flipping functionality in the future (https://github.com/osmosis-labs/osmosis/issues/1904#issuecomment-1182730437), I figured setting it up properly the first time around might make it easier to implement these other tests later.
- Add a test that makes sure `IsActive` always returns true
This change is a trivial rework / code cleanup …

Add basic test for IsActive

---

CONTRIBUTING.md
tests/e2e/initialization/init_test.go

Closes: #1954 
This PR introduces testing standards and templates to our `CONTRIBUTING.md` to align expectations on testing while we continue to refactor and clean up our old tests.
Add section for writing tests to `CONTRIBUTING.md` that covers:
1. A brief overview of table-driven development (with a link to a great intro resource)
2. A few rules of thumb for test-writing in the Osmosis repo
3. Three examples/templates (a message-related test, a keeper-related test, and a gamm-related test) with brief intros, permalinks, and code blocks for people to copy-paste from as needed …

Add test standards and test templates to CONTRIBUTING.md

---

tests/e2e/configurer/chain/queries.go
tests/e2e/e2e_test.go

Minor commit, moves more complexity around endpoints into QueryRPC
Driveby fix of changing the addr arg of QueryPropTally to be the correct proposalNumber

e2e: move endpoint complexity into config.QueryRPC

---

x/gamm/pool-models/balancer/pool_test.go

Closes: #1944 
Several tests in our balancer `pool_test.go` had setup functions as fields in test cases. These functions repeated code and overall were functionally not really "table-driven". This PR factors out the logic in these setup functions and replaces the function itself with relevant fields.
- Remove setup function field from `TestUpdateIntermediaryPoolAssetsLiquidity` and replace it with `newLiquidity`,
`originalPoolAssets`, and `expectPass` fields
- Move logic for finding expected assets to test-wide for loop
- Clean up error checks using `expectPass` …

x/gamm: refactor balancer pool_test.go tests to be properly table-driven

---

x/mint/keeper/export_test.go
x/mint/keeper/keeper.go
x/mint/keeper/keeper_test.go

Part of: https://github.com/osmosis-labs/osmosis/issues/1916
Splitting up https://github.com/osmosis-labs/osmosis/pull/2026  [per suggestion](https://github.com/osmosis-labs/osmosis/pull/2026#issuecomment-1184427409).
The dev rewards distribution logic is 1:1 copied from how it used to be and encapsulated into a function. Additionally, unit tested.
TestDistributeDeveloperRewards

refactor(x/mint): introduce distributeDeveloperRewards methods; unit tests (1/2)

---

tests/e2e/configurer/chain/queries.go

Closes: #2051 
Currently we use custom loops with custom logic to try connecting to the rpc enpoints.
This PR includes replacing that custom loop with `require.Eventually`
- Change custom loop used for qurieying to `require.Eventually`

chore(e2e): use `require.Eventually` in QueryRPC

---

simulation/types/manager.go
x/gamm/module.go
x/lockup/module.go

\## What is the purpose of the change
Remove random genesis state from module API, and demo this change for other people doing something on the SDK
- Rename and move GenerateGenesisState to a new extension interface, under better name RandomGenesisState.
(We still need to come back and unscrew up all the genesis handling, but this is a nice step in the direction)
FullAppSimulation still making lockup module messages succesfully. Checked via local execution.
- Does this pull request introduce a new feature or user-facing behavior changes?  yes
- How is the feature or change documented? code comment

Move random genesis to an extension interface

---

tests/e2e/configurer/chain/commands.go
tests/e2e/configurer/upgrade.go

Related to: https://github.com/osmosis-labs/osmosis/issues/2039
Discovered that upgrade proposals were broken after trying to upgrade our SDK.
I think the reason the CI was passing before is that despite switching v10 to v11 containers during the upgrade, the state machine was compatible so it was able to continue.
However, upon upgrading SDK, that wasn't the case anymore so the CI started failing.
The problem was that each node on a chain was submitting and voting on its own proposal. As a result, none of them would eventually be accepted.
This change makes only one node to submit a proposal and all other nodes vote on the unified proposal.
The tests passed with this change + SDK upgraded. The actual upgrade is coming in a separate PR.
- Formatted command logs consistently to improve the …

fix(e2e): upgrade proposals

---

.github/workflows/import_paths.yml
scripts/replace_import_paths.sh

Part of: #1709
This is a manual action to run the script to find and replace the import paths, create a branch and a open a pull request.
The following parameters are configurable:
- version (e.g. `v11`)
- source branch
* it is set to `update-paths` by default and it is added just in case we want to update 2 branches at once (e.g. `main` and `v11.x`)
- target branch (e.g. main or any other)
Tested on personal fork:
- auto-created PR: https://github.com/p0mvn/osmosis/pull/20
- CI passed on merge of the replaced paths: https://github.com/p0mvn/osmosis/commits/main

ci: manual job to replace import paths

---

tests/e2e/configurer/base.go
tests/e2e/configurer/chain/commands.go
tests/e2e/configurer/chain/node.go
tests/e2e/configurer/chain/queries.go
tests/e2e/containers/containers.go
tests/e2e/e2e_test.go
tests/e2e/initialization/node.go

Closes: #1624 , progress on #2100
To help with finding out why e2e execution is so slow. This PR achieves the following:
- add some basic time tracking to logs.
- Makes a unified method, and abstracts the log formatting for the container. This PR does it for txs, its up to a future PR to apply it everywhere else
- Switch the consensus config to be TM's test config (lower wait times intended for CI)
- Lower polling intervals. (This is also shows that we need more unification, theres so many different requires in this code. Really there should only be 2, One for CLI submission, one for query submission) …

E2E: speedup execution time, add basic time tracking

---

.github/workflows/import_paths.yml
scripts/replace_import_paths.sh

Related to: https://github.com/osmosis-labs/osmosis/issues/1709
After testing #2094 more, I realized that there are 3 issues:
1. A pull request opened from the manual action does not trigger CI
* There was a security limitation related to a supported token
* To work around this, I changed the GitHub action to [this](https://github.com/peter-evans/create-pull-request). It supports using `PAT` token that mitigates the security limitation
* Pull requests now trigger CI correctly
2. Proto files and proto scripts were not updates
* To fix this, added logic to the shell script, finding and replacing import paths in the proto files and scripts, running `make proto-gen` at the end
3. Did not have support of updating multiple branches at once because the same branch was always used as base of the …

ci: improve import path action

---

app/upgrades/v11/upgrades.go

Related to: https://github.com/osmosis-labs/osmosis/issues/1805
Although the app version was already set during the v9 upgrade, our v10 was a fork.
As a result, the upgrade handler was not executed to increment the app version.
This change helps to correctly set the app version for v11.
This change can be verified by e2e upgrade tests

chore(app/upgrades): set app version correctly for v11

---

x/gamm/pool-models/balancer/amm.go
x/gamm/pool-models/balancer/export_test.go
x/gamm/pool-models/balancer/pool.go
x/gamm/types/errors.go
x/mint/keeper/export_test.go
x/mint/keeper/keeper.go
x/mint/keeper/keeper_test.go
x/mint/types/errors.go

Closes: #2034 and #2035
Move tests to errors.go for consistency 
n/a
n/a

refactor(x/mint, x/gamm errors): move errors in mint and gamm keeper to errors.go

---

x/gamm/pool-models/balancer/pool_test.go

This PR fixes an issue with the test for `IsActive` in balancer that prevented it from ever actually running.
- Remove use of test suite from `IsActive` test in balancer

fix: remove suite receiver from IsActive test

---

x/mint/keeper/genesis_test.go
x/mint/keeper/grpc_query_test.go
x/mint/keeper/hooks_test.go
x/mint/keeper/keeper_test.go

The mint keeper tests had become egregiously slow - 2 minutes in CI, 45 seconds locally.
It now takes 2 seconds locally
This PR does some pretty basic speedups for it:
- Remove every test being ran 4 times (4x speedup)
- Make the default setup parameters have the `reduction period` be 10 epochs, rather than the default (365), lowering amount of iteration. (Estimated rest of speedup)
- Delete unneeded LP incentive setup. (This was doing absolutely nothing, I don't know why it was here)
From this, it also strikes out to me that we have a ways to go in improving these tests further. (A lot of these legacy tests are hard to follow / egregiously slow / not using our suite.app tooling)
- 20x speedup mint keeper tests
This change is already covered by existing tests, such as *(please describe …

Speedup mint keeper tests (20x locally)

---

CONTRIBUTING.md

Closes: #1580 
This pull request improves documentation on debugging with end to end testing as a part of our contributing guidelines.
Added e2e testing section on contributing.md
**This change is a trivial rework / code cleanup without any test coverage.**
*(or)*
*(or)*
*(example:)*
- Does this pull request introduce a new feature or user-facing behavior changes? (yes / **no**) …

Contributing.md e2e testing additions

---

tests/e2e/README.md
tests/e2e/configurer/base.go
tests/e2e/configurer/chain/chain.go
tests/e2e/configurer/chain/node.go
tests/e2e/configurer/chain/queries.go
tests/e2e/configurer/factory.go
tests/e2e/containers/config.go
tests/e2e/e2e_setup_test.go
tests/e2e/e2e_test.go
tests/e2e/initialization/init.go
tests/e2e/initialization/init_test.go
tests/e2e/initialization/node.go
tests/e2e/initialization/node/main.go

e2e: enable state-sync tests (final MVP)

---

app/apptesting/bench_test.go

Adds a benchmark for app keeper setup. It currently takes too long, with lots of GC induced. Going to write this in an issue, we should as a backburner task figure out why it creates so much heap and fix it.
- Add benchmark

Benchmark apptesting setup time

---

x/mint/keeper/genesis_test.go
x/mint/keeper/hooks_test.go
x/mint/keeper/keeper_test.go

Closes: #XXX
Making assertions on `Require()` fails test suite immediately. If it is not used, the execution of the test continues.
We should be using `Require()` in all cases.
If this is accepted, will create a follow-up issue for other modules.

chore(x/mint): use Require() for assertions in tests

---

simulation/simtypes/account.go
simulation/simtypes/action.go
x/lockup/simulation/operations.go
x/tokenfactory/simulation/sim_msgs.go

Closes: #XXX
Small patch that prevents the simulator from panicking when trying to lock a zero amount token. Also made this prevent negative numbers while I was at it.
- Adds check to RandomMsgLockTokens to prevent locking <= 0 coin amount

simulator: prevent locking zero tokens

---

go.mod
go.sum

Closes: #2170
Without this update, a majority of longer simulator runs fail due to bug in the authz simulator code.

chore(deps): bump sdk fork to v0.45.0x-osmo-v11-alpha.2

---

x/lockup/types/msgs.go
x/lockup/types/msgs_test.go

Closes: #XXX
@ValarDragon had mentioned that the fact ValidateBasic was not catching zero amount lockups in the simulator was a bug. This fixes that bug.
- Ensures all coins in MsgLockTokens are positive
To test that this worked, I made every lockup have a zero amount in the simulator and ran it through the ValidateBasic. No lockups errored. 

fix: check coins are positive in lockup ValidateBasic

---

.github/dependabot.yml

Unless folks particularly like dependabot being on daily, I'd like to suggest we keep it at weekly. I don't think theres much benefit to immediate updates (e.g. did we really need 3 golangci updates in 4 days?) - I typically go through the changelog and release notes / sometimes source for dep updates.
I'd only want instant PRs for security updates

Change depandabot timer from daily to weekly

---

simulation/simtypes/account.go
x/gamm/simulation/sim_msgs.go
x/tokenfactory/module.go
x/tokenfactory/simulation/sim_msgs.go

Closes: #XXX
There are two purposes of this PR:
1. Change RandomSimAccountWithMinCoins to accept sdk.Coins type as requested [here](https://github.com/osmosis-labs/osmosis/pull/2172#discussion_r926255240) 
2. Have SelAddrWithDenoms, RandomSimAccountWithMinCoins, and RandCoinSubset all return SpendableCoins rather than Coins (this was leading to various issues in the simulator).

simulator: return accs with SpendableCoins

---

simulation/executor/simulate.go
simulation/simtypes/action.go
simulation/simtypes/manager.go

Closes: #2131
Creates a struct that exports the module name of an Action. In the future, we can use this to export other various metadata from each action!
Tested locally, the output of each action now filters itself properly to its respective module!

simulator: create an ActionWithMetadata struct

---

.github/workflows/check-state-compatibility.yaml

Continues PR: [#2083 ](https://github.com/osmosis-labs/osmosis/pull/2083)
This PR improve the state-compatiblity check by:
- Forcing the workflow to fail in case of an `osmosisd` panic (Thanks @mattverse for the help spotting this)
- Add caching of `snapshots` to avoid re-downloading them every run if already available in the runner
- Schedule this workflow to run every day at `00.00` UTC
- Add slack notification in case of failure 
- Improve `check-state-compability` CI (caching, scheduling, notification in case of failures)
Now workflow fails on errors: 
https://github.com/osmosis-labs/osmosis-ci/runs/7434236108?check_suite_focus=true
Regular run:
https://github.com/osmosis-labs/osmosis-ci/runs/7448557374?check_suite_focus=true
- Does this pull request introduce a new feature or …

Improve CI for state-compatibility-check 

---

CHANGELOG.md
x/incentives/keeper/distribute.go

Closes: #XXX
This change is Devs work. He was able to speedup epoch in a state compatible manner. We decided to include this fix and tag it as v10.1.1.
- Utilize GetLocksLongerThanDurationDenom to get qualified lock list. Resulting list is less to iterate over.
This test ran through our new v10 state compatibility epoch check and passed.

feat: speedup epoch distribution, superfluid component

---

x/incentives/keeper/msg_server_test.go

Closes: #XXX
*(or)*
*(or)*
*(example:)*
- …

finished tests

---

x/incentives/keeper/export_test.go
x/incentives/keeper/gauge.go
x/incentives/keeper/msg_server.go
x/incentives/keeper/msg_server_test.go
x/incentives/simulation/operations.go
x/incentives/types/gauge.go

- move fees to types and export
- reuse fees in the simulator

move gauge fees to types 

---

app/keepers/keepers.go
go.mod
x/incentives/keeper/export_test.go
x/incentives/keeper/gauge.go
x/incentives/keeper/gauge_test.go
x/incentives/keeper/keeper.go
x/incentives/keeper/msg_server.go
x/incentives/keeper/msg_server_test.go
x/incentives/simulation/operations.go
x/incentives/types/expected_keepers.go
x/incentives/types/gauge.go

This is a backport of PR #2227

feat(incentives): create gauge and add to gauge fee charge (backport #2227)

---

CHANGELOG.md
go.mod
go.sum
tests/e2e/e2e_setup_test.go
tests/e2e/e2e_test.go
tests/e2e/e2e_util_test.go

Closes: #XXX
Upgrading sdk with the proposer deposit change and updating e2e to cover the new deposit at submission logic
This change is already covered by existing tests, such as e2e

chore(deps): upgrade sdk with min proposer deposit and update e2e

---

.github/mergify.yml
Makefile
app/app.go
app/upgrades/v11/constants.go
app/upgrades/v11/upgrades.go
app/upgrades/v12/constants.go
app/upgrades/v12/upgrades.go

Closes: #XXX
Moves v11 upgrade handler to v12, making v11 upgrade a no-op. This is done so that v11 upgrade is limited to the following change only:
https://github.com/osmosis-labs/osmosis/pull/2202
The limitation is done because v11 upgrade is expedited to mitigate the impact of gauge creation spam.
This also updated the mergify configuration to enable backports to the v11.x branch.
This change is covered by e2e upgrade tests here: #2217
The e2e upgrade test is failing in this PR because our `main` uses an updated sdk fork. Since we are now moving the upgrade handler logic to v12, to properly test v11 upgrade it needs to use SDK fork from `v10.x`
##217 PR is made to ensure that the upgrade logic for v11 is sound. E2E CI on main should be fixed separately by reconfiguring e2e to now …

chore(upgrade): move v11 upgrade handler to v12, no-op for v11

---

x/gamm/twap/export_test.go
x/gamm/twap/keeper_test.go
x/gamm/twap/store.go
x/gamm/twap/store_test.go
x/gamm/twap/types/keys.go

Store management from #2168 . Every method in here should be covered by tests, with exception of deletion, which is not yet integrated. #2198 
Adds files for TWAP store management
This change added tests for every function. I believe that all 2 asset pool functionality is covered, but please verify. We may need to add more tests for 3 asset pools for `getRecordAtOrBeforeTime`, I suggest we do that in multi-asset pool integration tests after more logic is through.
- How is the feature or change documented? TWAP spec, and code comments

TWAP store.go & store_test.go files

---

x/tokenfactory/types/codec.go

Closes: #XXX
Currently we cannot use codec for token factory module as it misses initialization for amino codec registration. 
This PR adds codec init to the tokenfactory module
- Add codec initialization to token factory module.

Add codec init to tokenfactory

---

x/epochs/spec/README.md
x/gamm/spec/README.md

Closes: #XXX
The markdown linter on v11.x is failing and breaking all other backport PRs. E.g. #2258
This PR fixes it.

fix(linter): markdown lint in epochs and gamm on v11.x

---

x/gamm/keeper/internal/events/emit_test.go
x/gamm/keeper/msg_server.go
x/gamm/keeper/msg_server_test.go
x/gamm/keeper/pool_service_test.go
x/gamm/spec/README.md

Closes: #XXX
Manually backporting #2141 since Mergify is not working ref: #2273
There are no state-breaking changes. There are no risks related to the recently discovered gas problem

test(x/gamm): add liquidity event tests (manual backport #2141)

---

.github/workflows/import_paths.yml

Closes: #XXX
Our Go imports path job [is broken](https://github.com/osmosis-labs/osmosis/actions/runs/2785591872) due to changing the token permissions for security reasons.
The updated token with the right permissions should be changed here. Context: https://github.com/osmosis-labs/osmosis/pull/2115#issuecomment-1187956054

fix(ci):import paths ci job token

---

CHANGELOG.md
app/keepers/keepers.go
x/incentives/keeper/gauge.go
x/incentives/keeper/gauge_test.go
x/incentives/keeper/keeper.go
x/incentives/keeper/msg_server_test.go
x/incentives/simulation/operations.go
x/incentives/types/expected_keepers.go

Closes: #2236
In  [`#2227`](https://github.com/osmosis-labs/osmosis/pull/2227) we hard coded the fee denom for create gauge and add to gauge fees. This was done to minimize the changes for a smooth and expedited v11 release.
However, the hard-coded denom causes issues with the simulator. Simulator assumes "stake" denom for majority of its tests by default. As a result, no account has the hard coded "uosmo" denom to pay the fee. The simulator doesn't run because no account has "uosmo", only "stake"
We should avoid backporting these changes to v11.x
Use dynamic denom calculation instead of hardcoding it in these tests ;
1. TestCreateGauge_Fee
2. TestAddToGauge_Fee
3. TestChargeFeeIfSufficientFeeDenomBalance
- Does this pull request introduce a new feature or user-facing behavior changes? …

x/incentives: refactor create gauge and add to gauge fees to use txfees denom

---

CHANGELOG.md
x/lockup/keeper/admin_keeper_test.go
x/lockup/keeper/export_test.go
x/lockup/keeper/lock.go
x/lockup/keeper/lock_test.go
x/lockup/keeper/msg_server.go

There was a State machine incompatability in v10.x, due to the ordering of gas measuring methods. cref:
* https://github.com/cosmos/cosmos-sdk/issues/12788
* https://twitter.com/valardragon/status/1554117537230618624?s=20&t=tixHGobU2WBZ6zlU8ov6Gw
These two PRs caused several gas-behavior changing logics, it just happens that the subtle case is what we hit on mainnet:
* https://github.com/osmosis-labs/osmosis/pull/2030
* https://github.com/osmosis-labs/osmosis/pull/2029
They changed the order of operations in the normal case (which is what caused the out of gas bug. They also cause wholly different behavior on error situations.
- Revert state machine incompatible changes
I reviewed all the commits in https://github.com/osmosis-labs/osmosis/tree/v10.x to look for any other state machine …

Fix v10.x state incompatability

---

.github/workflows/sim.yml
Makefile
tests/simulator/sim_test.go

As part of the simulator epic, we wanted to create various makefile cmds that isolate specific portions of the simulator as a whole.
- Fixes bug where app state determinism check wouldn't commit when run by itself
- Adds separate makefile cmds for 
- Running the entire simulation package
- Running just the simulator application check
- Running just the simulator determinism check
- Running just the benchmark that outputs to a file

simulator: add makefile cmds and fix determinism test

---

chain.schema.json
go.mod

Updates chain registry, also fixes incorrect cosmwasm version entry in both go.mod and chain registry. (Note that nothing about the cosmwasm version changed, despite the go.mod update, We have a replace directive further below that moves it to v0.27.0 thats been on mainnet since v9)
Update chain registry for upgrade
End to end should cover go/mod sanity check.

Update chain registry for Osmosis upgrade

---

.github/workflows/test.yml
Dockerfile
Makefile
tests/e2e/README.md
tests/e2e/configurer/chain/node.go

* Reorder cosmwasm steps to come earlier in dockerfile
* Run go mod download to cache the go dependency downloads. (Shaves ~30 seconds as far as I can tell)
* Use RUN --mount=type=cache to speedup repeat docker builds locally. (See below for why this doesn't work in CI, I tried a few times, at some point github cache stopped working, so I quit trying)
* Rename github action steps to be more concise
* Combine a few of the prior layers
Add go cache to dockerfile
This change is already covered by E2E tests

Try to speedup dockerfile build time

---

CHANGELOG.md
cmd/osmosisd/cmd/init.go
cmd/osmosisd/cmd/root.go

Reduce osmosis block times to about three seconds. 
* #2009 compliments this and has been used by notional and others since evmos upgraded.  Those using it and not are pretty strikingly visible here:
https://ping.pub/evmos/uptime
The trouble with the tm db branch is it is enormous and it is now very different from the mainline. I don't know if it will ever become the mainline. Here is the branch:
https://github.com/tendermint/tm-db/pull/237
This is still very much draft work, and doesn't help with wall clock time at all yet. 
* make init.go set the commit timeout to two seconds
* fix the commit timeout in root.go to two seconds
Please note that these are the only changes that have been made. I am treating additional changes that may be needed because of shorter block times is out of scope …

Commit timeout

---

app/apptesting/test_suite.go
x/epochs/keeper/grpc_query_test.go

Closes: #2241
- set epoch time KeeperTestHelper 
- set epoch time in `KeeperTestHelper` to be time.Now()
- fix `BeginNewBlock` issue with executeNextEpoch = true
- Does this pull request introduce a new feature or user-facing behavior changes?  no
- Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`?  no
- How is the feature or change documented?   not documented

set epoch time KeeperTestHelper

---

x/mint/keeper/export_test.go
x/mint/keeper/keeper_test.go

Closes: #XXX
This change simplifies `DistributeMintedCoin` by doing the following:
-  removing `TestDistributeMintedCoin_ToDeveloperRewardsAddr`. Instead, making this a table-driven test case in `TestDistributeMintedCoin`
- Removing all gauge logic from `TestDistributeMintedCoin`. 
* By having gauge logic in that test, as it was previously,  we were overcomplicating that test and making it a functional test as opposed to a unit test. 
* What we want to assert in the table-driven unit test at this level of abstraction is simply the fact that the `AfterDistributeMintedCoin` hook is called. It should be irrelevant what the `AfterDistributeMintedCoin` hook does. Instead, this should be verified by the tests for the  `AfterDistributeMintedCoin` or functional / integration tests.
* The fact …

refactor(x/mint): simplify TestDistributeMintedCoin

---

osmoutils/slice_helper.go
osmoutils/slice_helper_test.go

Closes: #2181 
Refactor `ReverseSlice` utility function to be mutative and reverse in place.
* refactor existing `ReverseSlice` function
* add tests in new test file specifically for this function
* `TestReverseSlice` in `slice_helper_test.go`

refactor: make ReverseSlice mutative

---

simulation/executor/mock_tendermint.go
x/incentives/simulation/operations.go

A couple of issues have been found on long simulator runs. This PR fixes both of the issues I have found so far
- Reduces rate at which validators double sign
- Caps double signs to allow a minimum of 10 validators at any time
- (we need to address this further by including some mech to add validators to the sim set)
- Now takes into consideration the respective gauge fees when calculating random Create/Add to gauge messages

simulator: include gauge fees and cap jailed validators

---

x/tokenfactory/README.md

Update documentation on role of admin: Since the admin can change, and therefore is not always the creator of the denom, the Burning, Minting, ChangeAdmin documentation should be updated to account for this possibility. 
Incorrect documentation for Burning: Section specified instructions for Minting, not Burning.

update documentation for admin role and burning

---

.github/workflows/mutest-issue-generate.yml

Closes: #2114
1. Make github action that runs once per week
2. It runs make test-mutation
3. Takes mutation_test_result.txt, and creates a github issue. (with some formatting. Perhaps only parse out failures, and split them up with a number and separate code block)
n/a
Untested because need `secrets.ADD_TO_PROJECT_PAT` access

[CI] Mutation testing: Automated github action to generate issue

---

x/gamm/pool-models/balancer/pool.go

`CalcJoinPoolShares` has a misleading/incorrect comment that claims that `updateIntermediaryPoolAssetsLiquidity` updates "effective pool state". 
This might lead someone to believe that `CalcJoinPoolShares` mutates pool state, which is not true and can lead to a lot of confusion on how our balancer pool joins work. This isn't immediately apparent from the code unless you're already familiar with other parts of the gamm module, so I figured it would be worth correcting in a small PR.
- Minor comment change …

minor: fix comments about pool state update in `CalcJoinPoolShares`

---

app/apptesting/osmoassert/assertions.go

Closes: #XXX
Currently, there is no way to format additional messages in `DecApproxEq`. These messages could be helpful with debugging.
For example, we currently have:
```
Messages:   	expected |d1 - d2| <:	2.000000000000000000
got |d1 - d2| = 		325000000000290.000000000000000000
d1: 50000000000000.000000000000000000, d2: 375000000000290.000000000000000000
```
With this change, we could format additional messages like:
```
Messages:   	expected |d1 - d2| <:	2.000000000000000000
got |d1 - d2| = 		325000000000290.000000000000000000
d1: 50000000000000.000000000000000000, d2: 375000000000290.000000000000000000
i:365
```
- note `i:365`
The implementation is taken from:
https://github.com/stretchr/testify/blob/181cea6eab8b2de7071383eca4be32a424db38dd/assert/assertions.go#L181
- Manually tested …

refactor(osmoassert): format additional parameters in DecApproxEq

---

.github/workflows/state-compatibility-check.yml

This pull requests generalizes the workflow on `v10.x` (https://github.com/osmosis-labs/osmosis/blob/v10.x/.github/workflows/check-state-compatibility.yaml) to be applied on any `v*` branch. 
To generalize the behaviour @czarcas7ic is also adding all the pre-epoch snapshots of the `v1....v9` osmosis versions to our snapshots digitalocean space.
Before merging, we need to 
- *Add workflow to check state compatibility on multiple osmosisd version*
I've run this workflow from the `osmosis-ci` repository:
- https://github.com/osmosis-labs/osmosis-ci/runs/7669805440?check_suite_focus=true …

Generalize state compatiblity check for multiple osmosisd version 

---

scripts/replace_import_paths.sh

Closes: #2367
Fixing our import paths ci job by including the new e2e tag in the script
Tested the script locally

fix(ci): go import paths update job

---

scripts/replace_import_paths.sh

Closes: #XXX
The ci script is not working for the new query generation because it selects specific files types to update import paths for. Instead, we should relax the constraint of what files should be updated (all but in `vendor/*`, `git/*` or `*.md` files)
Tested that script works locally

fix(ci): import paths script to work with query gen

---

Makefile
tests/e2e/README.md
tests/e2e/configurer/factory.go
tests/e2e/containers/containers.go
tests/e2e/e2e_setup_test.go

Closes: #2042
Based on my experience with e2e, we should be printing container logs from executing CLI commands by default to assist with debugging.
It does add verbosity. However, I think having more logs is better than having none.
Therefore, this PR adds a change to enable logs by default and adds an option to disable it via an environment variable `OSMOSIS_E2E_DEBUG_LOG`.
The output is printed at most 3 times per CLI command. Multiple prints may happen if the container is unresponsive/slow on startup. However, from my tests locally, it prints once per command most of the time.
Tested locally.
Example new logs: https://github.com/osmosis-labs/osmosis/runs/7811392841?check_suite_focus=true
- Is …

feat(e2e): container logs printed by default and option to disable

---

.github/workflows/state-compatibility-check.yml

Continues: [2299](https://github.com/osmosis-labs/osmosis/pull/2299)
This PR improves the state-compatibility checks by:
- Improving the self-hosted setup by using an external volume to cache latest snapshots
- Fixing halting height computation of previous versions
The state-compatibility  check works now on `v10.x` and `v11.x`. 
For the previous versions we have to backport the `osmo-builder` (I will open a new PR about it).
- Update state check CI
Check running on `osmosis-ci` repo:
- [v10](https://github.com/osmosis-labs/osmosis-ci/runs/7788544173?check_suite_focus=true)
- [v11](https://github.com/osmosis-labs/osmosis-ci/runs/7790521793?check_suite_focus=true)
- Is a relevant changelog entry added to …

[CI] Improve state-compatibility check

---

CHANGELOG.md
x/mint/keeper/keeper.go
x/mint/keeper/keeper_test.go
x/mint/types/hooks.go
x/pool-incentives/keeper/hooks.go

Closes: #XXX
`AfterDistributeMintedCoin`'s parameter is unused. Removing it in this PR.

refactor(x/mint): remove unused parameter from AfterDistributeMintedCoin

---

.github/workflows/import_paths.yml

…
Closes: #XXX
Currently, there are issues with running the job on non-main branches that were discovered after trying to use it more:
- one is PR name clash due to duplicate PR names (assuming we update `main` and old branch at ones) 
- checking out code on main by default prevents from opening the PRs on old branches
This change fixes the above problems

refactor(ci): improve update paths job with per-branch names and check out non-main branch

---

CHANGELOG.md
app/apptesting/test_suite.go
x/mint/keeper/export_test.go
x/mint/keeper/genesis.go
x/mint/keeper/hooks.go
x/mint/keeper/keeper.go
x/mint/keeper/keeper_test.go
x/pool-incentives/keeper/distr_test.go

Closes: #XXX
Currently, a lot of the keeper methods are exported when they are only used inside the keeper package or in tests.
For the purposes of information hiding, we should unexport as many methods as possible to avoid misuse from incorrect locations.
There are no changes other than unexporting some methods and none of the methods were removed.
- unexport `setLastReductionEpochNum`
- unexport `getLastReductionEpochNum`
- unexport `createDeveloperVestingModuleAccount`
- unexport `mintCoins`
- create a helper in `apptesting` for minting tokens in tests
- reshuffle order in mint `keeper.go` so that exported methods go first, then unexported
- Does this pull request introduce a new feature or user-facing behavior …

refactor(x/mint): unexport keeper methods

---

x/superfluid/keeper/stake.go

Closes: #XXX
Started getting some errors without a descriptive message in e2e:
https://github.com/osmosis-labs/osmosis/runs/7886227803?check_suite_focus=true
This PR improves the error messages to help with debugging.

refactor(x/superfluid): improve lock validation errors

---

Dockerfile
Makefile
contrib/images/osmobuilder/Makefile
tests/e2e/containers/containers.go

Closes: https://github.com/osmosis-labs/osmosis/issues/2362
This PR:
- Improves the main Dockerfile 
- Fixes reproducible builds in the Makefile
**🐳 General Dockerfile improvements:**
- Move up the layer to download `go` dependencies
- Automatically detect CosmWasm version and architecture to download the correct `libwasm`
- Explicitly use the `go build...` command
- Generalize runner images
**🛠 Reproducible build** idea:
- Compile the binary (statically linked with CosmWasm) while building the container image
- `cp` the binary out of the container and place it in the build folder
These simple changes drastically simplify the build process, and they allow very nice improvements:
1. `osmobuilder` is now deprecated as the functionality is now integrated in the main `Dockerfile`
> Removing …

Fix reproducible linux builds 

---

.github/workflows/docker.yml
Dockerfile

Continues: https://github.com/osmosis-labs/osmosis/pull/2427 
This PR adds additional flavors to the osmosis Docker image.
Now you can run the `osmosisd` binary from:
- [distroless container image](https://github.com/GoogleContainerTools/distroless#distroless-container-images)
- distroless non-root container image
- alpine image
All images have `amd64` and `arm64` support.
I have also changed the default docker image from `static:nonroot` to `static`.
Distroless container images are IMHO the best way to run a golang binary. However, `nonroot` images have created permission problems in the past. To simplify, I'm proposing to use `static` distroless images as our default but still offer the possibility to run a `nonroot` Docker image via the `-nonroot` suffix.
Distroless images contain, by …

feat: add multiple docker images

---

app/upgrades/v12/upgrades.go

Closes: #2432
Removes authz messages from ICA and adds superfluid unbound
- Authz messages can no longer be executed via ICA on v12
- Superfluid unbound messages can now be executed via ICA on v12
TBD. Not sure how to test upgrades
- Does this pull request introduce a new feature or user-facing behavior changes? (yes )

feat: Removed authz and added unbound to ics host params

---

app/keepers/keepers.go
app/upgrades/v12/upgrades.go
x/mint/types/params.go
x/twap/keeper.go
x/twap/types/params.go

Subcomponent of #2451
@stackman27 and @mattverse 's findings about parameters not being registered
This is a simplified version of #2451 to ease the review (w/o the genesis logic)
Our TWAP parameters are not registered. As a result, they are causing problems in tests:
https://github.com/osmosis-labs/osmosis/pull/2443/files#diff-9983ccd8fa700e5e15dd45524983b41aa06eb76f59df65691c5564df04cdd4e4R214
This change registers the parameters and updates to defaults ("day") in v12 upgrade handler.
- covered by e2e + tested more in #2451

feat(twap/upgrade): register TWAP parameters; update epoch id in upgrade handler

---

.github/workflows/mutest-issue-generate.yml
Makefile
scripts/mutation-test.sh

Related To: https://github.com/osmosis-labs/osmosis/issues/2426
We were previously hardcoding which module to run mutation tests on. This PR now allows for a comma separated `MODULES` argument to be given to the mutation test script and allows it to run all desired modules.
Example: 
`make test-mutation MODULES=twap`
OR
`make test-mutation MODULES=twap,superfluid`
Leaving `MODULES` blank assumes all modules are desired.
- Adds comma separated module arguments to be passed into script
- Runs mutation tests on root directory of module (twap especially needs this)
- Sets current weekly CI to only run for tokenfactory
- Is a relevant changelog entry added to …

feat: mutation test script improvements

---

.github/workflows/state-compatibility-check.yml

Closes: https://github.com/osmosis-labs/osmosis/issues/2413
This PR finalizes the state compatibility check to make it compatible with:
- `v11.x`
- `v10.x`
- `v8.x`
- `v6.x`
- `v3.x` 
Every new PR to these branches would trigger this workflow that:
- Builds the binary
- Downloads (if not already present in the runner) a snapshot that was taken 100 blocks before the last epoch of that version
- Configures the node to halt 50 blocks after the epoch
I also have:
- Removed the alarm step
- Moved the schedule trigger to the `osmosis-ci` repository to avoid confusion
- Modify state compatibility check to work with `v11.x`, `v10.x`, `v8.x`, `v6.x` and `v3.x` 
This workflow can be triggered manually in the `osmosis-ci` repository:
- [v11.x](https://github.com/osmosis-labs/osmosis-ci/runs/792182970 …

Finalize CI state compatibility to osmosisd version

---

CHANGELOG.md
app/upgrades/v7/upgrades.go
x/superfluid/keeper/gov/gov.go
x/superfluid/keeper/keeper_test.go
x/superfluid/keeper/superfluid_asset.go
x/superfluid/keeper/unpool_test.go

Closes: #XXX
Drive-by changes to improve error handling when adding superfluid assets.

refactor(x/superfluid): improve error handling for AddNewSuperfluidAsset

---

store/node.go
x/superfluid/keeper/intermediary_account.go

Relates to https://github.com/osmosis-labs/osmosis/issues/2414
Fix unclosed iterators
- Use custom tool to find unclosed iterators: https://github.com/baabeetaa/osmosis/issues/1
- Tested manually with osmosis v11.0.0 on mainnet for ~20mins and found no unclosed iterators.
Sometime i see an err in log, im not sure its is a new bug with pebbledb only (i havent tested with goleveldb) or maybe it does not relate to this PR.
```
11:41AM ERR recovered (default) panic. Could not capture logs in ctx, see stdout
Recovering from panic  {WritePerByte}
goroutine 664 [running]:
runtime/debug.Stack()
/usr/lib/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
/usr/lib/go/src/runtime/debug/stack.go:16 +0x19
github.com/osmosis-labs/osmosis/v10/osmoutils.PrintPanicRecoveryError({{0x277bd18, …
```

fix unclosed iterators

---

app/apptesting/gamm.go
x/twap/README.md
x/twap/api.go
x/twap/api_test.go
x/twap/keeper_test.go
x/twap/listeners_test.go
x/twap/logic.go
x/twap/store.go
x/twap/store_test.go
x/twap/types/utils.go
x/twap/types/utils_test.go

Part Of: #2426 
This PR brings the mutation test score for the twap module from ~33% to ~46%
PRing this now to prevent a large diff for the next / upcoming mutation fixes
- Adds `RunBasicJoin` as a GAMM keeper test helper
- Corrects lexicographical order of twap denoms
- `getMostRecentRecord` switches order
- also checks that the denoms are not equal
- Removes ordering from `GetBeginBlockAccumulatorRecord` (this is done in `getMostRecentRecord` which this function calls/returns. Better to have the logic at the higher level)
- Improves `TestGetBeginBlockAccumulatorRecord` …

chore: twap mutation fixes part 1

---

app/apptesting/test_suite.go
osmoutils/export_test.go
osmoutils/store_helper.go
osmoutils/store_helper_test.go
x/twap/store.go
x/twap/types/keys.go

Part of #2179
This change spearheads store testing of `osmoutils`. Additionally, it adds a convinenet way to iterate over prefix.
In future PRs, the rest of the methods will be tested.

feat/test(osmoutils): prefix iteration for osmoutils gather; begin testing store

---

Makefile

Related issue: [#2482](https://github.com/osmosis-labs/osmosis/issues/2482)
Addresses first task
This PR makes small changes to the `make build-reproducible` command to adapt it to the new release process.
The new release process doesn't use `osmobuilder` anymore, so we can finally deprecate it.
The new release process is complete and can be seen [here](https://github.com/osmosis-labs/osmosis-ci/blob/main/.github/workflows/create-release.yaml).
- Small changes to `Makefile` 
Changes are trivial.
I have tested the workflow by creating a fake release. 

Deprecate osmobuilder and remove contrib folder [1/2]

---

osmoutils/store_helper.go
osmoutils/store_helper_test.go

Closes: #XXX
This is the first PR for merging the mint truncations solution.
ADR is available in: https://github.com/osmosis-labs/osmosis/pull/2486
This change is extracted from: https://github.com/osmosis-labs/osmosis/pull/2342
This change only includes store helpers used from the original mint truncations solution as well as their tests.
In addition, it covers an already existing function `MustSet` with tests.

feat(osmoutils/mint): mint truncations pt1 - store helpers

---

x/mint/types/minter.go
x/mint/types/minter_test.go
x/mint/types/params.go
x/mint/types/params_test.go

Closes: #XXX
This is the second PR for merging the mint truncations solution.
ADR is available in: https://github.com/osmosis-labs/osmosis/pull/2486
This change is extracted from: https://github.com/osmosis-labs/osmosis/pull/2342
This change focuses on splitting the epoch provisions into 2 parts:
- so called "inflation provisions" - these are distributed from the mint module account
- developer vesting provisions - distributed from the developer vesting module account
The added params and minter logic is not used anywhere yet. The new changes will be used in future mint truncations PRs.
- How is …

refactor(x/mint): truncations pt 2 - provisions split in params and minter

---

x/gamm/pool-models/balancer/pool.go
x/gamm/pool-models/balancer/pool_suite_test.go
x/gamm/types/errors.go

Closes: #2207, #2445
This PR prevents `SpotPrice` from panicing and makes it return an error for invalid or overflowing spot prices instead. It also adds tests to ensure spot prices stay within the set bounds.
- `SpotPrice` now recovers panics and returns an error. It also sets a max spot price of 2^160
- New tests can be found in x/gamm/pool-models/balancer/pool_suite_test.go

x/gamm: Catch overflow panics on `CalculateSpotPrice`

---

simulation/executor/params.go

Closes: #XXX
After incorporating the SQL database, I observed that there were large periods of time in which no txs were happening on large stretches of blocks. After a short discussion with @ValarDragon , he found that the transition matrix that decides block sizes was configured in such a way that keeps the blocksize in the "default" state (which is a blocksize of 0) for a longer than intended time period.
- Small change to matrix values
As desired, we still have blocks with 0 txs, but they are few and far between. We may want to make the 0 txn blocks occur slightly more often, but that would just be a simple mod of this matrix, and now we know where the issue is coming from!
- Is a relevant changelog …

simulator: transition matrix fix

---

x/epochs/module.go

Closes: #XXX
- Epoch module imports mint/cli/rest and Registers it to it's routes.
- fixes typo causing epoch module to register mint rest routes.
- `RegisterRESTRoutes` does nothing now as epochs doesn't have legacy rest implemented.
- cannot test as ["mint paraters - legacy querier not supported for the x/mint module "](https://lcd.osmosis.zone/minting/parameters)
- Does this pull request introduce a new feature or user-facing behavior changes? (yes / no) no
- Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (yes / no) no 

Fix: epoch module imports mint rest

---

.gitignore
scripts/mutation-test.sh

Fixes `make test-mutation`, and ensures blocks.db from simulator is ignored regardless of directory

Minor CI tool fixes

---

CONTRIBUTING.md

Closes: #XXX
Add documentation for state-compatibility safety, patch and minor releases.

docs: state-compatibility documentation

---

osmoutils/cache_ctx.go
x/epochs/types/hooks.go

In #2515 @puneet2019 fixed that epochs isn't returning events, due to https://github.com/cosmos/cosmos-sdk/issues/12912 .
This also showed that were actually duplicating panic wrapping logic. This PR adds that fix to the general osmosis helper, and makes epochs use the general osmosis helper
- Apply events bug fix from #2515 to the general panic wrapper
- Make epochs use the general panic wrapper
This change is already covered by existing tests, that @puneet2019 added in #2515

Unify cache_ctx wraps

---

app/upgrades/v12/upgrades.go

Adds MsgTransfer from `ibctransfertypes` in the ICA Initialization progress for V12 upgrade handler.
- Add `MsgTransfer` from ibc transfer types to ICA Module allowed message
- Does this pull request introduce a new feature or user-facing behavior changes?  
- How is the feature or change documented? already documented

Add IBC MsgTransfer for ICA Module

---

app/upgrades/v12/upgrades.go

As discussed on chain dev call, we will remove the maxAgeNumBlocks change from the upgrade logic. The benefit to changing this is currently unconvincing and would need more time to further look into this.
- remove reduction of maxAgeNumBlocks from v12 upgrade handler

chore: remove maxAgeNumBlocks from upgrade

---

CHANGELOG.md
x/epochs/keeper/abci.go
x/epochs/keeper/hooks.go
x/epochs/types/hooks.go
x/epochs/types/hooks_test.go
x/incentives/keeper/hooks.go
x/mint/keeper/hooks.go
x/mint/keeper/hooks_test.go
x/superfluid/keeper/epoch.go
x/superfluid/keeper/hooks.go
x/twap/listeners.go
x/txfees/keeper/hooks.go

Closes: #XXX
A part of #2520 only implemented for epochs module. 
If it looks good, can go ahead and implement for other modules as well. 
would wait for #2519 to be merged before. (rebase, etc. then open up)
- Hooks errors can now be handled with [`ApplyFuncIfNoError`](https://github.com/osmosis-labs/osmosis/blob/main/osmoutils/cache_ctx.go#L16) 
- This implementation allows `hooks interface` functions to return an error.
- If functions return an error any state changes will not be written to the state.
- Currently it is only done for [`EpochHooks interface`](https://github.com/osmosis-labs/osmosis/blob/main/x/epochs/types/hooks.go#L9)
- Epoch Hooks now allow returning of error.
- All modules implementing EpochHooks also return error in place of panic.
- Updated and fixed test cases …

error returning epoch hooks

---

app/apptesting/gamm.go
x/twap/listeners.go
x/twap/listeners_test.go

Closes: #2540
> Add `trackChangedPool` to `AfterExitPool` listener
> Add tests for `AfterExitPool` hooks

Twap: after exit pool hook

---

osmoutils/store_helper.go
osmoutils/store_helper_test.go

Closes: #2179 
This PR adds tests for all the untested functions in `osmoutils/store_helper.go`.
- Add tests for the following functions:
`GatherAllKeysFromStore`
`GatherValuesFromStore`
`GatherValuesFromStorePrefix`
`GetFirstValueAfterPrefix`
`GetIterValuesWithStop`
`GetValuesUntilDerivedStop`
This change added tests (see functions listed above)

Make tests for osmoutils/store_helper

---

tests/e2e/configurer/chain/node.go

It seems we have zero issue running e2e tests locally, however have intermittent issues running through CI. By looking through previous failed runs and where they fail, they seem to fail specifically when starting the new containers after upgrade. While I don't have evidence since this is hard to debug when its only happening in CI, I have a feeling this has to do with weird docker networking problems rather than the upgrade itself failing. Because of this, I wanted to see if changing from the rpcClient health call to instead a height call would make a difference. 
- changes the run command to check the height rather than health
- Is a relevant changelog …

fix: e2e flakiness

---

app/apptesting/test_suite.go
app/test_helpers.go

cref #2148 , small speedup to app setup time / all tests
```
BEFORE
BenchmarkSetup-16             57          20107194 ns/op         1753442 B/op      22513 allocs/op
AFTER
BenchmarkSetup-16    	      76	  16989387 ns/op	 1087661 B/op	   13536 allocs/op
```
deduplicate genesis creation & encoding config every time its needed

Cache genesis setup in App.Setup

---

app/apptesting/test_suite.go
x/tokenfactory/keeper/genesis_test.go
x/tokenfactory/keeper/keeper_test.go

Closes: #2502 
In the keeper tests, in order to test that we are properly generating the module account, we need to first remove it. However, 
Dev suggested the following: Make a new suite.SetupGenesisTest() constructor that takes care of this so we don't need to worry about this with future tests.
n/a
Create new suite `TestGenesisTestSuite` for genesis_test

[Test] Create suite.SetupGenesisTest() that takes care of module account removal

---

x/twap/api.go
x/twap/api_test.go
x/twap/export_test.go
x/twap/keeper_test.go
x/twap/listeners_test.go
x/twap/logic.go
x/twap/logic_test.go
x/twap/store.go
x/twap/store_test.go
x/twap/types/errors.go

Closes: #2518
Modify TWAP pruning to keep the newest record younger than block time - keep period.
Please see #2518 for details.
Additionally, it switched assertions in `api_test.go` from asserting on error strings to actual errors. This required defining several custom errors.
- Modify pruning logic
- Modify existing table-driven tests to account for the change
- Add more tests for getting TWAP from times earlier than block time - keep period
- Modify hook test
This change added tests mentioned in changelog

feat(twap): pruning keep the newest record under keep threshold

---

go.mod
go.sum

Closes: n/a
Add support for Ledger Nano S+ (Ledger's newest device)
This pull request simply updates ledger-go to v0.9.3 which adds support for Ledger Nano S+.
The same was done in Cosmos Hub a little while back: https://github.com/cosmos/gaia/commit/0420982086799cfad795f1ce271446002b9e5258
The ledger-go v0.9.3 release can be found here to see the changes: https://github.com/cosmos/ledger-go/releases/tag/v0.9.3
- Upgrade ledger-go to v9.0.3 to add support for ledger nano s+
- Does this pull request introduce a new feature or user-facing behavior changes? (~~yes~~ / no)
- Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (~~yes~~ / no)
- How is the feature or change documented? (not …

Added support for ledger nano s+

---

CONTRIBUTING.md
Makefile
tests/e2e/scripts/run/check_image_sha.sh
tests/e2e/scripts/run/common.sh
tests/e2e/scripts/run/remove_stale_resources.sh

Closes: #2002, #2315
1. Add scripts and makefile steps for rebuilding docker image and clearing resources
- `make e2e-check-image-sha`
* compares the git sha assigned to the pre-existing tag against a local Git commit sha
* rebuilds the image if hashes do not match
- `make remove-resources`
* removes all e2e Docker resources, including containers and network
- `make e2e-setup`
* combines and runs both of the above steps
Create 3 separate Makefile steps for running e2e:
- `make test-e2e` to run in CI
* before starting runs `make e2e-setup`
- `make test-e2e-debug` to run full suite locally
* before starting runs `make e2e-setup`
* does not clear Docker resources at the end (for debugging)
- `make test-e2e-short` to run short test suite locally
* before starting runs `make e2e-setup`
* …

ux(e2e): Makefile steps to run e2e test suite locally

---

x/twap/api_test.go
x/twap/logic.go
x/twap/logic_test.go
x/twap/store_test.go

Closes: #2412 
This PR adds tests regarding overflow in accumulator within the TWAP module, specifically a test proving that it takes 2 ** 128 nano sec(over 292years) with max spot price for a pool to overflow our current accumulator.
This PR tests with testing field of sdk.Dec instead of time.Duration, because it becomes impossible to test overflowing testing scenarios since time.Duration would always automatically cap to time.Duration.MaxDuration, without erroring or panicing if we're trying to create a duration significantly big enough
- Adds overflow test for TWAP Accumulator
- How is the feature or …

TWAP: Add overflow test

---

go.mod
simulation/executor/mock_tendermint.go
simulation/executor/schema.sql
simulation/executor/simulate.go
simulation/executor/simulate_dev.go
simulation/executor/stats_db.go

This is some small simulator backend cleanup. Was doing this as driveby's with property check integration, decided to split this out into its own PR.
- We move validator type juggling to mock_tendermint
- Abstract db work into its own file + a schema file
To get further significant improvements in code readability & debugging, I think we need to:
* Be able to create the traces produced by logWriter, off of the statsDb, then we can start deleting  the logWriter and move `runBlockSimulator` to be based off the simpler simstate struct
* Ditto for event logging / tally fn
* Finally open up & tackle genesis handling
* Start improving queued operation (e.g. queued action)
Going to move some of these further works into new issues
This change is a trivial rework / code cleanup without any test …

Small simulator backend cleanup

---

.github/workflows/contracts.yml

This PR removes IBC rate-limiting tests from our github workflow as IBC rate-limiting code was removed from the v12 branch so these tests are causing backports to fail
- Remove ibc rate-limiting tests from workflow

Remove ibc rate limiting tests from gh workflow

---

x/twap/api.go
x/twap/api_test.go

Add time range safety check to GetArithmeticTwapToNow, to prevent incorrect API usage.

Add time range safety check to GetArithmeticTwapToNow

---

CHANGELOG.md
app/apptesting/gamm.go
x/gamm/README.md
x/gamm/keeper/grpc_query_test.go
x/gamm/keeper/msg_server_test.go
x/gamm/keeper/multihop.go
x/gamm/keeper/multihop_test.go
x/gamm/keeper/swap.go
x/gamm/types/constants.go
x/gamm/types/route.go

Closes: #2406
This pull request reduce swap fee for a half during calculation for each pool for routes with length of 2 and osmo intermediate, ex `ATOM -> OSMO -> USDC`. 
In general it is re-implementation of https://github.com/osmosis-labs/osmosis/pull/1069 with addition tests added.
- x/gamm Change `SwapExactAmountIn` and `SwapExactAmountOut`to take fee multiplier as addition input param.
- Update multihop swaps test, to insure that half fee applies only for osmo routed multihop swaps.
- *Added cases for existing multihop unit tests.*
- Does this pull request introduce a new feature or user-facing behavior changes? yes 
- Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`?  yes
- How is the feature or …

x/gamm: Reduce swap fee for Osmo-routed trades (#2406)

---

CHANGELOG.md
x/twap/README.md
x/twap/client/query_proto_wrap.go
x/twap/logic.go
x/twap/store.go
x/twap/types/keys.go

Notes / fixes from the live TWAP code review
Two important bugs found during code review! 
* Time.Now() bug in query that was getting vendored (fixed in this PR)
* Thankfully wouldn't have caused mainnet issue, since exec time always greater than block time, and we've well defined returning an error in this case
* Bug in pruning logic (not yet fixed)
Mostly comment + TODO adds

TWAP notes/fixes from code review

---

x/twap/store.go
x/twap/store_test.go

Fix a bug in multi-asset pool pruning that was found in code review.
- Fix bug in multi-asset pool pruning, by making seen index a triplet
Single test case added

Fix the multi_asset pool pruning bug

---

wasmbinding/query_plugin.go
wasmbinding/query_plugin_test.go
wasmbinding/stargate_whitelist.go

Current Stargate querier implementation would not proto unmarshal & json marshall as expected, if the query includes a repeated field, the query simply appending on top of the existing struct. This way each time we parse the protobuf data we are simply appending to the existing array, thus having to need to zero it out every time we load. 
This PR solves the existing problem by resetting the message every time we call a query request. 
- Reset proto message every time query is called
Adds a test case that includes query with iteration
Special thanks to @ethanfrey for helping with the insights here!

Fix: Add proto reset to Stargate Querier

---

x/twap/logic.go

[TWAP]: Add safety check regarding the number of records in updateRecords

---

wasmbinding/export_test.go
wasmbinding/query_plugin.go
wasmbinding/query_plugin_test.go
wasmbinding/stargate_whitelist.go

Make type safety guaranteed for Stargate query whitelist, and make it impossible to set things on it from other packages.

Add type safety to query whitelist

---

osmoutils/encoding_helper.go
osmoutils/encoding_helper_test.go
x/twap/keeper_test.go
x/twap/logic.go
x/twap/store_test.go
x/twap/types/keys.go
x/twap/types/keys_test.go

Fix lexicographic ordering for iterating over our key space by pool Id.
- Adds a helper for fixed length padding
- Uses it for twap MostRecentKey store
This change added tests.
We can see that the first commit captures the prior failing behavior, and the second subsequently fixes it.

Fix lexicographic ordering of get all most recent keys for pool

---

osmoutils/store_helper.go
osmoutils/store_helper_test.go
x/twap/api_test.go
x/twap/export_test.go
x/twap/store.go
x/twap/store_test.go
x/twap/types/keys.go
x/twap/types/keys_test.go

This is a minor performance improvement, but more importantly a complexity reduction for getting entries from the pool index. Do we want to go with this approach?
It came up on the TWAP review call. I am not sure that it is worth simplifying because:
* No known bug here
* Performance improvement isn't really a big deal (reduces gas usage of TWAPs, but should not be a huge deal)
* Removes +1ns hack (though we could also remove that via other means)
Depending on folks thoughts (cc @p0mvn @czarcas7ic @AlpinYukseloglu ), we should decide whether this is a helpful simplfiication or not.
- Simplify method of getting records in all TWAP queries
- Improve gas efficiency for multi-asset pool TWAP queries (not a usecase we care about optimizing) …

TWAP: Simplify historical pool index

---

.github/workflows/test.yml
Makefile

Closes: #2652
Stops double building the images by introducing a separate makefile step dedicated to CI that does not run image rebuilding logic.

fix(e2e/ci): stop double building docker images

---

.markdownlint.yml
Makefile

Closes: #2528 
Adds two makefile commands, `make mdlint` and `make markdown` that allow our markdown linter to be run locally in a way that is aligned with our CI markdown linter.
Running `make markdown` on our full codebase currently yields this: #2631 
- Add `make mdlint`, which runs our markdown linter without making any changes
- Add `make markdown`, which fixes as many markdown issues as it can and then displays the remaining ones

Create equivalent make commands for markdown linting

---

proto/osmosis/twap/v1beta1/query.proto
proto/osmosis/twap/v1beta1/query.yml
wasmbinding/stargate_whitelist.go
x/ibc-rate-limit/README.md
x/twap/client/grpc/grpc_query.go
x/twap/client/query_proto_wrap.go
x/twap/client/queryproto/query.pb.go
x/twap/client/queryproto/query.pb.gw.go

Renames these queries to remove the `Get` from their name

Remove Get from GetArithmeticTwap query & GetArithmeticTwapToNow query

---

cmd/osmosisd/cmd/airdrop.go.history
cmd/osmosisd/cmd/balances_from_state_export.go
cmd/querygen/templates/queryyml.go
simulation/executor/event_stats.go
simulation/executor/legacyconfig.go
simulation/simtypes/manager.go
store/legacy/v101/tree_test.go
tests/e2e/containers/containers.go
tests/e2e/e2e_test.go
tests/e2e/util/io.go
tests/simulator/genesis.go
tests/simulator/state.go
wasmbinding/test/custom_query_test.go
wasmbinding/test/store_run_test.go
x/gamm/client/cli/parse.go
x/lockup/client/cli/query.go

`make format` was failing locally due to a deprecated import:
This PR replaces the import with its updated version. cc: @ValarDragon since this mainly touches simulator code
- Replace all uses of `io/ioutil` with `os`

Replace deprecated `ioutil` imports with `os`

---

x/twap/api_test.go
x/twap/keeper_test.go
x/twap/logic_test.go

Closes: #2538
PR #2604 attempted to combine current tests with three asset pool tests. This proved to be very messy and unclear. This PR is another attempt at implementing these tests in a separate and clearer manner. Additionally, more complex test cases are used (varying spot prices for all three assets) for every three asset pool test case along with comments explaining the math behind each expected twap.
Part one addresses api_test.go
Part two will address logic_test.go and store_test.go
- Adds test cases for api_test.go
- Adds function in keeper_test.go to generate default three asset pools
- Is a relevant changelog entry added to the `Unreleased` …

x/twap: three asset pool tests (part 1 of 2)

---

x/twap/api_test.go

Closes: #2562 
This PR adds tests for `GetArithmeticTwap` to ensure it works correctly under spot price errors.
Test cases added:
- spot price error before start time
- spot price error in record between start/end time
- spot price error exactly at start time
- spot price error exactly at end time
This change adds tests.

TWAP: Test cases for LastSpotPrice Error

---

tests/e2e/containers/config.go
tests/e2e/e2e_test.go
tests/e2e/initialization/config.go
tests/e2e/scripts/nativeDenomThreeAssetPool.json

Closes: #2647 
Closes: #2723 
Converts TestTwap to test TWAP functions with a three asset pool
- Updates pre upgrade init image to mint ion during initialization. Without this, we only have two native assets (uosmo and stake)
- Adds three asset pool logic and inequalities to respective checks

e2e: make TWAP test for three asset pools

---

Makefile
tests/localosmosis/scripts/add_keys.sh
tests/localosmosis/scripts/setup.sh

Closes: #XXX
After the introduction of docker buildkits, we did not add this required buildkit to localosmosis. This fixes this issue.
I also:
* Changed the val key so its the same between localosmosis and localosmosis with mainnet state
* Added a line to the setup script to make changing between permissioned and permissionless cosmwasm easier

fix: localosmosis build patch

---

app/apptesting/test_suite.go

The SDK baseapp has a very undocumented / hard to understand dependence on new Ctx generations, that are needed for `App.DeliverTx` to work with the same go ctx we use in test code. This is something we reverse engineered to be correct within the simulator, and just painstakingly did for osmosis-rust.
This applies the fixes to our app testing framework, to mitigate chance of edge case in the future.
{TODO, after confirming incremental updates don't break things}
This change is already covered by existing tests passing
- How is the feature or change documented? (not applicable   /   specification …

App testing consistency improvements

---

wasmbinding/stargate_whitelist.go

I think we should revert this query in our whitelist, and have everyone use other queries. 
We shouldn't leak the internal proto representation of pools, and have this be a stable API for contracts. The other queries are the stable queries for pools. We should later on add a `PoolType()` query for stableswap.
- Remove pool query from stargate whitelist

Revert pool query being accessible via cosmwasm

---

CHANGELOG.md
go.mod
go.sum
simulation/executor/simulate_dev.go
tests/simulator/state.go
x/gamm/simulation/sim_msgs.go

Part of #2566
Upgrade wasmd to v0.28.0
Branch: https://github.com/osmosis-labs/wasmd/tree/v0.28.0x-osmo-v12
Tag: https://github.com/osmosis-labs/wasmd/releases/tag/v0.28.0-osmo-v12.1

chore: upgrade wasmd to v0.28.0

---

x/gamm/pool-models/stableswap/amm.go
x/gamm/pool-models/stableswap/amm_test.go

Closes: #2694 
From issue:
> While testing our stableswap CFMMs (both two-asset and multi), I noticed that given their complexity it is possible for certain really weird inputs to get passed into the solvers that go completely uncaught. Both for security reasons and for more time-effective testing/bug squashing, I think we should implement validity checks for inputs to (and outputs of) the CFMM solvers.
This PR adds these validity checks.
- Ensure inputs and outputs of CFMM functions are checked for basic validity (not negative, outputs not greater than reserves etc.)
This change added tests that verify negative input checks in `stableswap/amm_test.go` …

[stableswap]: Add checks for invalid cfmm inputs

---

x/lockup/types/msgs.go
x/lockup/types/msgs_test.go

Closes: #XXX
As discovered on the v12 integrator testnet, attempting a begin-unlock-by-id (MsgBeginUnlocking) results in an error. This is because we pass a nil Coins object to MsgBeginUnlocking when we unlock by id, and the newly added ValidateBasic requires a length of 1 (which would be used if we are unlocking a specific subset of the lock)

fix: MsgBeginUnlocking bug

---

CHANGELOG.md
wasmbinding/message_plugin.go
wasmbinding/queries.go
wasmbinding/test/messages_test.go
x/gamm/keeper/estimate_swap.go
x/gamm/keeper/grpc_query_test.go
x/gamm/keeper/swap.go

Sub component of  https://github.com/osmosis-labs/osmosis/pull/2378
https://github.com/osmosis-labs/osmosis/pull/2378 has some parts in code where code de-duplication can take place. This PR includes minor refactoring to for code cleanup and code de-duplication.
- Remove code duplication for Estimate methods

Refactor EstimateSwap (https://github.com/osmosis-labs/osmosis/pull/2378)

---

CHANGELOG.md
cmd/osmosisd/cmd/init.go
cmd/osmosisd/cmd/root.go

This reverts commit 701b391044da52e67c673f1a5f1304b98bfaa1f0.
Closes: #XXX
The PR from #2057 reduced time timeout to two seconds for all nodes, regardless of config settings. After discussion, we decided this is not desirable. I did leave the change to init.go so that any future nodes initialized will default to 2 (but can overwrite via their config file)

Revert "Commit timeout (#2057)"

---

x/twap/logic.go
x/twap/migrate.go
x/twap/store.go
x/twap/types/utils.go

Closes: #XXX
- Remove 2 redundant iterations from `GetAllUniqueDenomPairs`
- Obsolete comment in `updateRecords`
- Redundant casts in `MigrateExistingPools`
- Redundant allocation of `sentinelExistsValue` on every call
All changes are super minor. This is a drive-by change for best practices. None are state-breaking.

review(x/twap): minor post-review clean up (post v-12)

---

osmoutils/module_account.go
osmoutils/module_account_test.go
osmoutils/store_helper_test.go
x/gamm/keeper/pool_service.go

Make gamm pools still creatable if the underlying account already exists
- Add helper methods for creating module accounts, to override underlying ones. This is safe because module accounts as long created via the correct constructors, have domain separation and collision resistance from other addresses.
- Apply change to AMM module
- added unit tests that validate the new method works with prior addresses existing
- Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? no*
- How is the feature or change documented? code comments

Make gamm pools override addr already exists

---

x/twap/types/utils.go
x/twap/types/utils_test.go

Closes: https://github.com/osmosis-labs/osmosis/issues/2751
What is the purpose of the change
Solve 2751: types.GetAllUniqueDenomPairs returns pairs in increasing order so newTwapRecord doesn't have to perform unnecessary swaps
Brief Changelog
Denoms are sorted in lexicographically increasing order. tests changed
Testing and Verifying
This change is already covered by existing tests, such as "TestGetAllUniqueDenomPairs"
Documentation and Release Note
Does this pull request introduce a new feature or user-facing behavior changes? no
Is a relevant changelog entry added to the Unreleased section in CHANGELOG.md? no
How is the feature or change documented? not documented

[twap] Sort denoms in ascending order

---

x/incentives/types/gauge.go

Closes: #2757
When running state exported testnets, we ran into an issue where upcoming gauges would begin distributing after the first epoch post state export. It turns out the method we were using to determine Active or Upcoming was incorrect.
- Fixes IsActive and IsUpcoming

x/incentives: gauge method patch

---

tests/localosmosis/mainnet_state/stateprune.py

Closes: #XXX
Whenever we run a testnet with mainnet state, we normally have to wait ~2 hours to process the first block. Running this script reduces the time to wait to around 10 minutes.
- Removes ibc state
- Removes incentives state

testnet: prune script

---

tests/localosmosis/scripts/setup.sh

Closes: #XXX
We should default upload permissions to everybody in the localosmosis setup for new users without the knowledge of this option.
Additionally, adding 3rd denom at genesis by default. This is useful for testing multi hop swaps and other functionality.

refactor(localosmosis): upload permissions to everybody and extra denoms at genesis

---

CHANGELOG.md
x/gamm/client/cli/query.go

Closes: #XXX
Noticed this command not being present in `osmosisd`.

fix(cli/gamm): total pool liquidity command missing

---

wasmbinding/stargate_whitelist.go

Reverts #2738 
This is because folks need it to get pool weights at the moment, as pool wieghts are poorly abstracted

Revert commenting out the pool query

---

osmoutils/binary_search.go
osmoutils/binary_search_test.go

Progress towards: #2794 and #2702
This PR implements a `BigDec` binary search function for our general osmoutils package.
- Add `BinarySearchBigDec` to osmoutils
- Add `CompareBigDec` to osmoutils
- Refactor existing and new tests to be more readable (string map names, `t.Run` etc.)
This change added tests for both new functions in `osmoutils/binary_search_test.go`

Implement `BigDec` binary search in osmoutils

---

CONTRIBUTING.md

Closes old issue from docs here: https://github.com/osmosis-labs/docs/issues/18
Simple request to add link to the contribute page on Github.

Added link to contribute page

---

Makefile
tests/localosmosis/docker-compose.yml
tests/localosmosis/scripts/setup.sh

Closes: #XXX
After discussion with @p0mvn, we agreed it would be very useful to provide an option (non-default) for LocalOsmosis to start with some pre-loaded state. This MVP allows a user to start their LocalOsmosis instance with `make localnet-start-with-state` and have two pools automatically created (one two asset pool and one three asset pool).
- Adds state flag to setup.sh, when set:
- Creates a two asset pool
- Creates a three asset pool 

feat: add gamm state to localosmosis

---

x/gamm/keeper/msg_server_test.go

Caught this in re-reviewing all gamm changes for v12
Gamm keeper tests were getting double ran, due to:
```
keeper/keeper_test.go
23:	suite.Run(t, new(KeeperTestSuite))
```
and 
```
keeper/msg_server_test.go
20:	suite.Run(t, new(KeeperTestSuite))
```
This PR fixes this. 
Manually verified by doing `go test -v ./x/gamm/keeper/.` before and after this change.

Stop double running gamm tests

---

README.md

The link for join mainnet was directing to a no longer found page, updated with current docs location.

fix joining mainnet link in readme

---

osmomath/rounding_direction.go
osmomath/rounding_direction_test.go
x/gamm/pool-models/stableswap/README.md
x/gamm/pool-models/stableswap/amm.go
x/gamm/pool-models/stableswap/pool.go
x/gamm/pool-models/stableswap/pool_test.go

Closes: #2903 
Context in 2903, makes the API scale to/from BigDec.
Adds rounding mode for Int / U64 -> BigDec conversion
This updates tests for existing behavior. We need to add tests for other rounding modes.

stableswap: Improve the scaling factor API

---

CHANGELOG.md
osmoutils/cache_ctx.go

Backportable component of https://github.com/osmosis-labs/osmosis/issues/2487
Stop panic logs such as https://gist.github.com/jhernandezb/55b70c570a23dd2cc709b630a04acc16 in node operator logs
- Check if the error type is an out of gas error, if so suppress dumping panic logs

Stop returning error logs + stack trace when out of gas in ApplyFuncIfNoErr

---

x/gamm/pool-models/stableswap/README.md
x/gamm/pool-models/stableswap/amm.go
x/gamm/pool-models/stableswap/pool.go
x/gamm/pool-models/stableswap/pool_test.go

- Adds spec for swap methods
- Aligns swap code's scale rounding calls, and swap fee to be in line with spec
This code remains untested

Stableswap: swap, scale rounding & swapfee alignment w/ spec

---

app/export.go
cmd/osmosisd/cmd/root.go
go.mod
go.sum
osmoutils/cache_ctx.go

As part of the Merkle-drop contract, we wanted a way to provide quick exports of only the data we need. As it stands, we are required to export the entire state which takes up to an hour and a large amount of RAM. With this feature, the user can provide a comma separated list of desired modules to export. In our case, we just need to export bank which only takes ~45 seconds.
- Updates sdk fork to current osmosis-main
- Adds modulesToExport string array to export app
- Adds --modulesToExport flag to export command

feat: user defined modules to export

---

cmd/osmosisd/cmd/balances_from_state_export.go
cmd/osmosisd/cmd/root.go

The current flow is as follows:
1. Run `osmosisd export --modules-to-export="lockup,bank,gamm,staking" 2> export.json`. This gives you a state export of just those four modules (~40 seconds)
2. Run `osmosisd export-derive-balances export.json balances.json`. This gives you the balances
3. Finally, introduced in this PR, run `osmosisd staked-to-csv --minimum-stake-amount xxxxxxx balances.json airdrop.csv`
This final step gives you a csv of all accounts that have a minimum amount staked, which is then used in @p0mvn's merkledrop contract.
This staked-to-csv command should be expanded to cover many options that people may want to airdrop for (bonded gamm, holding certain assets, etc)
- adds `staked-to-csv` cli command …

feat: cli command to create csv for merkledrop

---

x/gamm/pool-models/stableswap/amm.go
x/gamm/pool-models/stableswap/amm_bench_test.go
x/gamm/pool-models/stableswap/amm_test.go

Remove "V" term from stableswap multi-asset equations, significantly lowering precision issues and improving computational overhead.
This is an accordance with the spec.
- How is the feature or change documented? Stableswap spec

Remove 'V' term from stableswap multi-asset eq's

---

cmd/osmosisd/cmd/balances_from_state_export.go

Now that we have introduced partial state exports, we have instances where we want to derive account balances for specific modules. For instance, if we just export the staking module, we dont want to error at deriving account bank balances because we expect this to be blank. This simply adds a check to see if the modules is blank, and if it is we do not require unmarshaling.
- Checks length of module when exporting balances. If zero, don't force unmarshaling and go to next module.

fix: skip unmarshaling of blank modules

---

CHANGELOG.md
app/modules.go
app/modules_test.go
osmoutils/partialord/partialord.go
osmoutils/partialord/partialord_test.go

Closes: #XXX
`ModuleNames()` function returns modules in non-deterministic order due to a map iteration. Our DAG took those modules to construct total order from a partial order. Although we tried to sort the module names to prevent non-determinism, we ended up erroneously providing the unsorted copy.
Additionally, there was no ordering constraint for the staking `EndBlock` to go after the gov `EndBlock`. The constraint is added here.
It seems that the DAG ordering problems haven't been causing issues since they were added. The ordering between stake and gov modules only matters in some edge cases. In our case, the following proposal has led to the dependency being fatal: https://www.mintscan.io/osmosis/proposals/337
Lastly, @alexanderbez created a test to make sure that the ordering is …

refactor: end block ordering - staking after gov and module sorting

---

go.mod
go.sum

Closes: #XXX
v11 state exports were broken after an ICA was made on mainnet due to ICA not being properly initialized. This is fixed in v12, but anyone trying to take a state export on a v11 height would be incapable of doing so. This fixes that issue.
- Removes ICAs from state export on v11

fix: ICA state export

---

.github/workflows/state-compatibility-check.yml

This PR allows the possibility to use a default addrbook when running the state compatibility check.
For now, the default addrbook is the chainlayer one but the plan is to migrate to our own.
- Use fixed addrbook in state compatibility check
Change tested in the `osmosis-ci` repo: https://github.com/osmosis-labs/osmosis-ci/actions/runs/3201062369

[CI] Use fixed addrbook in state compatibility check

---

x/lockup/keeper/lock.go
x/lockup/keeper/msg_server.go
x/lockup/keeper/msg_server_test.go

Closes: #2993
Context: https://github.com/osmosis-labs/osmosis/issues/2993

refactor: begin unlock event with uses split lock on partial unlock

---

scripts/generate-docs.sh

This change on the codegen scripts allows adding default servers on this openapi swagger file which will be used on the official docs. 
closes #2979

Add servers to openapi.yaml swagger file

---

x/gamm/pool-models/stableswap/README.md
x/gamm/pool-models/stableswap/amm.go
x/gamm/pool-models/stableswap/amm_test.go

Closes: #3004 and #3005
This PR expands our inverse relationship tests to accommodate multi-asset pools and scaling factors for stableswap.
- Clean up and update inverse relation tests to accommodate multi pools and scaling factors
- Add test cases for balanced and imbalanced multi pools and scaling factors
- Update multi-asset solver to accommodate negative inputs (as done with our two-asset solver in #2921
- All new and existing functionality is tested in `stableswap/amm_test.go`

[x/gamm][stableswap]: Expand inverse relation tests to multi assets and add scaling factors

---

x/gamm/pool-models/stableswap/amm.go
x/gamm/pool-models/stableswap/amm_bench_test.go
x/gamm/pool-models/stableswap/amm_test.go

Closes: #3083
This PR deprecates all uses of the two-asset binary search solver as it is no longer necessary after the recent optimizations to our multi-asset solver.
- Remove `solveCFMMBinarySearch` from under `solveCfmm`
- Delete `solveCFMMBinarySearch` and related tests (all other two-asset tests already accounted for the generalization to multi-asset solver)
- The final `solveCfmm` function passes against our full CFMM test suite in `amm_test.go`

[x/gamm][stableswap]: Deprecate two-asset binary search solver in favor of multi-asset one

---

x/gamm/pool-models/stableswap/amm.go
x/gamm/pool-models/stableswap/amm_test.go

Closes: #2730
This PR implements a direct solver for our multi-asset CFMM. Similar to our two-asset direct solver, it is intended to be kept in our codebase as a reference implementation and proof for our CFMM but is outclassed by our binary search solver for practical use.
- Implement direct multi-asset solver and test it against our full suite of CFMM cases
- The solver implementation is tested against our full multi-asset CFMM test suite in `amm_test.go`

[stableswap]: Implement simplified direct multi-asset CFMM solver

---

x/incentives/keeper/distribute.go

This is related to this issue here https://github.com/osmosis-labs/osmosis/issues/2327.
After discussion we agree that `GetModuleToDistributeCoins` of `incentives keeper` has the wrong logic. This PR fixes `GetModuleToDistributeCoins`
Use `UpcomingGaugesIterator` instead of `UpcomingGaugesIteratorAfterTime` in `GetModuleToDistributeCoins`
*(or)*
*(or)*
*(example:)*
- *Manually verified the change …

fix GetModuleToDistributeCoins

---

.github/mergify.yml

This PR removes unused osmosis versions from mergify backporting candidates.
This is not strictly necessary but it helps to avoid some confusion. Recently I had to backport a state-compatibility check PR to all *working*  osmosis versions and I backported it to versions that shouldn't be used (e.g. https://github.com/osmosis-labs/osmosis/pull/3026).
- Remove unused versions in mergify.yml

(chore) Remove unused versions in mergify backports

---

app/apptesting/test_suite.go
app/export.go
x/epochs/client/cli/query_test.go
x/gamm/client/cli/query_test.go
x/incentives/client/cli/query_test.go
x/lockup/client/cli/query_test.go
x/mint/client/cli/query_test.go
x/pool-incentives/client/cli/query_test.go
x/superfluid/client/cli/query_test.go
x/tokenfactory/client/cli/query_test.go
x/txfees/client/cli/query_test.go

Closes: #2457 
Create a func in apptesting to make sure state not change after query.
Create test in modules/client
Added new test
All test passed

Make testing suite to ensure queries never alter state

---

osmoutils/store_helper_test.go

Closes: #3138 
Add testcases for `GetIfFound` functions
All test added & passed

add tests for GetIfFound

---

app/apptesting/test_suite.go
x/gamm/keeper/pool_service.go
x/gamm/keeper/swap.go
x/gamm/keeper/swap_test.go

Closes: #3129 
Deprecates `SwapExactAmountInDefaultSwapFee` and `SwapExactAmountOutDefaultSwapFee` and ports existing test cases to use `SwapExactAmountIn` `SwapExactAmountOut`

deprecate `SwapExactAmountInDefaultSwapFee` in gamm

---

x/concentrated-liquidity/math.go
x/concentrated-liquidity/pool.go
x/concentrated-liquidity/tick.go
x/concentrated-liquidity/tick_test.go
x/gamm/pool-models/stableswap/README.md

Existing code base introduces a `lte` parameter, which was suppose to indicate if we're going down the tick or up the tick, depending on if we're setting the base asset as asset 0 or asset 1. 
The proposal is to change `lte` parameter to a varaiable `zeroToOne` to make the variable more clear and intuitive. 
ZeroToOne indicates that we're changing from asset zero to one if true. If false, changing asset one to zero

Change `lte` to `zeroToOne`

---

Makefile
tests/e2e/e2e_setup_test.go
tests/e2e/e2e_test.go
tests/e2e/initialization/init_test.go

Closes: #XXX
Build tags in e2e have reduced development UX. Build tags prevent code editors from highlighting syntax error, and worsen the experience of stepping through the code.
We can achieve the same purpose by using an environment variable instead.
- removed e2e build tags
- added environment variable instead
- `make test-e2e-short`
- `make test-unit`

chore(e2e): use environment variable instead of build tags to control e2e

---

.github/workflows/contracts.yml

Lints should use the stable rust version instead of nightly. That way we ensure they change less often.

changed lints to stable so they change less often

---

.vscode/launch.json
.vscode/tasks.json

Closes: #XXX
Add default debug .vscode configuration for e2e

chore(e2e): add vscode debug configurations

---

.dockerignore
Makefile
tests/e2e/containers/config.go
tests/e2e/e2e_test.go

Closes: #XXX
Fixed the following problems:
- tests folder excluded by dockerignore, disallowing Docker init image build
- init image being built for aarch64 when built from macs
* mitigated by specifying platform
- print debug logs for `test-e2e-debug`
- use `Require()`

fix(e2e): various e2e build issues breaking debugging on linux amd64

---

x/concentrated-liquidity/export_test.go
x/concentrated-liquidity/lp.go
x/concentrated-liquidity/math.go
x/concentrated-liquidity/math_test.go
x/concentrated-liquidity/pool.go
x/concentrated-liquidity/pool_test.go
x/concentrated-liquidity/tick.go
x/concentrated-liquidity/tick_test.go

This corrects faulty logic throughout the CL module, mostly within CalcOut and ComputeSwapStep
I think for now we should leave these tests as is, and have a subsequent issue convert it to a clean table driven test
This confirms OneToZero logic for CalcOut is good, I still need to check if ZeroToOne logic is sound (there is no reason why it shouldn't, but I didn't have time to check and wanted to get this merged to main ASAP)

CL: fix CalcOutAmtGivenIn and other logic

---

app/apptesting/test_suite.go
x/gamm/keeper/msg_server.go
x/gamm/keeper/pool_service.go
x/gamm/module.go
x/gamm/pool-models/stableswap/README.md
x/gamm/pool-models/stableswap/integration_test.go
x/gamm/pool-models/stableswap/msgs.go
x/gamm/pool-models/stableswap/msgs_test.go
x/gamm/pool-models/stableswap/pool.go

Re-enables stableswap messages, and adds validation for them working. Test currently failing right now, which means the message enabling likely hasn't been fixed.
Soundness cases needed to be added as well. Will be done in this PR
- Re-enable stableswap messages
- Add suite.RunMsg
- Start Stableswap message integration testing
*(example:)* …

Re-enable stableswap messages

---

scripts/multinode-local-testnet.sh
scripts/superfluid-test-startnode.sh

- Fixes multinode-local-testnet.sh script
- Cleans up redundant lines in multinode-local-testnet.sh & superfluid-test-startnode.sh
- Fixes issue with validator2 being set with validator3 setting in config.toml
- Improve readability
- Reduces time to start by 21 seconds
- Adds error check
- Kills osmosisd locally when you run multinode-local-testnet
- Manually verified via running both scripts locally & checking tmux instances are working as intended. 
- queried each RPCs status

chore: Fix local testnet scripts and cleanup

---

.github/workflows/contracts.yml
x/ibc-rate-limit/contracts/rate-limiter/src/lib.rs

Cosmwasm lints periodically fail due to rust versions being updated too often. Pinning the rust version to 1.65.0 and we can update it manually later. 
* Add an allow directive to ignore an unnecessary lint
* Ping rust version on the workflow to 1.65.0

Properly fix lints

---

x/concentrated-liquidity/pool.go
x/concentrated-liquidity/pool_test.go

Closes: #XXX
Adds initial SwapOutGivenIn logic. The respective test essentially check if applySwap was done on the pool, ensuring that the pool state was actually changed.
Since SwapOutGivenIn is an internal method (used in conjunction with SwapExactAmountIn), no funds are actually sent between the pool and the user. That will come next.

CL: SwapOutGivenIn logic

---

.github/workflows/state-compatibility-check.yml

This PR updates the state compatibility check to use the new snapshot service restoring its normal functionality
- Update state compatibility check CI
GitHub action running correctly on `osmosis-ci` repository: https://github.com/osmosis-labs/osmosis-ci/actions/runs/3402014427

Update snapshot service in state compatibility check CI

---

osmomath/rounding_direction.go
osmoutils/binary_search.go
osmoutils/binary_search_test.go
x/gamm/pool-models/stableswap/amm.go

Move rounding direction into error tolerance, rather than being another argument to binary search.
This change is already covered by existing binary search tests.
- How is the feature or change documented? Code comments

move rounding direction into error tolerance

---

.github/workflows/state-compatibility-check.yml

State-compatibility check for old osmosis versions ( < `v10.x` ) stalls because the node is not able to fetch old blocks from peers. Example: https://github.com/osmosis-labs/osmosis/actions/runs/3411823601/jobs/5676521439
This PR adds osmosis archive node as a persistent peer to fetch blocks for previous osmosis versions.
Add `p2p.archive.osmosis.zone` as a persistent peer 
Tested in `osmosis-ci` with `v8.x`: https://github.com/osmosis-labs/osmosis-ci/actions/runs/3412517099/jobs/5678132884
- Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? no 

Add p2p.archive.osmosis.zone as a persistent peer

---

x/gamm/pool-models/stableswap/README.md

Subcomponent of #1451 
Note in spec some of the complexity within error tolerance choices in stableswap.
This is docs updates, for existing tested behavior
- How is the feature or change documented? spec

Update stableswap spec for error tolerance mathematics

---

.github/workflows/check-state-compatibility.yml

This is a manual backport of the correct `check-state-compatibility` workflow.
We had different workflows on different branches created by cherry-picking commits while backporting. This PR aligns all `vY.x` branches to use the same workflow.
- Align check-state-compatibility workflow on all branches
N.A.
- How is the feature or change documented? no

[CI] Align check-state-compatibility workflow on v8

---

CHANGELOG.md
x/gamm/keeper/pool_service.go
x/gamm/keeper/swap.go

Closes: #3277 
Panic catch keeper operations
* panic catch keeper operations
- How is the feature or change documented? Code comments

Add keeper level panic catches

---

CHANGELOG.md
go.mod
go.sum

Upgrade to IBC v3.4.0, this should require no migration https://github.com/cosmos/ibc-go/releases/tag/v3.4.0
Adds the metadata field, needed to unblock cross-chain swaps with no multihop.
- Upgrade to IBC v3.4.0
Covered by E2E
- How is the feature or change documented? (not applicable

Upgrade to IBC v3.4.0

---

x/concentrated-liquidity/pool.go

Closes: #3291 
Use `pool.currentTick` has been saved in the last `applySwap` instead of recalculating the new one

Use current tick instead of recomputing

---

x/gamm/client/cli/flags.go
x/gamm/client/cli/tx.go
x/gamm/keeper/grpc_query.go
x/gamm/keeper/msg_server.go
x/gamm/keeper/pool.go

Closes: 
- Fix bug with not writing pool to state after attempting to set scaling factors
- Add CLI for setting scaling factors
- Fix gamm pools query for stableswap

feat/fix(stableswap): scaling factors CLI, fix bug with not saving pool to state

---

x/lockup/client/cli/tx.go
x/lockup/keeper/msg_server.go

Closes: #XXX
Prevents addresses with force unlock perms from unlocking any address. Limits their perms to only force unlock locks they create.
Also adds CLI for force unlock to lockup module.

fix: limit force unlock perms and add cli

---

Makefile
tests/localosmosis/docker-compose.yml
tests/localosmosis/scripts/setup.sh
tests/localosmosis/state_export/docker-compose.yml

Closes: #XXX
Moved localosmosis directory. Having it in the regular location, always overwrites my CLI settings for querying other RPC nodes. Additionally, it causes permission issues in the future since localosmosis is run as root in Linux with the conventional Docker setup.

chore: localosmosis in $HOME/.osmosisd-local folder

---

x/gamm/client/cli/tx.go
x/gamm/client/cli/tx_test.go
x/gamm/pool-models/stableswap/msgs_test.go
x/gamm/pool-models/stableswap/pool.go
x/gamm/pool-models/stableswap/pool_test.go

Closes: #XXX
Currently, the CLI auto-sorts the initial liquidity. As a result, denoms end up mismatching the desired scaling factor.
This PR  removes the sorting in CLI and adds the requirement in `ValidateBasic()` for initial liquidity coins to be sorted. Fails if not.
Tested on localnet. Summary: https://hackmd.io/40cR4cL5SBOuX7APZKTWIw?edit

fix(stableswap): require sorted initial liquidity

---

osmoutils/binary_search.go
x/gamm/pool-models/internal/cfmm_common/lp.go

Closes: #3355
This PR adds rounding support to our basic error tolerance `Compare` and cleans up rounding behavior for single asset joins
- Add rounding logic to `ErrTolerance`'s `CompareRounding` function as is implemented in `CompareBigDec`
- Fix binary search to properly compare expected and target (was backwards leading to odd rounding)
- Remove the subtraction by 1 on the input to `BinarySearchSingleAssetJoin`
- Remove additive error tolerance var and pass `sdk.OneInt()` in directly for `ErrTolerance` passed into `BinarySearchSingleAssetJoin`
- All binary search and single asset join tests pass
- How is the …

[x/gamm][stableswap]: Clean up rounding for single-asset joins

---

CHANGELOG.md
app/apptesting/gamm.go
wasmbinding/stargate_whitelist.go
x/gamm/keeper/grpc_query_test.go
x/gamm/keeper/pool.go
x/gamm/pool-models/balancer/constants.go
x/gamm/pool-models/stableswap/codec.go
x/gamm/pool-models/stableswap/msgs.go
x/gamm/pool-models/stableswap/msgs_test.go

Resolves an issue pointed out by @jonator 
- Add stableswap support for pooltype query
- Make pooltype query callable from cosmwasm
- Fix bug in stableswap msg validate basic, when no scaling factors provided
- Test has been added

Add stableswap to pooltype, and pooltype query to stargate whitelist

---

x/gamm/client/cli/query.go

Closes: #XXX
This PR adds cli for the new gamm queries, namely the pool type query and the pool with filter query in the gamm module. 
The pool with filter query has extra logic from the other cli commands since it uses a range args not an exact args, so we need extra review on this part. 
- Add cli support for new gamm queries

Add cli support for new gamm queries

---

x/gamm/pool-models/stableswap/README.md

This PR removes the choice of curve section from the spec as it is redundant with a number of other section.
N/A

[x/gamm][stableswap]: Remove choice of curve section from spec

---

Makefile

This PR fixes a bug in the `make build-reproducible` command that caused the latest  `v12.2.1` and `v12.3.0` release binaries to have an empty version specified. 
- Update `make build-reproducible` command
Build binaries:
- **amd64**   `make build-reproducible-amd64`
- **arm64**   `make build-reproducible-arm64`
Check that the version is set with `osmosisd version`

Release process: fix `make build-reproducible` 

---

.github/workflows/push-docker-images.yml

This PR updates the GitHub Actions CI to push docker images due to the deprecation of `set-output` commands in Github Action (source: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
The functionality's still the same.
- Update GitHub action logic
- Rename it to `push-docker-images.yaml` 
- `osmolabs/osmosis:12.3.0` and `osmolabs/osmosis:12.2.1` have already been pushed using the new logic [here](https://github.com/osmosis-labs/osmosis-ci/actions/runs/3463926268/jobs/5784817832)
- Does this pull request introduces a new feature or user-facing behavior changes? no

[CI] Update GitHub Action to push docker images 

---

x/ibc-rate-limit/contracts/rate-limiter/src/packet.rs
x/ibc-rate-limit/ibc_middleware_test.go
x/ibc-rate-limit/types/params.go

We weren't allowing the unset of the rate limiting contract param by setting the contract address to `""`
An empty string is now a valid contract address for rate limits
Added a test for this.

Allow to unset rate limiting contract param

---

osmoutils/binary_search.go
osmoutils/binary_search_test.go
x/gamm/pool-models/stableswap/README.md
x/gamm/pool-models/stableswap/amm.go
x/gamm/pool-models/stableswap/amm_test.go

Changes our stableswap binary search to be searching for k, with only a dependence in `y_{out}` not `y_final`. This fixes the convergence bound problem before, where we wasted the accuracy on the already-known bits of `y_final`, rather than the lower order bits we need.
- Make CFMM solving code cubic, rather than quartic. 
- Make it only cubic in the input amount
- Make big dec compare able to handle negatives
This change is already covered by existing tests, namely the hand worked out test vectors. Granted, we need more hand worked out test vectors for swaps. I'd not expect this to change things within the error tolerance bounds though. …

Make stableswap error in terms of input size

---

.github/workflows/mutest-issue-generate.yml

Closes: #3348
[Changes according to this](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
However, there are still many actions which depend on other actions, which were not updated. It is fine for now, but will break `1st of June 2023` Example: https://github.com/osmosis-labs/osmosis/issues/3348#issuecomment-1316364643

CI: undeprecate set-output

---

x/gamm/client/cli/query_test.go

Closes: #XXX
Add state alteration tests for the newly to be whitelisted queries: https://github.com/osmosis-labs/osmosis/pull/3217

test(gamm): CalcJoinPoolNoSwapShares, CalcJoinPoolShares, CalcExitPoolCoinsFromShares state alteration tests

---

scripts/replace_import_paths.sh

Closes: #3399
For some reason this [line](https://github.com/osmosis-labs/osmosis/blob/main/scripts/replace_import_paths.sh#L22) with normal paths returned `./x/twap/TWAP` file which does not exist. 
`Changes`: just added if statement that checks if a file exists when iterating them.
`Checks`: [successful action run](https://github.com/RusAkh/osmosis-fork/actions/runs/3476923028/jobs/5812582037)
Note that in this run I removed pull request job

CI: Fix import path

---

wasmbinding/stargate_whitelist.go

The old spot price stargate query should have been removed at one point, but seems that it has been added along in a different PR. 
This PR re-removes the old spot price query

Remove old SpotPrice query from stargate query

---

tests/e2e/e2e_test.go

Closes: #XXX
E2E has been erroring randomly lately due to the tight error precision required of the twap test. This slightly relaxes it from .1% to .2% (this could honestly be reduced to .11% if we really wanted)

fix: slight inc to error tolerance

---

x/concentrated-liquidity/export_test.go
x/concentrated-liquidity/keeper_test.go
x/concentrated-liquidity/lp.go
x/concentrated-liquidity/lp_test.go
x/concentrated-liquidity/math_test.go
x/concentrated-liquidity/msg_server.go
x/concentrated-liquidity/pool.go
x/concentrated-liquidity/pool_store.go
x/concentrated-liquidity/pool_test.go
x/concentrated-liquidity/position.go
x/concentrated-liquidity/tick.go
x/concentrated-liquidity/types/errors.go

Closes: #3143
Implemented the core functionality for removing liquidity in the concentrated liquidity module. The method is called `withdrawPosition`.
It shares a lot of the logic with `createPosition` that adds liquidity. 
In fact, a new method called `updateLiqudity` was refactored out of `createPosition`. It takes `liqudityDelta`. If the liquidity delta is negative, `updatePosition` assumes we remove liquidity. If positive, it assumes the addition of liquidity.
Please follow the method and function specs for more information on the details of the implementation.
I ended up extracting several smaller helper functions. While I have tested the high-level APIs in-detail, I still need to add tests for the helper functions. They are marked with TODOs and are tracked.

feat(CL): implement `withdrawPosition`

---

x/gamm/pool-models/stableswap/pool_test.go

Closes: #3434
> adding test cases for ValidateScalingFactors
>Added test cases in pool_test.go
- Added test cases that coverage all case of 'validateScalingFactors': 
```https://github.com/osmosis-labs/osmosis/blob/6398733549c124cb973eaa20d7aaba0fe6915ab9/x/gamm/pool-models/stableswap/pool.go#L439```

adding test cases for ValidateScalingFactors

---

go.mod
go.sum
osmoutils/cache_ctx.go

Update our SDK fork to revert the changes to cache Ctx for writing events there. While the changes are right, it changes events for IBC (adding duplicates), as IBC did a workaround similar to us. 
External things depend on IBC events, so the duplicate events causes problems for them. This is a blocker for updating to cosmwasm v0.29
After this PR, I'll PR an update to cosmwasm v0.29.x

Update our SDK fork

---

x/incentives/keeper/genesis.go

Closes: #XXX
We forget to initialize LastGaugeID despite properly exporting it. This properly initializes it with the exported param.

fix: initialize last gauge ID in init gen

---

scripts/replace_import_paths.sh

Closes: #XXX
In some cases `make proto-gen` modifies `go,mod`. As a result, that causes subsequent query-gen step to fail:
https://github.com/osmosis-labs/osmosis/actions/runs/3518190249/jobs/5896827173
Therefore, we should revendor after running proto-gen
Tested the script locally

chore: fix import paths CI vendoring failure

---

x/gamm/pool-models/internal/cfmm_common/lp.go
x/gamm/pool-models/stableswap/README.md
x/gamm/pool-models/stableswap/amm.go
x/gamm/pool-models/stableswap/amm_test.go
x/gamm/pool-models/stableswap/pool_test.go

We were accidentally over-charging swap fee for single asset joins. This PR causes us to no longer significantly over-charge. We now charge swapfee at `swapfee * fraction of pool ratio that is not the token your joining`. This is a slight over-charge, as your swap does change this ratio itself, but this is quite low. (Namely bips on the % change in liquidity ratio itself)
Reduce the amount of stableswap singleassetjoin swap fee
* Updates the test that ensures that we don't over-return funds on exit.
* Added tests that we return what is expected from the new internal function.
We should add more tests that:
* we don't return an insufficient amount, but I have spot-checked manually that this is tightly-close to the intended bound.
* Increase coverage of the join use case
* Split out single …

Fix swapfee for single asset joins

---

app/apptesting/test_suite.go
app/keepers/keepers.go
app/keepers/modules.go
app/upgrades/v13/constants.go
x/gamm/keeper/multihop_test.go
x/gamm/keeper/pool.go
x/gamm/keeper/pool_service.go
x/gamm/keeper/swap.go
x/gamm/keeper/swap_test.go
x/swaprouter/export_test.go
x/swaprouter/keeper.go
x/swaprouter/keeper_test.go
x/swaprouter/module/module.go
x/swaprouter/types/codec.go
x/swaprouter/types/constants.go
x/swaprouter/types/errors.go
x/swaprouter/types/events.go
x/swaprouter/types/expected_keepers.go
x/swaprouter/types/genesis.go
x/swaprouter/types/keys.go
x/swaprouter/types/listeners.go
x/swaprouter/types/msg_create_pool.go
x/swaprouter/types/msgs.go
x/swaprouter/types/msgs_test.go
x/swaprouter/types/params.go
x/swaprouter/types/routes.go
x/txfees/keeper/hooks.go
x/txfees/types/expected_keepers.go

Closes: #XXX
We would like to drop `concentrated-liquidity-main` branch to avoid branch synching overhead. As part of that, we are going to be incrementally merging the current concentrated liquidity feature state to `main`.
All this logic has already been given a round of reviews since we treated `concentrated-liqudiity-main` branch as `main` with appropriate review processes.
This particular PR does the following:
- fully merges `x/swaprouter/types`
- creates barebones swaprouter keeper and tests
- renames swap methods in `gamm` to legacy and adds new stubs (refactor to be continued in the future)
- minimal swaprouter wiring to be able to run unit-tests
For the latest state of the feature that we are merging, see: https://github.com/osmosis-labs/osmosis/tree/concentrated-liquidity-main …

feat(CL): swaprouter types and barebones keeper (merge to `main` 2)

---

app/apptesting/gamm.go
osmoutils/store_helper.go
osmoutils/store_helper_test.go
x/gamm/pool-models/balancer/msgs.go
x/gamm/pool-models/stableswap/msgs.go
x/gamm/pool-models/stableswap/pool.go
x/swaprouter/client/cli/cli_test.go
x/swaprouter/client/cli/common.go
x/swaprouter/client/cli/flags.go
x/swaprouter/client/cli/parse.go
x/swaprouter/client/cli/query.go
x/swaprouter/client/cli/query_test.go
x/swaprouter/client/cli/tx.go
x/swaprouter/client/cli/tx_test.go
x/swaprouter/client/query_proto_wrap.go
x/swaprouter/client/testutil/test_helpers.go
x/swaprouter/creator.go
x/swaprouter/creator_test.go
x/swaprouter/export_test.go
x/swaprouter/keeper.go
x/swaprouter/keeper_test.go
x/swaprouter/module/module.go
x/swaprouter/msg_server.go
x/swaprouter/msg_server_test.go
x/swaprouter/router.go
x/swaprouter/router_test.go
x/swaprouter/simulation/sim_msgs.go
x/swaprouter/simulation/sim_setup.go
x/swaprouter/types/routes.go

Closes: #XXX
We would like to drop `concentrated-liquidity-main` branch to avoid branch synching overhead. As part of that, we are going to be incrementally merging the current concentrated liquidity feature state to `main`.
All this logic has already been given a round of reviews since we treated `concentrated-liqudiity-main` branch as `main` with appropriate review processes.
This particular PR does the following:
- fully merges `x/swaprouter` and its tests
- disables the failing tests that depend on gamm refactor
- inclides minor non-breaking API changes in GAMM
This is the final swaprouter PR. As soon as we merge gamm refactor, the swap router can be fully enabled.
For the latest state of the feature that we are merging, see: …

feat(CL): core swaprouter logic and tests (merge to main 3)

---

.github/workflows/push-dev-docker-images.yml

This PR creates a GitHub Action to push development docker images on:
1. Every new tag containing a release candidate (e.g. `v1.2.3-rc4`).
`osmolabs/osmosis-dev:1.2.3-rc4` is pushed.
2. Every new commit to the main branch
`osmolabs/osmosis-dev:main-{SHORT_SHA}-$(date +%s)` is pushed.
3. Every new commit to a development branch vN.x (e.g. `v1.x`)
`osmolabs/osmosis-dev-v1.x:{SHORT_SHA}-$(date +%s)` is pushed.
> Note: $(date +%s) will be used later as an index to sort the tags chronologically in the docker registry to get the latest one.
All the images above support only `linux/amd64` (not `linux/arm64`) so they can be built a lot faster.
All the images are based on an alpine image for easy debugging (you would always have a shell to exec inside the container)
This is the first step for the …

[CI] Add GitHub Action to push development docker images

---

app/keepers/keepers.go
x/swaprouter/client/cli/cli_test.go
x/swaprouter/client/cli/common.go
x/swaprouter/client/cli/flags.go
x/swaprouter/client/cli/parse.go
x/swaprouter/client/cli/query.go
x/swaprouter/client/cli/query_test.go
x/swaprouter/client/cli/tx.go
x/swaprouter/client/cli/tx_test.go
x/swaprouter/client/query_proto_wrap.go
x/swaprouter/client/testutil/test_helpers.go
x/swaprouter/creator.go
x/swaprouter/events/emit.go
x/swaprouter/events/emit_test.go
x/swaprouter/export_test.go
x/swaprouter/keeper.go
x/swaprouter/keeper_test.go
x/swaprouter/module/module.go
x/swaprouter/msg_server.go
x/swaprouter/router.go
x/swaprouter/router_test.go
x/swaprouter/types/msgs_test.go

Closes: #XXX
We would like to drop `concentrated-liquidity-main` branch to avoid branch synching overhead. As part of that, we are going to be incrementally merging the current concentrated liquidity feature state to `main`.
All this logic has already been given a round of reviews since we treated `concentrated-liqudiity-main` branch as `main` with appropriate review processes.
This particular PR does the following:
- ports all cli and query logic while disabling tests
- ports swaprouter's `module` package w/o registering types
- ports all message server logic
- ports all keeper stubs but not the implementations, tests are disabled.
- adds a `SwapRouterKeeper` in `app/keepers/keepers.go` to let tests build. However, it does not initialize the keeper 
There should be no state or API breaks …

feat(CL): swaprouter cli, queries, module and keeper stubs (part 3 - no state breaks)

---

x/ibc-rate-limit/contracts/rate-limiter/src/error.rs
x/ibc-rate-limit/contracts/rate-limiter/src/integration_tests.rs

Add missing err assertion in rate limiter
- add error assertion to rate limiter test
This change added test

Add error test for rate limiter

---

x/gamm/client/cli/flags.go
x/gamm/client/cli/tx.go

Closes: #XXX
When testing osmosis multihop discount, I found that utilizing multiple pool ids and denoms in the cli was not getting parsed correctly. This fixes that issue

fix: fix multihop gamm cli

---

wasmbinding/queries.go
x/twap/api_test.go

Closes: #2962
This is a continuation of #3564 that fixes twap test asset misplace. There are no state-breaking changes here

fix/test: misplaced assets in twap tests

---

x/twap/api.go
x/twap/strategy.go

Closes: Part of https://github.com/osmosis-labs/osmosis/issues/3514 [1-3]
We need to expose a geometric TWAP API. Its implementation would be almost identical to the arithmetic TWAP API.
Therefore, we must develop proper abstractions to reduce code duplication and avoid complexity.
n/a
n/a

[x/TWAP] Expose a geometric TWAP API 

---

app/keepers/keepers.go
x/txfees/keeper/keeper.go

Closes: #XXX
Removed obsolete:
- `feeCollectorName
- `nonNativeFeeCollectorName`
These are defined globals in `types`. The keeper fields were left unused

refactor(txfees): remove redundant keeper fields and constructor params

---

CHANGELOG.md
app/export.go
cmd/osmosisd/cmd/root.go

Fixes the bug that prevents you from state exporting outside of the `.osmosisd` directory.
Driveby deletes the unused "zeroForOne" export code as well.
Tested manually

Allow state exporting from any directory

---

go.mod
go.sum

The dragonberry patch may or may not be implicitly applied from Osmosis dependencies.  This PR explicitly applies the dragonberry patch to osmosis in go.mod.  
There is an upcoming update to ics23 v0.9.0 which will replace this, but I think this is a good idea to have in v13.0.1 (and should probably be what validators upgrade to) 
* https://github.com/cosmos/ibc-go/pull/2875
The above PR may require changes to the osmosis-sdk, so for now, it likely makes sense to explicitly apply the dragonberry fix in the replace section of go.mod.
```go
// dragonberry
github.com/confio/ics23/go => github.com/cosmos/cosmos-sdk/ics23/go v0.8.0
```
to go.mod, and make a few other small cosmetic changes to go.mod
"Dragonberry active" should be visible in node logs. 
- Does this pull request introduce a new …

explicitly apply dragonberry patch

---

tests/e2e/e2e_test.go

Closes: #XXX
Roman had to disable the IBC rate limiter test due to an unknown bug. This fixes that bug and re-enables that e2e test.
The reason we incremented this before is because the contract was uploaded in the upgrade handler, and this was a prior workaround to test this within e2e itself. 
- Removed code ID increment prior to contract upload
- Re-enabled IBC test

fix: don't increment code ID in e2e before running

---

CHANGELOG.md
Makefile

Go 1.19 had changes that are consensus breaking. Thank you to @jhernandezb for pointing this out. This applies his suggested patch to Makefiles to ensure that all binary builds are done with the same go minor release line.
- Require go 1.18 installed for building the binary.
Try building the binary if you don't have go 1.18, or build being a success if you do have go 1.18.
I've tested both

Ensure go v1.18 used in make build & make install

---

app/test_helpers.go
x/ibc-hooks/ibc_middleware_test.go
x/ibc-rate-limit/ibc_middleware_test.go
x/ibc-rate-limit/testutil/chain.go
x/incentives/keeper/hooks.go

Does basic changes to speedup tests, driven by `x/ibc-rate-limit`, but should have more broad impact.
Locally `13.943s -> 2.670s`, CI: `86.922s -> 10.370s`. As a side effect:
IBC-hooks `107.357s -> 3.827s`
- Disable epochs on both chains in ibc-rate-limit tests (big win)
- Make epochs not allocate high amounts of RAM for events unless theres at least 10 gauges (small win)
- Remove invariants from our testing setups (small win, across many tests)
All tests still pass.
- How is the feature or change documented? (not applicable   /   specification N/A

Speedup CI tests

---

osmomath/decimal_test.go
osmomath/log2_bench_test.go

Closes: #XXX
This is related to: https://github.com/osmosis-labs/osmosis/issues/3540
Upon adding tests around max spot price for geometric twap, overflows started to occur.
To eliminate the possibility of log function being at fault, the tests around max spot price values are added directly to the log. Benchmark is also added to ensure that large values do not inflate the time it takes to run the log. The difference was indeed negligible.

test(osmomath): log tests around max spot price

---

osmoutils/conv_helper.go
x/gamm/client/cli/tx.go
x/gamm/keeper/pool_service.go
x/gamm/pool-models/balancer/pool.go
x/gamm/pool-models/balancer/pool_asset.go
x/gamm/types/constants.go
x/incentives/keeper/msg_server.go
x/lockup/keeper/msg_server.go
x/superfluid/keeper/internal/events/emit.go

This PR is created during the Informal Systems audit, after analysis of the existing specification and code inspection
Auditing is performed on commit hash: https://github.com/osmosis-labs/osmosis/commit/42d73f1cc1c52e85561518be1014b730ef6b7a12
This PR contains minor GAMM module code improvements noticed during code inspection with the aim of finding issues.
- gamm/utils/conv.go is moved to osmoutils package and renamed to conv_helper.go - because helper functions were used not only from the GAMM module but from other modules as well
- Some unsafe arithmetic operations were noticed -> sdk.Int values were cast to Int64 during error wrapping. This will not lead to aborting the tx because the possible issues are during returning of error (in already aborted tx), also string formatting was …

Gamm code improvements

---

CHANGELOG.md
osmomath/decimal.go
osmomath/decimal_test.go

Closes: #XXX
Context: https://github.com/osmosis-labs/osmosis/pull/3676#discussion_r1044555061
We would like to have a mutative and nonmutatuve `Power` function. This requires implementing a mutative multiplication function first. This PR does so by introducing `Clone`, `MulMut` functions defined on `BigDec` and `Mul` utilizing the new functions.
- covered by existing `Mut` tests.
- added tests for `Clone`
- added test to check `MulMut` mutates and `Mut` does not

feat(osmomath): BigDec Clone() and MulMut methods

---

CHANGELOG.md
osmomath/decimal.go
osmomath/decimal_test.go
osmomath/math.go

Progress towards: https://github.com/osmosis-labs/osmosis/issues/3013
This PR introduces a `PowerInteger` function defined on `BigDec` to compute the power with an integer exponent.
The implementation is copied over from [`sdk.Dec`](https://github.com/osmosis-labs/cosmos-sdk/blob/f6e51566a5d878c561bc73fa4f0852ad6e02aa3c/types/decimal.go#L466) and uses square and multiply algorithm.
All pre-existing tests are also copied from the SDK and pass. More tests around max spot price are added to ensure that there are no-overflows occurring in geometric twap.
This function will be used by the future `Power` function that takes a decimal exponent. In that function, we split integer and non-integer part of the exponent. The integer part will be computed using this `PowerInteger` function. The …

feat(osmomath): BigDec power function with integer exponent, overflow tests at max spot price

---

app/keepers/keepers.go
x/protorev/genesis.go
x/protorev/keeper/epoch_hook.go
x/protorev/keeper/epoch_hook_test.go
x/protorev/keeper/keeper_test.go
x/protorev/keeper/protorev.go
x/protorev/keeper/protorev_test.go
x/protorev/types/keys.go
x/protorev/types/utils.go

This PR includes all of the store keys + setters/getters needed to build cyclic arbitrage routes as well as the epoch hook which helps construct the stores. 
- *Keys for keeper*
- *Setters and getters for TokenPairArbRoutes*
- *Setters and getters for Osmo Pools*
- *Setters and getters for Atom Pools*
- *Epoch hook runs after every week to update the highest liquidity pool pairings*
This PR will also include our testing environment that is configured through `keeper_test.go`. This test suite initializes user accounts for trading, creates over 30 pools, sets up token pair routes, and allows us to test all of the setters and getters for stateful information.
- *Added unit tests for OsmoPools*
- *Added unit tests for AtomPools*
- *Added …

Protorev Basic Keeper + Epoch Hook

---

CHANGELOG.md
osmomath/decimal.go
osmomath/decimal_test.go

Closes: #XXX
Context: https://github.com/osmosis-labs/osmosis/pull/3676#discussion_r1044555061
We would like to have a mutative and non-mutatuve Power function. This PR implements in and adds mutation tests.
- Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (es

feat(osmomath): mutative `PowerIntegerMut` function on `osmomath.BigDec`

---

x/epochs/client/cli/cli_test.go
x/epochs/client/cli/query.go

x/epochs: osmocli tests migrate

---

.github/workflows/build.yml
.github/workflows/contracts.yml
.github/workflows/lint.yml
.github/workflows/sim.yml
.github/workflows/test.yml
app/app.go

This PR makes:
go linter CI only run if:
- go mod/sum edited
- go file edited
- CI configs edited
- Makefile edited
md linter CI only run if
- go mod;sum edited
- markdown file edited
- Makefile edited
E2E tests (and simulation) only run if
- go mod;sum edited
- non-test go file edited
- anything in tests/** edited
- .wasm binary edited
- Makefile edited
Compile CI only run if:
- go mod;sum edited
- non-test go file edited
- .wasm binary edited
- Makefile edited
Should hopefully speedup our average case CI time more.

Add more file-awareness for tests

---

x/protorev/keeper/routes.go
x/protorev/keeper/routes_test.go

This PR implements the logic of building cyclic arbitrage routes given a swap. There are two primary methods for route generation: Highest Liquidity Pools and Hot Routes.
- *Build routes that start and end with osmo (Highest Liquidity Pools)*
- *Build routes that start and end with atom (Highest Liquidity Pools)*
- *Build routes that start and end with osmo or atom from the set of hot routes (Hot Routes)*
- *Added unit tests for atom routes*
- *Added unit tests for osmo routes*
- *Added unit tests for routes built with tokenPairArbRoutes*
- *Added unit tests for BuildRoutes (which is a wrapper to the above three)*
There are two types of trades that must be considered:
1. **The assets in the trade are neither Atom nor Osmo**
- In this …

ProtoRev: Route building

---

CHANGELOG.md
osmoutils/binary_search.go
osmoutils/binary_search_test.go
x/gamm/pool-models/balancer/pool_test.go
x/gamm/pool-models/internal/cfmm_common/lp.go
x/gamm/pool-models/stableswap/amm.go
x/gamm/pool-models/stableswap/amm_test.go

Progress towards: #3540 
Suggesting to change additive tolerance to a Decimal to improve the experience when testing math functions that require high precision.

refactor(osmoutils): use Dec for additive tolerance instead of Int

---

osmomath/decimal.go
osmomath/decimal_test.go
osmomath/export_test.go

Progress towards: #3540
As per title, this is needed to prevent import cycles in tests.
The import cycle I encountered is with `osmoutils` to import `ErrTolerance`.

refactor/test(osmomath): change package of decimal_test.go to osmomath_test

---

osmoutils/osmocli/query_cmd_wrap.go
x/epochs/client/cli/query.go

Fixes a bug in epochs CLI (and outputs a more human readable error)
- Do QueryFnName override for epochs command that needed it
- Make a human readable error when this fails
Manually tested

Fix epochs CLI

---

CHANGELOG.md
osmomath/decimal.go
osmomath/decimal_test.go
osmoutils/binary_search_test.go

Progress towards: #3540 
I missed the existence of `Power` when adding `PowerInteger`. As a result, these functions are identical.
I propose removing the old `Power` and replace all calls with `PowerInteger` since I am adding a new `Power` function that takes a decimal exponent.
**Note:**
- The removed `Power` is identical with `PowerInteger`
- The existing `PowerInteger` tests include and cover all removed test cases.

refactor(osmomath): replace Power with PowerInteger

---

x/twap/migrate_test.go

Closes: #3542
The original goal of twap record migrations was assumed to have the need to initialize the new geometric accumulator to 0.
Upon more testing, I realized that the new fields are getting initialized to zero by default during proto deserialization. As a result, the migrations aren't needed.
This PR adds a marshal/unmarshal test to prove this. 
Also, https://github.com/osmosis-labs/osmosis/issues/3728 will help confirm that this is valid

test(x/twap): geometric twap accum initialized to zero by default

---

.github/workflows/push-docker-images.yml

Closes: https://github.com/osmosis-labs/osmosis/issues/3631
In this backport https://github.com/osmosis-labs/osmosis/pull/3471 we merged conflicts on the docker ci. 
```yaml
jobs:
<<<<<<< HEAD:.github/workflows/docker.yml
docker:
runs-on: ubuntu-latest
=======
osmosisd-images:
runs-on: self-hosted
>>>>>>> a5f88e14 (feat(e2e/ci): auto-build and publish to docker hub e2e init images on release (#3249)):.github/workflows/push-docker-images.yml
```
which is likely the cause of https://github.com/osmosis-labs/osmosis/issues/3631
- Fix merge conflict
- Rename `docker.yml` --> `push-docker-images.yml`
N.A.
- How is the …

Fix merge conflicts in docker ci

---

CHANGELOG.md
osmomath/binary_search.go
osmomath/binary_search_test.go
osmomath/math.go
x/gamm/pool-models/balancer/pool_test.go
x/gamm/pool-models/balancer/util_test.go
x/gamm/pool-models/internal/cfmm_common/lp.go
x/gamm/pool-models/internal/test_helpers/test_helpers.go
x/gamm/pool-models/stableswap/amm.go
x/gamm/pool-models/stableswap/amm_test.go

Closes: #3251 , cref #3744  
Context in issues
Move binary search from osmoutils into osmomath
- How is the feature or change documented? n/a

Move binary search from osmomath to osmoutils

---

osmomath/decimal_test.go
osmomath/export_test.go
osmomath/log2_bench_test.go
osmomath/math_test.go
osmomath/rounding_direction_test.go
osmomath/sigfig_round_test.go
x/gamm/types/constants.go

Needed to split osmomath into its own go.mod
This basically involved making an exported var for `gammtypes.MaxSpotPrice`, and removing Conditional Panic cases. Only affects test files.

Remove osmomath's dependency on osmoassert & gammtypes

---

CHANGELOG.md
app/apptesting/test_suite.go
wasmbinding/queries.go
x/gamm/keeper/grpc_query.go
x/gamm/keeper/pool_service.go
x/gamm/keeper/pool_service_test.go
x/gamm/pool-models/balancer/pool.go
x/gamm/pool-models/balancer/pool_suite_test.go
x/gamm/pool-models/stableswap/amm.go
x/gamm/pool-models/stableswap/pool.go
x/gamm/pool-models/stableswap/pool_test.go
x/swaprouter/types/pool.go
x/twap/logic.go
x/twap/types/expected_interfaces.go
x/twap/types/twapmock/amminterface.go
x/txfees/keeper/feetokens.go
x/txfees/keeper/feetokens_test.go
x/txfees/types/expected_keepers.go

Closes: #XXX
This PR fixes the SpotPrice keeper function.
It fixes the underlying balancer pool bug and stableswap pool hack. Then, it switches parameter order on the keeper layer so that TWAP does not require migrations.
The parameter order is switched for the following functions:
- [`CalculateSpotPrice`](https://github.com/osmosis-labs/osmosis/blob/16eb3e55e3712cffdde9e26c5b22e056b586704a/x/gamm/keeper/pool_service.go#L24)
- [`balancer.SpotPrice`](https://github.com/osmosis-labs/osmosis/blob/16eb3e55e3712cffdde9e26c5b22e056b586704a/x/gamm/pool-models/balancer/pool.go#L625)
- [`stableswap.SpotPrice`](https://github.com/osmosis-labs/osmosis/blob/16eb3e55e3712cffdde9e26c5b22e056b586704a/x/gamm/pool-models/stableswap/pool.go#L334)
It refactors tests that utilize these functions. As an …

fix(gamm): SpotPrice keeper function

---

x/tokenfactory/client/cli/cli_test.go
x/tokenfactory/client/cli/query.go

- refactor query.go
- add test case for GetCmdDenomAuthorityMetadata
- test case for GetCmdDenomsFromCreator
- add field to QueryCliTestCase to check for wrong responses (does not return error)
- refactor RunQueryTestCase to check ExpectedNotEqual
- missed return
- add wrong test cases
Migrate to use osmocli tests in tokenfactory module. Also adds a field to `QueryCliTestCase` to check the return value of a query, to be able to check for wrong response (might be not really important to add this, will wait for review)
not documented

osmocli: migrate to osmocli tests in tokenfactory cli

---

app/apptesting/gamm.go
x/gamm/pool-models/balancer/pool_suite_test.go

Closes: #XXX
https://github.com/osmosis-labs/osmosis/pull/3764 needs `PrepareBalancerPool` helper that takes coins and pool params.
This PR introduces these helpers and slightly cleans them up.
- Introduced `PrapareCustomBalancerPool` that takes pool assets and pool params
- Introduced `PrepareCustomBalancerPoolFromCoins` that takes coins and pool params. Each coin is converted to asset with a weight of 1
- Removed `PrepareBalancerPoolWithPoolAssets` that takes pool assets only. There was only one use case. Replaced with `PrepareCustomBalancerPool instead
- Reused all existing helpers where applicable to reduce code duplication
For example, `PrepareBalancerPoolWithPoolAssets` was

refactor(app/apptesting): PrepareBalancerPool helpers (simplifying swaprouter merge PR)

---

osmoutils/module_account_test.go
osmoutils/noapptest/cdc.go
osmoutils/noapptest/ctx.go
osmoutils/store_helper_test.go
osmoutils/test_ctx.go

<!-- < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < ☺
v                               ✰  Thanks for creating a PR! ✰    
v    Before smashing the submit button please review the checkboxes.
v    If a checkbox is n/a - please still include it but + a little note why
v    If your PR doesn't close an issue, that's OK!  Just remove the Closes: #XXX line!
☺ > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > >  --
As part of getting osmoutils into its own go.mod, makes its store tests and module accounts test no longer depend on integrated osmosis testing. Instead we directly setup a custom store for store tests, and directly wire an auth keeper for module account testing.
What remains to get osmoutils into its own go.mod is:
I plan to do those two in separate …

Make osmoutils store + module account tests not import osmosis

---

x/protorev/keeper/keeper_test.go
x/protorev/keeper/rebalance.go
x/protorev/keeper/rebalance_test.go
x/protorev/keeper/routes.go
x/protorev/keeper/routes_test.go
x/protorev/keeper/statistics.go
x/protorev/keeper/statistics_test.go
x/protorev/types/expected_keepers.go
x/protorev/types/genesis.go
x/protorev/types/keys.go

This PR implements all of the logic surrounding finding the most profitable arbitrage opportunities given a set of routes, executing the most profitable arbitrage route, and storing profits in the module account. Additionally, the module tracks various statistics about how many trades have been executed, what pools had the most amount of arbitrage opportunities and more. Lastly, this PR refactors routes.go to use SwapAmountInRoutes instead of the custom route struct as it plugs into the gamm interface in a cleaner way.
Linking main issue for reference : https://github.com/osmosis-labs/osmosis/issues/3594.
- *Calculating whether a cyclic arbitrage route is profitable*
- *Determining the most profitable cyclic arbitrage route from a set of routes given a swap*
- *Executing the most …

ProtoRev: Trade Execution + Statistics

---

x/twap/logic_test.go
x/twap/strategy.go
x/twap/strategy_test.go

Closes: #XXX
The old three asset twap equal record test assumes additional validation from `computeTwap` function. Therefore, we should move the test case from being made against strategies to be against `computeTwap` function.
Additionally, we should add a test case against the arithmetic twap strategy where we end up having a time delta of zero, making it panic (Currently marked as TODO)

test(x/twap): move three asset same record test to TestComputeTwap

---

x/swaprouter/keeper_test.go
x/swaprouter/router_test.go

Closes: #XXX
Testing the new `GetPoolModule` method. Part of the merge

test(x/swaprouter): TestGetPoolModule

---

x/twap/api.go
x/twap/export_test.go
x/twap/keeper.go
x/twap/logic.go
x/twap/logic_test.go
x/twap/strategy.go
x/twap/strategy_test.go

Closes: Part of https://github.com/osmosis-labs/osmosis/issues/3514 [3-8]
1. geometric implementation is added to strategy.go
2. Refactor computeTwap to take twapStrategy instead of twapType.
3. move logic from computeArithmeticTwap to its respective strategy's computeTwap.
4. getTwap function is introduced to api.go
5. getArithmeticTwap utilizes arithmetic strategy and calls getTwap
6. getTwapToNow function is introduced to api.go
7. run these tests for both arithmetic and Geometric strategies, minimizing code duplication in tests
n/a
moved test from logic_test.go to strategy_test.go 
- How is the …

[x/TWAP] Refactor geometric & arithmetic TWAP for reusable API functions

---

tests/localosmosis/scripts/setup.sh

Closes: #3725 
While we initialize the swaprouter already with uosmo as the default denom, it is good practice to ensure this gets overridden when making a new localnet in the case this unexpectedly changes.
This PR simply removes the commented out code that changed the default pool creation fee denom from the gamm module to where it now exists (the swaprouter module)

chore: add swaprouter change to localosmosis

---

x/twap/export_test.go
x/twap/logic.go
x/twap/logic_test.go
x/twap/strategy.go
x/twap/strategy_test.go

Closes: #3540 
This PR switches to use the new `Exp2` function (#3708) in x/twap for computing geometric twap.
It also adds a test at max spot price, showing that there is no overflow.
This change added overflow test and refactored twap math function tests to be simpler.
Note that adding more hand-calculated tests is tracked in: https://github.com/osmosis-labs/osmosis/issues/3541
On top of this PR, I made a PR with query tests that currently pass: https://github.com/osmosis-labs/osmosis/pull/3802

feat(x/twap): use exp2 in twapPow; add overflow test

---

Makefile
tests/e2e/containers/containers.go

Closes: #2653
Debugging E2E via CI is pretty unusable. It emits over 13000 log lines right now.
This PR:
* Turns the debug flag off
* Sets it s.t. in event of a tx / general action failing in E2E, we output stdout & stderr as was previously done.
I claim that this will massively reduce log output, and maintain the same debuggability.
- Reduce E2E noisiness in CI

Lower noise of e2e tests

---

x/concentrated-liquidity/model/msgs.go
x/concentrated-liquidity/msg_server.go
x/concentrated-liquidity/msg_server_test.go
x/concentrated-liquidity/types/expected_keepers.go

Closes: #3723 
Adds denom check upon pool creation via msg server. 
The original design discussed in the issue was doing the validation using msg validation method, but this is found impossible, as we need to use bank keeper for the verification.
The denom check done here is namely the `GetDenomMetaData` check using Bank keeper, reviewers please confirm if this is the correct check we want to do here.

[CL]Misc: Add Denom Check upon pool creation

---

osmomath/sigfig_round_test.go
x/gamm/pool-models/balancer/pool_suite_test.go
x/twap/logic.go
x/twap/logic_test.go

Closes: #XXX
This PR handles spot price errors in the context of geometric twap. When a spot price error occurs, twap module sets sp0 and sp1 to zero.
In geometric calculation logic, we take the log of sp0. Since logarithm of zero is undefined, we should be careful not to do it.
Therefore, we handle this edge case by not updating the geometric accumulator and setting last error time to the `newTime`
Additionally, it includes test cases for sig fig rounding and spot price that I use to facilitate my understanding of when errors are returned.
Added tests

refactor(x/twap): handle spot price error case in the context of geometric twap

---

CHANGELOG.md
wasmbinding/stargate_whitelist.go
x/twap/README.md

Closes: #XXX
Added geometric twap queries to stargate whitelist

feat(x/twap): whitelist GeometricTwap and GeometricTwapToNow

---

scripts/protocgen.sh

Closes: #XXX
Upon more testing, I discovered that I made a [wrong change](https://github.com/osmosis-labs/osmosis/pull/3854#discussion_r1056877782) in https://github.com/osmosis-labs/osmosis/pull/3854 last minute. We don't need `osmoutils` extenstion in the copy to path.

fix(scripts): proto gen osmoutils path

---

app/apptesting/concentrated_liquidity.go
app/keepers/keepers.go
x/concentrated-liquidity/client/cli/query.go
x/concentrated-liquidity/client/cli/tx.go
x/concentrated-liquidity/genesis_test.go
x/concentrated-liquidity/grpc_query.go
x/concentrated-liquidity/internal/math/tick.go
x/concentrated-liquidity/internal/swapstrategy/swap_strategy_test.go
x/concentrated-liquidity/keeper_test.go
x/concentrated-liquidity/model/codec.go
x/concentrated-liquidity/model/msgs.go
x/concentrated-liquidity/pool.go
x/concentrated-liquidity/position.go
x/concentrated-liquidity/swaps_test.go
x/concentrated-liquidity/tick.go
x/concentrated-liquidity/types/codec.go
x/concentrated-liquidity/types/events.go
x/concentrated-liquidity/types/msgs.go

Closes: #XXX
This PR is a follow-up to: https://github.com/osmosis-labs/osmosis/pull/3868
It fixes all build issues in #3868 while continuing to preserve state compatibility with `main`.
The new keeper/module is not yet registered. The amino and codec are not registered either. Tests relying on these registrations are disabled until we merge state-breakage logic in a separate PR. 
The `ConcentratedLiquidityKeeper` is added to the app to avoid build issues in tests. However, it continues to be unwired.

chore: CL merge to main build fixes (no state-breaks)

---

osmoutils/osmocli/parsers.go

Closes: #XXX
Osmocli does not allow negatives. This is a workaround. This needs to get merged since we utilize this as its own gomod package, so local changes do not overwrite like before.

fix: add negative to cli

---

osmoutils/accum/accum.go
osmoutils/accum/accum_test.go

Closes: #XXX
This PR is extracted from https://github.com/osmosis-labs/osmosis/pull/3893
We should be updating the accumulator instead of overwriting its value. The accumulator is likely to always grow. As a result, this is a UX feature.
In the unlikely case when it is needed to reset the accumulator value, the user can still do so by providing negative input.
Additionally, added a `GetValue()` API on the accumulator.
Tests added.

refactor(osmoutils): UpdateAccumulator does not overwrite; tests

---

osmoutils/accum/accum.go
osmoutils/accum/accum_test.go

Closes: #XXX
When we `ClaimRewards` from the accumulator store, we are likely to utilize them for sdk operations such as "bank send". All such operations utilize `sdk.Coins` instead of `sdk.DecCoins`.
Therefore, in terms of UX, it is beneficial to return `sdk.Coins` right away.
It is also helpful for reinvesting the truncation change into the newly created position after claiming the rewards so that this change isn't lost.

refactor(osmoutils): accumulator ClaimRewards returns sdk.Coins

---

osmoutils/accum/accum.go
osmoutils/accum/accum_helpers.go
osmoutils/accum/accum_test.go
osmoutils/accum/errors.go
osmoutils/accum/export_test.go

Closes: #XXX
Index position by string name instead of the address. This is required for some use cases such as concentrated liquidity (CL).
In CL, we need to index positions by the owner, pool id, and ticks.
The flexibility to index by address is still provided since address can easily be converted to string.

refactor(osmoutils): index position by string name instead of address

---

CHANGELOG.md
app/app.go
go.mod
go.sum
go.work.sum
osmoutils/module_account.go
x/ibc-hooks/go.mod
x/ibc-hooks/go.sum

Osmoutils wouldn't compile on chains that didn't use osmosis' sdk fork because ClawbackVestingAccount is not available.
This ensures that that struct is not needed at compile time.
Doing this via a global variable might be a bit controversial, but I think it's the cleanest abstraction to avoid having to maintain several other packages and/or have implementors override this with replace/fork.
We could use this pattern in other reusable packages and it might even be usable for supporting different versions of the sdk or ibc. 
- ClawbackVestingAccount is no longer part of osmoutils and is now injected in app.go
all tests pass
- Does this pull request introduce a new feature or user-facing behavior changes? (/ no)
- Is a relevant changelog entry added to the `Unreleased` …

Making osmoutils compile on chains that don't use our SDK fork

---

go.mod
go.sum
go.work.sum
osmomath/binary_search.go

2ac5d3561928b0f60bd7f9451b9168f6e1ad5344 breaks stableswap because osmomath requires the users of the binsearch functions to use the name `input` for the function's argument. This removes that requirement
Make function used by binary search on osmomath more flexible
All tests continue to pass

Fix stableswap use of osmomath

---

x/concentrated-liquidity/genesis_test.go
x/concentrated-liquidity/internal/swapstrategy/swap_strategy_test.go
x/concentrated-liquidity/keeper_test.go
x/concentrated-liquidity/types/codec.go
x/concentrated-liquidity/types/msgs.go

Progress towards: #3556
Finalizing merge to main. This PR focuses on re-enabling CL module tests and amino registration
Tests:
Codec removals:

chore(CL): re-enable CL module tests (finalize merge #2)

---

CHANGELOG.md
wasmbinding/stargate_whitelist.go

Closes: https://github.com/osmosis-labs/osmosis/issues/3882
This PR adds swaprouter queries(namely `Numpools`, `EstimateSwapExactAmountIn`, `EstimateSwapExactAmountOut`) to stargate query whitelist.

[CL]: Add swaprouter queries to stargate whitelist

---

osmomath/binary_search.go
x/gamm/types/constants.go
x/twap/strategy.go
x/twap/strategy_test.go

Closes: #XXX
Adds geometric twap edge case tests. Defines min spot price as `sdk.SmallestDec()`
The old test case setup was incorrect as it was taking the logarithm of the accumulator instead of just the price. To mimic the real environment, this test case is now incorporated into `TestComputeGeometricStrategyTwap` table-driven test with quote assets in both denomes.
With one of the denoms, there is a panic due to precision loss. This happens because we end up taking 1 / < extremely large value >, resulting in a value smaller than the smallest Dec possible.
This test case assumes that the spot price is the smallest dec possible. By taking a logarithm of the smallest value (0, 1) and multiplying it by 100 years, we confirm that our math functions do not accidentally cause an underflow.
The …

test(x/twap): geometric twap edge case tests

---

osmomath/binary_search.go
x/gamm/types/constants.go
x/twap/export_test.go
x/twap/logic.go
x/twap/logic_test.go
x/twap/strategy.go
x/twap/strategy_test.go

Addresses: https://github.com/osmosis-labs/osmosis/issues/3541#issuecomment-1360745153
Progress toward: https://github.com/osmosis-labs/osmosis/issues/3541
This is an optimization that can reduce the frequency of precision loss due to taking multiplicative inverses. 
Currently, we might have to do 2 redundant multiplicative inverses:
1. If the arithmetic mean of log prices is negative, making the power function exponent be negative
2. if the quote asset is asset 1.
Instead, we can detect all cases when the multiplicative inverse is needed and do it only once.
These cases are listed in the comments:
**Case 1**: exponent is negative and quoteAsset is asset 0.
- This means that we need to invert the result to get the true value of the geometric mean.
**Case 2**: exponent is positive and …

refactor(x/twap): geometric twap reduce multiplicative inverses

---

x/gamm/keeper/swap.go
x/gamm/keeper/swap_test.go
x/swaprouter/router.go

Closes: #3798
This PR adds inactive pool check to the swap router module, more specifically does a check before each swap if the pool is inactive or not. If not, errors out.
This PR changed existing test for inactive pool from using gamm module -> swaprouter module.

[CL][SwapRouter]: Move Inactive pool check to Swaprouter module

---

app/apptesting/test_suite.go
go.work.sum
x/concentrated-liquidity/model/codec.go
x/concentrated-liquidity/types/msgs_test.go

- go work sum
- MsgCreateConcentratedPool (de)ser check
- test for MsgCreateConcentratedPool
- MsgWithdrawPosition check
- MsgWithdrawPosition test case
- MsgCreatePosition check
- MsgCreatePosition test case
- add check to make sure result is expected and add else branch for msgs not yet checked
Closes: #3914
adds test that makes sure serialization/deserialization of CL's messages work as expected
no

concentrated-liquidity: add test to check (de)serialization of cl's messages

---

osmoutils/accum/accum.go
osmoutils/accum/errors.go
x/concentrated-liquidity/export_test.go
x/concentrated-liquidity/fees.go
x/concentrated-liquidity/fees_test.go
x/concentrated-liquidity/tick.go
x/concentrated-liquidity/tick_test.go

Closes: #3956
Implementing the initialization for the fee growth outside tee accumulator.
This is extracted from the original fee POC: https://github.com/osmosis-labs/osmosis/pull/3893
- Implement and test `getInitialFeeGrowthOtsideForTick`
- Implement and test  `chargeFee`
- Refactor and test `getTickinfo`

feat(CL Fees): initialize fee growth outside for ticks

---

x/valset-pref/client/cli/tx.go
x/valset-pref/simulation/sim_msgs.go
x/valset-pref/valpref-module/module.go

Part of : https://github.com/osmosis-labs/osmosis/issues/2579
Adds simulator test support for RandomMsgReDelegateToValSet, RandomMsgWithdrawRewardsFromValSet and add cli tx commands. 
Cli tested all the commands. More Info: https://hackmd.io/6eb1WIyRQYiFmD1QjI-ivQ
- How is the feature or change documented? (not applicable   /   specification (`x/<module>/spec/`)  /  [Osmosis docs …

[ValSet-Pref] Add Redelegate, Withdraw cli commands and sim_msgs

---

osmoutils/accum/accum.go
osmoutils/accum/accum_test.go

Closes: #3950 
Removes the position accumulator from state when the numShares for the position is equal to zero. 
This check / action happens when the update Position, specifically `RemoveFromPosition` is happening.
- Remove position accumulator from state when numshares is zero
Added new tests for this / changed existing test cases

feat(osmoutil/accum): Remove position Accumulator from state

---

x/concentrated-liquidity/tick.go
x/concentrated-liquidity/tick_test.go

Closes: #XXX
This PR adds updating ticks for `feeGrowthOutside` in `initOrUpdateTick`
Tests has been added to check tick's fee growth outside to existing tests

(CL Fees): update tick `feeGrowthOutside` in `initOrUpdateTick`

---

cmd/osmosisd/cmd/init.go

> Adjust MaxNumInboundPeers and MaxNumOutboundPeers
- The current MaxNumInboundPeers is 320. This is excessive and unnecessary. Recommend to change to 80 in the PR. 
- The current MaxNumOutboundPeers is 40. This is not too bad, but we at Polkachu use 60 consistently. Recommend to change to 60 in this PR. 
- How is the feature or change documented? (not applicable   /   specification (not documented)

Adjust MaxNumInboundPeers and MaxNumOutboundPeers

---

go.mod
go.sum
osmoutils/accum/accum.go
osmoutils/accum/accum_test.go
x/concentrated-liquidity/export_test.go
x/concentrated-liquidity/fees.go
x/concentrated-liquidity/fees_test.go

Closes: #XXX
Currently, our CL fees positions are prefixed by the owner. However, they should be prefixed by pool id, owner, lower and upper tick.
This PR changes the logic to apply the appropriate position prefixing.
Additionally, we should not allow re-initializing a position with non-zero liquidity to avoid accidentally overriding it. However, we do want to override a zero-liquidity position because a user might want to provide liquidity at the ticks where their old position used to be.
- changed position prefixing
- added `HasPosition` accumulator method
- tested `HasPosition`
- refactored `initializeFeeAccumulatorPosition`
- refactor `initializeFeeAccumulatorPosition` test to account for the new prefix and behavior
- Does this pull request introduce a new …

refactor(CL Fees): prefix positions by pool id, owner and ticks

---

x/valset-pref/valpref-module/module.go

Closes: #XXX
One of the simulator messages for valset pref is failing. This is temporarily disabling the simulator messages for valset pref until @stackman27 has time to look further into it.
* Disables valset pref sim messages in module.go

chore: disable valset pref sim

---

x/concentrated-liquidity/internal/math/tick.go
x/concentrated-liquidity/internal/math/tick_test.go
x/concentrated-liquidity/lp.go
x/concentrated-liquidity/swaps.go
x/concentrated-liquidity/swaps_test.go

Closes: #3988 
See https://github.com/osmosis-labs/osmosis/issues/3988 for details
The only thing to note here is I chose to keep the test cases in expectedPrice, then within the test itself we transform the expected price into a sqrtPrice. IMO this makes more sense since its harder to conceptualize what is correct when having to look at sqrtPrices

chore: switch to sqrt price for tick functions

---

go.mod
go.sum
go.work.sum
osmoutils/accum/accum.go
osmoutils/accum/accum_test.go
x/concentrated-liquidity/export_test.go
x/concentrated-liquidity/fees.go
x/concentrated-liquidity/fees_test.go
x/concentrated-liquidity/keeper_test.go

Closes: #XXX
This PR implements the `collectFees` method and tests it.
Additionally, it adds and tests`SetPositionCustomAcc` `accum` package method that is necessary for collecting fees.
Fee collection works by retrieving fee growth outside of the range given by the position we are trying to collect the fees from.
Next, we update that position's accumulator for the fee growth outside.
Once that's done, we claim rewards by substracting the updated position's fee growth outside of the fee growth global and multiplying by the number of shares. This is abstracted by the `accum` package's `ClaimRewards` function.
Finally, we send the fees from the pool to the position owner.
- implement and test `SetPositionCustomAcc`
- implement and test `collectFees`
- Does this pull …

feat(CL Fees): collect fees

---

go.mod
go.sum

This change ensures that we don't use a software repository that has been 
subject to a hostile takeover and thus cannot be trusted.
It is a sad thing.
* use informal tendermint fork
- Does this pull request introduce a new feature or user-facing behavior 
changes? no
- Is a relevant changelog entry added to the `Unreleased` section in 
`CHANGELOG.md`? no
- How is the feature or change documented? 
https://twitter.com/fekunze/status/1613896692037980167

fix: use informal tendermint

---

tests/e2e/README.md
tests/e2e/initialization/README.md

- upd e2e README
- upd e2e/initialization README
Have been reading `e2e` docs. Noticed some stuff was outdated. This PR focuses on fixing minor outdated things in READMEs of e2e. Please, let me know if I made any mistakes in these changes

docs(e2e): fix outdated info

---

x/concentrated-liquidity/architecture.md
x/concentrated-liquidity/export_test.go
x/concentrated-liquidity/lp.go
x/concentrated-liquidity/lp_test.go
x/concentrated-liquidity/position.go
x/concentrated-liquidity/position_test.go

Part of: #3951 
Currently, when a user makes a concentrated liquidity position and removes it in it's entirety, the position is still persisted in state. This PR removes any position from state when their is no more liquidity remaining.
- Adds a check in `withdrawPosition` to `ClaimRewards` if the number of shares for a given position becomes zero
- Adds a check in `withdrawPosition` to clear the position from CL state if the number of shares becomes zero
- Updates `TestWithdrawPosition` to validate both of the above

feat[CL]: delete position from state when completely removed

---

tests/e2e/README.md
tests/e2e/initialization/config.go

This PR adds a function to register denom metadata in genesis state of bank module in e2e tests.
https://github.com/osmosis-labs/osmosis/pull/4038 while working at this PR I have faced a problem that you cannot create a concentrated pool with any denom you want (what is weird, `gamm` does not have `DenomMetadata` check). Because of that, I was unable to add `CreateConcentratedPool` function to `e2e`, because tests would not pass (reason: using `UpgradeConfigurer` which does not register denoms other than `uosmo`). This PR is backport and introduces:
- A general function to add `DenomMetadata` to genesis state of bank module
- More denoms added to genesis state of bank module

e2e: setDenomMetadata

---

x/concentrated-liquidity/lp_test.go

Part of adding different invariant testings to the cl module.
This test adds inverse relationship testing between `CreatePosition` and `WithdrawPosition`
We specifically test the following four invariants upon the two methods
1.  amount for denom0 and denom1 upon creating and withdraw position should be same
2. user balance and pool balance after creating / withdrawing position should be same
3. Position should be deleted
4. pool state should come back to original state
Add inverse relationship testing between `CreatePosition` and `WithdrawPosition`
Changes existing test code structure to avoid code duplication upon test cases and adds new test cases …

(CL Test): Add inverse relationship testing between `CreatePosition` and `WithdrawPosition`

---

x/valset-pref/README.md
x/valset-pref/msg_server.go
x/valset-pref/msg_server_test.go
x/valset-pref/types/msgs.go
x/valset-pref/validator_set.go

Closes: [#3761](https://github.com/osmosis-labs/osmosis/issues/3761) 
Part of : https://github.com/osmosis-labs/osmosis/issues/2579
In https://github.com/osmosis-labs/osmosis/pull/3599 the redelegate to (new valset pref list) message redelegates from your current valset.
Instead, we should change this to redelegate from all of your current staked positions. So that way the UX can be "Set new valset preference", "Redelegate everything to this new preference list", and it gracefully handles that you used to stake without a preference list.
n/a
testing redelegation with existing non-valset delegation
- How …

[ValSet-Pref] Make Redelegate to valset read all your current stake positions

---

x/lockup/keeper/lock.go
x/lockup/keeper/lock_test.go
x/superfluid/keeper/stake.go
x/superfluid/keeper/unpool.go
x/superfluid/types/expected_keepers.go

Return lock id from `BeginForceUnlock`. This PR is 1st part of implementing partial withdraw from super fluid
https://github.com/osmosis-labs/osmosis/issues/3830
Algorithm for SF partial withdraw is the following
```
1. SuperfluidUndelegate
2. Unbond lock for partial amount of the lock and return the new underlying lock that was split
3. Re-delegate remainder
4. Create synthetic unlocking lock for the new lock from step 2
```
This PR makes step 2 possible.
- *Return lock id from `BeginForceUnlock`*

Return lock id from BeginForceUnlock

---

app/keepers/modules.go
app/modules.go
x/concentrated-liquidity/clmodule/module.go
x/concentrated-liquidity/genesis_test.go
x/concentrated-liquidity/simulation/sim_msgs.go

Closes: #XXX
Abstracts the module package from keeper. Preparation for simulator testing
n/a
n/a 

[CL] chore: abstract module package from keeper

---

app/upgrades/v14/constants.go
app/upgrades/v14/upgrades.go
app/upgrades/v15/constants.go
app/upgrades/v15/export_test.go
app/upgrades/v15/upgrade_test.go
app/upgrades/v15/upgrades.go
tests/e2e/containers/config.go

in this pr I am trying to understand why e2e does not pass on https://github.com/osmosis-labs/osmosis/pull/4052
First of all, upgrade-handler's branch had wrong tags specified, but even after a fix, I got an error: 
```
recovered: UnmarshalJSON cannot decode empty bytes\nstack:\ngoroutine 277
```
when e2e test tried to execute:
```
"[osmosisd tx gamm create-pool --pool-file=./osmosis/pool1A.json --from=val --chain-id=osmo-test-a -b=block --yes --keyring-backend=test --log_format=json]", success condition is "code: 0"
```

upgrade-handler code gen: investigating why e2e does not pass

---

x/concentrated-liquidity/swaps_test.go

Closes: #XXX
A bug was introduced in https://github.com/osmosis-labs/osmosis/commit/a352af1be78a4ba5665f5b43b642d04fcd7cb944, where test cases were not properly running for `TestCalcAndSwapOutAmtGivenIn`. This was caused due to the combination of refactoring + merge conflicts. Thanks @p0mvn  for catching this
This PR re-enables the swap test cases properly

(CL Bug): Re-run swap test cases

---

Makefile

Closes: #2315
Clear stale Docker resources after `make test-e2e`

e2e: clear Docker resources after make test-e2e

---

scripts/cl/README.md
scripts/cl/common.py
scripts/cl/main.py
scripts/cl/math.py
scripts/cl/one_for_zero.py
scripts/cl/zero_for_one.py
x/concentrated-liquidity/architecture.md
x/concentrated-liquidity/fees.go
x/concentrated-liquidity/lp.go
x/concentrated-liquidity/swaps.go
x/concentrated-liquidity/swaps_test.go

Closes: #XXX
This PR introduces the implementation for swap fees when swapping for amount out given token in.
The test vectors are estimated using the Python `sympy` scripts. The documentation for running the scripts is added.
There are some internal methods that are untested:
- https://github.com/osmosis-labs/osmosis/issues/4087
- https://github.com/osmosis-labs/osmosis/issues/4086
It is best to test them after swap fees in the other direction are complete (ref: https://github.com/osmosis-labs/osmosis/issues/4088). The reason is that we might refactor and remove these methods so it doesn't make sense to spend time adding detailed tests right now. The test coverage via script estimates is sufficient at this stage.
Lastly, there are some prints left in the codebase for development …

feat/test(CL Swaps): Swap fees for amount out given in

---

x/concentrated-liquidity/position.go
x/concentrated-liquidity/position_test.go
x/concentrated-liquidity/types/keys.go

Closes: [#4115](https://github.com/osmosis-labs/osmosis/issues/4115)
Currently in CL pools we Getpositions by poolid, userid, lowerTick, upperTick. We also would like to retrieve all current positions across many pools.
- Added new keeper method that retrieves users position
added tests 

[CL: Positions] Add GetPositionsByUserAddress for CL user positions

---

osmoutils/osmocli/query_cmd_wrap.go
x/gamm/client/cli/query.go
x/poolmanager/client/cli/query.go

Closes: #4084
- Add override QueryFnName for `EstimateSwapExactAmountIn`.`
- We need this override because when adding this query cmd,  function`ParseExpectedQueryFnName`  return SwapExactAmountIn instead of  EstimateSwapExactAmountIn. 
- Also, we have the same issue with  `EstimateSwapExactAmountOut query cmd.
- Does this pull request introduce a new feature or user-facing behavior changes? (yes / no) no
- Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (yes / no) no
- How is the feature or change documented? (not applicable   /   specification (`x/<module>/spec/`)  /  [Osmosis docs repo](https://github.com/osmosis-labs/docs)   /   not documented) no

override QueryFnName

---

.github/workflows/test.yml
tests/e2e/README.md

Closes: #4045 
> Write node Docker container logs to a file, persist as artifacts in CI
- *Write the docker container logs to a temporary file on the host. Then, persists these log files as artifacts in CI.*
- *Use `make test-e2e-debug` to skip cleanup container*
- *I have tested in fork version [here](https://github.com/anhductn2001/osmosis/actions/runs/4022809583/jobs/6912940242)

e2e: Write node Docker container logs to a file

---

Makefile

Closes: #2853 
> Deprecate docker-build-debug-alpine in Makefile
> Always use the alpine image in debug
Following @p0mvn 's suggestion:
- Remove docker-build-debug in Makefile
- Rename docker-build-debug-alpine Makefile step to docker-build-debug

Replace `docker-build-debug-alpine` to `docker-build-debug` in Makefile

---

go.mod
go.sum
go.work.sum
x/ibc-hooks/types/keys.go
x/ibc-hooks/wasm_hook.go

Closes: #4157 
~Allow users to customize whether contract callbacks can fail IBC timeouts~
Timeouts always return a success, but emit the error if there is any
- ~Added configurable timeout failures for contracts~
- Timeputs always return a success, but emit any errors in the contract
All tests should pass

Timeouts always return a success

---

x/gamm/keeper/migrate.go
x/gamm/keeper/migrate_test.go

Closes: #XXX
This is a small patch to prevent migration links from being created between two pools that don't contain the same denoms. It also checks if the balancer pool in question has more than two assets. If it does, it throws an error.
Some tests had to be changed around, since the default balancer pool actually creates a four asset pool! 
- Adds check for balancer pools with more than two assets
- Adds check for balancer pool assets to match cl pool assets
- Adds respective tests to ensure this logic is sound
- How is the feature or change documented? (not applicable   /   specification …

CL: check denoms match when creating migrate link

---

x/poolmanager/module/module.go

Closes: #XXX
@iboss-ptk reported having issue with executing pool manager swaps from smart contracts.
Upon more investigation, it was found that we never registered a message server.
After reproducing Boss's issue and adding this line, the problem was gone and swaps msgs continued to execute as expected from cosmwasm.
Tested manually.

fix(poolmanager): register message server

---

tests/e2e/configurer/chain/chain.go
tests/e2e/configurer/chain/commands.go
tests/e2e/configurer/chain/queries.go
tests/e2e/containers/config.go
tests/e2e/e2e_test.go
x/concentrated-liquidity/grpc_query.go
x/concentrated-liquidity/msg_server.go

- CreatePosition
- rename to CreateConcentratedPosition
Closes: #4055
This PR adds a function - `CreateConcentratedPosition` - that creates a concentrated position
`CreateConcentratedPosition` added to `commands.go`
Testing blocked before #4038 is merged
no

[CL][e2e]: CreateConcentratedPosition

---

x/superfluid/client/cli/tx.go

Add CLI command for `SuperfluidUndelegateAndUnbondLock`
- *add CLI  command for `SuperfluidUndelegateAndUnbondLock`*

Add SuperfluidUndelegateAndUnbondLock to CLI

---

.github/workflows/build.yml
.github/workflows/check-generated.yml
.github/workflows/lint.yml
.github/workflows/sim.yml
.github/workflows/test-e2e-makefile.yml
.github/workflows/test.yml

Closes: #XXX
In https://github.com/osmosis-labs/osmosis/pull/3947, we introduced a bump of our go version from v1.18 to v1.19. 
This PR changes the existing CI tests so that we also bump CI go versions from 1.18 to 1.19
Bump go versions in CI
Existing CI passes

Bump CI go versions to 1.19

---

x/concentrated-liquidity/swaps.go
x/concentrated-liquidity/swaps_test.go
x/concentrated-liquidity/types/constants.go

Closes: #XXX
`UpperPriceLimit` and `LowerPriceLimit` are incorrect. These values were added while prototyping dynamic tick spacing.
The correct price limits of `MaxSpotPrice ` and `MinSpotPrice` were also added. However, some references to the old limits were left out, causing pre-mature exit of the swap in fee tests because of hitting the wrong limits.
This PR removes the old limits completely.

fix(CL Swaps): remove incorrect price limit constants

---

.github/workflows/test.yml

Closes: #XXX
The e2e makefile step was switched to debug, leading to increased noise in CI logs.
Switching back to the correct makefile step with excessive logs disabled

chore: re-lower noise in e2e tests

---

.github/mergify.yml

Closes: #XXX
Mergify backport labels update for the next release.
Remove concentrated liquidity configuration since we are not using that branch anymore

chore(mergify): add v15.x backport label; remove cl backport label

---

x/twap/types/genesis.go
x/twap/types/genesis_test.go

Closes: #XXX
This broke state-exported testnet upgrade.
Geometric twap is allowed to be negative. This PR relaxes the validation and adds tests.

fix(x/twap): geometric twap genesis validation

---

CHANGELOG.md
app/upgrades/v15/export_test.go
app/upgrades/v15/upgrade_test.go
app/upgrades/v15/upgrades.go

[Closes: #4224](https://github.com/osmosis-labs/osmosis/issues/4224)
Add denom metadata for uosmo, uion
- Add denom metadata for uosmo, uion
tested in upgrade handler 

Add uosmo, uion denom metadata

---

osmoutils/accum/accum.go
osmoutils/accum/accum_helpers.go
osmoutils/accum/export_test.go

Closes: #XXX
This PR makes the `getPosition` function in the accum package public. This is so that position records need to be accessed to be properly tested in other modules (e.g. ensuring that new CL positions take on the correct initial accum value).
- Made `getPosition` public

[osmoutils][accum] Make `getPosition` in accumulator package public

---

x/concentrated-liquidity/internal/math/tick.go
x/concentrated-liquidity/internal/math/tick_test.go
x/concentrated-liquidity/types/constants.go

Closes: #3986 
Right now, we utilize a GetMinAndMaxTicksFromExponentAtPriceOne function to determine the min and max ticks given an exponentAtPriceOne:
https://github.com/osmosis-labs/osmosis/blob/a3f2abbd9235b3b1f8b74c3409fa262c99c9c0a1/x/concentrated-liquidity/internal/math/tick.go#L180-L185
This PR pre-computes the min and max ticks for the allowed exponentAtPriceOne [-1,-12]. The get function fetches these precomputed values, and if the provided exponentAtPriceOne is not one of the authorized values, it calculates it on the fly like before.
- Adds `ComputeMinAndMaxTicksFromExponentAtPriceOneInternal` which on the fly computes min and max ticks
- Modifies `GetMinAndMaxTicksFromExponentAtPriceOneInternal` to fetch pre-computed min and max ticks for authorized exponentsAtPriceOne.
- For …

chore[CL]: pre-compute min and max ticks

---

CHANGELOG.md
x/incentives/keeper/gauge.go
x/incentives/keeper/msg_server_test.go
x/incentives/simulation/operations.go
x/incentives/types/gauge.go

@JeremyParish69 pointed out that there is currently a bug, where it is possible to add more rewards to an already finished gauge.
This PR fixes that as a bug vector.
Furthermore it also fixes a bug in `IsFinishedGauge` and `IsActiveGauge`, which is only used in `InitGenesis` logic
* Prevent `AddToGauge` from succeeding on a Finished gauge, from which funds can never get distributed.
* Fix an InitGenesis bug around ActiveGauge vs FinishedGauge classification
This change adds a unit test to ensure it works.

Prevent adding to a finished gauge

---

.github/workflows/push-dev-docker-images.yml
.github/workflows/push-docker-images.yml

Closes: #XXX
In #4317, it was found that we push incorrect e2e init image to Docker hub. Instead of pushing the desired image, we end up pushing regular `osmosis` image.
This PR fixes this in `.github/workflows/push-dev-docker-images.yml` that uses a separate step "Build and Push E2E Init Docker Images" that uses the right Dockerfile, pushing to the right Docker Hub repository.
The change in `.github/workflows/push-docker-images.yml` is passthrough. It simply converts a Github Actions job to a step since all the setup boilerplate is the same between the jobs

fix(ci): incorrect e2e images pushed to Docker hub

---

x/concentrated-liquidity/swaps_test.go

Closes: #3992
This PR adds tests for the `writeCtx` being returned in the calc methods.
The `writeCtx` does not alter any pool state as we handle pool state changes in the `applySwap` method. Instead, it changes the fee accumulator state upon being called. The test case being added tests if calling `writeCtx` succesfully alters fee accum state whilst leaving the pool state as is. 
Add test case for `writeCtx` being returned via calc methods.
This PR adds tests
- How is the feature or change documented? (not applicable   /   specification (`x/<module>/spec/`)  /  [Osmosis docs …

(CL test): `writeCtx` tests for calc methods

---

x/concentrated-liquidity/internal/math/math.go

[Closes: #3887](https://github.com/osmosis-labs/osmosis/issues/3887)
Uni v3 claims these the first of these two formulas is more accurate and the later is used for overflows. We should investigate if this is needed for our implementation.
`sqrtPriceNext = (liquidity * sqrtPriceCurrent) / ((liquidity) + (amountRemaining * sqrtPriceCurrent))`
`sqrtPriceNext = ((liquidity)) / (((liquidity) / (sqrtPriceCurrent)) + (amountRemaining))`
We are only gonna use the top equation
n/a
all tests run as expected
- How is the feature or change documented? (not applicable   /   specification (`x/<module>/spec/`)  / …

[Cl:Math] Remove less precise formula

---

tests/e2e/README.md
tests/e2e/configurer/chain/chain.go
tests/e2e/configurer/config/constants.go
tests/e2e/configurer/upgrade.go
tests/e2e/containers/config.go
tests/e2e/containers/containers.go
tests/e2e/e2e_test.go
tests/e2e/scripts/hermes_bootstrap.sh

Closes: #XXX
This relates to #4244
- updating chain init image needed for upgrade testing
- fixing e2e chain init image upload in ci to Dockerhub: https://github.com/osmosis-labs/osmosis/pull/4319
- updating pre-upgrade pool id used in various tests 
- setting the config for the hermes relayer to account for the new fee logic
- fixing `SendIBC` to exclude fee token from the balance check
- adding docs

fix(e2e): fix e2e test for consensus min gas fee #4244

---

app/keepers/keepers.go
x/ibc-rate-limit/ics4_wrapper.go
x/ibc-rate-limit/rate_limit.go

Closes: #XXX
Discovered with @czarcas7ic . We might be overriding params for rate limiting module

param space initialization for rate limiting

---

x/concentrated-liquidity/architecture.md

Closes: #XXX
This PR is the first step towards refactoring `architecture.md` towards becoming a module spec.
Originally, `architecture.md` served the purpose of a general design document, including the gamm refactor and the pool manager module. However, now, the pool manager module has its own spec so it makes sense to start refactoring `architecture.md` to be only concerned with the `x/concentrated-liquidity` module details.
Additionally, the spec is outdated and is missing a lot of information. This PR focused on removing stale TODOs and sections, updating the messages and the section about the relationship to the pool manager module. …

docs(CL): begin converting `architecture.md` into module spec

---

CHANGELOG.md
tests/e2e/e2e_test.go
x/twap/api.go
x/twap/keeper_test.go
x/twap/logic.go
x/twap/logic_test.go
x/twap/strategy.go
x/twap/strategy_test.go
x/twap/types/utils.go
x/twap/types/utils_test.go

Closes: #4342
This PR fixes twap jitter that is caused by nanoseconds being accounted for in the time delta calculations.
In twap, we assume the time delta in milliseconds. However, the block time is given in nanoseconds. As a result, there were some cases such as:
```go
timeDelta := endRecord.Time.Sub(startRecord.Time)
```
where if `startRecord.Time` contained just a few nanoseconds, it would cause the timeDelta to fall by 1 ms below the expected value, causing a larger denominator in arithmetic mean computations. This would lead the final twap being off in the 10^-4-10^-2 digit.
To fix this, a function `types.CanonicalTimeMs` is introduced that converts the time stored in state into unix milliseconds with monotonic clock stripped away. This is consistent with how [CometBFT handles …

fix(x/twap): incorrect time delta due to nanoseconds in time

---

CHANGELOG.md
app/app.go

https://github.com/osmosis-labs/osmosis/pull/4174 changed the maximum bytecode size to 2MB. I didn't realize at the time that the max size for wasm upload via proposals was already set to 3MB, so that change actually "decreesed" the maximum allowed bytecode size for mainnet (since most contracts are uploaded via proposals) and only increased it for the testnet and allowed uploaders.
This change sets the wasm bytecode size to 3MB for both proposals and allowed wallets. 
All stored contract codes have a maximum of 3MB now
all tests pass
- Does this pull request introduce a new feature or user-facing behavior changes? (yes /)
- Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (yes /)

Set proper wasm bytecode size

---

tests/e2e/containers/config.go
tests/e2e/e2e_test.go

Closes: #XXX
Updating previous (V14) e2e chain init Docker image to apply genesis changes from #4393 needed for #4384

test(e2e): upgrade e2e init image for Stride migration

---

tests/e2e/e2e_test.go

Closes: #XXX
Fixing typo when skipping test

fix(e2e): typo when skipping TestStridePoolMigration locally

---

Makefile

Building has sporadically been failing with:
```
❯ make build
--> Ensure dependencies have not been modified
github.com/osmosis-labs/osmosis/osmoutils : missing ziphash: open hash: no such file or directory
github.com/osmosis-labs/osmosis/x/ibc-hooks : missing ziphash: open hash: no such file or directory
github.com/osmosis-labs/osmosis/v15 : missing ziphash: open hash: no such file or directory
make: *** [go.sum] Error 1
```
This is because `go mod verify` is run without GOWORK=off and thus picks up the information from the local fs
This fixes that.
Added GOWORK=off to the verify command
All tests pass
`make build` works as expected
- Is a relevant changelog entry added to the `Unreleased` …

using GOWORK=off on go mod verify

---

proto/osmosis/tokenfactory/v1beta1/tx.proto
x/tokenfactory/keeper/admins_test.go
x/tokenfactory/keeper/bankactions.go
x/tokenfactory/keeper/msg_server.go
x/tokenfactory/types/codec.go
x/tokenfactory/types/msgs.go
x/tokenfactory/types/tx.pb.go

Closes: #XXX
This PR adds the functionality of Force Transfer, in which allows the admin of the token factory denom to transfer the token factory denom from one account to the other.
Another change included in this PR is adding `mintTo` and `burnFrom` address, which adds functionality to designate a minting address or a burning address from the existing Mint and Burn messages in the token factory module.
- Add `ForceTransfer`, `BurnFrom` and `MintTo` fields in Burn and Mint messages
Adds tests to existing tests, verified CI and tests are not failing.
- How is the feature or change documented? (not …

[TokenFactory] Add `ForceTranfer`, `BurnFrom` and `MintTo`

---

app/modules.go

Closes: #XXX
Rate limited params init genesis is failing to run because the module is not correctly wired. As a result, the state export isn't functioning properly. This PR adds the wiring.
Discovered with @czarcas7ic

fix: init genesis rate-limited-params not running

---

x/gamm/README.md

There was a small markdown mistake that made the markdown render kinda funny. Lmk if it's necessary for me to go through song and dance of the full contribution process described in `CONTRIBUTING.md`.
Closes: #-
Fix small markdown mistake.
- Fix small markdown mistake.
Rendered it, looks much better now. Should not impact prod unless you have references to your docs.
- Tiny markdown fix!

fix small markdown mistake

---

x/concentrated-liquidity/export_test.go
x/concentrated-liquidity/fees_test.go
x/concentrated-liquidity/swaps.go
x/concentrated-liquidity/swaps_test.go

Closes: #4425
This PR refactors the wiring between `SwapOutAmtGivenIn` and `SwapExactAmountIn` so that all mutations happen within `SwapOutAmtGivenIn`. Additionally, `SwapOutAmtGivenIn` is changed from a public to a private method. 
The reason for this is to make `SwapExactAmountIn` the only entrypoint, since we have previously been calling `SwapOutAmtGivenIn` directly.
Once this is approved, the same will be done for the InGivenOut pair.
See the following issue for comments on the use of errTolerance for the inverse test.
https://github.com/osmosis-labs/osmosis/issues/4475
* Moves the bank sends from `SwapExactAmountIn` to `SwapOutAmtGivenIn`
* Makes `SwapOutAmtGivenIn` private …

CL: make swapOutAmtGivenIn mutate user/pool balances

---

x/protorev/types/codec.go

Closes: #XXX
Adds support for legacy amino codec for the proto-rev module. 
- Add legacy amino codec registration for proto-rev module.
untested 

Add legacy amino codec for proto-rev module

---

x/protorev/keeper/posthandler.go

Closes: #XXX
- Adds panic catching in the ProtoRevTrade function so that nothing ProtoRev does has the ability to stop the regular tx
- ProtoRevTrade is the only real function that has the ability to bork a user tx by running out of gas (or other panics that may not be forseen now but may arise later)
This change is already covered by existing tests, all tests still pass

Catch panics in ProtoRevTrade

---

x/concentrated-liquidity/pool.go
x/concentrated-liquidity/pool_test.go
x/concentrated-liquidity/types/errors.go

Part of: https://github.com/osmosis-labs/osmosis/pull/4299/files
Adds `GetPoolDenoms` and `CalculateSpotPrice` to the concentrated liquidity keeper. 
This is a necessary step in order to wire CL <> Pool Manager Module <> Twap module.
- Add `GetPoolDenoms` and `CalculateSpotPrice` to CL Keeper
Adds new tests 

CL: Add `CalculateSpotPrice` and `GetPoolDenoms` to CL Keeper

---

x/concentrated-liquidity/internal/math/math.go
x/concentrated-liquidity/internal/math/math_test.go
x/concentrated-liquidity/internal/swapstrategy/one_for_zero.go
x/concentrated-liquidity/internal/swapstrategy/zero_for_one.go

Progress towards: https://github.com/osmosis-labs/osmosis/issues/4427
One of the problems with swap in given out was that we use the same method for computing next sqrt price as in out given in.
When we swap for in given out, we are moving in the opposite direction on the curve from out given in. As a result, we must be performing a subtraction as opposed to addition in the next sqrt price functions.
This PR splits the math helper for getting the next sqrt price in a variant for in given out and out given in. It adds tests for the desired rounding direction at precision end and adds extensive documentation.
The work on this is to be continue in subsequent PRs towards https://github.com/osmosis-labs/osmosis/issues/4427
- split `GetNextSqrtPrice` into variants for in given out and out given …

feat/refactor: implement and test get next sqrt price helpers for out given in and in given out

---

app/upgrades/v15/upgrade_test.go
wasmbinding/stargate_whitelist.go

Closes: #XXX
Adds denomTrace query from ibc-go to stargate whitelist. This is needed for XCS registry contract to be released in the near future.
- Adds DenomTrace query to whitelist

chore: stargate whitelist denom trace query

---

tests/localosmosis/README.md
tests/localosmosis/scripts/submit_upgrade_proposal.sh

This pull request adds a `submit_upgrade_proposal.sh` script to simplify the process of testing software upgrades in localosmosis. 
Assuming you have a localosmosis instance running, all you have to do is execute:
```bash
./submit_upgrade_proposal.sh <VERSION>
```
The new script automatically creates an upgrade proposal for the specified version and votes "yes" on the proposal. 
The `README.md` has been updated with instructions on how to use the script.
- Added `submit_upgrade_proposal.sh` script to automate the submission of an upgrade proposal and voting "yes" on the proposal.
- Updated the documentation to include instructions on how to use the new script.
- Start localOsmosis instance
- Execute `submit_upgrade_proposal.sh` script 
- Does this pull request introduce a new feature or …

Add upgrade proposal script to localOsmosis

---

tests/e2e/initialization/config.go

This reverts commit b8e84eacae56779b2788889b8b5003658de8c999.
Closes: #XXX
This reverts #4217 since CI running on merge to `main` broke: https://github.com/osmosis-labs/osmosis/actions/runs/4338982856/jobs/7576658435
Discussed offline and going to resubmit with the fix to CI

Revert "[tests/e2e]: simplify the logic for adding..." (#4217)

---

tests/e2e/scripts/hermes_bootstrap.sh
x/txfees/keeper/feedecorator.go
x/txfees/keeper/feedecorator_test.go

A problem cited by people on the testnet, was that the consensus min fee violated their expectations around simulate txs.
Namely that they should be able to simulate execution with 0 fees, in order to determine the required amount of fees.
- Skip consensus min fee check during tx simulation
Added a simulate test vector.
Raising an SDK issue for simulation tx guarantees

Skip consensus min fee checks during simulate

---

app/modules.go

Closes: #XXX
Wiring for packet forward middleware was not added in modules.go.
- Adds wiring for packet forward middleware in modules.go

fix: add packet forward module wiring

---

CHANGELOG.md
Dockerfile
Makefile

References: cosmos/gaia#2017
Dockerfile receives a minor tweak for proper output.
BuildTags value is expected as a plain `netgo,ledger,muslc` string, however the current approach wraps quotes inside of quotes, and the resulting string is `'netgo,ledger,muslc'` which gets escaped a few more times (unnecessarily).
Additionally, Makefile receives a minor tweak for everyone who builds directly.
With Make 4.3+, the empty whitespace does not seem to work as originally intended. This causes build tags to be `netgo ledger,` on Ubuntu 22.04 and other systems that include the newer Make version. The build tags were intended as `netgo,ledger` which can be observed on Make 4.2 (shipped with Ubuntu 20.04).
This change swaps out the `+=` use in favor of an explicit `:=`. …

Consistently generate build tags metadata

---

tests/cl-go-client/main.go

Current range for the upper tick used to create positions is received via the following way
`upperTick = maxTick - rand.Int63n(int64(math.Abs(float64(maxTick-lowerTick)))+1)`
However, this causes a bug in the process of producing random swaps, as the range for the upper tick specified can go below or have the same value as the lower tick.
Suppose a situation where maxTick is at 10, and minTick is 2.
lower tick(`lowerTick = rand.Int63n(maxTick-minTick+1) + minTick`) gives us a random value between 0 ~ 10.
Meanwhile, using the previous equation for the upper tick, we would get a random value betweem 1 ~ 10. 
In the case of where min tick is 10, for the upper tick, we would be able to get a value of 10 for the upper tick.
Removing the  +1 solves this provlem
Change upper tick range for go …

(CL Positions Client): Fix: Fix range for upper tick

---

app/test_helpers.go

Closes: #4121 
Refer from #4121 , all tests are using the same directory. 
After referring to approaches given in the issue, I think it's best to use random directories instead of adding arguments to the function
*(or)*
*(or)*
*(example:)*
- *Added integration tests for …

Fix Level DB set up, use random directory

---

app/params/config.go
x/concentrated-liquidity/store.go
x/concentrated-liquidity/types/keys.go

Closes: #4608
Address key was serialized to store with a string format. As a result, it was causing issues when getting deserialized.
This PR changes the format to %x which corresponds to lowercase bytes.
```go
go test -timeout 10s -run TestKeeperTestSuite/TestGetAllUserPositions github.com/osmosis-labs/osmosis/v15/x/concentrated-liquidity -count=100
ok      github.com/osmosis-labs/osmosis/v15/x/concentrated-liquidity    5.193s
```

fix(CL): address key format bug causing test flakiness

---

app/keepers/keepers.go
x/gamm/keeper/pool_service_test.go
x/twap/export_test.go
x/twap/keeper.go
x/twap/listeners_test.go
x/twap/logic.go
x/twap/logic_test.go
x/twap/types/expected_interfaces.go
x/twap/types/twapmock/amminterface.go

Adds CL wiring to the CL module.
This includes changing `AmmInterface` to `PoolManagerInterface`, where now the twap module receives the API needed from the pool manager for a generalized form of getting pool denoms and spot price,  instead of getting it directly from the gamm module.
- Add TWAP wiring to CL 
Necessary tests are included

Add TWAP wiring to CL

---

x/concentrated-liquidity/internal/math/math.go
x/concentrated-liquidity/internal/swapstrategy/export_test.go
x/concentrated-liquidity/internal/swapstrategy/fees.go
x/concentrated-liquidity/internal/swapstrategy/fees_test.go
x/concentrated-liquidity/internal/swapstrategy/one_for_zero.go
x/concentrated-liquidity/internal/swapstrategy/one_for_zero_test.go
x/concentrated-liquidity/internal/swapstrategy/swap_strategy.go
x/concentrated-liquidity/internal/swapstrategy/swap_strategy_test.go
x/concentrated-liquidity/internal/swapstrategy/zero_for_one.go
x/concentrated-liquidity/internal/swapstrategy/zero_for_one_test.go
x/concentrated-liquidity/swaps.go

Closes: #4427
This is progress towards: https://github.com/osmosis-labs/osmosis/issues/4424
Currently, our swap logic is needlessly complex because we have a single method for computing swaps out given in and in given out. In fact, merging the implementations was incorrect because the rounding behavior and swap direction are the opposite for in given out from out given in. While working on this refactor, a bug with given out was found #4423 that still needs to be fixed.
There are various edge cases between the two methods. As a result, it makes sense to split the internal calculations implementation into separate methods - `ComputeSwapStepOutGivenIn` and `ComputeSwapStepInGivenOut`.
Separating the methods allows us to improve readability, testability, and documentation.
In this PR, tests …

refactor/test(cl/swapstrategy): separate compute swap steps for out given in and in given out

---

go.mod
go.sum

Closes: #XXX
Fixing ci from go mod bot breakage

chore: update go mod to fix ci on main

---

tests/e2e/initialization/config.go

Closes: #1628 
Update logic add account to genesis in e2e testing
This change is already covered by existing tests, it pass all e2e task after run `make test-e2e-short`

[tests/e2e]: simplify the logic for adding accounts to genesis sdk side and integrate into e2e

---

x/protorev/client/cli/query.go
x/protorev/client/cli/tx.go
x/protorev/client/cli/utils.go
x/protorev/keeper/msg_server.go
x/protorev/keeper/msg_server_test.go
x/protorev/protorev.md

In this PR, I add the remaining admin transactions to the CLI. Additionally, I add one modification to `MsgSetMaxPoolPointsPer(Tx/Block)` so that the max pool points per tx cannot be set to something higher than the max pool points per block and vice versa.
- *Added all protorev txs to the cli*
- *Added an additional check to `SetMaxPoolPointsPerTx` and `SetMaxPoolPointsPerBlock`*
- *Update the protorev spec*
This change is already covered by existing tests. Additionally, I tested all of the CLI commands locally with accounts that were designated as the admin account and those that were not, with various params (correct and incorrect), and more. The CLI commands function as expected.
Updated the `x/protorev` spec to include all of the updates made in this PR.

ProtoRev: Adding Txs to CLI

---

tests/e2e/configurer/chain/commands.go

Closes: #XXX
In E2E, we parse the response of CreatePosition in order to determine the position_id that was created. The solution that was put in place proved to be flakey. This is an attempt at making the response parsing be more reliable by utilizing the json instead of plain text response.
An example of a failed run due to this parsing can be found here https://github.com/osmosis-labs/osmosis/actions/runs/4512657404/jobs/7946415111#step:9:483
- CreatePosition returns json string
- Json string is parsed for position ID
This change is already covered by existing tests (E2E)
- How is the feature or …

fix: e2e response parsing

---

x/concentrated-liquidity/export_test.go
x/concentrated-liquidity/fees.go
x/concentrated-liquidity/fees_test.go
x/concentrated-liquidity/genesis.go
x/concentrated-liquidity/genesis_test.go
x/concentrated-liquidity/incentives.go
x/concentrated-liquidity/incentives_test.go
x/concentrated-liquidity/types/keys.go

Closes: #4096 
As part of looking into: https://github.com/osmosis-labs/osmosis/issues/4096, noticed the accumulator indexes include multiple bytes. We only need one byte for the prefix to differentiate from other keys.
Additionally, we should have all keys and helpers defined in a single place - types/keys.go

refactor: shorten fee and uptime accumulator prefixes; move to keys.go

---

x/concentrated-liquidity/internal/swapstrategy/one_for_zero.go
x/concentrated-liquidity/internal/swapstrategy/one_for_zero_test.go
x/concentrated-liquidity/internal/swapstrategy/zero_for_one.go
x/concentrated-liquidity/internal/swapstrategy/zero_for_one_test.go
x/concentrated-liquidity/types/constants.go

Closes: #4701
There are historic ratios that do not make sense anymore. We should replace them with min and max sqrt price derived from the min and max price used in the rest of the CL module.

refactor(CL): remove MaxSqrtRatio and MinSqrtRatio

---

chain.schema.json

Closes: (https://github.com/cosmos/chain-registry/pull/1740/files)
Adapts Osmosis' version of chain schema to match Chain Registry
specifically, changes the 'tendermint version' property to the 'consensus' object, which holds the same data.
- Does this pull request introduce a new feature or user-facing behavior changes? (/ no)
- Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (/ no)

Replace Chain Schema Tendermint version with Consensus

---

osmoutils/cosmwasm/helpers.go

Closes: #XXX
This PR merges https://github.com/osmosis-labs/osmosis/pull/4675 in smaller chunks.
The focus is merging it helper functions to interact with the cosmwasm pool contract.
Since these functions might be useful outside of the `x/cosmwasmpool` module, they are added to `osmoutils`
- Since these functions are simple wrappers no direct unit tests are added. However, they are tested via callers in #4675

feat(osmoutils): cosmwasm query and message wrappers

---

x/concentrated-liquidity/store.go
x/concentrated-liquidity/store_test.go
x/concentrated-liquidity/types/keys.go

Closes: #XXX
Fixes the incentives bug stemming from serializing addresses as raw bytes. This would lead to raw bytes in the address being interpreted as our key separator and parsing problems.
This PR ensures that we write bech32 to disc. Bech32 is base32 encoded so it does not contain the key separator in its alphabet.
There is another problem PR stemming from #4526

fix(CL): incentives gov bug

---

x/concentrated-liquidity/model/codec.go

Closes: #XXX
Registers Concentrated Pool Extension for Pool Proto struct for CL.
Without this un-serializing a CL pool to any struct is impossible- causing panics during init Genesis while unmarshalling pool structs for CL.
- Register Concentrated Pool Extension for Pool Proto struct
Manually tested and verified that Registering CL pool extension for CL Pool proto struct solves existing problems faced while unmarshalling CL pools
- How is the feature or change documented? (not applicable   /   specification (`x/<module>/spec/`)  /  [Osmosis docs repo](https://github.com/osmosis-labs/docs)   /   not …

Register Concentrated Pool Extension for Pool Proto struct

---

CHANGELOG.md
app/apptesting/test_suite.go
app/upgrades/v15/upgrade_test.go
proto/osmosis/gamm/pool-models/balancer/balancerPool.proto
proto/osmosis/gamm/pool-models/stableswap/stableswap_pool.proto
tests/e2e/scripts/ibcDenomPool.json
tests/e2e/scripts/nativeDenomPool.json
tests/e2e/scripts/nativeDenomThreeAssetPool.json
tests/e2e/scripts/pool1A.json
tests/e2e/scripts/pool1B.json
tests/ibc-hooks/ibc_middleware_test.go
x/gamm/keeper/genesis_test.go
x/gamm/keeper/keeper_test.go
x/gamm/keeper/pool_service_test.go
x/gamm/keeper/pool_test.go
x/gamm/pool-models/balancer/amm_test.go
x/gamm/pool-models/balancer/balancerPool.pb.go
x/gamm/pool-models/balancer/marshal_test.go
x/gamm/pool-models/balancer/msgs_test.go
x/gamm/pool-models/balancer/pool_test.go
x/gamm/pool-models/stableswap/msgs_test.go
x/gamm/pool-models/stableswap/stableswap_pool.pb.go
x/poolmanager/create_pool.go
x/poolmanager/create_pool_test.go
x/superfluid/keeper/unpool_test.go

Closes: #4371 
After discussing with @p0mvn, we decided to keep the current proto struct, and just not allow the creation of pools with non zero exit fees in the future.
- add conditions when creating pool
- updated tests
*(or)*
*(or)*
*(example:)* …

Disable create pool with non exit fee

---

tests/e2e/initialization/init.Dockerfile

https://github.com/osmosis-labs/osmosis/pull/4783 broke CI because the docker image doesn't point to the correct wasmvm. Those tests only run on main. 
Update wasmvm version for E2E
All tests should pass (here and on main)

Update dockerfile to use new wasmvm for E2E tests

---

x/concentrated-liquidity/incentives_test.go

Closes: #4815 
- Fix fail of the last test case of `TestClaimAllIncentives`
- With the old version, when we update `joinTime` with add 1 month, the number of days in month will change so the `expectedError` with change too  => fail
- I updated `joinTime` with 28 days instead (minimum), so it's ok now
- Tested and passed
- Does this pull request introduce a new feature or user-facing behavior changes? ( no)

Fix: `TestClaimAllIncentives` is not passing on `main`

---

x/concentrated-liquidity/fees_test.go
x/concentrated-liquidity/swaps_test.go

Closes: #4095 
This pull request adds a new `TestFunctionalSwaps` function to the `KeeperTestSuite`. This test function performs multiple swaps on a custom concentrated liquidity pool, tracking the resulting changes in the spot price and liquidity. The test covers various scenarios, including full range positions, narrow range positions, consecutive range positions, and overlapping range positions. 
The test ensures that the resulting spot price and liquidity changes match the expected values calculated beforehand, with a multiplicative tolerance of 0.0001%. 
- Modifies `swapAndTrackXTimesInARow` function to also return the total `amountIn` and `amountOut` resulting from the x number of swaps specified
- Adds the `TestFunctionalSwaps` described above
- Does this pull request introduce a …

test[CL]: swap functional test

---

x/pool-incentives/keeper/genesis.go
x/pool-incentives/keeper/genesis_test.go
x/pool-incentives/keeper/keeper.go

Closes: https://github.com/osmosis-labs/osmosis/issues/4770
Currently, export genesis would fail, as we do not have the logic to support CL pools in the pool incentives export genesis. 
This PR fixes it so that in export genesis, we check if it's a CL pool, if so handle it accordingly.
- Fix pool incentives genesis to support Concentrated Liquidity Pools
Test cases have been fixed

Fix pool incentives genesis to support Concentrated Liquidity Pools

---

tests/cl-go-client/main.go

Multiple go routines (threads) were trying to access the ignite client account info at the same time. I use a Mutex to avoid routes from trying to access the same memory at the same time and throwing exceptions.
```go
package main
// ... (existing imports) ...
import "sync"
// ... (existing constants and variables) ...
var (
// ... (other existing variables) ...
accountMutex sync.Mutex
)
// ... (rest of the existing code) ...
func createPosition(client cosmosclient.Client, poolId uint64, senderKeyringAccountName string, lowerTick int64, upperTick int64, tokenDesired0, tokenDesired1 sdk.Coin, tokenMinAmount0, tokenMinAmount1 sdk.Int) (amountCreated0, amountCreated1 sdk.Int, liquidityCreated sdk.Dec) {
accountMutex.Lock() // Lock access to getAccountAddressFromKeyring
senderAddress := …
```

(CL) `make localnet-cl-create-positions` fix: concurrency issue
